### ISSUE TITLE
Loss 问题

### ISSUE THREAD

**Issue by NjustWrunning** [hukaixuan19970627/yolov5_obb#124]
## ❔Question
单分类问题
已将类别数nc 该为2 ，box loss一直不降低 并且修改了data 中的 hyo.scratch.yaml 将box分类从0.1 改为0.5 但是训练loss还是下降不了
![image](https://user-images.githubusercontent.com/73689702/146140871-d2d4a0f1-b5fe-44a3-9864-b1eebe635ee8.png)
![image](https://user-images.githubusercontent.com/73689702/146140669-83840194-85d6-4477-843e-a8866a9456ba.png)
![image](https://user-images.githubusercontent.com/73689702/146141279-59c0f3bc-f4ba-44d5-8678-2e3e1d9f79c1.png)

**Comment by NjustWrunning** [comment]
我学习率为0.08 batch-size 为32，感觉对于这套代码很多参数我不知道该怎么调，不知道应该调什么值，目前我这个数据集是一个单分类的船只检测，目标较分散 且目标较小

**Comment by hukaixuan19970627** [comment]
tensorboard看loss曲线图更方便一点。
需要调节的参数也就各loss权重，数据增强策略的一些参数，别的参数除非你知道代码逻辑否则保持默认就好。
一些遥感图像的tricks你可以看看这篇博客：https://zhuanlan.zhihu.com/p/422764914
