### ISSUE TITLE
一个目标多个框

### ISSUE THREAD

**Issue by NjustWrunning** [hukaixuan19970627/yolov5_obb#128]
## ❔Question
![0a8d5d261](https://user-images.githubusercontent.com/73689702/147443803-81683274-311e-4c27-8344-09dc0d969a03.png)
![0b8cc092d](https://user-images.githubusercontent.com/73689702/147443809-53734c89-1dfc-4fd6-8c0d-bc526d5575d7.png)
![0b7d1c160](https://user-images.githubusercontent.com/73689702/147443814-bb913d96-2a02-459f-ad86-c871ce61eebb.png)
我跑的yolov5s detect的时候出现了很多很多这种一个目标多个框，这种有没有比较好的方法解决，谢谢

**Comment by hukaixuan19970627** [comment]
生成的loss曲线看看，大概率还没收敛

**Comment by NjustWrunning** [comment]
> 生成的loss曲线看看，大概率还没收敛
![image](https://user-images.githubusercontent.com/73689702/147539172-240cc336-82e9-408c-9dfd-4c11a69f08bd.png)

已经训练了300epoch 了

**Comment by NjustWrunning** [comment]
> 生成的loss曲线看看，大概率还没收敛

已经训练了300epoch 了，还需要继续训练吗

**Comment by hukaixuan19970627** [comment]
> > 生成的loss曲线看看，大概率还没收敛
> 
> 已经训练了300epoch 了，还需要继续训练吗

数据集的量级是多少呢，dota的量级大概在2w张左右，训300epoch才可以达到最佳精度

**Comment by hukaixuan19970627** [comment]
更了一版新的，训练速度和精度有很大提升，可以试试
