### ISSUE TITLE
角度预测 and detect 效果

### ISSUE THREAD

**Issue by lzfshub** [hukaixuan19970627/yolov5_obb#131]
## Additional context
![image](https://user-images.githubusercontent.com/61589851/147815792-51492035-84a3-43fe-bf3e-1a1409822a39.png)
这是detect效果
![image](https://user-images.githubusercontent.com/61589851/147815855-6800a0fb-3e10-465c-9dca-bb3cc84da21d.png)
这是按照您的文章训练150次的loss
计算map显示为检测不到类别，麻烦您看一下，谢谢！

**Comment by hukaixuan19970627** [comment]
trainbatch012提供一下。你有切割dota吗，训练150epoch效果不应该这么差。
另外可视化结果说明已经检测到小车、大车两类物体了，evaluation.py检测不出结果的话，说明操作步骤有误。
readme里面提供了demo文件以及训练好的权重文件，按照步骤运行先走一遍流程，然后对照一下自己实验和提供的demo生成的文件有哪些区别

**Comment by lzfshub** [comment]
![image](https://user-images.githubusercontent.com/61589851/147824447-3c89247b-ccb8-481a-bbfd-178e6716a0b6.png)

![image](https://user-images.githubusercontent.com/61589851/147824542-c02c55d4-cbf8-4956-971d-83907f242979.png)
![image](https://user-images.githubusercontent.com/61589851/147824557-bfa5c9b0-7c51-4b70-8669-b4ba9a1aa0f3.png)

**Comment by lzfshub** [comment]
没有切割，我用的您的demofile

**Comment by hukaixuan19970627** [comment]
......demo文件只是个示例，方便减少整个流程的花费时间，同时测试环境是否安装成功。就demo那几张图，训出来的模型也是没有泛化能力的。你要训练的话得下载dota数据集，切割后训练。
你要测试的话拿我提供的权重文件测试mAP吧
