### ISSUE TITLE
关于训练DOTAv1.0的问题

### ISSUE THREAD

**Issue by 113HQ** [hukaixuan19970627/yolov5_obb#133]
## ❔Question
大牛，我在你给的权重的基础上冻结网络训了120轮DOTAv1.0，但是map不高，和FPN_CSL中的很多类别差的很多，emmm!百思不得其姐。
这是评估结果：'plane'：91.859, 'baseball-diamond'：74.065, 'bridge'：45.102, 'ground-track-field'：44.269,  'small-vehicle'：64.172, 'large-vehicle'：79.724, 'ship'：92.494, 'tennis-court'：88.068,  'basketball-court'：60.109, 'storage-tank'：72.348,  'soccer-ball-field'：41.483, 'roundabout'：55.003,  'harbor'：72.135, 'swimming-pool'：48.951, 'helicopter'：44.883
map:0.6498 
## Additional context
训练结果图：
![results](https://user-images.githubusercontent.com/57024487/147847470-ddc9c29d-3a9c-4a15-921a-2115dde32bb5.png)
检测的时候切割1024，gap为200，IOU阈值0.3，置信度阈值0.1，部分检测结果图示例：
![P0047__1__0___0](https://user-images.githubusercontent.com/57024487/147847481-2051c9fd-7e1d-446d-9dd2-04aaeb24aaf3.png)
![P0053__1__0___397](https://user-images.githubusercontent.com/57024487/147847500-2fca3e35-c4ff-4e04-aa0c-41c7c7eaae92.png)
![P0060__1__2472___824](https://user-images.githubusercontent.com/57024487/147847524-a794ad9f-e9e3-4242-9bda-7a5d1a0f57d9.png)
![P0131__1__0___256](https://user-images.githubusercontent.com/57024487/147847533-4fd8dc8c-63f4-4348-88d8-196c86160fbf.png)
![P1751__1__2472___2976](https://user-images.githubusercontent.com/57024487/147847541-56863d99-cb5f-4f27-a938-8d992f689b0c.png)
![P2766__1__824___1648](https://user-images.githubusercontent.com/57024487/147847549-0dd3808f-ff80-42ef-b467-776cf9114169.png)
![P2766__1__824___2472](https://user-images.githubusercontent.com/57024487/147847553-5359c32e-b1e2-45a9-a4a8-e3acab897712.png)

**Comment by hukaixuan19970627** [comment]
不大正常，同样的检测器在dotav1.5上不加TTA的检测mAP@0.5能达到65的，在DOTAv1上mAP过70是很容易的事情。
我给的权重mAP在dotav1.5上都有65。
不过这一版本的代码很久没维护了，当时入门旋转检测时改建的，训练效率很低，我自己平常都不怎么用，这周内会放一版新的。训练速度会大幅加快，大概dotav1.5 batchsize=40 epoch=300只需要花24h左右，而且添加了validation功能，复现最佳精度会容易一点，不急的话可以等等。
对部署没需求只追求精度的，可以试试这个[repo](https://github.com/hukaixuan19970627/OrientedRepPoints_DOTA)，SOTA精度，只需36epoch就可以收敛

**Comment by 113HQ** [comment]
好，我等等，我对v5情有独钟。。。谢谢大哥！

**Comment by HKVINS89757** [comment]
> 不大正常，同样的检测器在dotav1.5上不加TTA的检测mAP@0.5能达到65的，在DOTAv1上mAP过70是很容易的事情。 我给的权重mAP在dotav1.5上都有65。 不过这一版本的代码很久没维护了，当时入门旋转检测时改建的，训练效率很低，我自己平常都不怎么用，这周内会放一版新的。训练速度会大幅加快，大概dotav1.5 batchsize=40 epoch=300只需要花24h左右，而且添加了validation功能，复现最佳精度会容易一点，不急的话可以等等。 对部署没需求只追求精度的，可以试试这个[repo](https://github.com/hukaixuan19970627/OrientedRepPoints_DOTA)，SOTA精度，只需36epoch就可以收敛

坐等更新up更新

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/148634410-184b896d-d1c8-4ffc-8554-4081cfa34175.png)
已经改完了，v1.5的效果很棒，yolov5m单尺度的validation的HBB mAP@0.5的已经到74了，比老版本要高了至少5个点

**Comment by hukaixuan19970627** [comment]
这两天上传，正在重写readme，为了提高代码效率把labels 预处理的代码重构了一遍，dotav1.5_gap200_rate1.0_subsize1024 batch20的数据集在2080Ti上300epoch大概花40h，不过我看了一下其实差不多100epoch就收敛到最佳精度了，新版的yolov5确实很强，yolov5m-obb要比yoloxm-obb精度要高10个点

**Comment by HKVINS89757** [comment]
> 不过我看了一下其实差不多

牛逼666

**Comment by 113HQ** [comment]
厉害呀，新版v5又有什么改进吗，比yolox强了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月8日(周六) 下午2:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 关于训练DOTAv1.0的问题 (Issue #133)




 

 已经改完了，v1.5的效果很棒，yolov5m单尺度的validation的HBB ***@***.***的已经到74了，比老版本要高了至少5个点
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hukaixuan19970627** [comment]
> 厉害呀，新版v5又有什么改进吗，比yolox强了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年1月8日(周六) 下午2:35 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 关于训练DOTAv1.0的问题 (Issue #133) 已经改完了，v1.5的效果很棒，yolov5m单尺度的validation的HBB ***@***.***的已经到74了，比老版本要高了至少5个点 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

已更，改进太多不好说。总之训练速度，精度，工程部署难易度是我用过的旋转检测器里权衡的最好的，挑不出毛病。
另外yolox的旋转改建我之前做过，yoloxm在dotav1.5 test-dev上的精度也就60~65之间，和这一版的yolov5-obb差别比较大

**Comment by 113HQ** [comment]
是，立刻去膜拜！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月9日(周日) 晚上9:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 关于训练DOTAv1.0的问题 (Issue #133)




  
厉害呀，新版v5又有什么改进吗，比yolox强了
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年1月8日(周六) 下午2:35 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 关于训练DOTAv1.0的问题 (Issue #133) 已经改完了，v1.5的效果很棒，yolov5m单尺度的validation的HBB @.的已经到74了，比老版本要高了至少5个点 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
  
已更，改进太多不好说。总之训练速度，精度，工程部署难易度是我用过的旋转检测器里权衡的最好的，挑不出毛病。
 另外yolox的旋转改建我之前做过，yoloxm在dotav1.5 test-dev上的精度也就60~65之间，和这一版的yolov5-obb差别比较大
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 113HQ** [comment]
内部机，win10下from . import nms_rotated_ext报错，这个.cpp该怎么转换一下?



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月9日(周日) 晚上9:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 关于训练DOTAv1.0的问题 (Issue #133)




  
厉害呀，新版v5又有什么改进吗，比yolox强了
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年1月8日(周六) 下午2:35 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 关于训练DOTAv1.0的问题 (Issue #133) 已经改完了，v1.5的效果很棒，yolov5m单尺度的validation的HBB @.的已经到74了，比老版本要高了至少5个点 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
  
已更，改进太多不好说。总之训练速度，精度，工程部署难易度是我用过的旋转检测器里权衡的最好的，挑不出毛病。
 另外yolox的旋转改建我之前做过，yoloxm在dotav1.5 test-dev上的精度也就60~65之间，和这一版的yolov5-obb差别比较大
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hukaixuan19970627** [comment]
> 内部机，win10下from . import nms_rotated_ext报错，这个.cpp该怎么转换一下?
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年1月9日(周日) 晚上9:34 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 关于训练DOTAv1.0的问题 (Issue #133) 厉害呀，新版v5又有什么改进吗，比yolox强了 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年1月8日(周六) 下午2:35 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 关于训练DOTAv1.0的问题 (Issue #133) 已经改完了，v1.5的效果很棒，yolov5m单尺度的validation的HBB @.的已经到74了，比老版本要高了至少5个点 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 已更，改进太多不好说。总之训练速度，精度，工程部署难易度是我用过的旋转检测器里权衡的最好的，挑不出毛病。 另外yolox的旋转改建我之前做过，yoloxm在dotav1.5 test-dev上的精度也就60~65之间，和这一版的yolov5-obb差别比较大 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

环境没装好，重新按install.md检查一遍
