### ISSUE TITLE
一个关于训练结果的疑问，

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#135]
## ❔Question
![10_0_0](https://user-images.githubusercontent.com/42164696/147899762-8c23b34e-9743-4bb1-b62f-62a0953b76e2.png)

上面是我的xu训练的检测结果图像，

下面是我训练的loss
![results](https://user-images.githubusercontent.com/42164696/147899792-7012add2-0f69-4442-8cb1-ab6cfeb55a2f.png)

框体还是有点杂乱的，训练的图像尺寸是1024*1024

**Comment by hukaixuan19970627** [comment]
感觉box 的loss曲线还没收敛，box loss的权重可以再调高一点。接着这次的权重接着训练试试看

**Comment by HKVINS89757** [comment]
> 感觉box 的loss曲线还没收敛，box loss的权重可以再调高一点。接着这次的权重接着训练试试看

还有一个问题，就是角度的问题，我那个问你已经关闭了哈，所以再这里问问大佬

就是只要严格按照这个规则弄我的样本就可以了吗？
* Θ: The angle between the longside and the x-axis(The x-axis rotates clockwise).x轴顺时针旋转遇到最长边所经过的角度

**Comment by hukaixuan19970627** [comment]
> > 感觉box 的loss曲线还没收敛，box loss的权重可以再调高一点。接着这次的权重接着训练试试看
> 
> 还有一个问题，就是角度的问题，我那个问你已经关闭了哈，所以再这里问问大佬
> 
> 就是只要严格按照这个规则弄我的样本就可以了吗？
> 
> * Θ: The angle between the longside and the x-axis(The x-axis rotates clockwise).x轴顺时针旋转遇到最长边所经过的角度

那个关于角度的边界问题我已经回答了，还有疑问的话，可以再reopen。
目前这个版本的代码需要labels满足这个要求，labels是poly形式的话可以参考DOTA_devkit_YOLO进行转化。
下个版本对labels就不需要自己来转化了，内部代码会完成自动转化，只需要确保labels数据形式和DOTA数据集给出来的一致就行

**Comment by HKVINS89757** [comment]
> 

其实我觉得，还是不要确保labels的数据形式和dota的数据形式一样为好，这样的话，因为这个开源的应用不仅仅在于卫星地图，还是根据“Θ: The angle between the longside and the x-axis(The x-axis rotates clockwise).x轴顺时针旋转遇到最长边所经过的角度”这个规则进去数据，这样用标注软件标注也方便一些

**Comment by HKVINS89757** [comment]
> > > 感觉box 的loss曲线还没收敛，box loss的权重可以再调高一点。接着这次的权重接着训练试试看
> > 
> > 
> > 还有一个问题，就是角度的问题，我那个问你已经关闭了哈，所以再这里问问大佬
> > 就是只要严格按照这个规则弄我的样本就可以了吗？
> > 
> > * Θ: The angle between the longside and the x-axis(The x-axis rotates clockwise).x轴顺时针旋转遇到最长边所经过的角度
> 
> 那个关于角度的边界问题我已经回答了，还有疑问的话，可以再reopen。 目前这个版本的代码需要labels满足这个要求，labels是poly形式的话可以参考DOTA_devkit_YOLO进行转化。 下个版本对labels就不需要自己来转化了，内部代码会完成自动转化，只需要确保labels数据形式和DOTA数据集给出来的一致就行

hi 年轻有为帅气的大佬，我现在在看您写的这个模型的c++ windows部署的问题，需要把训练的模型文件转为torch支持的模型文件对吧？尝试了一些转的方法，在调用的时候始终有错，不知能否厚颜请求大佬顺手把这个脚本的源文件也开源一下

**Comment by hukaixuan19970627** [comment]
已更
