### ISSUE TITLE
训练测试问题

### ISSUE THREAD

**Issue by weizhiyangq** [hukaixuan19970627/yolov5_obb#136]
## ❔Question
train里面没有test部分代码，自己找其他博客弄了一下，p，r,map都是0。不知怎么修改，请问大佬可以更新一下test部分的代码吗，谢谢

**Comment by hukaixuan19970627** [comment]
这个版本不支持在线validation，下个版本支持，本周内会上传

**Comment by hukaixuan19970627** [comment]
已更，请下载最新版本，最终精度和训练速度都有很大的提升
