### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by bozihu** [hukaixuan19970627/yolov5_obb#137]
## ❔Question

detect代码不支持多GPU测试，如何能够多GPU对数据集进行测试？

**Comment by hukaixuan19970627** [comment]
下个版本会基于最新的yolov5进行改建，到时候会支持所有的功能。本来预计本周上传的，但现在精度跌的有点厉害，正在找问题呢

**Comment by bozihu** [comment]
感谢大佬维护升级

**Comment by HKVINS89757** [comment]
> 下个版本会基于最新的yolov5进行改建，到时候会支持所有的功能。本来预计本周上传的，但现在精度跌的有点厉害，正在找问题呢

精神鼓励支持，大佬可以报个地址嘛，我给你送一杯初雪天的第一杯奶茶

**Comment by hukaixuan19970627** [comment]
已更，新版代码无论是速度还是精度都挑不出毛病，yolov5确实香的很
