### ISSUE TITLE
Export a YOLOv5 PyTorch model to other formats. [torchscript onnx coreml openvino saved_model tflite tfjs] 

### ISSUE THREAD

**Issue by xinsuinizhuan** [hukaixuan19970627/yolov5_obb#138]

**Comment by HKVINS89757** [comment]
同问，我现在在用c++调Python的接口摸索

**Comment by hukaixuan19970627** [comment]
原版yolov5可以的话，那最新的yolov5-obb也支持。毕竟就是添加了几个预测通道而已，模型结构本身几乎没变化

**Comment by HKVINS89757** [comment]
> 原版yolov5可以的话，那最新的yolov5-obb也支持。毕竟就是添加了几个预测通道而已，模型结构本身几乎没变化

我已经弄出来了，可以用vs2019调c++接口跑，3060一帧0.15ms左右(1024*1024)

**Comment by xinsuinizhuan** [comment]
> > 原版yolov5可以的话，那最新的yolov5-obb也支持。毕竟就是添加了几个预测通道而已，模型结构本身几乎没变化
> 
> 如果用libtorch直接用c++处理好像不能很好的部署，我简单的试了一下，没成功，如果大佬成功了请指点一下，但是我试了可以用vs2019c++ python混合编程跑，3060一帧0.1ms左右(1024_1024)，python直接跑也是0.1ms(1024_1024),目测没啥区别 ![图片](https://user-images.githubusercontent.com/42164696/148549608-e17b1286-094e-4279-8861-a3ff35700d14.png)
> 
> 下图右面是c++，左面是python直接跑的 ![图片](https://user-images.githubusercontent.com/42164696/148550193-330919e1-92e0-4caf-b892-9cb0c7c7d705.png)

可以onnx推理吗？

**Comment by hukaixuan19970627** [comment]
> > > 原版yolov5可以的话，那最新的yolov5-obb也支持。毕竟就是添加了几个预测通道而已，模型结构本身几乎没变化
> > 
> > 
> > 如果用libtorch直接用c++处理好像不能很好的部署，我简单的试了一下，没成功，如果大佬成功了请指点一下，但是我试了可以用vs2019c++ python混合编程跑，3060一帧0.1ms左右(1024_1024)，python直接跑也是0.1ms(1024_1024),目测没啥区别 ![图片](https://user-images.githubusercontent.com/42164696/148549608-e17b1286-094e-4279-8861-a3ff35700d14.png)
> > 下图右面是c++，左面是python直接跑的 ![图片](https://user-images.githubusercontent.com/42164696/148550193-330919e1-92e0-4caf-b892-9cb0c7c7d705.png)
> 
> 可以onnx推理吗？

试过了，可以，export.py支持torchscript onnx coreml openvino saved_model tflite tfjs等格式的转换，只要对应环境版本不出问题，推理一切正常

**Comment by HKVINS89757** [comment]
哇哦 我要去试试

**Comment by xinsuinizhuan** [comment]
onnx的模型支持。但是tensorrt的模型暂时不支持，暂时没有转换成功。

**Comment by hukaixuan19970627** [comment]
> onnx的模型支持。但是tensorrt的模型暂时不支持，暂时没有转换成功。

![image](https://user-images.githubusercontent.com/72599120/150759577-2908ee68-72ea-4984-9372-70f5435a04af.png)
自己检查下环境问题

**Comment by xinsuinizhuan** [comment]
> 

怎么导出的呢？什么命令？需要安装什么库？

**Comment by xinsuinizhuan** [comment]
> > onnx的模型支持。但是tensorrt的模型暂时不支持，暂时没有转换成功。
> 
> ![image](https://user-images.githubusercontent.com/72599120/150759577-2908ee68-72ea-4984-9372-70f5435a04af.png) 自己检查下环境问题

您怎么使用tensorrt导出的呢？
我是使用https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5大神的工具，尝试导出，但是默认的m模型，使用类型gd gm数据，导出失败。
windows anaconda环境下，能导出吗？我在yolov5训练环境下，pip install tensorrt，但是导出的时候，提示没有tensorrt模块。
可以详细贴一下步骤吗？

**Comment by hukaixuan19970627** [comment]
和原版yolov5操作一模一样，你先用搜索引擎找一下tensorrt环境安装教程吧-------- 原始邮件 --------发件人： xinsuinizhuan ***@***.***>日期： 2022年1月25日周二 13:37收件人： hukaixuan19970627/yolov5_obb ***@***.***>抄送： hukaixuan19970627 ***@***.***>, State change ***@***.***>主    题： Re: [hukaixuan19970627/yolov5_obb] Export a YOLOv5 PyTorch model to other formats. [torchscript onnx coreml openvino saved_model tflite tfjs]  (Issue #138)





onnx的模型支持。但是tensorrt的模型暂时不支持，暂时没有转换成功。



 自己检查下环境问题



您怎么使用tensorrt导出的呢？

我是使用https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5大神的工具，尝试导出，但是默认的m模型，使用类型gd gm数据，导出失败。

windows anaconda环境下，能导出吗？我在yolov5训练环境下，pip install tensorrt，但是导出的时候，提示没有tensorrt模块。

可以详细贴一下步骤吗？

**Comment by xylieong** [comment]
Hi, after conversion of yolo-obb to openvino, does the model still support orientated detection result?

**Comment by weiyaokun** [comment]
> onnx的模型支持。但是tensorrt的模型暂时不支持，暂时没有转换成功。

模型导出为onnx命令能贴下吗？我是直接在export里面修改  感觉有点麻烦，还有就是我想问下，部署在c++上，用onnx好还是torchscript好呢？

**Comment by weiyaokun** [comment]
大佬，可以指点下怎么部署onnx吗

**Comment by weiyaokun** [comment]
这个输出是四个点的坐标吗

**Comment by weiyaokun** [comment]
大佬，有部署的源码吗？可以参考下吗
