### ISSUE TITLE
大佬能建个qq群交流这个项目嘛？我建一个大佬进来转给你？

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#139]
## ❔Question

群号：568733136

**Comment by hukaixuan19970627** [comment]
不了吧，我就一个人，没那么多精力顾及一整个群，有问题提issue挺好的

**Comment by yangcyz** [comment]
> 不了吧，我就一个人，没那么多精力顾及一整个群，有问题提issue挺好的

大佬，是基于v4版本改建的吗

**Comment by HKVINS89757** [comment]
> > 不了吧，我就一个人，没那么多精力顾及一整个群，有问题提issue挺好的
> 
> 大佬，是基于v4版本改建的吗

V5 V4原版是darknet的
