### ISSUE TITLE
数据集怎么弄？(How to prepare the datasets labels/targets)

### ISSUE THREAD

**Issue by xinsuinizhuan** [hukaixuan19970627/yolov5_obb#140]
使用labelimg2做了旋转矩形的数据集，然后怎么转换？

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/148717515-7d07dbac-de2a-40bf-9f6b-3f47f5ad454b.png)
转成这样就行，可以参考该repo里rbox_utils中的rbox2poly函数进行转换：
![image](https://user-images.githubusercontent.com/72599120/148717603-72580f81-aada-4ed9-bbb2-829a5d5627f1.png)
