### ISSUE TITLE
ImportError: cannot import name 'nms_rotated_ext' from 'utils.nms_rotated'

### ISSUE THREAD

**Issue by Jim0530** [hukaixuan19970627/yolov5_obb#143]
ImportError: cannot import name 'nms_rotated_ext' from 'utils.nms_rotated'

**Comment by hukaixuan19970627** [comment]
Check the environment first, you can refer to [install.md]（https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/install.md）
![image](https://user-images.githubusercontent.com/72599120/148718259-eb397bab-cd68-4921-b3d3-56dde3f98e2e.png)

**Comment by Jim0530** [comment]
好的看到了謝謝 若不需要做切割影像 數據格式跟上一版是不是不太依樣
改採下面這個格式嗎？謝謝
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/48552674/148719430-232b0f4a-ce08-4cb4-b196-9eff85a52227.png">

**Comment by hukaixuan19970627** [comment]
是的，为了加快训练速度，代码能重构的地方都重构了，所以这一版的数据格式换成了poly格式
你可以参照start.md花十分钟先运行一遍demo，就能知晓所有流程

**Comment by Jim0530** [comment]
好的謝謝您細心地講解
