### ISSUE TITLE
转换C++代码，最后解析，请教：

### ISSUE THREAD

**Issue by xinsuinizhuan** [hukaixuan19970627/yolov5_obb#144]
在non_max_suppression_obb函数中解析数据的时候：
我理解的一个一个结果是长度为7的数组：
第0-4位旋转矩形框：
       第0-3位为旋转矩形的左上角坐标和长宽
      第4位为旋转角度
第5位为置信度
第6位为类别id
这样理解对吗？

**Comment by hukaixuan19970627** [comment]
.....emmm，这个代码里不是有注释咩。这个repo里的关键函数我基本都写了注释，以及输入输出的数据格式。
![image](https://user-images.githubusercontent.com/72599120/148741693-e90ca90b-250a-41bf-ac15-a947e5fbb086.png)

**Comment by hukaixuan19970627** [comment]
算了，我还是更新一下注释吧，估计是cx cy和x y引起你的疑虑了

**Comment by xinsuinizhuan** [comment]
嗯。英文的，所以没太看懂 cx xy l s obj num_class theta_class都是啥意思，都是缩写

**Comment by xinsuinizhuan** [comment]
> 算了，我还是更新一下注释吧，估计是cx cy和x y引起你的疑虑了

注释可以中文不，哈哈

**Comment by hukaixuan19970627** [comment]
> > 算了，我还是更新一下注释吧，估计是cx cy和x y引起你的疑虑了
> 
> 注释可以中文不，哈哈

有些系统里中文会乱码，而且这是目标检测的通用单词，很常用的

**Comment by xinsuinizhuan** [comment]
cx 中心点x坐标
cy中心点y坐标
l 长边
s 短边
obj ???
num_cls 类别id
theta_class 角度[-pi/2, pi/2)

**Comment by xinsuinizhuan** [comment]
cx 中心点x坐标
cy中心点y坐标
l 长边
s 短边
obj 得分阈值
num_cls 类别id
theta_class 角度[-pi/2, pi/2)
??

**Comment by hukaixuan19970627** [comment]
center_x
center_y
long edge
short edge
objectness
number of class
number of θ class

**Comment by xinsuinizhuan** [comment]
我仿照做的角度解析，不对的：
			float pangle = it[6];
			float pre_angle = std::max((float)it[6], (float)1);
			float temangle = (pre_angle - 90) / 180 * PI_VALUE;
			float angle = (temangle < 0) ? (360 + temangle) : temangle;
不知道那里错了？

**Comment by HKVINS89757** [comment]
想问下您这个c++是用的什么库呢？

**Comment by xinsuinizhuan** [comment]
目前，是使用onnxruntime库推理，但是推理完成后，现在角度解析还不对，坐标什么的，都可以了。

**Comment by xinsuinizhuan** [comment]
> center_x center_y long edge short edge objectness number of class number of θ class

这个角度怎么提取呢，直接跟坐标轴一样解析，还是跟阈值一样解析呢？

**Comment by HKVINS89757** [comment]
> onnxruntime
objectness这个具体代表什么呢 方便高速一下吗 这个阈值事干嘛的呢

**Comment by hukaixuan19970627** [comment]
我已经提供了detect代码，你debug一下就全清楚了

**Comment by HKVINS89757** [comment]
> 我已经提供了detect代码，你debug一下就全清楚了

up说的对，对照一下detect的代码都可以解析的，我已经弄完啦

**Comment by xinsuinizhuan** [comment]
> > 我已经提供了detect代码，你debug一下就全清楚了
> 
> up说的对，对照一下detect的代码都可以解析的，我已经弄完啦

大神，留个微信？交流一下？

**Comment by HKVINS89757** [comment]
> > > 我已经提供了detect代码，你debug一下就全清楚了
> > 
> > 
> > up说的对，对照一下detect的代码都可以解析的，我已经弄完啦
> 
> 大神，留个微信？交流一下？

我加您

**Comment by xinsuinizhuan** [comment]
> > > > 我已经提供了detect代码，你debug一下就全清楚了
> > > 
> > > 
> > > up说的对，对照一下detect的代码都可以解析的，我已经弄完啦
> > 
> > 
> > 大神，留个微信？交流一下？
> 
> 我加您

我的微信：xinsuinizhuan。麻烦您大神加一下，这个问题，困扰我很久了，角度解析就是不对。

**Comment by xinsuinizhuan** [comment]
已经解决。角度是取的索引值，而不是实际值。

**Comment by Zahirgeek** [comment]
> > > > 我已经提供了detect代码，你debug一下就全清楚了
> > > 
> > > 
> > > up说的对，对照一下detect的代码都可以解析的，我已经弄完啦
> > 
> > 
> > 大神，留个微信？交流一下？
> 
> 我加您

大佬，可否分享后处理的代码，想观摩学习
