### ISSUE TITLE
训练加multiscale参数问题

### ISSUE THREAD

**Issue by sutiyu** [hukaixuan19970627/yolov5_obb#145]
作者你好，貌似训练加multiscale参数问题后看到保留的train_batch图片里框和目标会出现不对应的情况

**Comment by hukaixuan19970627** [comment]
嗯，这个地方忘改了，已添加。不过不推荐用，略浪费显存。
yolov5中RandomScaleCrop其实已经隐式地完成了multi-scale操作，效率比单纯的多尺度要高。
