### ISSUE TITLE
训练数据集问题

### ISSUE THREAD

**Issue by Antactz** [hukaixuan19970627/yolov5_obb#146]
请问训练数据集还需要切分成1024x1024吗，现在的label是不是可以理解为使用DOTA原始的labels就行，不需要再像之前那样做长边转换

**Comment by hukaixuan19970627** [comment]
是，代码内部自动完成转换操作。
GetStart.md里有demo，可以选择切也可以不切，支持任意宽高比的图像输入，高分辨率数据集的话选择split进行train/test能够获得更好的结果。
