### ISSUE TITLE
关于数据格式

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#150]
![image](https://user-images.githubusercontent.com/42164696/148885569-b361c04e-9b1e-4c21-a0ab-4058c45b7ef7.png)
最后一行的这个1是什么呢

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/148888139-9d04a3fb-6530-4c13-a845-3801196307f6.png)
![image](https://user-images.githubusercontent.com/72599120/148888191-09f99c5c-3da0-4218-9571-c13babb8ccbc.png)
