### ISSUE TITLE
关于置信度的问题

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#155]
![image](https://user-images.githubusercontent.com/42164696/148940671-9d7454c7-2c17-4ecf-821b-92d00f6a3bbb.png)
这个zhi'xin'du置信度是不是有点低了

**Comment by hukaixuan19970627** [comment]
测试的命令是啥

**Comment by HKVINS89757** [comment]
![image](https://user-images.githubusercontent.com/42164696/148941167-a27bafde-e9a5-404b-904b-2c70896d7bf9.png)

**Comment by HKVINS89757** [comment]
![image](https://user-images.githubusercontent.com/42164696/148942696-e90a3db4-af6c-4557-b7bd-1b8cc05f9067.png)
用的这个模型

**Comment by hukaixuan19970627** [comment]
还行吧。一般部署都是conf_thresh设置为0.2。
而且yolov5本身的训练方式就会使得置信度不高，https://github.com/ultralytics/yolov5/issues/2864#issuecomment-823409583，想提高置信度，你直接对它开个方就行
