### ISSUE TITLE
关于数据集问题，我的数据集里面有30个类，但是我只想训练其中的2种，会报错，

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#157]
![image](https://user-images.githubusercontent.com/42164696/149066945-538aa84e-7a64-4702-97ad-97f623d9e277.png)
bu'zhi'd不知道这种训练方式是不是支持呢？

**Comment by hukaixuan19970627** [comment]
这种问题你可以直接去yolov5的issues里搜，它支持的话我这个就支持，它没有的功能我也没添加，我只是把它改成了旋转检测而已。

**Comment by HKVINS89757** [comment]
> 

好的 我 额外的写了一个脚本，解决了这个问题
