### ISSUE TITLE
训练报错，thread: [10,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#159]
![图片](https://user-images.githubusercontent.com/42164696/149142085-ac46250c-eaed-4975-98a1-dd011554130e.png)

**Comment by HKVINS89757** [comment]
哪位遇到过可以交流一下吗

**Comment by HKVINS89757** [comment]
up主在线不

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/149147837-4931d216-6476-4649-b22f-fa63483da4af.png)

**Comment by HKVINS89757** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/149147837-4931d216-6476-4649-b22f-fa63483da4af.png)


那这个数值调高不会影响性能吗 ，我调到了0.08才不报错 我天

**Comment by HKVINS89757** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/149147837-4931d216-6476-4649-b22f-fa63483da4af.png)

已经设置到0.33333了

**Comment by HKVINS89757** [comment]
![图片](https://user-images.githubusercontent.com/42164696/149262719-4b1bdab8-f91e-4887-bc69-ac2a6a1127cb.png)
训练了2000多个 终于上去了准确度
