### ISSUE TITLE
请问up主大佬，这个模型的cfg文件可以自己加载其他的么？

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#160]
![图片](https://user-images.githubusercontent.com/42164696/149183015-c842dc63-0e21-4273-b8f0-583b89579c95.png)
上图红圈框的这个

**Comment by HKVINS89757** [comment]
![图片](https://user-images.githubusercontent.com/42164696/149183249-86cf3791-1ad9-4a9f-94f0-0b8add772de0.png)
这些文件都是大佬写的obb的吗？

**Comment by HKVINS89757** [comment]
这个默认的好像是加载预训练模型吧，我以前玩darknet比较多，yolov5还真不熟悉，请大佬多多指教

**Comment by HKVINS89757** [comment]
上面这些yaml文件是yolov5的自带的还是大佬您整理的，如果是自带的可以用来直接训练obb吗？

**Comment by HKVINS89757** [comment]
![图片](https://user-images.githubusercontent.com/42164696/149188693-d3406a88-e98c-4fa8-96f6-2718b3d62f28.png)
因为我看到Getstart里面训练的时候好像没有建议加载cfg文件

**Comment by hukaixuan19970627** [comment]
和yolov5用法完全一样，可以去原repo学习，教程更多也更丰富

**Comment by HKVINS89757** [comment]
> ###

好的已经弄好了，但是我好像gpu内存有点小，直接加载模型训练的会有内存超标，加载预训练模型就不会，另外问一句，这个可以直接用yolov5的预训练模型吧
