### ISSUE TITLE
yoloV5版本的问题

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#162]
请问大佬这个是基于yolov5-6.0版改的吗？

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/149300045-cfe16e8b-8b58-4fe5-9d0f-56fe59991b99.png)

**Comment by HKVINS89757** [comment]
已经弄完了，谢谢大佬
