### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by smartbird66** [hukaixuan19970627/yolov5_obb#163]
大神您好，很佩服您的工作，我是个小白，不太懂深度学习这块，看到了您的代码，正好符合我的工作需求，在这里先拜谢并学习了。
我的工作是钢体图像的特殊位置检测，您可以参考下图3（训练过程中的一个Batch）。
之前我曾用没有旋转的标签在yoloV5上训练测试过可以正常收敛，但是效果一般。
现在我使用大神您的旋转YOLO去做目标检测，遇到了一些困难，希望您可以抽空帮我解答一下，谢谢：
1.训练过程中可以看到图3中的检测结果还算正常，但是到测试阶段，检测结果如图1、2不是很理想。 
我的数据集包含了大约200张标记的图像（不包含Augmented data），目标只包含一个类别，在T4GPU上训练了200epoch，图像尺寸640，其余均采用了模型的标准参数设置。测试的时候，我把置信度阈值conf-thres，IOU-thres，都进行了大量的尝试，结果都不是很理想。

2. 再发现测试结果不是很理想之后，我又大量更改了训练及测试的超参数，结果还是不理想。
在打开results.txt进行检查时，我注意到训练时可以看到只有角度的loss值在下降，请问这正常吗（详见图4）
3. 同样还是在图4中，precision,recall,map的曲线很异常，请问是否可以提供一些思路解决这个问题？
4. 我的数据是采用rolabelimg（https://gitee.com/libin971204/roLabelImg）标注成XML格式，之后按照您给的格式转换，训练时可以看到只有角度的loss值在下降，请问这有可能会是什么原因导致的呢。

还望大神您百忙之中抽出时间帮我小白解惑哈，谢谢！
![Image_20211202140148443_37](https://user-images.githubusercontent.com/56995125/149291657-21f3d8c4-278b-4264-a39b-f93be1d4282e.jpg)
图1 测试图
![Image_20211202140148443](https://user-images.githubusercontent.com/56995125/149291712-51b8d8a2-d2b3-456f-bb4f-29634b2914ed.jpg)
图2 测试图
![train_batch1](https://user-images.githubusercontent.com/56995125/149281867-601a1ac9-b749-4db6-b671-e88f4ba83dd6.jpg)
图3 训练过程中的train_batch1.jpg
![results](https://user-images.githubusercontent.com/56995125/149281795-1a5759e4-9ef7-4ee5-8158-deff71bf961e.png)
图4 Training Progress
![image](https://user-images.githubusercontent.com/56995125/149282104-d1a770bb-a880-40c3-a92e-dc961a3ce01d.png)
图5 模型超参数
![image](https://user-images.githubusercontent.com/56995125/149282148-70adbf44-f130-4552-801c-d3bd9ea55279.png)
图6 opt.yaml设置截图

**Comment by hukaixuan19970627** [comment]
更新下版本，上周这套代码就已经大更新了。这版的训练效率和训练精度相比老版本有一个巨幅的提升，不过由于部分代码重构，记得重新按照readme 安装新环境以及重新跟随一遍使用demo

**Comment by smartbird66** [comment]
> 更新下版本，上周这套代码就已经大更新了。这版的训练效率和训练精度相比老版本有一个巨幅的提升，不过由于部分代码重构，记得重新按照readme 安装新环境以及重新跟随一遍教程demo

好的，多谢大佬，我上周下载的刚好是没更新的版本，我去重新试一下这个新版本。
