### ISSUE TITLE
旧模型如何在新版本中使用

### ISSUE THREAD

**Issue by lrh454830526** [hukaixuan19970627/yolov5_obb#164]
您好  非常感谢您的开源贡献，但是在使用新版的模型以后发现一个问题  就是如果将旧版的模型直接用新版代码运行，会出现旋转角度不正确的问题，如下图所示，请我应该如何更改代码  让新版的可以顺利运行旧版的模型？
[![7l8QfI.png](https://s4.ax1x.com/2022/01/13/7l8QfI.png)](https://imgtu.com/i/7l8QfI)
[![7l8MtA.png](https://s4.ax1x.com/2022/01/13/7l8MtA.png)](https://imgtu.com/i/7l8MtA)

**Comment by lrh454830526** [comment]
> 您好 非常感谢您的开源贡献，但是在使用新版的模型以后发现一个问题 就是如果将旧版的模型直接用新版代码运行，会出现旋转角度不正确的问题，如下图所示，请我应该如何更改代码 让新版的可以顺利运行旧版的模型？ [![7l8QfI.png](https://camo.githubusercontent.com/9915b17f8585879359acf1cd0c945194301a947213393199ec239372df8e291e/68747470733a2f2f73342e617831782e636f6d2f323032322f30312f31332f376c385166492e706e67)](https://imgtu.com/i/7l8QfI) [![7l8MtA.png](https://camo.githubusercontent.com/204280e4c88e2ad2659db32e50493b2a6e9458d02f1410ed080c7e8549a85cf4/68747470733a2f2f73342e617831782e636f6d2f323032322f30312f31332f376c384d74412e706e67)](https://imgtu.com/i/7l8MtA)

刚刚看了下 旧版本里面使用的是-180~180  新版本直接使用的弧度运算  所以我只需要在rbox2poly 将旧版本的角度转换成弧度即可，请问我的理解对么

**Comment by hukaixuan19970627** [comment]
不建议用旧模型，新版代码重构之后无论是训练速度还是最终的精度都有一个巨幅的提升（DOTAv1.5 test-dev上比老版本代码的最高精度还要高五个点，而且更容易复现最佳精度）。可能你改代码花的时间都够新版代码训好一个模型了。

**Comment by lrh454830526** [comment]
好的  感谢您的建议 刚才试了下   新版本在以前版本的基础上果然提了好几个点
