### ISSUE TITLE
训练报错：IndexError: select(): index 775 out of range for tensor of size [698, 5] at dimension 0

### ISSUE THREAD

**Issue by smartbird66** [hukaixuan19970627/yolov5_obb#168]
大佬你好，我在训练的自己标注的数据集的过程中会出现这个错误，有可能会是什么问题？
我猜想可能是我的标注数据出了问题，但是我通过opencv的line方法去按照坐标画出每个框并没有出现out of index的错误，并且每个坐标也都没有超过图片的范围，图二是我标注的数据。
pytorch版本：1.10.0
device： cpu
![image](https://user-images.githubusercontent.com/56995125/149487849-cfd08bde-2e99-48f5-8434-f0c81bd5dc40.png)
![image](https://user-images.githubusercontent.com/56995125/149489105-b3e89bf0-ea39-4f57-aa6b-78dda06b153a.png)

**Comment by smartbird66** [comment]
> 大佬你好，我在训练的自己标注的数据集的过程中会出现这个错误，有可能会是什么问题？ 我猜想可能是我的标注数据出了问题，但是我通过opencv的line方法去按照坐标画出每个框并没有出现out of index的错误，并且每个坐标也都没有超过图片的范围，图二是我标注的数据。 pytorch版本：1.10.0 device： cpu ![image](https://user-images.githubusercontent.com/56995125/149487849-cfd08bde-2e99-48f5-8434-f0c81bd5dc40.png) ![image](https://user-images.githubusercontent.com/56995125/149489105-b3e89bf0-ea39-4f57-aa6b-78dda06b153a.png)

**Comment by hukaixuan19970627** [comment]
找不出问题的话，val就暂时别开启了，训练时--noval置为True，之后有训练权重了再用val.py慢慢排查问题吧

**Comment by smartbird66** [comment]
多谢大佬，可以了，我先把val设置为False了，把final epoch的val也注释掉了，然后简单跑了10个epoch，预测结果都是下面这种情况：预测的都是一个方向，并且长宽比都很大，是训练的epoch太小了？
![image](https://user-images.githubusercontent.com/56995125/149646974-2c2071dd-0413-42e5-990e-59d2e63a02b8.png)

**Comment by hukaixuan19970627** [comment]
描述不详细。训练效果不好的原因可多了去了，你提供的信息越多，沟通效率越高

**Comment by Sunnyio8** [comment]
好像训练的目标比较大就会出现这种情况，我训练自己的数据集的时候也会出现这个问题
