### ISSUE TITLE
关于训练的数据的长短边问题，求助

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#169]
你好，如下两个框
![image](https://user-images.githubusercontent.com/42164696/149616705-b1992ce1-1070-46a7-b37f-e21db61143bd.png)

我用标定软件标定的结果为：
![image](https://user-images.githubusercontent.com/42164696/149616741-db9f90fb-849e-41a9-8d82-6ced8ae11f51.png)
转为dota数据的txt结果，无论从角度还是第一个点来看，这里面并没有长短边之分，那么这样的话会对后续的训练造成什么影响吗？还是在训练的程序中自动对长短边进行了区分？
![image](https://user-images.githubusercontent.com/42164696/149616729-13d48f17-93a4-4b7b-916a-1a314a64cd2a.png)

**Comment by HKVINS89757** [comment]
我看您里面事用了csl，这个事有自动的长短边区分对吗？也就是说无论我送进去的点的顺序是什么样，内部做了一个长短边区分对吗

**Comment by hukaixuan19970627** [comment]
https://arxiv.org/abs/2003.05597v2
https://zhuanlan.zhihu.com/p/111493759

**Comment by HKVINS89757** [comment]
> 

是的 这个我已经看了  跟进数据的话 这个对 -89 和89的处理也很好， 我看着像是训练的时候程序内部已经做了处理，但是不太确定，所以来问问大佬，不知道大佬怎么理解的

**Comment by hukaixuan19970627** [comment]
def poly2rbox(), poly转长边表示法
