### ISSUE TITLE
关于推理结果，长边的长度小于短边

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#170]
请问作者大佬，和各位，在推理的时候有没有遇到过长边比短边短的情况，我这大概遇到的概率1%~3%左右。如下图

![image](https://user-images.githubusercontent.com/42164696/149646397-713a727a-d981-4d48-9f73-7f21740ad1bd.png)

**Comment by hukaixuan19970627** [comment]
回归通道和labels的设定有一定偏差很正常

**Comment by HKVINS89757** [comment]
> 回归通道和labels的设定有一定偏差很正常

好的，谢谢大佬的无私奉献，我已经顺利部署了，
