### ISSUE TITLE
关于训练过程中，Linux的缓存占用过大的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/yolov5_obb#171]
![image](https://user-images.githubusercontent.com/54108453/149684739-c3714525-420e-42c7-8f11-a4c70e92f7ca.png)
越训练到后面，cache 占用就越大？这是什么问题呢？
是不是有内存泄漏？是不是一直打开个什么东西，没关？申请内存没释放呢？

**Comment by hukaixuan19970627** [comment]
能调一下系统内存的使用率曲线不。对比一下--noval为true和false的曲线变化情况，看看是不是validation的cuda代码里的问题
