### ISSUE TITLE
关于您的预训练模型效果的问题？

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/yolov5_obb#172]
![image](https://user-images.githubusercontent.com/54108453/149721700-bec263a9-fa4e-43c6-95dd-bd7534b79d7c.png)
最后在test的训练集的效果是70.98。 请问，您是如何对test集进行检测以及合并的呢？
73的结果是在val集上的，还是在test的集上的呢？

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/149722351-3dbce6a0-a996-4234-970f-02fb6595ca6a.png)

**Comment by hukaixuan19970627** [comment]
你是重新训的吗，还是直接用的我提供的权重

**Comment by kuazhangxiaoai** [comment]
> 你是重新训的吗，还是直接用的我提供的权重

 用的您的权重文件(yolov5_dotav15_obb.pt). image size : 1024 * 1024 +  gap: 200

**Comment by hukaixuan19970627** [comment]
。。。你还是按照我get_start里的操作来弄吧，里面提供了dota数据集task1中所有的操作demo
