### ISSUE TITLE
大佬您好，话说预训练模型怎么制作，大佬有对应的脚本吗？

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#173]

**Comment by hukaixuan19970627** [comment]
--weights '' --cfg 'yolov5s.yaml'

**Comment by HKVINS89757** [comment]
貌似这样不行吧，还有个问题，我尝试加了一层 。不知道您写的这个带角度的是不是支持，我的model文件如下，

# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 6  # number of classes
depth_multiple: 0.67  # model depth multiple
width_multiple: 0.75  # layer channel multiple
anchors:
  - [8,9, 11,8, 13,7]  # P3/8
  - [9,17, 28,10, 14,35]  # P3/8
  - [30,61, 62,45, 36,120]  # P4/16
  - [146,56, 176,258, 450,500]  # P5/32
# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]], #-4
   [-1, 1, nn.Upsample, [None, 2, 'nearest']], #-3
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3 -2
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)  -1
   
   [-1, 1, Conv, [256, 1, 1]],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 20 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 23 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 26 (P5/32-large)

   [[17, 20, 23,26], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]




训练是没问题的，但是还没训练完毕。

![image](https://user-images.githubusercontent.com/42164696/150291940-61d7d989-f9c8-47be-9edd-3eed478b8d0d.png)

**Comment by hukaixuan19970627** [comment]
预训练模型就是train from scratch，直接训

**Comment by HKVINS89757** [comment]
> 预训练模型就是train from scratch，直接训

啥意思大佬，不要惜字如金嘛

**Comment by hukaixuan19970627** [comment]
> > 预训练模型就是train from scratch，直接训
> 
> 啥意思大佬，不要惜字如金嘛

那你就问清楚一点，哪个地方不清楚直接问。用预训练模型的那叫finetune；不用预训练模型的那就是train from scratch，生成的模型可用于finetune，这不就是你要的预训练模型吗

**Comment by HKVINS89757** [comment]
> finetune

好的大佬，那我就清楚了 ，我上面这个加了一层的貌似还可以能到73，在我的数据集上略低于您原版的2，3个点
