### ISSUE TITLE
指标计算和模型保存的问题

### ISSUE THREAD

**Issue by Ethan-niu** [hukaixuan19970627/yolov5_obb#175]
1、阅读大佬的代码，发现模型保存的best.pt是按照hbb的计算指标保存的，请问下，hbb的计算指标和obb的计算指标是否线性相关的，就是hbb的指标高一定代表obb的指标高；
2、抛开DOTA这个数据集需要split的情况，在一些其他数据记上面是不是可以吧train_val过程中的指标计算换成obb方式

**Comment by hukaixuan19970627** [comment]
1. obb相比于hbb是较高的精度指标，不存在什么绝对的线性关系, 例如我提供的demo中，hbb的评估结果每个类别都有极高的AP，但是obb的评估结果中有一类物体的AP是0，不过obb mAP高的检测器，其hbb mAP不会低。同样的，mAP HBB @0.5:0.95也是高精度指标，它高则obb mAP@0.5 也不会低到哪里去
2. 你换呗，changelog里讲了用hbb做validation就是因为它的计算效率更高，你愿意花更多的时间换更准的best.pt也不是不行
