### ISSUE TITLE
关于dataset的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/yolov5_obb#176]
请问，您的代码的dataset的部分中，rect是什么功能能呢？我看出来的图片的size是1056*xxx，不应该是1024吗？如果让rect=False呢？
![image](https://user-images.githubusercontent.com/54108453/149900298-d937650d-01cd-4d99-ac7f-ac5e861963d9.png)

**Comment by hukaixuan19970627** [comment]
你用搜索引擎搜一下 yolov5 矩形训练 就清楚了
