### ISSUE TITLE
softnms

### ISSUE THREAD

**Issue by shenhaibb** [hukaixuan19970627/yolov5_obb#178]
我看到路径utils/nms_rotated/nms_rotated_wrapper.py下有obb_nms ，那是否有对应的obb_soft_nms呢
![image](https://user-images.githubusercontent.com/64736467/150051516-9c4a0207-d97c-4407-aacc-15580a5db427.png)

**Comment by hukaixuan19970627** [comment]
没有，你用只计算poly iou的cuda算子的话自己改一个呗

**Comment by shenhaibb** [comment]
> 没有，你用只计算poly iou的cuda算子自己改一个呗

大佬 请问您是把poly_nms改成poly_softnms，然后把obb_nms替换成poly_softnms吗
![image](https://user-images.githubusercontent.com/64736467/150126885-6cea7598-8ff9-4847-80bd-9a70d3f13621.png)

**Comment by hukaixuan19970627** [comment]
这个repo没有只计算poly iou的算子，你要自己改成soft nms的话可以去OBBDetection这个repo下面把计算poly iou的cuda算子copy过来
