### ISSUE TITLE
recall too low

### ISSUE THREAD

**Issue by luweishuang** [hukaixuan19970627/yolov5_obb#180]
请教大佬，我是在自己的数据集上训练测试，549张训练集，51张测试集，共8类。在测试集上每一类的recall都比较低，您知道是啥原因么
![confusion_matrix](https://user-images.githubusercontent.com/12368977/150281923-06034ceb-3984-48b9-a710-17b8373f9787.png)

**Comment by luweishuang** [comment]
训练集中每一类实例的数量是rust : 366
broken : 50
endjump : 16
straightpipebend : 21
laughcrack : 157
corroison : 28
damage : 12
bondlinebroken : 15

**Comment by luweishuang** [comment]
同样的数据集我也尝试了yolox来训练，表现比yolov5_obb好些，但同样存在各类别recall偏低的情况

**Comment by hukaixuan19970627** [comment]
trainbatch0/1/2，训练loss曲线，detect图等可视化信息提供一下。
另外描述的信息越准确越丰富（最好能让人复现结果），沟通效率越高。
recall低，那具体的量化数据是多少，一般baseline的recall大概是多少呢
