### ISSUE TITLE
关于论文的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/yolov5_obb#181]
请问，可以用您这套代码撰写论文吗？

**Comment by gejintaohua** [comment]
在RemoteSensing上看到了一篇YOLOv5+CSL的，不知道是不是用这个代码

**Comment by kuazhangxiaoai** [comment]
> 在RemoteSensing上看到了一篇YOLOv5+CSL的，不知道是不是用这个代码

能发个链接吗？

**Comment by hukaixuan19970627** [comment]
> > 在RemoteSensing上看到了一篇YOLOv5+CSL的，不知道是不是用这个代码
> 
> 能发个链接吗？

那篇是RepVGG + yolov5 + CSL，看可视化图片的话应该是基于老版本的代码进行进一步改建的。
不过yolov5 和 csl代码和论文都是现成的，直接拿来写论文未免太那啥了，至少得加点自己创新的东西进去才行。

**Comment by yanxioa** [comment]
> > > 在RemoteSensing上看到了一篇YOLOv5+CSL的，不知道是不是用这个代码
> > 
> > 
> > 能发个链接吗？
> 
> 那篇是RepVGG + yolov5 + CSL，看可视化图片的话应该是基于老版本的代码进行进一步改建的。 不过yolov5 和 csl代码和论文都是现成的，直接拿来写论文未免太那啥了，至少得加点自己创新的东西进去才行。

大佬有论文链接吗

**Comment by gejintaohua** [comment]
BiFA-YOLO: A Novel YOLO-Based Method for
Arbitrary-Oriented Ship Detection in High-Resolution
SAR Images

**Comment by gejintaohua** [comment]
> > > > 在RemoteSensing上看到了一篇YOLOv5+CSL的，不知道是不是用这个代码
> > > 
> > > 
> > > 能发个链接吗？
> > 
> > 
> > 那篇是RepVGG + yolov5 + CSL，看可视化图片的话应该是基于老版本的代码进行进一步改建的。 不过yolov5 和 csl代码和论文都是现成的，直接拿来写论文未免太那啥了，至少得加点自己创新的东西进去才行。
> 
> 大佬有论文链接吗

BiFA-YOLO: A Novel YOLO-Based Method for
Arbitrary-Oriented Ship Detection in High-Resolution
SAR Images

**Comment by shenhaibb** [comment]
> BiFA-YOLO: A Novel YOLO-Based Method for
> Arbitrary-Oriented Ship Detection in High-Resolution
> SAR Images

这篇我也看过 是基于bifpn在sar图像做的 大佬说的那个repvgg不知道是不是这个Improved YOLO Network for Free-Angle Remote Sensing Target Detection https://doi.org/10.3390/rs13112171
