### ISSUE TITLE
dotav1.0 obb yolov5s大家有出结果的吗

### ISSUE THREAD

**Issue by shenhaibb** [hukaixuan19970627/yolov5_obb#182]
我训练了150代 已经跑到73.7了，接下来还要训练，训练到300代 
之前hbb最高跑到71.多 这新版的yolov5 也太牛了吧
大家也是这个值吗 高得我有点害怕 怀疑是不是自己跑错了

**Comment by shenhaibb** [comment]
已经到74.5了 200代

**Comment by hukaixuan19970627** [comment]
训完的话可以按照readme中的格式，给训练生成的所有文件打个包上传网盘，然后提个pr

**Comment by shenhaibb** [comment]
> 训完的话可以按照readme中的格式，给训练生成的所有文件打个包上传网盘，然后提个pr

想问下这个test dota数据集的test注释文件不是不公开的吗，那这个，，数据集怎么测试的呢。。
![image](https://user-images.githubusercontent.com/64736467/150628954-5b6c69fc-154a-4a95-9218-e2c6a470296a.png)

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/150629264-247ef022-4694-4690-a059-ee12e2e3a43d.png)

**Comment by shenhaibb** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/150629264-247ef022-4694-4690-a059-ee12e2e3a43d.png)

我知道测试集要去官网提交 我的意思是readme里那一行 --task ‘test’ 不是会选择dotav15_poly.yaml的test路径里找test数据集吗 然后通过val.py进行测试 可是官网不是不公开test注释吗 是不是--task ‘val’呢
![image](https://user-images.githubusercontent.com/64736467/150635358-7b894ace-d84d-4280-b477-b2b6392cda08.png)
![image](https://user-images.githubusercontent.com/64736467/150635831-844e4e84-f81d-467e-b81d-f57fe3181b1b.png)

**Comment by hukaixuan19970627** [comment]
。。。。这种问题没必要问吧，你跑一遍不就知道了。
你要检测val，那你就设置task为’val‘，你要检测test，那就设置task为’test‘，用法和yolov5一模一样。
你不测试test数据集，就没有检测结果，没有检测结果你拿什么上传官网进行评估？

**Comment by shenhaibb** [comment]
> 。。。。这种问题没必要问吧，你跑一遍不就知道了。 你要检测val，那你就设置task为’val‘，你要检测test，那就设置task为’test‘，用法和yolov5一模一样。 你不测试test数据集，就没有检测结果，没有检测结果你拿什么上传官网进行评估？

哦哦哦 我以为测试的时候还要和之前一样用detect检测出所有结果，再去官网提交检测结果呢/捂脸 懂了懂了 谢谢你！～

**Comment by Henry-web1** [comment]
为什么我训练的精度要比之前用hbb的还要低呢？是什么问题呢
数据格式？是应该使用这样的格式吧？
![image](https://user-images.githubusercontent.com/65850346/211262748-8d43bc6b-72f0-4ca5-8b00-95159dbfd141.png)
