### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by nhathoang0110** [hukaixuan19970627/yolov5_obb#183]
Can you guide how to create dataset for the new version. I use the old version very well but the new repo after changing the dataset format, although when I stop viewing the images for example train_batch0,1,2 it is still correct but the results after training are very bad

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/150643301-b30a7872-3880-4b1f-af12-d49a1516b4c5.png)
You can refer to [GetStart.md](https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/GetStart.md)
