### ISSUE TITLE
Training error：'Nonetype' object has no attribute 'python_exit_status'

### ISSUE THREAD

**Issue by nhathoang0110** [hukaixuan19970627/yolov5_obb#184]
![image](https://user-images.githubusercontent.com/55668910/150664131-06a0ba1f-eb80-4c56-a268-a3d742e7a725.png)
When the training is over, this error appears, do you know what it is and how it affects you?

**Comment by hukaixuan19970627** [comment]
I haven't met this error. Maybe you should check your [requirements](https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/install.md)
