### ISSUE TITLE
训练报RuntimeError: CUDA error: device-side assert triggered 

### ISSUE THREAD

**Issue by yangl720** [hukaixuan19970627/yolov5_obb#185]
我使用SGD+yolov5m、SGD+yolov5l，SGD+yolov5x，SGD+yolov5x6都没有问题，但是使用优化器改成adam时就会出现如下错误，每次报错的节点epoch都不一样，但都是在验证这一步出现问题
1.  /pytorch/aten/src/ATen/native/cuda/Indexing.cu:662:indexSelectLargeIndex:block:[4,0,0].thread: (17,0,0] Assertion 'srcIndex < srcSelectDimSize failed.

2. RuntimeError: CUDA error: device-side assert triggered
![20220126101909](https://user-images.githubusercontent.com/93321311/151095483-4d8a0e92-7c6d-4c29-a377-15411e7c096a.jpg)

**Comment by kubbistar** [comment]
same issue here.
我的解决方案是在train中设置noval=True，来跳过每一个epoch的validation

**Comment by hukaixuan19970627** [comment]
#147
