### ISSUE TITLE
关于高斯窗函数半径的问题

### ISSUE THREAD

**Issue by 113HQ** [hukaixuan19970627/yolov5_obb#187]
为什么窗半径直接就是高斯的方差？方差设为1或2，再定义一个窗长，窗长以外的都是0，这样效果会不会更好？

**Comment by hukaixuan19970627** [comment]
建议看一遍CSL原文

**Comment by hukaixuan19970627** [comment]
。。论文里有，多看几遍。r=0敞口函数就变成脉冲函数了，也就是普通的one+hot标签
