### ISSUE TITLE
为什么有时不显示正在训练的batch图片？

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#188]
这个需要在哪里设定呢

**Comment by hukaixuan19970627** [comment]
遇到问题可以先自己debug一下定位问题源头。要么就描述详细一点，起码你得让人复现你遇到的问题不是？
实现画train_batch图片的函数是on_train_batch_end

**Comment by HKVINS89757** [comment]
好的哈 ，谢谢
