### ISSUE TITLE
pycocotools unable to run: Results do not correspond to current coco set

### ISSUE THREAD

**Issue by shenhaibb** [hukaixuan19970627/yolov5_obb#189]
我先用DOTA2COCO.py生成了val.json
然后val.py测试，想获得APs APm APl
但是报了错误
![image](https://user-images.githubusercontent.com/64736467/151495574-8fc6b2dd-c1dc-410c-8a2d-3c76d5014861.png)
是因为coco评估只能评估垂直框，不支持评估旋转框吗

**Comment by shenhaibb** [comment]
之前用hbb的时候，还是yolo格式的，我将yolo格式转换成了coco格式，可以出来评估结果，想问下您，旋转框的时候需要怎么弄呢

**Comment by shenhaibb** [comment]
这个错误我从1开始命名就没了
但是现在又出现了新的错
![QQ20220128-203526@2x](https://user-images.githubusercontent.com/64736467/151548133-a05fee2e-0313-461a-aa27-a013854ad1f7.jpg)
list input can be bounding box (Nx4) or RLEs ([RLE]
是因为coco评估不适合旋转框的吗


**Comment by hukaixuan19970627** [comment]
OBB评估在get start里有。
pycocotools使用时要符合coco json文件的输入规范
