### ISSUE TITLE
关于anchor的问题？

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/yolov5_obb#191]
看着您的anchor有些问题。好像是longside>shortside？为什么会这样呢？您模型用的anchor是默认的吗？和老版的区别挺大的。
![image](https://user-images.githubusercontent.com/54108453/152114491-69ecdeb4-3bc5-49c1-9141-d74cb2ae048d.png)
谢谢

**Comment by hukaixuan19970627** [comment]
初始anchor无所谓，反正不合适的话会k-means重新生成
