### ISSUE TITLE
RuntimeError: CUDA error: device-side assert trigger

### ISSUE THREAD

**Issue by XDxiaoqi** [hukaixuan19970627/yolov5_obb#192]
Epoch   gpu_mem       box       obj       cls     theta    labels  img_size
   143/999      2.1G   0.05015  0.005766  0.001596     0.045         9       640: 100%|██████████| 1/1 [0
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | /opt/conda/conda-bld/pytorch_1603728993639/work/aten/src/ATen/native/cuda/Indexing.cu:605: indexSelectSmallIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

yolov5_obb/utils/nms_rotated/nms_rotated_wrapper.py", line 40, in obb_nms
    inds = nms_rotated_ext.nms_rotated(dets_th, scores, iou_thr)
RuntimeError: CUDA error: device-side assert triggere

**Comment by hukaixuan19970627** [comment]
#147

**Comment by XDxiaoqi** [comment]
非常感谢
