### ISSUE TITLE
关于计算正样本匹配的代码？

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/yolov5_obb#197]
请问大佬，您在知乎上说，yolov5的正样本匹配不是用的iou，而是用的shape阈值匹配。这部分相关的代码写在哪里了呢？什么是shape阈值呢？既然是利用shape阈值，那么与正样本相匹配的anchor的位置是如何确定的呢？那个feature_wh变量是干什么的呢？
十分感谢。

**Comment by hukaixuan19970627** [comment]
1. def build_target()
2. gt框和anchor的wh比值处于一个范围（比如1/4~4）内，说明形状相似，即正样本匹配成功
3. feature_wh代码里表示对应特征层的宽高

**Comment by kuazhangxiaoai** [comment]
> 1. def build_target()
> 2. gt框和anchor的wh比值处于一个范围（比如1/4~4）内，说明形状相似，即正样本匹配成功
> 3. feature_wh代码里表示对应特征层的宽高

那请问与正样本相匹配的anchor的位置是如何确定的呢？只通过max(w0/w1, h0/h1)，只能确定形状的相似性，那位置方面的匹配，是如何完成的呢？是使用iou算的吗？
