### ISSUE TITLE
训练自定义数据集时出现index XXX out of range for tensor size [ ] at dimension 0的错误

### ISSUE THREAD

**Issue by calvinIsAwesome** [hukaixuan19970627/yolov5_obb#200]
请问以上错误是什么原因造成的呢以及如何解决？多谢！
<img width="820" alt="Screen Shot 2022-02-15 at 10 33 46 AM" src="https://user-images.githubusercontent.com/24402619/153982605-983febde-55bb-46a1-9a37-6c9edf9991d1.png">
！

**Comment by hukaixuan19970627** [comment]
介绍一下数据集的情况，另外把训练时生成的所有文件都发一下，方便定位问题

**Comment by calvinIsAwesome** [comment]
> 介绍一下数据集的情况，另外把训练时生成的所有文件都发一下，方便定位问题

使用的是自己标定的飞机旋转目标，用Matlab写了个转换数据格式的代码转换成了getstart.md中所需要的格式如下
<img width="546" alt="Screen Shot 2022-02-15 at 2 11 19 PM" src="https://user-images.githubusercontent.com/24402619/154003397-1e070c7c-cbf2-4e14-bcbb-fbc67e4c48ca.png">
<img width="714" alt="Screen Shot 2022-02-15 at 2 11 36 PM" src="https://user-images.githubusercontent.com/24402619/154003434-2bd32283-8fda-4941-8257-ae4e638b5d44.png">
<img width="1002" alt="Screen Shot 2022-02-15 at 2 08 34 PM" src="https://user-images.githubusercontent.com/24402619/154003488-b728f491-7e87-4cc9-8a2b-6b7957c07664.png">
测试训练： python3 train.py --device cpu --single-cls --batch-size 2 --imgsz 256 --epochs 2
<img width="1061" alt="Screen Shot 2022-02-15 at 2 17 41 PM" src="https://user-images.githubusercontent.com/24402619/154003683-075d2aee-d49b-46cd-af6d-5c3be174992b.png">
一般有概率出现如上所示错误
生成文件如下所示：
<img width="901" alt="Screen Shot 2022-02-15 at 2 19 05 PM" src="https://user-images.githubusercontent.com/24402619/154003853-b2e9b657-6cae-4508-8325-de26ebb9165c.png">
<img width="903" alt="Screen Shot 2022-02-15 at 2 19 26 PM" src="https://user-images.githubusercontent.com/24402619/154003900-aa9e5d38-b107-4ceb-9a5d-ea924709d477.png">
<img width="583" alt="Screen Shot 2022-02-15 at 2 19 51 PM" src="https://user-images.githubusercontent.com/24402619/154003943-72e3dbf3-898a-4a86-9ce8-04e37a291672.png">
<img width="974" alt="Screen Shot 2022-02-15 at 2 20 03 PM" src="https://user-images.githubusercontent.com/24402619/154003967-42913055-2f8e-42ea-a321-5b00b19f1f6d.png">
转换的时候四边形定点取整使用了round函数，会不会是因为生成的bbox不是规整矩形导致dets有out of range的数据产生？
<img width="850" alt="Screen Shot 2022-02-15 at 2 24 42 PM" src="https://user-images.githubusercontent.com/24402619/154004606-d52e47fd-9c67-4f2c-b16b-8473be3b0df1.png">

**Comment by chl916185** [comment]
遇到了和你一样的问题，是在对验证集进行验证出现的，怎么解决呢，

**Comment by calvinIsAwesome** [comment]
> 遇到了和你一样的问题，是在对验证集进行验证出现的，怎么解决呢，



> 遇到了和你一样的问题，是在对验证集进行验证出现的，怎么解决呢，

我好像也是val的时候遇到的，希望大神能有解决方法提供🙏

**Comment by chl916185** [comment]
可以看看作者的这个回复，[](https://github.com/hukaixuan19970627/yolov5_obb/issues/147)

**Comment by calvinIsAwesome** [comment]
> 可以看看作者的这个回复，[https://github.com/hukaixuan19970627/yolov5_obb/issues/147](url)

您的得到解决了？

**Comment by hukaixuan19970627** [comment]
val.py报问题的话，按这个回答检查下： https://github.com/hukaixuan19970627/yolov5_obb/issues/147#issuecomment-1009625752
单目标检测把nc改为2，name另一个名字随意取，检测效果会好一点

**Comment by calvinIsAwesome** [comment]
> val.py报问题的话，按这个回答检查下： [#147 (comment)](https://github.com/hukaixuan19970627/yolov5_obb/issues/147#issuecomment-1009625752)
> 单目标检测把nc改为2，name另一个名字随意取，检测效果会好一点

您好，是在train.py中出现了此问题。好像是因为dets (tensor/array): (num, [cx cy w h θ]) θ∈[-pi/2, pi/2)中维度出现溢出所以报错index XXX out of range for tensor size [XXX，5 ] at dimension 0，数据集标定用的rolabelImg，但格式转换自己后来用matlab转换的，会不会是因为bbox数据出现了问题？然后修改了可能会出现超过图像边界点的值的问题，但报错依然存在，请问还有什么情况会导致溢出么？或者有没有可以直接进行数据格式转换的工具？多谢～

**Comment by hukaixuan19970627** [comment]
> > val.py报问题的话，按这个回答检查下： [#147 (comment)](https://github.com/hukaixuan19970627/yolov5_obb/issues/147#issuecomment-1009625752)
> > 单目标检测把nc改为2，name另一个名字随意取，检测效果会好一点
> 
> 您好，是在train.py中出现了此问题。好像是因为dets (tensor/array): (num, [cx cy w h θ]) θ∈[-pi/2, pi/2)中维度出现溢出所以报错index XXX out of range for tensor size [XXX，5 ] at dimension 0，数据集标定用的rolabelImg，但格式转换自己后来用matlab转换的，会不会是因为bbox数据出现了问题？然后修改了可能会出现超过图像边界点的值的问题，但报错依然存在，请问还有什么情况会导致溢出么？或者有没有可以直接进行数据格式转换的工具？多谢～

train.py验证操作时会调用val，一样按那个评论进行问题排查

**Comment by calvinIsAwesome** [comment]
> > > val.py报问题的话，按这个回答检查下： [#147 (comment)](https://github.com/hukaixuan19970627/yolov5_obb/issues/147#issuecomment-1009625752)
> > > 单目标检测把nc改为2，name另一个名字随意取，检测效果会好一点
> > 
> > 
> > 您好，是在train.py中出现了此问题。好像是因为dets (tensor/array): (num, [cx cy w h θ]) θ∈[-pi/2, pi/2)中维度出现溢出所以报错index XXX out of range for tensor size [XXX，5 ] at dimension 0，数据集标定用的rolabelImg，但格式转换自己后来用matlab转换的，会不会是因为bbox数据出现了问题？然后修改了可能会出现超过图像边界点的值的问题，但报错依然存在，请问还有什么情况会导致溢出么？或者有没有可以直接进行数据格式转换的工具？多谢～
> 
> train.py验证操作时会调用val，一样按那个评论进行问题排查

已解决，多谢
