### ISSUE TITLE
关于hrsc2016数据集

### ISSUE THREAD

**Issue by shenhaibb** [hukaixuan19970627/yolov5_obb#201]
我用HRSC2DOTA.py进行转换数据集
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/64736467/153984631-1a37e842-8aef-40f4-b56b-7b22ce4630f0.png">
进行训练的时候
![QQ20220214-213011@2x](https://user-images.githubusercontent.com/64736467/153984675-fb2221c3-3032-4544-bce7-a8fc370a702e.jpg)
然后跑到一半就会报错
![QQ20220214-213025@2x](https://user-images.githubusercontent.com/64736467/153984701-0e8eb70f-504f-4c8d-8754-be4d9337b786.jpg)
为什么转换后的数据集会有负值呢

**Comment by shenhaibb** [comment]
出现warning的图片，cache会排除这些图片进行训练吗

**Comment by shenhaibb** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/147#issuecomment-1009625752 我试试这个

**Comment by hukaixuan19970627** [comment]
自定义数据集在转成poly形式坐标时，做一下clip处理，使坐标取值范围落在图像范围内。
如果自定义数据集包含切割操作的话，参考一下dota数据集对待不完整目标的做法:
![image](https://user-images.githubusercontent.com/72599120/154617027-2852051b-356a-4e6e-aa7a-f3a0dc9a8e8b.png)

另外srcIndex那个问题在最新提交的PR https://github.com/hukaixuan19970627/yolov5_obb/commit/0fd0d673eac4f2478822d5d526f237c2eaf49123中已修复
