### ISSUE TITLE
cannot import name 'nms_rotated_ext' (运行train文件报错)

### ISSUE THREAD

**Issue by GHASCZ** [hukaixuan19970627/yolov5_obb#203]
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import) 想问下大佬这个问题是什么原因导致的呀

**Comment by hukaixuan19970627** [comment]
环境没装好，先看一遍install.md和getstart.md

**Comment by GHASCZ** [comment]
> 环境没装好，先看一遍install.md和getstart.md

![image](https://user-images.githubusercontent.com/33053791/154799328-b91df1d9-6bde-408d-b16f-2f1241bc6ced.png)
楼主 我安装完后训练的时候 突然出现了killed的情况 这个是因为我设备的原因吗

**Comment by hukaixuan19970627** [comment]
> > 环境没装好，先看一遍install.md和getstart.md
> 
> ![image](https://user-images.githubusercontent.com/33053791/154799328-b91df1d9-6bde-408d-b16f-2f1241bc6ced.png) 楼主 我安装完后训练的时候 突然出现了killed的情况 这个是因为我设备的原因吗

应该是吧，如果是代码问题导致kill掉的话会显示出错的具体地方和原因。如果是系统kill掉这个进程的话那就没办法了，可以查查日志。
