### ISSUE TITLE
刚开始训练时前三个epoch,precision极高，之后正常

### ISSUE THREAD

**Issue by zwh1221** [hukaixuan19970627/yolov5_obb#204]
![Uploading QQ浏览器截图20220218110619.png…]()
其他指标均正常，precision曲线epoch超过3后也正常，就是不知什么原因

**Comment by zwh1221** [comment]
![QQ浏览器截图20220218110619](https://user-images.githubusercontent.com/57865122/154611447-db7b4318-1468-4531-8531-dc8cd170f90b.png)

**Comment by hukaixuan19970627** [comment]
precision=TP/(TP+FP)，单独一个指标说明不了什么问题
