### ISSUE TITLE
fps计算

### ISSUE THREAD

**Issue by shenhaibb** [hukaixuan19970627/yolov5_obb#205]
![yolov5s](https://user-images.githubusercontent.com/64736467/154798709-299b6a8e-bf4e-4ced-8b57-8ee27f4f3799.jpg)

fps的计算是1/inference time吗
10.4ms = 0.0104s
那就是1s/0.0104s=96.....这么大合理吗。。。

**Comment by hukaixuan19970627** [comment]
只见过有人嫌检测器速度慢，没见过嫌快的。
这是2080Ti下分辨率1024×1024的测试结果，你对比一下看看合不合理。
![image](https://user-images.githubusercontent.com/72599120/154799081-a7561bf2-4cac-4b86-82a5-7b9d7621573f.png)

**Comment by shenhaibb** [comment]
> 只见过有人嫌检测器速度慢，没见过嫌快的。 这是2080Ti下分辨率1024×1024的测试结果，你对比一下看看合不合理。 ![image](https://user-images.githubusercontent.com/72599120/154799081-a7561bf2-4cac-4b86-82a5-7b9d7621573f.png)

哈哈哈哈哈不是的 只是我看到的论文就三四十多 我一直怀疑我算错了

**Comment by hukaixuan19970627** [comment]
> > 只见过有人嫌检测器速度慢，没见过嫌快的。 这是2080Ti下分辨率1024×1024的测试结果，你对比一下看看合不合理。 ![image](https://user-images.githubusercontent.com/72599120/154799081-a7561bf2-4cac-4b86-82a5-7b9d7621573f.png)
> 
> 哈哈哈哈哈不是的 只是我看到的论文就三四十多 我一直怀疑我算错了

测速度的话要公平对比的，像yolov5自带FP16推理，所以推理速度可能比FP32的快一倍

**Comment by shenhaibb** [comment]
好勒 谢谢大佬指点！
