### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by ZhangRan24** [hukaixuan19970627/yolov5_obb#206]
Transferred 507/513 items from weights/yolov5m.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 83 weight, 94 weight (no decay), 86 bias
train: Scanning '/home/zhangranran/Research/yolov5_obb-master/dataset/dota/train
train: WARNING: /home/zhangranran/Research/yolov5_obb-master/dataset/dota/train/images/P0032.png: ignoring corrupt image/label: 'large-vehicle' is not in list
train: New cache created: /home/zhangranran/Research/yolov5_obb-master/dataset/dota/train/labelTxt.cache
Traceback (most recent call last):
  File "/home/zrr/Research/yolov5_obb-master/train.py", line 632, in <module>
    main(opt)
  File "/home/zrr/Research/yolov5_obb-master/train.py", line 529, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/zrr/Research/yolov5_obb-master/train.py", line 213, in train
    train_loader, dataset = create_dataloader(train_path, imgsz, batch_size // WORLD_SIZE, gs, names, single_cls,
  File "/home/zrr/Research/yolov5_obb-master/utils/datasets.py", line 101, in create_dataloader
    dataset = LoadImagesAndLabels(path, names, imgsz, batch_size,
  File "/home/zrr/Research/yolov5_obb-master/utils/datasets.py", line 444, in __init__
    labels, shapes, self.segments = zip(*cache.values())
ValueError: not enough values to unpack (expected 3, got 0)

请问这个问题是数据的原因么？

**Comment by ZhangRan24** [comment]
请问这个问题是数据的原因么

**Comment by hukaixuan19970627** [comment]
getstarted.md都跑通了吗，里面有准备好的数据集demo，你按照那个格式弄你自己的数据集就行

**Comment by ZhangRan24** [comment]
非常感谢您的回复，按照您说的用demo运行这个ImgSplit_multi_process.py生成的数据是可以了！我偷懒了直接用了自己的数据+之前那一个版本提供DOTA_devkit中的ImgSplit_multi_process.py生成的文件。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hukaixuan19970627/yolov5_obb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月20日(星期天) 中午1:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hukaixuan19970627/yolov5_obb] ValueError: not enough values to unpack (expected 3, got 0) (Issue #206)





 
getstarted.md都跑通了吗，里面有准备好的数据集demo，你按照那个格式弄你自己的数据集就行
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZhangRan24** [comment]
您好，还想请教您一个问题。我知道我之前为什么会出现错误了。是因为我自己的数据集里面有很多普通目标检测中的端正框（ploy的四个点是从左上角开始，顺时针）。
当我用ImgSplit_multi_process.py切割图像的时候，发现端正框的标签信息没有被保存下来。有很多空白的.txt标签文件。
为了能够将端正框的标签信息保存下来，对ImgSplit_multi_process.py文件做了如下修改。虽然标签信息能够被保存，但是训练的时候由于标签被程序认为无效，自动不训练对应的训练图像。我分割后的每张图都有端正框，所以最终相当于没有训练图像了。所以还想请教一下您关于ImgSplit_multi_process.py切割端正框得问题。
![image](https://user-images.githubusercontent.com/27479531/154847244-ae2ad4b8-5995-4e2e-8991-9f740124ea8b.png)

**Comment by hukaixuan19970627** [comment]
没听明白，你能加点可视化图片进行辅助说明吗；
另外自制数据集label格式只要和DOTA一致（任意四边形poly坐标）是可以直接用DOTA-Devkit工具进行切割的，不需要更改代码。
