### ISSUE TITLE
运行预测文件ResultMerge_multi_process出错

### ISSUE THREAD

**Issue by GHASCZ** [hukaixuan19970627/yolov5_obb#207]
楼主 想问下运行预测文件的时候 obb_predictions_Txt_Merged这个文件夹下整合的是空的
![image](https://user-images.githubusercontent.com/33053791/154881538-25080957-8296-4478-945c-ddcf80173cbb.png)
然后运行dota_evaluation_task1.py这个文件就报错了呢 
![image](https://user-images.githubusercontent.com/33053791/154881702-6c8c5978-1d6e-4676-bf29-096d89badef0.png)
这里需要改动什么嘛 我是用的val文件夹下的图片进行验证的

**Comment by hukaixuan19970627** [comment]
使用流程请参考GetStart.md，里面有demo

**Comment by Henry-web1** [comment]
请问你解决这个问题了吗
