### ISSUE TITLE
label format

### ISSUE THREAD

**Issue by weijie1111** [hukaixuan19970627/yolov5_obb#208]
你好，请问一下我的数据集标签是下图 您看可以吗，看您最新的代码，改进成了，每一个点的坐标，这个有点不太懂。
我的数据集是自己制作的数据集，但是不需要切割，请问，您切割的代码在哪个地方（有点笨，没有找到）。如果，要按照您最新的标签训练，请问，您有转标的代码吗。 您网络的改进，比如替换backbone，是和YOLOv5的修改同样的吗
![image](https://user-images.githubusercontent.com/73890136/154956372-54b85842-6dfb-4fb2-a91e-43dfefc54cd3.png)

**Comment by hukaixuan19970627** [comment]
项目大改过了，重新安装下环境和熟悉下使用流程吧，花十分钟跟readme走一遍install、getstart流程就都清楚了

**Comment by weijie1111** [comment]
你好，请问，您的数据集是如何标注的，原来我用的是旋转框，现在对您新的项目，这种四点坐标导出感觉比较困难，所以想问您一下，有没有简易

**Comment by hukaixuan19970627** [comment]
emmm，旋转框也是四边形，也有四点坐标，你把它转换过来不就可以了吗。
转换代码你可以参考项目里的def rbox2poly():(长边表示法转poly)
![image](https://user-images.githubusercontent.com/72599120/156115314-06229468-d981-436f-bdaf-6b879dbc1875.png)

**Comment by wubalahao** [comment]
> 你好，请问一下我的数据集标签是下图 您看可以吗，看您最新的代码，改进成了，每一个点的坐标，这个有点不太懂。 我的数据集是自己制作的数据集，但是不需要切割，请问，您切割的代码在哪个地方（有点笨，没有找到）。如果，要按照您最新的标签训练，请问，您有转标的代码吗。 您网络的改进，比如替换backbone，是和YOLOv5的修改同样的吗 ![image](https://user-images.githubusercontent.com/73890136/154956372-54b85842-6dfb-4fb2-a91e-43dfefc54cd3.png)

老哥你的问题解决了吗
