### ISSUE TITLE
召回率太低

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#210]
![image](https://user-images.githubusercontent.com/42164696/155162263-0d663ea7-1900-499f-8344-1eac1b709d7b.png)

作者您好，上图可以看出有个别的分类召回率过低，这个除了锚框的设定可能会导致这种问题之外(大多是长宽比比较大的甚至长低于10个像素，宽可能到100个像素以上)，还可能有其他问题么？

**Comment by hukaixuan19970627** [comment]
你得先确定引起召回率低的诱因，是因为漏检、定位框不准、还是识别成了错误的分类？之后才好分析
