### ISSUE TITLE
windows：Error compiling objects for extension

### ISSUE THREAD

**Issue by BigHao6** [hukaixuan19970627/yolov5_obb#211]
问题：
        （1）安装yolov5-obb报错，截图如下：
![IC7IPL8$ZGSRS8EM @_)U8S](https://user-images.githubusercontent.com/100271256/155279453-65c855ba-259b-456e-b10d-0544daed677a.png)
       （2）运行时出现错误，截图如下：
![)@ TU6}C@WG%SVK9V6`65WD](https://user-images.githubusercontent.com/100271256/155279576-6d5c00b7-58b3-4e3f-93fc-e28adfa997fd.png)

安装的环境如下：
         （1）显卡所支持的最高cuda驱动为10.1，截图如下：
![)RPK}3OMF2ER%Z37T{ EA(7](https://user-images.githubusercontent.com/100271256/155279971-80c8a6c7-1226-491a-b702-9b2c665b1f9a.png)
          （2）cuda工具包版本（运行时版本）为10.1，截图如下：
M(XM](https://user-images.githubusercontent.com/100271256/155280261-3c939c62-334a-411f-ab92-b3344d73ea4c.png)
           （3）进行安装的torch使用的命令是：
 CUDA 10.1
pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
安装的是cuda为10.1时所支持的最高torch版本

困扰：已经满足了CUDA 驱动程序版本 ≥ CUDA 工具包版本（运行时版本） = torch.version.cuda，不知道哪里还出错了，请各位大佬指教

**Comment by hukaixuan19970627** [comment]
建议找到报错的位置，然后根据error提示来慢慢修改，windows编译这类带c++的项目很麻烦，我身边没有带nvidia显卡的windows电脑，解决不了。
建议你搜搜看同类型的问题看看别人是怎么解决的https://github.com/hukaixuan19970627/yolov5_obb/issues?q=windows

**Comment by BigHao6** [comment]
> 建议找到报错的位置，然后根据error提示来慢慢修改，windows编译这类带c++的项目很麻烦，我身边没有带nvidia显卡的windows电脑，解决不了。 建议你搜搜看同类型的问题看看别人是怎么解决的https://github.com/hukaixuan19970627/yolov5_obb/issues?q=windows

嗯嗯好嘞

**Comment by xxxjjjx** [comment]
> 

请问你解决这个问题了吗

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/224
