### ISSUE TITLE
About the val

### ISSUE THREAD

**Issue by fzhq** [hukaixuan19970627/yolov5_obb#212]
大佬，您好。首先感谢您的项目。在不需要切割的数据集上评估时，直接使用val.py得到mAP结果不可以吗？为什么先获取HBB指标，再合成为poly形式，最后通过DOTA_devkit得到mAp呢？

**Comment by hukaixuan19970627** [comment]
网络输出的是obb结果，但在后处理代码中会同时生成一个hbb结果，因为原始的val.py只支持hbb评估，懒得改动太多代码，这样操作又省事儿训练效率还高。之后保存obb结果用DOTA_devkit评估就行

**Comment by fzhq** [comment]
> 网络输出的是obb结果，但在后处理代码中会同时生成一个hbb结果，因为原始的val.py只支持hbb评估，懒得改动太多代码，这样操作又省事儿训练效率还高。之后保存obb结果用DOTA_devkit评估就行

您的意思是在线评估时产生的val_batch是obb的，而val.py得出的mAP是hbb的，所以要后续那样转化下来计算mAP吗？

**Comment by fzhq** [comment]
大佬，在运行val.py的时候总会显示[Errno 2]No such file or directory: '../coco/annotations/instances_val2017.json'
![Screenshot from 2022-03-01 17-20-37](https://user-images.githubusercontent.com/70955329/156141850-74ee8d5f-6b2b-4b9d-99e7-4644d59e5d47.png)

**Comment by hukaixuan19970627** [comment]
> 大佬，在运行val.py的时候总会显示[Errno 2]No such file or directory: '../coco/annotations/instances_val2017.json' ![Screenshot from 2022-03-01 17-20-37](https://user-images.githubusercontent.com/70955329/156141850-74ee8d5f-6b2b-4b9d-99e7-4644d59e5d47.png)

你本来就没有这个json文件，这个是指训练集的json文件，反正pycocotools也只支持HBB评估，没啥用，忽略就行
