### ISSUE TITLE
final format

### ISSUE THREAD

**Issue by yang-gis** [hukaixuan19970627/yolov5_obb#213]
您好作者。
`def poly2rbox_single(poly):
    """
    poly:[x0,y0,x1,y1,x2,y2,x3,y3]
    to
    rrect:[x_ctr,y_ctr,w,h,angle]`
这个代码是将四点坐标的poly转为x_ctr,y_ctr,w,h,angle格式，我有点疑惑，就是您这个转换貌似最后return的并没有进行归一化，这样输入到yolo网络应该是不行的。或者是您在poly:[x0,y0,x1,y1,x2,y2,x3,y3]做了归一化吗？所以转为rrect:[x_ctr,y_ctr,w,h,angle]就不需要再做归一化了？

**Comment by yang-gis** [comment]
> 1. yolov5_obb中的yolo网络不需要进行label进行归一化便可以训练
> 
>     2. yolov5_obb的预处理代码是重建过的，Data Augmentation全程以poly形式进行，训练时会转换为长边表示法。
额，我看作者您在知乎中并无提及此事。此外，不管您是任何表示方法，应该都要做归一化才可以往yolo网络入口输入才对。。。很不理解

**Comment by yang-gis** [comment]
![图片](https://user-images.githubusercontent.com/49702076/156305051-e248ddab-2333-4675-ad28-9dc7c4cf1520.png)

**Comment by yang-gis** [comment]
> ![图片](https://user-images.githubusercontent.com/49702076/156305051-e248ddab-2333-4675-ad28-9dc7c4cf1520.png)

这种长边表示法的xc、yc、longside、shortside theta这些值按道理都应要归一化才可以往yolo网络里输入

**Comment by yang-gis** [comment]
![图片](https://user-images.githubusercontent.com/49702076/156305286-b4164a48-efea-42a7-9360-0225ebbbb7ae.png)
类似这个人参考您的这个repo，他也是做了归一化的。所以不是很理解您的说法

**Comment by yang-gis** [comment]
> 1. yolov5_obb中的yolo网络不需要进行label进行归一化便可以训练
> 
>     2. yolov5_obb的预处理代码是重建过的，Data Augmentation全程以poly形式进行，训练时会转换为长边表示法。

![图片](https://user-images.githubusercontent.com/49702076/156307322-2014858c-fafd-4bf5-9d84-a8a4836d1323.png)
也就是说，我只需将数据标签按照上面准备，代码后面在开始训练后会自动进行长边表示法转换？

**Comment by yang-gis** [comment]
另外diffcult的设置应该如何设置呢？

**Comment by yang-gis** [comment]
> 1. 为什么要归一化？因为原版yolov5只支持归一化后的label输入，那我更改代码让网络结构支持非归一化的label输入不就行了吗。yolov5_obb老版本的代码确实是需要归一化的，不过这个版本不需要。
> 
>     2. 知乎上的是第一版的代码说明，这个项目已经release一年多了，版本是要更迭的，所以一切以github上的为准，readme里的环境安装、使用流程demo都是最新的。
> 
>     3. 至于为什么大改，主要原因是按照原版yolov5的数据处理逻辑来处理旋转检测图像的话，训练效率会很低，不容易达到精度上限，而且归一化后的label会出现各种各样的问题（例如不支持任意宽高的图像进行训练等等），这个版本无论是训练速度、使用限制还是最终精度都要比老版本的代码好。每个大版本的改动说明都会放在changelog.md里，你可以直接参考，更具体地就得看代码了

多的多谢大佬指导

**Comment by d5423197** [comment]
作者你好,

看源码后, 看到difficult是2就跳过, 没有找到这个difficult还又别的什么用途, 请问这个difficult参数是还有什么用途

谢谢,

ZD

**Comment by hukaixuan19970627** [comment]
> 作者你好,
> 
> 看源码后, 看到difficult是2就跳过, 没有找到这个difficult还又别的什么用途, 请问这个difficult参数是还有什么用途
> 
> 谢谢,
> 
> ZD

没有用途，单纯是为了删除DOTA数据集切割时出现的极难识别的不完整目标，从而稳定训练。
![image](https://user-images.githubusercontent.com/72599120/167290238-04e9b3ba-7d4c-4a15-b7de-5cf4d2823ce8.png)
