### ISSUE TITLE
label format

### ISSUE THREAD

**Issue by yang-gis** [hukaixuan19970627/yolov5_obb#216]
大佬，请问。我们在数据准备时是需要制作成下面你给的getstart中的样子吗：
![图片](https://user-images.githubusercontent.com/49702076/156387688-a4fd4c7a-4197-485b-b1a7-816a713d90fb.png)
另外，请问大佬difficult这个值如何给定，是随便给一个吗，这个difficult在后续训练时重要吗？

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/156502740-72a1b7d5-3f0d-4e92-bedb-213a300d6154.png)

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/156502805-fd8d6f24-2417-4788-ac5f-ed0428911b0a.png)

**Comment by yang-gis** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/156502805-fd8d6f24-2417-4788-ac5f-ed0428911b0a.png)

作者这个实在让人搞不明白。
![图片](https://user-images.githubusercontent.com/49702076/156503177-843c9db7-b0ff-44a2-8d6f-3372ef651eca.png)
通过这个图片可以看到你的数据输入格式并不符合下面的图片所示格式：
![图片](https://user-images.githubusercontent.com/49702076/156503286-2dfe549e-b09c-4721-b6f3-e7eb1594931c.png)
