### ISSUE TITLE
训练单个类别的数据出现map0.5几乎为0的情况

### ISSUE THREAD

**Issue by Trzyh** [hukaixuan19970627/yolov5_obb#220]
数据：烟码（每条烟上面都有一个32位的数字），其中有一部分数字是倾斜的，我需要得到一个旋转的矩形框。
问题:由于我的数据是的单个类别，但看你知乎说这个单类别识别问题在最新版本的代码已经解决了，然而我的map0.5还是几乎为0，我又不需要加入新的类别，怕影响对烟码的检测精度
我的数据输入：先把图片resize成688*600的，然后输入网络进行训练
![Uploading IMG_0326.jpg…]()
![Uploading 97ELD({)2FEYPHL(%BJEZHT.png…]()
![`EYO)Z1I~I0DN8ZP0(S9}7U](https://user-images.githubusercontent.com/45352707/156715727-6a499d96-1119-4ac6-8fd4-17ab5b2a7493.png)
。

**Comment by hukaixuan19970627** [comment]
你把训练生成的所有文件都上传一下。

**Comment by Trzyh** [comment]
这边上传不了，出现一些错误，我发邮件给你？

**Comment by Trzyh** [comment]
[results.csv](https://github.com/hukaixuan19970627/yolov5_obb/files/8184236/results.csv)
![results](https://user-images.githubusercontent.com/45352707/156727248-1ea033ee-d075-41e4-b10b-6db10c3c16b9.png)
![P_curve](https://user-images.githubusercontent.com/45352707/156727265-c4abadf2-26dd-44bd-aa3f-ef714e9e5923.png)
![PR_curve](https://user-images.githubusercontent.com/45352707/156727271-c349ea42-f839-4b51-9ce9-fc940d6122b6.png)
![train_batch0](https://user-images.githubusercontent.com/45352707/156727295-c51cbfd7-4283-4814-a6bc-77ccd64ae275.jpg)

![R_curve](https://user-images.githubusercontent.com/45352707/156727279-b9016c4d-5948-4234-b271-f0e412cf9c5f.png)

**Comment by Trzyh** [comment]
![confusion_matrix](https://user-images.githubusercontent.com/45352707/156727573-a2f56eb5-f16f-4bc9-be03-caec67bd490c.png)

**Comment by Trzyh** [comment]
![labels_correlogram](https://user-images.githubusercontent.com/45352707/156727653-6a1a0204-6752-4fa5-9131-c06672a49205.jpg)

**Comment by Trzyh** [comment]
![labels_xyls](https://user-images.githubusercontent.com/45352707/156727669-45413115-ef83-4ced-948f-9a4c6194a720.jpg)

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/156732396-47e470d0-de6e-44d1-97c6-d89da99bbb46.png)

**Comment by pyl62112991** [comment]
请问问题解决了吗？我也是出现了这种情况
