### ISSUE TITLE
训练问题，在图像边缘得目标检测效果不佳，漏检严重

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#221]
作者您好，再次感谢您的开源风险，我训练得时候在图像中间完整的目标检测效果不错，但是图像边缘的目标就效果比较差，我的训练参数文件如下：
请问是哪个参数来调节这个问题呢？是 shear么？

# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

lr0: 0.002
lrf: 0.2
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.05
cls: 0.66
cls_pw: 0.825
theta: 0.44
theta_pw: 0.6
obj: 0.97
obj_pw: 1.525
iou_t: 0.20
anchor_t: 3.2
#anchors: 3.2
fl_gamma: 0.0
hsv_h: 0.01
hsv_s: 0.45
hsv_v: 0.33
degrees: 180.0
translate: 0.245
scale: 0.56
shear: 0.56
perspective: 0.0
flipud: 0.5
fliplr: 0.5
mosaic: 0.95
mixup: 0.1
copy_paste: 0.0
cls_theta: 180
csl_radius: 2.0

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/156871509-b7e7fc9c-238f-459a-aa39-ad3094e3d826.png)
把上述选定的文件提供一下

**Comment by HKVINS89757** [comment]
这些jpg文件我好像没有哎，opt.yaml是啥

**Comment by HKVINS89757** [comment]
shear剪切的方式是怎么样的呢

**Comment by HKVINS89757** [comment]
[results.csv](https://github.com/hukaixuan19970627/yolov5_obb/files/8190140/results.csv)

**Comment by HKVINS89757** [comment]
训练的时候中间修了几次参数

**Comment by HKVINS89757** [comment]
主要是 cls  theta  obj的权重值

**Comment by hukaixuan19970627** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/156871509-b7e7fc9c-238f-459a-aa39-ad3094e3d826.png) 把上述选定的文件提供一下

配合可视化图片详细描述一下问题，再以截图的形式把上述文件提供一下，都是训练生成的文件，不可能没有。

**Comment by HKVINS89757** [comment]
这个shear是剪切的概率(比如1一张图的被剪切的概率)呢，还是对目标剪切的大小(设置成0.56 就是只保留剪切后面积大于0.56的目标吗)呢？


![image](https://user-images.githubusercontent.com/42164696/156884566-eeec6d82-010b-4fb3-aac9-2ecb9e34af3f.png)
![image](https://user-images.githubusercontent.com/42164696/156884628-7bd8f5b7-2c97-48e4-8eff-a3aceed461e1.png)

比如上图 这样半截的就没有出现检测结果

**Comment by hukaixuan19970627** [comment]
1. 你不提供那些文件我就无法判断训练情况，只能靠瞎猜，整理一下重新提供一次。
2. 不明白参数代表的具体意义的话最好不要调节默认参数，如果非要调整的话就关注一下trainbatch图片，和数据增强有关的操作都可以从trainbatch0/1/2图片中体现出来，它的作用就是将前几个iter中的batch数据可视化（默认显示前8个batch的数据，可通过utils/loggers/__init__.py中的def on_train_batch_end()进行调节）。
![image](https://user-images.githubusercontent.com/72599120/156912248-05926279-e24c-47d4-ad0a-96e2f46a38bb.png)

**Comment by HKVINS89757** [comment]
好的哈我重新训练整理一下

**Comment by HKVINS89757** [comment]
![image](https://user-images.githubusercontent.com/42164696/157579265-c192a4a7-87cc-4f98-89bc-953a9ceb9e29.png)
大佬，比如我像让切过后的最左面这个目标也打上标签，应该调整哪个参数呢？

**Comment by HKVINS89757** [comment]
就是最左面哪个切过之后还剩一般的目标，这个应该调整哪个参数呢

**Comment by HKVINS89757** [comment]
![image](https://user-images.githubusercontent.com/42164696/157579596-f7bbc7d6-96d3-4818-8344-aa560c621994.png)
是调整这个0.6么

**Comment by HKVINS89757** [comment]
![image](https://user-images.githubusercontent.com/42164696/157581332-dc74249b-207e-4a25-8f32-5221295c76e5.png)
![image](https://user-images.githubusercontent.com/42164696/157581370-ee1d0f01-b88d-48e6-a33a-6b190950a9fe.png)
好像也不是，调成0.1都打不上标签

**Comment by HKVINS89757** [comment]
好像也不是这个
![image](https://user-images.githubusercontent.com/42164696/157584579-4852099b-2ec1-4066-ba91-7e492f451bf9.png)

**Comment by HKVINS89757** [comment]
![image](https://user-images.githubusercontent.com/42164696/157584619-fa49cbd1-a789-49e6-baa5-c6ce0ac67e54.png)



从这个框看的话阈值好像是0.5左右

**Comment by HKVINS89757** [comment]
难道是在mosaic里面么

**Comment by HKVINS89757** [comment]
![image](https://user-images.githubusercontent.com/42164696/157591029-98b1e0e1-4ce2-4c4a-a14b-be0188b3675b.png)
貌似这个segments 是0呀

**Comment by HKVINS89757** [comment]
![image](https://user-images.githubusercontent.com/42164696/157592957-c7d612ee-0c60-49ce-be3d-e4608a67bbcf.png)
这一句话好像是没有作用的

**Comment by HKVINS89757** [comment]
好像是在这里过滤的？ 中心点在图像里需要？
![Uploading image.png…]()
