### ISSUE TITLE
How to export onnx model？

### ISSUE THREAD

**Issue by Madara25** [hukaixuan19970627/yolov5_obb#222]
用yolov5原生的export.py得出的onnx模型，解析出的矩阵似乎少了代表角度的这一项

**Comment by hukaixuan19970627** [comment]
。。。我这项目里不是有export.py吗，为啥非得用原生的呢，原生的只支持HBB检测当然没有角度的预测分支，yolov5_obb才支持obb检测

**Comment by Madara25** [comment]
感谢老师的回复，我尝试了yolov5_obb里的export.py，但在import的时候就报错
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import) (E:\Workshop\yolo_detection\yolov5_obb-master\utils\nms_rotated\__init__.py)
似乎是有环状引用。

**Comment by hukaixuan19970627** [comment]
> 感谢老师的回复，我尝试了yolov5_obb里的export.py，但在import的时候就报错 ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import) (E:\Workshop\yolo_detection\yolov5_obb-master\utils\nms_rotated__init__.py) 似乎是有环状引用。

[install.md](https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/install.md)

**Comment by GalSang17** [comment]
@hukaixuan19970627 老师你好，感谢你的项目，我目前使用DOTAv1.5训练了一个简单的模型，导出为onnx进行推理也没有问题，我想问如果onnx转TensorRT的engine格式需要在YOLOv5原作的C++转换代码上作何改动？

**Comment by hukaixuan19970627** [comment]
> engine

![image](https://user-images.githubusercontent.com/72599120/157412783-9f2553e4-57fb-40f7-9b78-826eadc9b355.png)
export.py直接转就行了，前提是TensorRT的环境要安装对

**Comment by GalSang17** [comment]
> > engine
> 
> ![image](https://user-images.githubusercontent.com/72599120/157412783-9f2553e4-57fb-40f7-9b78-826eadc9b355.png) export.py直接转就行了，前提是TensorRT的环境要安装对

感谢指导，但engine的推理结果似乎不太正确，像这几张截图
![image](https://user-images.githubusercontent.com/49866330/157416641-1d3d81f0-1826-486e-be97-ae93174b75f1.png)
![image](https://user-images.githubusercontent.com/49866330/157416985-30e0a0f8-f846-418f-b677-78c96a2b4baf.png)

**Comment by hukaixuan19970627** [comment]
> > > engine
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/72599120/157412783-9f2553e4-57fb-40f7-9b78-826eadc9b355.png) export.py直接转就行了，前提是TensorRT的环境要安装对
> 
> 感谢指导，但engine的推理结果似乎不太正确，像这几张截图，应该不会是TendorRT8和7.2.3的差异导致的吧？ ![image](https://user-images.githubusercontent.com/49866330/157416641-1d3d81f0-1826-486e-be97-ae93174b75f1.png) ![image](https://user-images.githubusercontent.com/49866330/157416985-30e0a0f8-f846-418f-b677-78c96a2b4baf.png)

你转换engine时的命令是什么

**Comment by GalSang17** [comment]
python export.py -weights best.pt --include engine，就是按照脚本注释提示的usage转换的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月9日(周三) 晚上7:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 老师，请问我想把得到的pt模型转为onnx能用yolov5自带的export.py吗 (Issue #222)




    
engine
  
 export.py直接转就行了，前提是TensorRT的环境要安装对
  
感谢指导，但engine的推理结果似乎不太正确，像这几张截图，应该不会是TendorRT8和7.2.3的差异导致的吧？  
  
你转换engine时的命令是什么
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hukaixuan19970627** [comment]
> python export.py -weights best.pt --include engine，就是按照脚本注释提示的usage转换的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年3月9日(周三) 晚上7:14 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 老师，请问我想把得到的pt模型转为onnx能用yolov5自带的export.py吗 (Issue #222) engine export.py直接转就行了，前提是TensorRT的环境要安装对 感谢指导，但engine的推理结果似乎不太正确，像这几张截图，应该不会是TendorRT8和7.2.3的差异导致的吧？ 你转换engine时的命令是什么 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

试一下--half置为True
