### ISSUE TITLE
HRSC2DOTA.py

### ISSUE THREAD

**Issue by chentp-1183** [hukaixuan19970627/yolov5_obb#225]
老师你好！由于实验室硬件资源匮乏，我打算用该模型训练HRSC数据集，在运行prepare_hrsc2016.py文件时，显示：
from DOTA_devkit.HRSC2DOTA import genera6te_txt_labels
ModuleNotFoundError: No module named 'DOTA_devkit.HRSC2DOTA'
应该是DOTA_devkit里面没有HRSC2DOTA文件导致的，在这里想问老师能否提供一下该文件呀？
学生感激不尽！

**Comment by hukaixuan19970627** [comment]
我这个项目没有这个文件哎，DOTA_devkit是从别的项目里copy过来的，你使用这个项目里的DOTA_devkit处理HRSC2016数据集就行。 https://github.com/csuhan/ReDet
