### ISSUE TITLE
置信度的损失函数是怎么计算的

### ISSUE THREAD

**Issue by 7718258** [hukaixuan19970627/yolov5_obb#226]

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/157373943-a8f0568c-7335-4fec-9106-2dd82db282ba.png)

**Comment by 7718258** [comment]
看您知乎的文章里写，置信度分支的权重系数有两种方案，旋转框IOU和水平IOU，项目里用的是哪一种方案呢

**Comment by hukaixuan19970627** [comment]
> 看您知乎的文章里写，置信度分支的权重系数有两种方案，旋转框IOU和水平IOU，项目里用的是哪一种方案呢

采用的是后者。
