### ISSUE TITLE
SSDD Dataset Training Question

### ISSUE THREAD

**Issue by xxxjjjx** [hukaixuan19970627/yolov5_obb#227]
精度前面几个周期还在上升，之后就一直为0.
验证的图片框不对，要么角度不对，或者框太小

**Comment by xxxjjjx** [comment]
![train_batch0](https://user-images.githubusercontent.com/93917073/157220049-f7dfe441-347b-4e66-94ed-a758ce08a53a.jpg)
![train_batch1](https://user-images.githubusercontent.com/93917073/157220102-c6f06f78-713d-472d-b693-1c2c1f169ff1.jpg)
![train_batch2](https://user-images.githubusercontent.com/93917073/157220120-18ed963a-6840-4347-a4a4-7b50b6b594d8.jpg)

**Comment by xxxjjjx** [comment]
![val_batch0_labels](https://user-images.githubusercontent.com/93917073/157220339-a1a3693d-6d31-4f00-a66f-b003784a677b.jpg)

**Comment by xxxjjjx** [comment]
![000002](https://user-images.githubusercontent.com/93917073/157220555-6004b878-2dc7-4e07-af53-83565aee0bf1.jpg)
![000003](https://user-images.githubusercontent.com/93917073/157220631-4d987e14-6bbf-43de-8f23-928f49162c49.jpg)
![000017](https://user-images.githubusercontent.com/93917073/157220812-049e02b5-53dd-46f0-9fd1-9474c00df63a.jpg)
![000076](https://user-images.githubusercontent.com/93917073/157221200-9158380a-6efc-4059-b21f-906c957ddab5.jpg)

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/157373264-bd9e9f9e-f977-4abf-8921-cc30d9a341df.png)
把上述选定的文件整理一下再发一次。

**Comment by xxxjjjx** [comment]
[results.csv](https://github.com/hukaixuan19970627/yolov5_obb/files/8220398/results.csv)
![train_batch0](https://user-images.githubusercontent.com/93917073/157591167-b8cd2367-94b8-4fa7-99fc-5e47a9aca837.jpg)
![train_batch1](https://user-images.githubusercontent.com/93917073/157591180-853a1525-0006-44da-aec1-04059ee9332b.jpg)
![train_batch2](https://user-images.githubusercontent.com/93917073/157591182-2c4bbdf0-88c2-49b8-9754-89960402eb67.jpg)
![val_batch0_labels](https://user-images.githubusercontent.com/93917073/157591221-5a5f89f9-85cd-4603-b964-816fb00ae174.jpg)
![val_batch0_pred](https://user-images.githubusercontent.com/93917073/157591242-1a39cca9-3d58-43ea-b9d5-69f619e34aa2.jpg)

**Comment by xxxjjjx** [comment]
我用DOTA1.5d的数据集不会出现这种情况。
我把SSDD数据转成所需要的标签格式，然后开始训练。就会出现mAP一直为0
把nc改为2还是一直在0上下。detect出来的效果图也不好。

**Comment by xxxjjjx** [comment]
[hyp.txt](https://github.com/hukaixuan19970627/yolov5_obb/files/8220515/hyp.txt)
[opt.txt](https://github.com/hukaixuan19970627/yolov5_obb/files/8220519/opt.txt)
这是yaml文件

**Comment by xxxjjjx** [comment]
[results.csv](https://github.com/hukaixuan19970627/yolov5_obb/files/8220522/results.csv)

**Comment by hukaixuan19970627** [comment]
你就不能截图吗，我只是想通过这些文件查看你的训练情况而已，你这样发我还得一个个下载下来看，另外你还少发了results.png，整理下再重发一次。
![image](https://user-images.githubusercontent.com/72599120/157807409-4a22f8e5-b278-4821-b014-dbfdb973c9fc.png)

**Comment by xxxjjjx** [comment]
好的，大佬。我现在再跑，想多跑一会儿。设备跟不上啊

**Comment by junjuncv** [comment]
> 我用DOTA1.5d的数据集不会出现这种情况。 我把SSDD数据转成所需要的标签格式，然后开始训练。就会出现mAP一直为0 把nc改为2还是一直在0上下。detect出来的效果图也不好。

你好，请问这个问题解决了吗？是不是应为labels数据的角度转换出的问题？
