### ISSUE TITLE
训练的batch-size问题

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#228]
![image](https://user-images.githubusercontent.com/42164696/157374854-bbdae5a5-5eeb-4919-97d4-8c6bd6fee87e.png)
![image](https://user-images.githubusercontent.com/42164696/157374706-7beb15d5-bc57-41bf-83e6-c64ec87fa82e.png)

大佬您好，我这面是12G的显卡，训练的时候需要2.61G的显存，为啥我的batch-size最多智能设置为2呢，理论上设置成4应该没有问题啊，但是一设置超过2就报显存不足的错误

**Comment by hukaixuan19970627** [comment]
nvidia-smi查看的才是显存的实际占用量。

**Comment by HKVINS89757** [comment]
![image](https://user-images.githubusercontent.com/42164696/157387214-5100df4a-3737-4b0b-9fe4-ad76a5cb7078.png)
是呀 xu训练的时候还开了一大堆其他的程序才用了5个多G 为啥空余的7，8个G不能用呀

**Comment by hukaixuan19970627** [comment]
建议显示工作交给集显来做，不要来占独显的显存。弄好之后你再来测batchsize吧。
另外训练深度学习模型的时候GPU不要做其它的工作，否则会大大降低训练速度。

**Comment by HKVINS89757** [comment]
> 建议显示工作交给集显来做，不要来占独显的显存。弄好之后你再来测batchsize吧。 另外训练深度学习模型的时候GPU不要做其它的工作，否则会大大降低训练速度。

是呀 开机只运行着一个程序还是batchsize只能到2 3，4就报错
