### ISSUE TITLE
作者大佬您好，copy_paste没有被有效调用

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#229]
![image](https://user-images.githubusercontent.com/42164696/157600883-3bba37cb-a6b3-42bb-9844-ec2b36792962.png)
z这一行是始终不会被打印的

也就是说下面这一句是无效的吗
![image](https://user-images.githubusercontent.com/42164696/157601014-5fa51126-64c4-49c5-b0e0-2cab7e93f5f2.png)

**Comment by hukaixuan19970627** [comment]
使用Mixup中copy_paste的前提是有segment标注
