### ISSUE TITLE
 Scanning 'dataset\train\labelTxt.cache' 718 found, 0 missing, 0 empty, 718 corrupted

### ISSUE THREAD

**Issue by alandechang** [hukaixuan19970627/yolov5_obb#231]
请问大佬们以前的标签是正确的，并且在YOLO转换工具里使用了4.1.2，最终转换的格式都一样，但是还是全部corrupted损坏

**Comment by alandechang** [comment]
格式不再是YOLO格式，而是DOTA格式

**Comment by hukaixuan19970627** [comment]
[getstart.md](https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/GetStart.md)
