### ISSUE TITLE
作者大大你好：训练效果挺好，但是部分数据推理时出现框过长以及mosaic时标签会多一截

### ISSUE THREAD

**Issue by wubalahao** [hukaixuan19970627/yolov5_obb#234]
作者大大你好我在推理的时候遇到了这些问题
下面是部分推理的结果
![image](https://user-images.githubusercontent.com/65750931/157861185-ea904da3-6604-497c-9110-3b7b35840d8f.png)
![image](https://user-images.githubusercontent.com/65750931/157861114-68d18ce8-1455-424d-b8e5-f448abe1f57a.png)
下面是训练的batch，我发现在做mosaic的时候标签会多画一截
<img width="341" alt="image" src="https://user-images.githubusercontent.com/65750931/157861761-496cdc25-2d02-47be-9916-09928820e8fb.png">
<img width="298" alt="image" src="https://user-images.githubusercontent.com/65750931/157861815-9a279d8c-9043-4134-9b26-871b88ec48ee.png">
![image](https://user-images.githubusercontent.com/65750931/157861950-49fb1318-3a70-47ba-9d80-311723b7e6cf.png)
下面是train时候的loss曲线以及参数
![image](https://user-images.githubusercontent.com/65750931/157862127-6704490c-c8fb-4218-89d8-129670021454.png)
<img width="663" alt="image" src="https://user-images.githubusercontent.com/65750931/157862221-2ab90081-a268-45d4-a2b7-1d71b7321a19.png">
下面是detect时的参数
<img width="737" alt="image" src="https://user-images.githubusercontent.com/65750931/157862270-6c2e89dc-6850-42fb-a166-8b70b32fe4ef.png">

**Comment by hukaixuan19970627** [comment]
1. 还未完全收敛：
![image](https://user-images.githubusercontent.com/72599120/158007442-4e67b74e-40c1-471f-ab62-299dd912a148.png)
2. trainbatch图片那不是多一截，是因为物体本身就那么长，只不过被截断了而已。

**Comment by wubalahao** [comment]
好的大佬又训练了100轮收敛了现在问题解决了谢谢
