### ISSUE TITLE
from . import nms_rotated_ext 出错

### ISSUE THREAD

**Issue by HTRT** [hukaixuan19970627/yolov5_obb#235]
运行train文件时，出现以下错误信息
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import）
请问怎么解决？

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/158007657-0a405218-719a-480d-8ca5-bcf8f9bfd24e.png)

![image](https://user-images.githubusercontent.com/72599120/158007638-20b4a712-9427-4f07-9570-d7fd224027fa.png)

**Comment by Xiaoanan6789** [comment]
> 运行train文件时，出现以下错误信息 ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import） 请问怎么解决？

**Comment by Xiaoanan6789** [comment]
请问你解决了吗？
