### ISSUE TITLE
Custom Dataset Question : 贴片元件角度检测

### ISSUE THREAD

**Issue by DSHuang123** [hukaixuan19970627/yolov5_obb#237]
最近用了自己的电子元件数据集做了一下角度检测，imgsize是2592*1944，只放了89张（同一类别的元件），bachsize为8,epoch为200，高斯窗口函数的窗口半径分别试了2.0和6.0，最终训练出来的模型一张图片也检测不出，非常疑惑

**Comment by hukaixuan19970627** [comment]
https://user-images.githubusercontent.com/72599120/158007557-d4874ae9-6e69-45a5-8ceb-f90c62f512e9.png
将上述选定文件截图发上来，看看你的训练情况。

**Comment by DSHuang123** [comment]
![hyp yaml](https://user-images.githubusercontent.com/97818208/158009655-638e2278-ffe0-4025-8659-64abfa8ae33f.png)
![labels_correlogram](https://user-images.githubusercontent.com/97818208/158009657-fb904ba7-8be7-4912-86ba-82b29f01ee90.jpg)
![labels_xyls](https://user-images.githubusercontent.com/97818208/158009659-3627b871-a989-409a-b099-90c2adcc88e5.jpg)
![opt yaml(上)](https://user-images.githubusercontent.com/97818208/158009660-1dca96fa-5611-4293-965e-3939a659cbaa.png)
![opt yaml(下)](https://user-images.githubusercontent.com/97818208/158009661-26c23d41-a5aa-4a53-87d3-1811ac5d3335.png)
![results](https://user-images.githubusercontent.com/97818208/158009662-3806e0e9-8fa2-4eaf-8bc7-38a6328db348.png)
![train_batch0](https://user-images.githubusercontent.com/97818208/158009665-6b6bf13b-1902-43d7-9a54-ab510017295c.jpg)
![train_batch1](https://user-images.githubusercontent.com/97818208/158009666-fc08b9df-430d-4895-b065-2aa1d42b74ae.jpg)
![train_batch2](https://user-images.githubusercontent.com/97818208/158009667-26617b9e-c70b-4b38-9a74-889ed5f7c840.jpg)
![train_batch3](https://user-images.githubusercontent.com/97818208/158009668-cd406ae9-c2c1-4db1-9c48-b614f5f680ca.jpg)
![train_batch4](https://user-images.githubusercontent.com/97818208/158009670-40d561b9-41c9-47a8-88e6-9f6c0b7c18c4.jpg)
![train_batch5](https://user-images.githubusercontent.com/97818208/158009671-5eb8d690-0e32-417f-9424-f821a9331ca1.jpg)
![train_batch6](https://user-images.githubusercontent.com/97818208/158009674-6ac191b3-bef0-40f7-900a-495816d2e232.jpg)
![train_batch7](https://user-images.githubusercontent.com/97818208/158009676-bb283589-21bd-4730-91df-19f1b478ccfb.jpg)
![val_batch0_labels](https://user-images.githubusercontent.com/97818208/158009677-490042d5-ac74-4b3c-b93e-20ecdb0c23eb.jpg)
![val_batch0_pred](https://user-images.githubusercontent.com/97818208/158009679-4008ed2a-97bc-4243-9800-cbd774ff2fc9.jpg)
![val_batch1_labels](https://user-images.githubusercontent.com/97818208/158009681-c6351630-3836-4393-8fa8-2bb9d67425fb.jpg)
![val_batch1_pred](https://user-images.githubusercontent.com/97818208/158009682-15cc11f8-fcf6-4f95-9ca6-ee962a8b0223.jpg)
![val_batch2_labels](https://user-images.githubusercontent.com/97818208/158009684-da09eb84-a974-43fb-b3f0-94278a6d10ae.jpg)
![val_batch2_pred](https://user-images.githubusercontent.com/97818208/158009685-c49f9de5-30a3-4e2e-87a0-26378017ae80.jpg)

我在google colab上跑的，配置requirements环境的时候出现了如下报错（但可以继续运行）
![febf16d3766014a539232cfbe1a7b3d](https://user-images.githubusercontent.com/97818208/158009718-54fa3853-2567-4cbf-a423-c8e01e3fa131.png)

配置pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html 时，出现如下报错（也可以继续运行）
![d4bc918d361f9fcea49dcb8ff83519b](https://user-images.githubusercontent.com/97818208/158009736-066b3de7-63b6-4daf-8c2b-d726fee54ba1.png)

有劳作者！

**Comment by DSHuang123** [comment]
hyp.yaml图没截全，漏了一个高斯半径，设置为2.0

**Comment by hukaixuan19970627** [comment]
一个epoch89张图，batchsize为8，200个epoch模型也才迭代2000多次而已。
而且results.png中的mAP曲线也可以看出模型离收敛还差得远呢。建议设置--epoch 2000 --patience 200

**Comment by hukaixuan19970627** [comment]
另外如果单目标识别训练效果不好的话建议参考下这个issue：#179

**Comment by DSHuang123** [comment]
好的！
我每张图片只有一种元件，有好几类图片，目前先跑一类试试看。之前跑这个数据集的时候，有几次都是100epoch之内优化不更新了，达到patience（100）之后自己就停止训练了，然后系统推荐我设置为300左右。所以连续好几个epoch优化没有变化，过了好多epoch之后再有变化是正常、允许发生的吗？

**Comment by DSHuang123** [comment]
作者晚上好！
将patience设置成了300，下午跑了一下，到671自己停了，实际训练了371，参数没动，PR曲线看起来好一些，但是mAP还没有收敛，检测结果还是什么也检测不出，冒昧请您看一下！
![image](https://user-images.githubusercontent.com/97818208/158055506-c08345ee-a4ed-4840-830f-2dabc59d068f.png)
![image](https://user-images.githubusercontent.com/97818208/158055528-00ddcb97-edc8-41c1-8d76-d7cc16c70b7f.png)
![image](https://user-images.githubusercontent.com/97818208/158055540-690a5e73-be4f-4e3b-ae2f-e1e261324980.png)
val_batch_label
![image](https://user-images.githubusercontent.com/97818208/158055556-9fdf3c9f-355a-4925-a450-4ce7ebd10959.png)

val_batch_pred
![image](https://user-images.githubusercontent.com/97818208/158055565-a0811b78-1e6f-4457-8964-6db4c1b29840.png)

PR_curve
![image](https://user-images.githubusercontent.com/97818208/158055590-4ba2696b-0b71-4b1f-85e6-c6df290433ba.png)

**Comment by DSHuang123** [comment]
目前正在将nc设置为2，重新训练一下单类元件数据集，patience=200，epoch=2000，bs=8

**Comment by hukaixuan19970627** [comment]
提前停了你的patience就继续加大呗，干脆设置成和epoch一样好了。
看results曲线的话模型还没到收敛的时候。你数据集的目标数量总共就80多个，自然训练效率比较低。

**Comment by DSHuang123** [comment]
作者晚上好！
我把nc设置为2之后就有效果了...在colab上训练了820个epoch，时间不够自己给停了，bs=8，更新次数约8000次，检测了一下发现比之前好多了。
![image](https://user-images.githubusercontent.com/97818208/158156893-8c58d40e-ad6d-4491-8016-8fffe3ec96bd.png)
![image](https://user-images.githubusercontent.com/97818208/158156959-e355368a-47c7-4a24-b0c7-bcf5a5d125f3.png)
小元件没有检测到
![image](https://user-images.githubusercontent.com/97818208/158157196-41638d5b-790f-4409-a285-21624264d215.png)

针对训练迭代次数，看见网上有人说更新参数20000次左右，有人说要观察loss和mAP是否收敛，我的数据集一共600张左右的图片，6个类别，请问作者您有什么好的训练建议吗？非常感谢！

**Comment by hukaixuan19970627** [comment]
你的数据集既然有600多张那就直接训练呗，何必挑几十张出来训，数据集规模越大，基于深度学习的模型训练效果才越好

**Comment by DSHuang123** [comment]
谢谢作者的贡献！训练效果越来越好了！
还有个疑问，train_batch和val_batch_label是经过minAreaRect函数操作后的可视化还是原先我标注的四边形label的可视化呢？

**Comment by DSHuang123** [comment]
在Dataset.py中，LoadImageAndLabels类里，def__getitem__中将DOTA标签转换成长边表示法，以后模型训练用的也是长边表示法的label，那么train_batch的可视化也应该是长边表示法也就是用了minAreaRect函数之后的矩形框。val同理，请问作者，这样理解对吗？谢谢指导！

**Comment by hukaixuan19970627** [comment]
代码有不明白的地方你可以直接打断点，debug看每个函数的功能，而且我基本在每个关键函数处都写了注释

**Comment by junjuncv** [comment]
> 在Dataset.py中，LoadImageAndLabels类里，def__getitem__中将DOTA标签转换成长边表示法，以后模型训练用的也是长边表示法的label，那么train_batch的可视化也应该是长边表示法也就是用了minAreaRect函数之后的矩形框。val同理，请问作者，这样理解对吗？谢谢指导！



> 谢谢作者的贡献！训练效果越来越好了！ 还有个疑问，train_batch和val_batch_label是经过minAreaRect函数操作后的可视化还是原先我标注的四边形label的可视化呢？

你好，请问下你的txt数据是怎么转换得到的呢？
是用rolabelimg标注的图片吗，然后又用哪个脚本转换到DOTA格式的txt？有劳回复谢谢

**Comment by DSHuang123** [comment]
作者您好！又来打扰您了...
在使用CSL-高斯窗口函数这里，原公式是这样：
![image](https://user-images.githubusercontent.com/97818208/159630532-7a4016e3-e45b-4b5e-b9a3-c6805b2a4f09.png)

源码最后index和return处一直不理解和原公式的区别，您是不是做了改进？
![image](https://user-images.githubusercontent.com/97818208/159630229-707e5a56-2eea-4ca1-9336-bcc8e9de1f80.png)
我和您当时一样，跨专业转CV，非常感谢您耐心的回复！

**Comment by tkone2018** [comment]
@DSHuang123 你好，请问你是如何制作数据集的，谢谢

**Comment by tkone2018** [comment]
@DSHuang123  好的

**Comment by hukaixuan19970627** [comment]
> 作者您好！又来打扰您了... 在使用CSL-高斯窗口函数这里，原公式是这样： ![image](https://user-images.githubusercontent.com/97818208/159630532-7a4016e3-e45b-4b5e-b9a3-c6805b2a4f09.png)
> 
> 源码最后index和return处一直不理解和原公式的区别，您是不是做了改进？ ![image](https://user-images.githubusercontent.com/97818208/159630229-707e5a56-2eea-4ca1-9336-bcc8e9de1f80.png) 我和您当时一样，跨专业转CV，非常感谢您耐心的回复！

你画一下图就清楚了。
![image](https://user-images.githubusercontent.com/72599120/160562256-07cb608b-2536-42c8-aa8c-6a0671997053.png)
