### ISSUE TITLE
HBB Detection : 水平框数据集问题

### ISSUE THREAD

**Issue by XiangqingZhang** [hukaixuan19970627/yolov5_obb#238]
作者你好，我想问下你的代码支持水平框yolo标签的训练数据集吗，我目前只有水平框的数据标签，有没有办法转换为旋转框，进行训练，请大佬赐教，谢谢

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/158016276-4a43d18f-916d-49b1-8330-6eb57ad70f10.png)

**Comment by XiangqingZhang** [comment]
![image](https://user-images.githubusercontent.com/22740766/158021183-d718560c-9077-428c-8855-aea475a4ce25.png)

我编译utils/nms_rotated文件时出现错误，怎么回事
