### ISSUE TITLE
nan in my custom dataset training

### ISSUE THREAD

**Issue by Mason1992-Git** [hukaixuan19970627/yolov5_obb#239]
训练时全是nan
训练集标签格式
![image](https://user-images.githubusercontent.com/79744902/158094042-5d36c496-d972-4b22-87ea-3b37f3bf419f.png)
train_batch0
![image](https://user-images.githubusercontent.com/79744902/158094230-74c73e05-491e-41bb-ac69-a724176bfc9f.png)
train_batch1
![image](https://user-images.githubusercontent.com/79744902/158094292-ccf9160b-5310-4357-9ced-aa17ae6ed074.png)
train_batch2
![image](https://user-images.githubusercontent.com/79744902/158094335-f7b15f00-b614-486c-ae41-8db9c307c83a.png)
结果文件hyp.yaml
lr0: 0.001
lrf: 0.2
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.05
cls: 0.5
cls_pw: 1.0
theta: 0.5
theta_pw: 1.0
obj: 1.0
obj_pw: 1.0
iou_t: 0.2
anchor_t: 4.0
fl_gamma: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 180.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.5
fliplr: 0.5
mosaic: 0.95
mixup: 0.1
copy_paste: 0.0
cls_theta: 180
csl_radius: 2.0
结果文件opt.yaml
weights: weights\yolov5m.pt
cfg: ''
data: data\yolov5obb_demo.yaml
hyp: data\hyps\obb\hyp.finetune_dota.yaml
epochs: 10
batch_size: 1
imgsz: 1024
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\exp

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/158325556-f5abdea5-e2ad-4ea0-b6ba-726613aa3083.png)
把上述标记的文件整理一下截图发过来，另外再详细介绍一下你使用的数据集

**Comment by Mason1992-Git** [comment]
您好，您的来信已收到，我会尽快阅读并回信。谢谢。袁磊

**Comment by Mason1992-Git** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/158325556-f5abdea5-e2ad-4ea0-b6ba-726613aa3083.png) 把上述标记的文件整理一下截图发过来，另外再详细介绍一下你使用的数据集
hyp.yaml截图
![image](https://user-images.githubusercontent.com/79744902/158328282-3835cb5d-c4c5-4d34-a672-16ec610ee3d7.png)
opt.yaml截图
![image](https://user-images.githubusercontent.com/79744902/158328460-ef5f3449-f01a-4151-a538-bedc9ee694fa.png)
results截图
![image](https://user-images.githubusercontent.com/79744902/158328657-d4f7c5d8-bcff-476c-9e72-c7ac927afd80.png)
train_batch0截图
![image](https://user-images.githubusercontent.com/79744902/158328778-b447fd6e-b926-4a8c-9cd5-f8670c7a27db.png)
train_batch1截图
![image](https://user-images.githubusercontent.com/79744902/158328894-ba1a8569-4cf4-4bc2-99d6-635bb3cdaad6.png)
train_batch2截图
![image](https://user-images.githubusercontent.com/79744902/158328944-ff176138-5292-42e5-b654-40e29b188a0e.png)
val_batch0_labels截图
![image](https://user-images.githubusercontent.com/79744902/158329085-0d576e8a-23f1-444e-a92e-c01daa8cf46b.png)
val_batch0_pred截图
![image](https://user-images.githubusercontent.com/79744902/158329181-0acca8b0-ede0-4809-8e53-2fb02042cf0a.png)
没有生成labels.jpg

我的数据集：
![image](https://user-images.githubusercontent.com/79744902/158329371-8472475c-008d-42d8-aa2f-d42da563129d.png)
images:
![image](https://user-images.githubusercontent.com/79744902/158329420-12ae60f3-7ea9-4012-8f0a-6781c1cd1160.png)
txt:
![image](https://user-images.githubusercontent.com/79744902/158329484-c4e620d3-7a61-48de-818d-f563a1685463.png)
![image](https://user-images.githubusercontent.com/79744902/158330017-6331d9e9-c874-4aeb-b8dc-556aec4917b2.png)
数据集一共50张图片，仅为了测试代码能否在其他场景跑通，所以只选择了50张图片。

**Comment by hukaixuan19970627** [comment]
1. 度盘提供了DOTAv1.5的训练权重以及所有的训练参数文件，所以除非你知道每个参数的具体意义和影响否则不要自己更改参数
2. 格式文件的类别名是字符串
3. 训练后缺少文件说明训练过程中有问题，检查一下

**Comment by wjmicheal** [comment]
使用了demo中的数据集，P0032，分割也没有问题，但是训练的时候也是一样全是nan，不知道是什么原因，怀疑是不是在编译nms_rotated时出了问题。在编译nms_rotated时，在poly_nms_cuda.cu文件中出现错误提示：identificer 'eps' is undefined  in device code，由于变量'eps'定义在文件中定义的是常量，因此将使用eps中的地方直接替换为常量，编译通过。

**Comment by wjmicheal** [comment]
追踪train.py 代码 第324行， 将pred 打印出来，添加 print(pred)发现 pred全是nan

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/224

**Comment by hukaixuan19970627** [comment]
如果你是windows+CUDA11的话可以参考下这个issue：https://github.com/ultralytics/yolov5/issues/5815

**Comment by Mason1992-Git** [comment]
> 如果你是windows+CUDA11的话可以参考下这个issue：[ultralytics/yolov5#5815](https://github.com/ultralytics/yolov5/issues/5815)

感谢作者！这个问题已解决，是显卡和pytorch版本问题。换到30系列可以训练

**Comment by LUO77123** [comment]
![image](https://user-images.githubusercontent.com/87272337/168233924-740d7299-405b-4efe-ad60-66adf1c39805.png)
![image](https://user-images.githubusercontent.com/87272337/168234079-385ae657-d738-4844-807c-0158feb0ce98.png)
![image](https://user-images.githubusercontent.com/87272337/168234309-fe988578-35fd-479c-987f-d0ca191e315e.png)
![image](https://user-images.githubusercontent.com/87272337/168234475-7e4b22f2-153b-4851-8183-2e925e989568.png)
![image](https://user-images.githubusercontent.com/87272337/168234635-c847c131-1463-45f7-8b12-bad1a50c27a8.png)
![image](https://user-images.githubusercontent.com/87272337/168234716-f4d9f07e-9362-4626-b68a-6f6f8cbe8f3c.png)

**Comment by Mason1992-Git** [comment]
您好，您的来信已收到，我会尽快阅读并回信。谢谢。袁磊

**Comment by LUO77123** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/158325556-f5abdea5-e2ad-4ea0-b6ba-726613aa3083.png) 把上述标记的文件整理一下截图发过来，另外再详细介绍一下你使用的数据集

数据集就是DATA，分割1024*1024，gap=512

**Comment by Mason1992-Git** [comment]
您好，您的来信已收到，我会尽快阅读并回信。谢谢。袁磊
