### ISSUE TITLE
No labels in {cache_path}. Can not train without labels.

### ISSUE THREAD

**Issue by kurt369** [hukaixuan19970627/yolov5_obb#240]
数据集组织格式如下：
![image](https://user-images.githubusercontent.com/58777130/158191420-32f7e94a-91da-45be-ac78-14fac80c89d6.png)
yaml文件：
![image](https://user-images.githubusercontent.com/58777130/158191563-8f7dff8d-6cfb-4a4f-a1f4-b88610db0b60.png)
报错信息：
![image](https://user-images.githubusercontent.com/58777130/158191757-098b6e7f-d878-4fd6-a318-5c2681f89cfd.png)

**Comment by hukaixuan19970627** [comment]
先把getstart.md所有流程全部都跑通，参考一下demo数据集的存放结构

**Comment by goodfishboy** [comment]
> 数据集组织格式如下： ![image](https://user-images.githubusercontent.com/58777130/158191420-32f7e94a-91da-45be-ac78-14fac80c89d6.png) yaml文件： ![image](https://user-images.githubusercontent.com/58777130/158191563-8f7dff8d-6cfb-4a4f-a1f4-b88610db0b60.png) 报错信息： ![image](https://user-images.githubusercontent.com/58777130/158191757-098b6e7f-d878-4fd6-a318-5c2681f89cfd.png)

你好，这个问题解决了吗，我也碰到这个问题了，能看下你现在的数据集格式和yaml文件吗

**Comment by XDEDLS** [comment]
> > 数据集组织格式如下： ![image](https://user-images.githubusercontent.com/58777130/158191420-32f7e94a-91da-45be-ac78-14fac80c89d6.png) yaml文件： ![image](https://user-images.githubusercontent.com/58777130/158191563-8f7dff8d-6cfb-4a4f-a1f4-b88610db0b60.png) 报错信息： ![image](https://user-images.githubusercontent.com/58777130/158191757-098b6e7f-d878-4fd6-a318-5c2681f89cfd.png)
> 
> 你好，这个问题解决了吗，我也碰到这个问题了，能看下你现在的数据集格式和yaml文件吗

你好，这个问题解决了吗，我也碰到这个问题了
