### ISSUE TITLE
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import) (/home/zgchen/PycharmProjects/yolov5_obb/utils/nms_rotated/__init__.py)

### ISSUE THREAD

**Issue by ChenZhenGui** [hukaixuan19970627/yolov5_obb#241]

**Comment by zysc1996** [comment]
我也遇到了这个问题，有点不知所云

**Comment by hukaixuan19970627** [comment]
1. 遇到问题提issue之前可以自己先搜索一下有没有人提同类型的问题，节省时间；
2. 使用一个项目的时候读一下Readme，install.md有安装环境教程，getstart.md里有使用教程，demo都运行不成功说明是环境问题，再按照install.md检查一遍。
![image](https://user-images.githubusercontent.com/72599120/158574085-04bbb2d2-8ada-4e8d-acca-61cf4493b791.png)

**Comment by ChenZhenGui** [comment]
已收到，谢谢

**Comment by Xiaoanan6789** [comment]
> 你解决了吗？你的pytorch，CUDA等的版本配置是怎样的？

**Comment by ChenZhenGui** [comment]
已收到，谢谢
