### ISSUE TITLE
有关于模型转换的问题

### ISSUE THREAD

**Issue by calvinIsAwesome** [hukaixuan19970627/yolov5_obb#242]
目前手里有一个开发板，使用他们的转换工具可以将onnx框架下的模型转换成C代码后运行在上面，请问在使用export.py在进行模型转换输出的onnx模型支持旋转框嘛？
谢谢🙏🙏～

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/158573198-581d5d56-10f0-419d-81b7-92dfbd8c28e4.png)
