### ISSUE TITLE
No module named '_polyiou'

### ISSUE THREAD

**Issue by rhj0103** [hukaixuan19970627/yolov5_obb#243]
![图片](https://user-images.githubusercontent.com/86508657/158564324-f117a535-9fda-4da9-abcf-2ae05f42bc5d.png)

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/158572815-30f22570-541d-417b-99c4-d91c59f793a9.png)

**Comment by rhj0103** [comment]
好的，谢谢~
