### ISSUE TITLE
关于自定义数据集训练的epoch、bs和收敛问题

### ISSUE THREAD

**Issue by Michaelnlearn** [hukaixuan19970627/yolov5_obb#244]
您好，首先感谢您的贡献，我成功修改了部分内容并且应用到了自己的数据集上，并且取得了良好的效果。
因为我修改了网络结构，所以是从头开始训练的，没有用预训练权重，可能效果比较一般。
我是个目标检测小白，所以想问问一般batch_size取多少？和对应epoch需要多少？怎么判断如何收敛？
我是bs为2，训练了75个epoch，bs为4，训练了110个epoch，bs为8，训练了190个epoch，下面是我的tensorboard结果。

**Comment by Michaelnlearn** [comment]
下面三个不同颜色的曲线，分别对应我的三次训练

**Comment by yang-gis** [comment]
> 

你好，请问自定数据集的标签格式是什么啊？使用什么工具去标注？

**Comment by yang-gis** [comment]
> 您好，首先感谢您的贡献，我成功修改了部分内容并且应用到了自己的数据集上，并且取得了良好的效果。 因为我修改了网络结构，所以是从头开始训练的，没有用预训练权重，可能效果比较一般。 我是个目标检测小白，所以想问问一般batch_size取多少？和对应epoch需要多少？怎么判断如何收敛？ 我是bs为2，训练了75个epoch，bs为4，训练了110个epoch，bs为8，训练了190个epoch，下面是我的tensorboard结果。

你好，请问自定数据集的标签格式是什么啊？使用什么工具去标注？

**Comment by Michaelnlearn** [comment]
我用的是dota格式，和项目作者一样。标注的话，我没用标注工具，是用网上找到的数据集和对应的annotation自己转化成dota格式的。
不过如果你想自己标注，可以用rlabel+标签转化代码，转化为dota数据集格式。



---原始邮件---
发件人: "yang ***@***.***&gt;
发送时间: 2022年3月17日(周四) 上午8:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 关于自定义数据集训练的epoch、bs和收敛问题 (Issue #244)




   
你好，请问自定数据集的标签格式是什么啊？使用什么工具去标注？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yang-gis** [comment]
> 我用的是dota格式，和项目作者一样。标注的话，我没用标注工具，是用网上找到的数据集和对应的annotation自己转化成dota格式的。 不过如果你想自己标注，可以用rlabel+标签转化代码，转化为dota数据集格式。
> […](#)
> ---原始邮件--- 发件人: "yang ***@***.***&gt; 发送时间: 2022年3月17日(周四) 上午8:57 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 关于自定义数据集训练的epoch、bs和收敛问题 (Issue #244) 你好，请问自定数据集的标签格式是什么啊？使用什么工具去标注？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好的谢谢兄弟的答复

**Comment by hukaixuan19970627** [comment]
1. 验证集的mAP曲线可以看出是否已经完全收敛，还在上升说明还可以继续收敛
2. 在模型都能收敛的前提下batch_size数值对最终精度影响不大，epoch数自己根据训练效果进行调整，时间多往大了设就是了，反正yolov5会保存表现最好的best.pt。

**Comment by Michaelnlearn** [comment]
谢谢您的回复，看来我的还没收敛，我还继续训练看看收敛后，是否比原来的结果更好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月17日(周四) 中午1:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 关于自定义数据集训练的epoch、bs和收敛问题 (Issue #244)




  
验证集的mAP曲线可以看出是否已经完全收敛，还在上升说明还可以继续收敛 

在模型都能收敛的前提下batch_size数值对最终精度影响不大，epoch数自己根据训练效果进行调整，时间多往大了设就是了，反正yolov5会保存表现最好的best.pt。 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Michaelnlearn** [comment]
已解决
