### ISSUE TITLE
单类别数据训练时无法收敛的原因是什么？

### ISSUE THREAD

**Issue by yangl720** [hukaixuan19970627/yolov5_obb#245]
单类别数据在训练时,迭代100多个epoch，P和R保持稳定，一直时0.1多左右，数据集验证过是没有问题的，那么造成这一问题的原因是什么呢？

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/158943362-327bda2c-2447-48a2-82bc-6488fad9d702.png)
上述选定的文件截图发一下，我看看训练情况是怎样的，另外介绍一下使用的数据集相关信息。
单类别可以训练，只不过比较考验调参技术
