### ISSUE TITLE
where is the dataset_demo_rate1.0_split1024_gap200

### ISSUE THREAD

**Issue by cyp-happy** [hukaixuan19970627/yolov5_obb#246]
dataset_demo_rate1.0_split1024_gap200这个数据集合再哪里下载

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/159151218-52b5e066-bf7a-435c-a07d-284d07757a7a.png)
花十分钟先走一遍getstart，里面有demo教程
![image](https://user-images.githubusercontent.com/72599120/159151261-d911210e-f74c-44df-8a4a-5fa8fec96295.png)
