### ISSUE TITLE
python train.py --data 'data/yolov5obb_demo_split.yaml' --epochs 10 --batch-size 2 --img 1024 --device 0

### ISSUE THREAD

**Issue by ChenZhenGui** [hukaixuan19970627/yolov5_obb#247]
运行原始数据集 所有指标都为0 是因为数据集太少导致的吗
![image](https://user-images.githubusercontent.com/52156532/158949697-4868070e-3068-42fb-b855-b3d06a8619a8.png)

**Comment by ChenZhenGui** [comment]
成功跑通 但是只有飞机的有指标 请问是什么问题
![image](https://user-images.githubusercontent.com/52156532/158964786-0c95eec5-6be3-4174-8172-41634843db66.png)

**Comment by hukaixuan19970627** [comment]
demo只是为了在最短的时间内验证环境是否安装正确，以及走通整个项目的使用流程。
