### ISSUE TITLE
Best val mAP is 72 but the test mAP just 48

### ISSUE THREAD

**Issue by rhj0103** [hukaixuan19970627/yolov5_obb#248]

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/159151049-cbcfc8dd-5aab-435e-8db6-d3b280f006ba.png)

**Comment by rhj0103** [comment]
请问是需要把测试数据集切割成1024大小嘛？

**Comment by hukaixuan19970627** [comment]
你可以用SplitOnlyImage.py切割测试集，非要用ImgSplit.py的话写个脚本给测试集生成空labels文件一样可以切割
