### ISSUE TITLE
ResultMerge_multi_process.py Error : IndexError: List index out of range

### ISSUE THREAD

**Issue by rhj0103** [hukaixuan19970627/yolov5_obb#249]
![图片](https://user-images.githubusercontent.com/86508657/159104913-cb9ca67d-1723-46fc-8141-5a3b0f00af13.png)

**Comment by hukaixuan19970627** [comment]
描述不详细，起码你得让人能够复现你的问题才可以。建议对照getstart.md使用流程检查下

**Comment by rhj0103** [comment]
![图片](https://user-images.githubusercontent.com/86508657/159688352-f634a77e-048a-4d18-8776-63fb0cee93c0.png)
你好，我在完成前面两个命令后，进行第三步结果合并的时候，发现以下错误：
![图片](https://user-images.githubusercontent.com/86508657/159688586-4af06f93-2656-4029-be96-ece1468d6da6.png)
文件夹结构如下：
![图片](https://user-images.githubusercontent.com/86508657/159688849-e29ea66a-c155-4cd3-963c-9e03ef6e1436.png)
代码中的路径如下：
![图片](https://user-images.githubusercontent.com/86508657/159688958-3cb862ea-2e38-46ab-9d6a-09dccd761109.png)

**Comment by wycwcq** [comment]
同问，我也遇到了这个问题

**Comment by rhj0103** [comment]
是因为测试集需要裁剪成1024大小，可以修改ImgSplit部分代码，只让他裁剪图片就可以了。

**Comment by wycwcq** [comment]
哦哦好哒，谢谢解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hukaixuan19970627/yolov5_obb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月24日(星期四) 中午1:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hukaixuan19970627/yolov5_obb] ResultMerge_multi_process.py Error : IndexError: List index out of range (Issue #249)





 
是因为测试集需要裁剪成1024大小，可以修改ImgSplit部分代码，只让他裁剪图片就可以了。
