### ISSUE TITLE
(where is the download link)你好，请问你的demo file可以发我一下了，链接过期了

### ISSUE THREAD

**Issue by ctgu123** [hukaixuan19970627/yolov5_obb#250]

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/159150845-ef78ee12-c5b4-412b-8574-f9c8e3d45514.png)

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/159150874-6e1fa375-e3d7-4e03-abc4-2b7e7a7a3d5b.png)
