### ISSUE TITLE
What's the meaning of "diffculty" in label format?

### ISSUE THREAD

**Issue by DnYoZn** [hukaixuan19970627/yolov5_obb#251]
hello，你在git项目中描述的数据标签的形式为任意4点，是把转换标签的的过程放在训练中间了么
那网络的输出是应该是按照长边描述法定义的对么

**Comment by DnYoZn** [comment]
顺便问下标签中的difficult项是什么含义，data数据集自带的么？

**Comment by hukaixuan19970627** [comment]
1. yolov5_obb使用的是长边表示法(cx, cy, longedge, shortedge, θ), θ ∈ [-pi/2, pi/2)/[-90°, 90°)，poly格式和rbox格式之间的转换工作只在预处理代码以及后处理代码中完成
2. 
![image](https://user-images.githubusercontent.com/72599120/159212767-e7f11aeb-74f2-4b88-8527-8aa181340c33.png)

**Comment by LemonWang0110** [comment]
> 1. yolov5_obb使用的是长边表示法(cx, cy, longedge, shortedge, θ), θ ∈ [-pi/2, pi/2)/[-90°, 90°)，poly格式和rbox格式之间的转换工作只在预处理代码以及后处理代码中完成
> 
> ![image](https://user-images.githubusercontent.com/72599120/159212767-e7f11aeb-74f2-4b88-8527-8aa181340c33.png)

你好，请教一下如果想把  θ范围调整为 θ ∈ [-pi, pi)/[-180°, 180°)，需要做哪些修改呢？

**Comment by hukaixuan19970627** [comment]
> > 1. yolov5_obb使用的是长边表示法(cx, cy, longedge, shortedge, θ), θ ∈ [-pi/2, pi/2)/[-90°, 90°)，poly格式和rbox格式之间的转换工作只在预处理代码以及后处理代码中完成
> > 
> > ![image](https://user-images.githubusercontent.com/72599120/159212767-e7f11aeb-74f2-4b88-8527-8aa181340c33.png)
> 
> 你好，请教一下如果想把 θ范围调整为 θ ∈ [-pi, pi)/[-180°, 180°)，需要做哪些修改呢？

因为旋转框的定义方式发生了改变，所以除了backbone和Neck结构外，其余的代码都要改。
当然也有一种更简单的方式，反正你只是想测得物体头部的具体朝向而已，通过旋转矩形的四个点的顺序信息就可以确定旋转物体头部的具体朝向，所以可以在yolov5_obb的基础上对其head新增四个通道，这四个通道用于标注poly四个点的具体顺序。例如dota数据集中的标注(x1,y1, x2,y2, x3,y3, x4,y4)中的（x1，y1）就是物体头部左边的顶点坐标
![image](https://user-images.githubusercontent.com/72599120/159419033-63a5586f-d8a6-4795-8652-05dadabcf5ef.png)

**Comment by LemonWang0110** [comment]
@hukaixuan19970627 你好，今天按照你的思路摸索了一下，但没能搞出来，你能说下大致需要改哪些吗？
