### ISSUE TITLE
rotLabelImg这个软件标注的xml文件中的angle怎么转换为实际目标框的旋转角度？

### ISSUE THREAD

**Issue by GalSang17** [hukaixuan19970627/yolov5_obb#253]

**Comment by GalSang17** [comment]
solved

**Comment by 619732457** [comment]
> solved

你好，rotLabelImg的xml文件转为需要的txt文件，这块有代码能实现吗

**Comment by GalSang17** [comment]
DOTA格式看下就知道了，rotLabelimg是弧度制，math.degrees转角度制就可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月4日(周三) 晚上9:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] rotLabelImg这个软件标注的xml文件中的angle怎么转换为实际目标框的旋转角度？ (Issue #253)




  
solved
  
你好，rotLabelImg的xml文件转为需要的txt文件，这块有代码能实现吗

**Comment by 619732457** [comment]
好的，谢谢，我去看下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hukaixuan19970627/yolov5_obb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月4日(星期三) 晚上9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hukaixuan19970627/yolov5_obb] rotLabelImg这个软件标注的xml文件中的angle怎么转换为实际目标框的旋转角度？ (Issue #253)





 DOTA格式看下就知道了，rotLabelimg是弧度制，math.degrees转角度制就可以了 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年5月4日(周三) 晚上9:06 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [hukaixuan19970627/yolov5_obb] rotLabelImg这个软件标注的xml文件中的angle怎么转换为实际目标框的旋转角度？ (Issue #253) 
 
 
 
 
    
 solved 
    
 你好，rotLabelImg的xml文件转为需要的txt文件，这块有代码能实现吗
