### ISSUE TITLE
抱歉，请问下自定义数据集用什么工具进行标注的？花了好多时间数据层面都还没走通啊

### ISSUE THREAD

**Issue by junjuncv** [hukaixuan19970627/yolov5_obb#254]
@hukaixuan19970627 抱歉，请问标注自己的数据用的是什么工具，是labelme标注poly？最后又怎么转换到DOTA格式的txt数据的这个步骤可以再说明下吗？看readme没看出怎么转换到DOTA数据格式，花了很多时间。
![image](https://user-images.githubusercontent.com/102046845/159294043-3822dac7-a41f-45c7-81ab-b245a76ea882.png)

ps：目前我用rolabelImg工具进行的标注。

**Comment by GalSang17** [comment]
> @hukaixuan19970627 抱歉，请问标注自己的数据用的是什么工具，是labelme标注poly？最后又怎么转换到DOTA格式的txt数据的这个步骤可以再说明下吗？看readme没看出怎么转换到DOTA数据格式，花了很多时间。 ![image](https://user-images.githubusercontent.com/102046845/159294043-3822dac7-a41f-45c7-81ab-b245a76ea882.png)
> 
> ps：目前我用rolabelImg工具进行的标注。

  我也是rotLabelimg标注的，但rotLabelimg中的角度表示是弧度制，需要转为角度制，但我转了后的训练batch图框和目标物又不对应了，我自己用脚本手工验证确实是对的，希望老师能解答下 @hukaixuan19970627

**Comment by UNeedCryDear** [comment]
改写一下ImgSplit_multi_process，从txt里面度去框数据改成从json里面读取，最主要的就是返回旋转矩形框的4个xy的值
![1](https://user-images.githubusercontent.com/52729998/159394439-75868ba7-e084-4dba-af17-eb1b05e0a547.jpg)
![2](https://user-images.githubusercontent.com/52729998/159394440-e368d39b-8121-4629-9275-788ead7a02dc.jpg)
![3](https://user-images.githubusercontent.com/52729998/159394443-2cd20e96-df08-42d9-8798-671c6d15ba90.jpg)

**Comment by GalSang17** [comment]
> 改写一下ImgSplit_multi_process，从txt里面度去框数据改成从json里面读取，最主要的就是返回旋转矩形框的4个xy的值 ![1](https://user-images.githubusercontent.com/52729998/159394439-75868ba7-e084-4dba-af17-eb1b05e0a547.jpg) ![2](https://user-images.githubusercontent.com/52729998/159394440-e368d39b-8121-4629-9275-788ead7a02dc.jpg) ![3](https://user-images.githubusercontent.com/52729998/159394443-2cd20e96-df08-42d9-8798-671c6d15ba90.jpg)

我的图像分辨率集中在900*900左右，不需要对数据集进行切分操作，还有你说的从json读取，是从哪里的json，rotLabelimg产生的不是XML文件么，四个角点的坐标是对的，这个已经验证过了，还请指教

**Comment by UNeedCryDear** [comment]
xml是一致的，主要就是获取8个点坐标放在object中返回，不需要切分的话，你将subsize改的很大就不会切分了

**Comment by GalSang17** [comment]
> xml是一致的，主要就是获取8个点坐标放在object中返回，不需要切分的话，你将subsize改的很大就不会切分了

我找到原因了，只需要对坐标对按照X大小升序就可以

**Comment by junjuncv** [comment]
> > @hukaixuan19970627 抱歉，请问标注自己的数据用的是什么工具，是labelme标注poly？最后又怎么转换到DOTA格式的txt数据的这个步骤可以再说明下吗？看readme没看出怎么转换到DOTA数据格式，花了很多时间。 ![image](https://user-images.githubusercontent.com/102046845/159294043-3822dac7-a41f-45c7-81ab-b245a76ea882.png)
> > ps：目前我用rolabelImg工具进行的标注。
> 
> 我也是rotLabelimg标注的，但rotLabelimg中的角度表示是弧度制，需要转为角度制，但我转了后的训练batch图框和目标物又不对应了，我自己用脚本手工验证确实是对的，希望老师能解答下,张两张图分别是我训练和自己验证的图 @hukaixuan19970627 ![image](https://user-images.githubusercontent.com/49866330/159390455-2c64150e-04aa-44be-b6b8-8db7197e5d71.png) ![image](https://user-images.githubusercontent.com/49866330/159390484-4d2ab07e-cce0-413f-9a5f-a6d660cf827e.png)

请问“训练batch图框和目标物又不对应”，是不是rolabelimg的xml转DOTA的txt，其中的poly坐标或者角度出现错误呢，你这边解决了？

**Comment by GalSang17** [comment]
用cv2.boxPoints，参数中的角度要用math.degrees转为角度制，出来的结果sorted后就是正常的了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月24日(周四) 凌晨3:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 抱歉，请问下自定义数据集用什么工具进行标注的？花了好多时间数据层面都还没走通啊 (Issue #254)




   
@hukaixuan19970627 抱歉，请问标注自己的数据用的是什么工具，是labelme标注poly？最后又怎么转换到DOTA格式的txt数据的这个步骤可以再说明下吗？看readme没看出怎么转换到DOTA数据格式，花了很多时间。 
 ps：目前我用rolabelImg工具进行的标注。
  
我也是rotLabelimg标注的，但rotLabelimg中的角度表示是弧度制，需要转为角度制，但我转了后的训练batch图框和目标物又不对应了，我自己用脚本手工验证确实是对的，希望老师能解答下,张两张图分别是我训练和自己验证的图 @hukaixuan19970627  
  
请问“训练batch图框和目标物又不对应”，是不是rolabelimg的xml转DOTA的txt，其中的poly坐标或者角度出现错误呢，你这边解决了？

**Comment by junjuncv** [comment]
> 用cv2.boxPoints，参数中的角度要用math.degrees转为角度制，出来的结果sorted后就是正常的了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年3月24日(周四) 凌晨3:01 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 抱歉，请问下自定义数据集用什么工具进行标注的？花了好多时间数据层面都还没走通啊 (Issue #254) @hukaixuan19970627 抱歉，请问标注自己的数据用的是什么工具，是labelme标注poly？最后又怎么转换到DOTA格式的txt数据的这个步骤可以再说明下吗？看readme没看出怎么转换到DOTA数据格式，花了很多时间。 ps：目前我用rolabelImg工具进行的标注。 我也是rotLabelimg标注的，但rotLabelimg中的角度表示是弧度制，需要转为角度制，但我转了后的训练batch图框和目标物又不对应了，我自己用脚本手工验证确实是对的，希望老师能解答下,张两张图分别是我训练和自己验证的图 @hukaixuan19970627 请问“训练batch图框和目标物又不对应”，是不是rolabelimg的xml转DOTA的txt，其中的poly坐标或者角度出现错误呢，你这边解决了？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你好，感谢回复。我现在的问题估计就是从rolabelimg格式的txt--->输出poly格式的txt四个坐标出问题了。但为什么需要sorted才行呢?下面是我poly四个坐标的txt。
![image](https://user-images.githubusercontent.com/102046845/159840736-8874d152-c767-4a9e-b01e-a114f6611914.png)

您可以具体些吗，改写哪个项目中脚本cv2.boxPoints？我现在是角度制呢？
![image](https://user-images.githubusercontent.com/102046845/159840669-c1500536-5ce4-4a6a-9718-333d94a9a393.png)

**Comment by GalSang17** [comment]
自己写脚本转，输入就是rotLabelimg对应的点和弧度信息，需要sorted是因为DOTA数据集的第一个点是目标物正向时的左上角



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月24日(周四) 中午12:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 抱歉，请问下自定义数据集用什么工具进行标注的？花了好多时间数据层面都还没走通啊 (Issue #254)




  
用cv2.boxPoints，参数中的角度要用math.degrees转为角度制，出来的结果sorted后就是正常的了
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年3月24日(周四) 凌晨3:01 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 抱歉，请问下自定义数据集用什么工具进行标注的？花了好多时间数据层面都还没走通啊 (Issue #254) @hukaixuan19970627 抱歉，请问标注自己的数据用的是什么工具，是labelme标注poly？最后又怎么转换到DOTA格式的txt数据的这个步骤可以再说明下吗？看readme没看出怎么转换到DOTA数据格式，花了很多时间。 ps：目前我用rolabelImg工具进行的标注。 我也是rotLabelimg标注的，但rotLabelimg中的角度表示是弧度制，需要转为角度制，但我转了后的训练batch图框和目标物又不对应了，我自己用脚本手工验证确实是对的，希望老师能解答下,张两张图分别是我训练和自己验证的图 @hukaixuan19970627 请问“训练batch图框和目标物又不对应”，是不是rolabelimg的xml转DOTA的txt，其中的poly坐标或者角度出现错误呢，你这边解决了？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
你好，感谢回复。我现在的问题估计就是从rolabelimg格式的txt---&gt;输出poly格式的txt四个坐标出问题了。但为什么需要sorted才行呢?下面是我poly四个坐标的txt。
 
 
您可以具体些吗，改写哪个项目中脚本cv2.boxPoints？我现在是角度制呢？

**Comment by junjuncv** [comment]
感谢，我再研究研究。
若是有脚本提供分享就更好了 ，时间尴尬 


| |
ajuncv
|
|
***@***.***
|
在2022年3月24日 ***@***.***> 写道：

自己写脚本转，输入就是rotLabelimg对应的点和弧度信息，需要sorted是因为DOTA数据集的第一个点是目标物正向时的左上角



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月24日(周四) 中午12:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 抱歉，请问下自定义数据集用什么工具进行标注的？花了好多时间数据层面都还没走通啊 (Issue #254)





用cv2.boxPoints，参数中的角度要用math.degrees转为角度制，出来的结果sorted后就是正常的了
…
---原始邮件--- 发件人: @.&gt; 发送时间: 2022年3月24日(周四) 凌晨3:01 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 抱歉，请问下自定义数据集用什么工具进行标注的？花了好多时间数据层面都还没走通啊 (Issue #254) @hukaixuan19970627 抱歉，请问标注自己的数据用的是什么工具，是labelme标注poly？最后又怎么转换到DOTA格式的txt数据的这个步骤可以再说明下吗？看readme没看出怎么转换到DOTA数据格式，花了很多时间。 ps：目前我用rolabelImg工具进行的标注。 我也是rotLabelimg标注的，但rotLabelimg中的角度表示是弧度制，需要转为角度制，但我转了后的训练batch图框和目标物又不对应了，我自己用脚本手工验证确实是对的，希望老师能解答下,张两张图分别是我训练和自己验证的图 @hukaixuan19970627 请问“训练batch图框和目标物又不对应”，是不是rolabelimg的xml转DOTA的txt，其中的poly坐标或者角度出现错误呢，你这边解决了？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;

你好，感谢回复。我现在的问题估计就是从rolabelimg格式的txt---&gt;输出poly格式的txt四个坐标出问题了。但为什么需要sorted才行呢?下面是我poly四个坐标的txt。


您可以具体些吗，改写哪个项目中脚本cv2.boxPoints？我现在是角度制呢？

**Comment by junjuncv** [comment]
> 感谢，我再研究研究。 若是有脚本提供分享就更好了 ，时间尴尬 | | ajuncv | | ***@***.*** | 在2022年3月24日 ***@***.***> 写道： 自己写脚本转，输入就是rotLabelimg对应的点和弧度信息，需要sorted是因为DOTA数据集的第一个点是目标物正向时的左上角
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年3月24日(周四) 中午12:13 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 抱歉，请问下自定义数据集用什么工具进行标注的？花了好多时间数据层面都还没走通啊 (Issue #254) 用cv2.boxPoints，参数中的角度要用math.degrees转为角度制，出来的结果sorted后就是正常的了 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年3月24日(周四) 凌晨3:01 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 抱歉，请问下自定义数据集用什么工具进行标注的？花了好多时间数据层面都还没走通啊 (Issue #254) @hukaixuan19970627 抱歉，请问标注自己的数据用的是什么工具，是labelme标注poly？最后又怎么转换到DOTA格式的txt数据的这个步骤可以再说明下吗？看readme没看出怎么转换到DOTA数据格式，花了很多时间。 ps：目前我用rolabelImg工具进行的标注。 我也是rotLabelimg标注的，但rotLabelimg中的角度表示是弧度制，需要转为角度制，但我转了后的训练batch图框和目标物又不对应了，我自己用脚本手工验证确实是对的，希望老师能解答下,张两张图分别是我训练和自己验证的图 @hukaixuan19970627 请问“训练batch图框和目标物又不对应”，是不是rolabelimg的xml转DOTA的txt，其中的poly坐标或者角度出现错误呢，你这边解决了？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 你好，感谢回复。我现在的问题估计就是从rolabelimg格式的txt---&gt;输出poly格式的txt四个坐标出问题了。但为什么需要sorted才行呢?下面是我poly四个坐标的txt。 您可以具体些吗，改写哪个项目中脚本cv2.boxPoints？我现在是角度制呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ryouchinsa** [comment]
[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel, you can draw oriented bounding boxes and export to the DOTA OBB format.
```
x1 y1 x2 y2 x3 y3 x4 y4 category difficult
1300.536987 1413.503784 1192.848755 1535.568848 530.876038 951.562073 638.564270 829.497009 truck 0
```

![draw_obb_polygon](https://user-images.githubusercontent.com/1954306/209951610-a343bd8c-7d49-4382-a4dd-bd9cf92bd318.jpg)

**Comment by ZJTTJ** [comment]
> 

你好，近期在研究转格式问题1，可以分享一下转格式的具体代码吗。目前使用Rolabelimg进行标注。
