### ISSUE TITLE
【训练速度问题】 yolov5s模型比yolov5s6模型训练速度快很多，差距快10倍了。

### ISSUE THREAD

**Issue by UNeedCryDear** [hukaixuan19970627/yolov5_obb#255]
我试过yolov5s.pt模型，由于数据量不大（1000来张），3090下16 batch size，1280x1280大小图片，yolov5s模型一轮epoch大致在2分钟，但是yolov5s6模型一轮epoch在22分钟，差距过大，按照我的理解，yolov5s6比s模型多一个输出口，而且还是64步长的，那速度会慢，也不应该慢这么多.

**Comment by UNeedCryDear** [comment]
debug半天，不如重启大法好用
![346](https://user-images.githubusercontent.com/52729998/159896130-790069ea-3df3-4b34-ac7b-e74cfec61455.jpg)

**Comment by HKVINS89757** [comment]
啥数据库啊
