### ISSUE TITLE
ONNX output format

### ISSUE THREAD

**Issue by calvinIsAwesome** [hukaixuan19970627/yolov5_obb#256]
作者及各位大佬您好，请教在通过export.py转换为ONNX模型后输出层的1x4032x187这种结构该如何解读？我猜测的是4032=3x32x32+3x16x16+3x8x8；187=179个角度+8个坐标值？
<img width="482" alt="截屏2022-03-22 14 03 28" src="https://user-images.githubusercontent.com/24402619/159417924-c0618395-6c3c-4f48-baf1-833be350f881.png">
但是观察输出的数据格式，没有理解各个数分别代表什么
<img width="1387" alt="截屏2022-03-22 14 05 06" src="https://user-images.githubusercontent.com/24402619/159418106-67c87012-063b-4797-a660-b43bff0d7c9a.png">
多谢～

**Comment by hukaixuan19970627** [comment]
模型输出会经nms处理得到list:[cx, cy, l, s, θ, conf, clsid] θ ∈ [-pi/2, pi/2)
另外detect支持onnx推理，所以你debug non_max_suppression_obb函数就清楚了
![image](https://user-images.githubusercontent.com/72599120/159421299-08714f2f-c6b0-4be2-8def-855c753c0689.png)

**Comment by calvinIsAwesome** [comment]
谢谢！我研究一下🙏

**Comment by GalSang17** [comment]
> 模型输出会经nms处理得到list:[cx, cy, l, s, θ, conf, clsid] θ ∈ [-pi/2, pi/2) 另外detect支持onnx推理，所以你debug non_max_suppression_obb函数就清楚了 ![image](https://user-images.githubusercontent.com/72599120/159421299-08714f2f-c6b0-4be2-8def-855c753c0689.png)

![image](https://user-images.githubusercontent.com/49866330/160044802-d77e1990-f29f-41cf-8fb6-99b95ac41f2e.png)
老师你好，我现在有一个这样的问题请教你，就是我在训练自己的模型时pt保存的信息如我截图的代码部分所示，然后转onnxF32推理是正常的，转onnxF16会报错，转engine的时候，F32会直接报错，就是export.py生成engine部分会直接走expect部分，但是转engine的F16就又是正常的，但是速度会特别慢（20min+）且显存会占掉10G+(2080Ti)，用F16的engine推理一个目标上会出现两个框,，所有目标都是这个情况，conf和nms都是0.8进行的推理，需要提醒的一点就是我训练的时候anchor是修改过的，且模型用的yolo的L结构，未使用预训练权重，我不清楚现在是这些步骤中的哪一个导致的推理结果不对，期待老师的解答 @hukaixuan19970627

**Comment by hukaixuan19970627** [comment]
> > 模型输出会经nms处理得到list:[cx, cy, l, s, θ, conf, clsid] θ ∈ [-pi/2, pi/2) 另外detect支持onnx推理，所以你debug non_max_suppression_obb函数就清楚了 ![image](https://user-images.githubusercontent.com/72599120/159421299-08714f2f-c6b0-4be2-8def-855c753c0689.png)
> 
> ![image](https://user-images.githubusercontent.com/49866330/160044802-d77e1990-f29f-41cf-8fb6-99b95ac41f2e.png) ![image](https://user-images.githubusercontent.com/49866330/160047782-49a0afff-d870-4288-808c-b6e478db0603.png)
> 
> 老师你好，我现在有一个这样的问题请教你，就是我在训练自己的模型时pt保存的信息如我截图的代码部分所示，然后转onnxF32推理是正常的，转onnxF16会报错，转engine的时候，F32会直接报错，就是export.py生成engine部分会直接走expect部分，但是转engine的F16就又是正常的，就是速度会特别慢（20min+）且显存会占掉10G+(2080Ti)，用F16的engine推理所有图都没有结果，conf和nms都是0.5进行的推理，还有一点就是我如果用onnx2trt这个工具在命令行直接转onnx到engine的话速度很快(1min+)，推理也有结果输出，但是每个目标都会出现两个框，像截图2所示，需要提醒的一点就是我训练的时候anchor是修改过的，且模型用的yolo的L结构，未使用预训练权重，我不清楚现在是这些步骤中的哪一个导致的推理结果不对，期待老师的解答 @hukaixuan19970627

你试试转换一下我提供的weights权重文件，然后detect项目的demo图片，看看是否会发生同样的问题
