### ISSUE TITLE
val.py 和 detect.py不再生成汇总的文件了

### ISSUE THREAD

**Issue by alandechang** [hukaixuan19970627/yolov5_obb#258]
大佬你好，初代版本会有原始图片的整合以及生成相应的txt文件，但是新版本没看到

**Comment by alandechang** [comment]
有针对每个图片的，但是没有进行直接的汇总

**Comment by hukaixuan19970627** [comment]
ResultMerge.py会生成针对每个类别汇总的txt，txt里包含了目标边框信息和它所在的原图文件名称。
你可以根据这个自己写个程序转一下，我最近较忙，懒得写
