### ISSUE TITLE
nan in training on Windows

### ISSUE THREAD

**Issue by wjmicheal** [hukaixuan19970627/yolov5_obb#260]
![nan](https://user-images.githubusercontent.com/102284898/160222657-46c9cbab-fd25-4dfa-972c-ede8a9a97e84.jpg)
大佬，你好，我使用demo中的数据进行训练时，box obj cls theta 等损失显示为nan？不知是什么原因

**Comment by wjmicheal** [comment]
以下
![train_batch0](https://user-images.githubusercontent.com/102284898/160222721-f54d29ab-89b7-4d27-bf66-a6486e620ef4.jpg)
![train_batch1](https://user-images.githubusercontent.com/102284898/160222723-a5c2d261-4219-49b4-a033-748cedbfb3e4.jpg)
![train_batch2](https://user-images.githubusercontent.com/102284898/160222725-9ea050f0-6ae5-448c-9d59-181524021548.jpg)
![train_batch3](https://user-images.githubusercontent.com/102284898/160222726-66d33244-be13-44f9-aa24-918b945fa61a.jpg)
![train_batch4](https://user-images.githubusercontent.com/102284898/160222727-0406db35-ad11-4882-9ad9-68fd38dca66a.jpg)
![train_batch5](https://user-images.githubusercontent.com/102284898/160222728-5b096ec3-fb38-4bab-8bd4-673d6c75d2b4.jpg)
![train_batch6](https://user-images.githubusercontent.com/102284898/160222729-32f287b2-cf64-4277-9b7c-52b91f832c13.jpg)
![train_batch7](https://user-images.githubusercontent.com/102284898/160222731-b633f2eb-4ecd-4cea-9767-77e5bb96c2f0.jpg)
![val_batch0_labels](https://user-images.githubusercontent.com/102284898/160222733-1a16395b-92c8-4894-b9fc-6afee6117ac4.jpg)
![val_batch0_pred](https://user-images.githubusercontent.com/102284898/160222734-bdf9eb0c-063e-4a64-b5c5-d2cc3647874c.jpg)
![val_batch1_labels](https://user-images.githubusercontent.com/102284898/160222736-3fb6d3e5-b5ef-417f-b17f-b1b1854af6d2.jpg)
![val_batch1_pred](https://user-images.githubusercontent.com/102284898/160222737-017e8581-080c-4000-aebe-420511eddae1.jpg)
是训练后runs/train/exp 文件夹下相关文件

**Comment by wjmicheal** [comment]
这是hyp.ymal和opt.ymal
[hyp.txt](https://github.com/hukaixuan19970627/yolov5_obb/files/8354591/hyp.txt)
[opt.txt](https://github.com/hukaixuan19970627/yolov5_obb/files/8354592/opt.txt)

**Comment by wjmicheal** [comment]
研究了好几天，运行detect.py检测结果是正常的，但是train一直出现nan，期待您的回复

**Comment by wjmicheal** [comment]
这是result.csv 和result.png两个文件
[results.csv](https://github.com/hukaixuan19970627/yolov5_obb/files/8354601/results.csv)
![results](https://user-images.githubusercontent.com/102284898/160223102-7d5f0b16-e420-42b8-8234-5ffb350cda8d.png)

**Comment by wjmicheal** [comment]
另外，我的run/train/exp文件夹下未生成   labels.jpg  labels_correlogram.jpg   这两个文件

**Comment by hukaixuan19970627** [comment]
如果你是windows+CUDA11训练过程中出现nan的话可以参考下这个issue：https://github.com/ultralytics/yolov5/issues/5815
