### ISSUE TITLE
提示yolov5_obb/utils/nms_rotated/nms_rotated_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPvmm

### ISSUE THREAD

**Issue by yangming168-gif** [hukaixuan19970627/yolov5_obb#261]
ImportError: /home/x317/yang/yolov5_obb/utils/nms_rotated/nms_rotated_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPvmm

**Comment by QueenZK520** [comment]
me too.

**Comment by hukaixuan19970627** [comment]
Delete nms_rotated_ext.cpython-39-x86_64-linux-gnu.so and install yolov5_obb again.

**Comment by hukaixuan19970627** [comment]
> 我是win10,运行setup.py报错，无法生成ext文件，有救吗，旋哥 RuntimeError: Error compiling objects for extension

#224

**Comment by BrantonLiu** [comment]
> Delete nms_rotated_ext.cpython-39-x86_64-linux-gnu.so and install yolov5_obb again. ![image](https://user-images.githubusercontent.com/72599120/161373246-000df671-b759-4a95-a806-f575c42a3b8e.png)

remember to delete build file at the same time, then setup.py again. This works for me.

**Comment by YsanZyh** [comment]
> > Delete nms_rotated_ext.cpython-39-x86_64-linux-gnu.so and install yolov5_obb again. ![image](https://user-images.githubusercontent.com/72599120/161373246-000df671-b759-4a95-a806-f575c42a3b8e.png)
> 
> remember to delete build file at the same time, then setup.py again. This works for me.

请问Linux中运行python setup.py develop 生成的就是.so文件吗，之前在Windows下生成的是.pyd文件

**Comment by BrantonLiu** [comment]
> > > Delete nms_rotated_ext.cpython-39-x86_64-linux-gnu.so and install yolov5_obb again. ![image](https://user-images.githubusercontent.com/72599120/161373246-000df671-b759-4a95-a806-f575c42a3b8e.png)
> > 
> > 
> > remember to delete build file at the same time, then setup.py again. This works for me.
> 
> 请问Linux中运行python setup.py develop 生成的就是.so文件吗，之前在Windows下生成的是.pyd文件

时间有点久有点忘了，印象中是的

**Comment by xuxiansheng2018** [comment]
> 请问Linux中运行python setup.pydevelop生成的就是.so文件吗，之前在Windows下生成的是.pyd文件

请问解决了吗

**Comment by weiyaokun** [comment]
之前一直能用   过一段时间  再用时候就出现这个错误了，
ImportError: /home/mtd/mnt/B/weiyk/yolov5_obb/utils/nms_rotated/nms_rotated_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _Z13__THCudaCheck9cudaErrorPKci
  删除nms_rotated_ext.cpython-39-x86_64-linux-gnu.so  这个，  然后又重新生成  还是不管用   但是我看了下生成日期  不是现在日期是以前的日期   请问这是什么问题导致的呢？
