### ISSUE TITLE
my data is corrupted?  train.py :Scanning   

### ISSUE THREAD

**Issue by syncsyncsync** [hukaixuan19970627/yolov5_obb#264]
Hi,

 I confirmed the command in GetStart.md works perfectly, 
``python train.py --data 'data/yolov5obb_demo.yaml' --epochs 10 --batch-size 1 --img 1024 --device 0``

Then, I replace the original dataset by my custom dataset.
My images and labels are like below:

image type:
       PNG image data, 720 x 540, 8-bit grayscale, non-interlaced

label format:
      311,225,340,284,299,304,271,245,class1,0

I'm thinking that label format is correct, and my image-size is not large so I don't need to used any Split-Image
command.

But I use the same command,
``python train.py --data 'data/yolov5obb_demo.yaml' --epochs 10 --batch-size 1 --img 512  --device 0``

I got an error message saying,
"Scanning 'dataset/dataset_demo/labelTxt' images and labels...38 found, 2 missing, 0 empty, 38 corrupted"

I can not see why my images are regarded as corrupted in the first place.
Can you have any advice?   
Thank you .

----
albumentations: Blur(always_apply=False, p=0.01, blur_limit=(3, 7)), MedianBlur(always_apply=False, p=0.01, blur_limit=(3, 7)), ToGray(always_apply=False, p=0.01), CLAHE(always_apply=False, p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
train: Scanning 'dataset/dataset_demo/labelTxt' images and labels...38 found, 2 missing, 0 empty, 38 corrupted: 100%|███████████████████████| 40/40 [00:00<00:00, 2685.00it/s]
train: WARNING: dataset/dataset_demo/images/frame000004.png: ignoring corrupt image/label: list index out of range
train: WARNING: dataset/dataset_demo/images/frame000024.png: ignoring corrupt image/label: list index out of range
train: WARNING: dataset/dataset_demo/images/frame000074.png: ignoring corrupt image/label: list index out of range
train: New cache created: dataset/dataset_demo/labelTxt.cache
Traceback (most recent call last):
  File "train.py", line 632, in <module>
    main(opt)
  File "train.py", line 529, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 217, in train
    mlc = int(np.concatenate(dataset.labels, 0)[:, 0].max())  # max label class
  File "/home/****/lib/python3.7/site-packages/numpy/core/_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by hukaixuan19970627** [comment]
I guess your dataset file structure is not right.

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/161372874-fe9fa7dc-85a0-459c-b2af-72ed884d594c.png)

**Comment by cyp-happy** [comment]
我也遇到了这个问题，但我是之间用dota标签，发现也能运行demo，然后把所有dota数据放进去就出现这个错误了

**Comment by syncsyncsync** [comment]
Hi cyp-happy, thanks your comments.
I've been stuck this issue yet, I think this doesn't come from dataset structure but somewhere else.

> 我也遇到了这个问题，但我是之间用dota标签，发现也能运行demo，然后把所有dota数据放进去就出现这个错误了

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/165228346-2f1ff936-1a9e-4945-a31b-ee1cc7d37037.png)
That means dataset.labels is a  zero-size array. Can you give a download link for the dataset?

**Comment by syncsyncsync** [comment]
I can't upload the images but labels are here, 
https://github.com/syncsyncsync/tmp.git
Thanks

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/165505537-4e9f1314-2ebb-4f2e-86a2-defb650ffc6d.png)

**Comment by syncsyncsync** [comment]
Changing  'Int -> float' worked.
Thank you a lot.

**Comment by pangyanhua** [comment]
> Changing polygon coordinates from 'Int' to ' float' worked. Thank you a lot!

how did you convert int to float？

**Comment by ChristoCai** [comment]
应该是数据格式的问题

**Comment by ZJTTJ** [comment]
> 我也遇到了这个问题，但我是之间用dota标签，发现也能运行demo，然后把所有dota数据放进去就出现这个错误了

我最近刚开始做这个，demo部分是如何运行的，我无法从博主的过期链接中获取demofiles，我直接下载了DOTAV1.5的数据放入dataset中，也报了和这个一样的错误，请问一下分享一下demo的运行过程和demo的文件吗？该问题的解决方法Changing polygon coordinates from 'Int' to ' float' worked.有解决吗
