### ISSUE TITLE
cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' 

### ISSUE THREAD

**Issue by devil1213** [hukaixuan19970627/yolov5_obb#265]
你好 我下载运行这个项目显示报错 这个报错了from . import nms_rotated_ext 请问是没有这个吗

**Comment by devil1213** [comment]
> 你好 我下载运行这个项目显示报错 这个报错了from . import nms_rotated_ext 请问是没有这个吗

ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import) 这个错误

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/161373034-8ba75b7b-cbe0-4650-bf8c-c79a3a2c650e.png)

**Comment by devil1213** [comment]
> 你好！请问这个问题您解决掉了吗？ 谢谢答复
我的电脑内存炸了 我还没去尝试 我的是torch 1.11 应该是这个的原因 你可以试试1.10版本的看看

**Comment by Winniesea** [comment]
> 

我的torch就是1.10诶，我继续调试，如果成功了再来告诉你

**Comment by hukaixuan19970627** [comment]
@Winniesea @devil1213 
![image](https://user-images.githubusercontent.com/72599120/161897166-6a90dcf6-158b-417b-aa49-aaaa68865168.png)
![image](https://user-images.githubusercontent.com/72599120/161897200-761c98a6-c2c1-40ea-95bd-e62caad61714.png)
......花十分钟看一遍readme，按install.md检查环境 ，按getstarted.md走一遍使用流程，这些问题早解决了

**Comment by devil1213** [comment]
已经解决 Windows的问题 按照之前的issuse就可以解决 麻烦了

**Comment by Winniesea** [comment]
请问是按照哪个issue解决掉的呢？感谢回复！


| |
王梦妮
|
|
***@***.***
|
On 4/8/2022 ***@***.***> wrote：

已经解决 Windows的问题 按照之前的issuse就可以解决 麻烦了

**Comment by devil1213** [comment]
> 请问是按照哪个issue解决掉的呢？感谢回复！ | | 王梦妮 | | ***@***.*** | On 4/8/2022 ***@***.***> wrote： 已经解决 Windows的问题 按照之前的issuse就可以解决 麻烦了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

https://github.com/hukaixuan19970627/yolov5_obb/issues/224#issue-1161120376  这个

**Comment by Winniesea** [comment]
好的！非常感谢！：D


| |
王梦妮
|
|
***@***.***
|
On 4/8/2022 ***@***.***> wrote：

请问是按照哪个issue解决掉的呢？感谢回复！ | | 王梦妮 | | @.*** | On 4/8/2022 @.> wrote： 已经解决 Windows的问题 按照之前的issuse就可以解决 麻烦了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.>

#224 (comment) 这个

**Comment by hecheng000** [comment]
> 已经解决 Windows的问题 按照之前的issuse就可以解决 麻烦了

你好 请问怎么解决的啊 可以加个联系方式告知详细步骤吗

**Comment by hecheng000** [comment]
> 好的！非常感谢！：D | | 王梦妮 | | ***@***.*** | On 4/8/2022 ***@***.***> wrote： 请问是按照哪个问题解决决定掉的呢？谢谢回复！ | | 王梦妮 | | @.*** | On 4/8/2022 @.> wrote： 已经解决 Windows 的问题 按照之前的问题就可以解决 麻烦了 — 直接回复这封邮件，在 GitHub 上查看它，或者退订。您收到此邮件是因为您被提及。消息 ID：@.> #224（评论）这个 — 直接回复此电子邮件，在 GitHub 上查看它，或取消订阅。您收到此邮件是因为有人提到了您。消息 ID：***@***。***>

你好 请问怎么解决啊

**Comment by BigBeardYT** [comment]
请问一下，在install的第 e 步中，前面所有的流程全部正确，但是运行到 python setup.py develp时，报错以下信息，是什么原因呢？
(yolo_obb) D:\Python_OD_project\yolov5_obb-master\utils\nms_rotated>python setup.py develop
running develop
E:\Anaconda3\envs\yolo_obb\lib\site-packages\setuptools\command\develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
E:\Anaconda3\envs\yolo_obb\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing nms_rotated.egg-info\PKG-INFO
writing dependency_links to nms_rotated.egg-info\dependency_links.txt
writing top-level names to nms_rotated.egg-info\top_level.txt
reading manifest file 'nms_rotated.egg-info\SOURCES.txt'
writing manifest file 'nms_rotated.egg-info\SOURCES.txt'
running build_ext
building '.nms_rotated_ext' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
