### ISSUE TITLE
TypeError: barrier() got an unexpected keyword argument 'device_ids'

### ISSUE THREAD

**Issue by Grifcc** [hukaixuan19970627/yolov5_obb#266]
File "/home/NewPartion/Grifcc/yolov5_obb/utils/torch_utils.py", line 35, in torch_distributed_zero_first
    dist.barrier(device_ids=[local_rank])
TypeError: barrier() got an unexpected keyword argument 'device_ids'

**Comment by hukaixuan19970627** [comment]
You can refer to this [issue](https://github.com/ultralytics/yolov5/issues/4480)
