### ISSUE TITLE
关于预训练权重

### ISSUE THREAD

**Issue by Michaelnlearn** [hukaixuan19970627/yolov5_obb#267]
你好，项目作者，我想问问你的测试结果map0.77左右是用了yolov5m.pt预训练权重，再开始训练300epochs达到的。还是没用预训练权重，直接从头开始训练得到的，我从头开始训练效果只有0.6多map。
然后，修改了网络结构后还可以用预训练权重吗？
非常感谢！

**Comment by hukaixuan19970627** [comment]
1.
![image](https://user-images.githubusercontent.com/72599120/161504725-d9f05aa5-7a27-4793-a38a-cbe09b48b260.png)
![image](https://user-images.githubusercontent.com/72599120/161504765-d702ccfa-1778-4d4d-90a1-1f4e5d9b5b77.png)
2.可以，参数会一直加载至无法和模型结构一一对应为止

**Comment by Michaelnlearn** [comment]
嗯嗯，我修改了模型发现效果不好，是因为我没加载预训练权重，重头开始训练的。
昨晚看了源码，会取结构相同的层初始化权重，但是我修改了backbone，导致对应字典名字不一样，要自己修改一下初试化权重的函数。
谢谢作者

**Comment by Michaelnlearn** [comment]
it was dealed
