### ISSUE TITLE
训练时默认rect参数为False，可以更改为true吗？

### ISSUE THREAD

**Issue by kurt369** [hukaixuan19970627/yolov5_obb#269]
不开启矩形训练感觉速度还是很慢，开启后会影响旋转目标的预测框的定位吗？

**Comment by hukaixuan19970627** [comment]
首先你要分析限制训练速度提升的原因是什么。例如：查看训练时的gpu利用率，如果时常利用率为0，说明一轮数据的训练完成之后下一轮的数据还没准备好，这表明电脑的cpu性能应付不了这么多的数据量，这个时候减小batchsize反而能提升整体的训练效率。

**Comment by hukaixuan19970627** [comment]
另外关于矩形训练的rect参数，只要trainbatch0/1/2/.../n.jpg里的labels没问题那就随你更改

**Comment by kurt369** [comment]
谢谢大哥回答，另外还有两个问题:&nbsp;
1）专用Gpu内存利用率基本是满的（21.2/24），copy那一项在训练时一直是0，在验证的时候就跳到88%，这是正常的吗？
2）我是4000*2000的图片，imgsize设置的是4000，按照yolo的处理方式，没开启矩形训练的话，会被pad成4000*4000，在开启矩形训练之后，应该会被pad成4000*2016，按理说开启矩形训练之后，gpu占用和训练时间都会减小才对，可是我开启矩形训练之后，发现gpu占用和训练时间并没有变化，这是什么原因呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月8日(周五) 下午2:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 训练时默认rect参数为False，可以更改为true吗？ (Issue #269)




 
另外关于矩形训练的rect参数，只要trainbatch0/1/2/.../n.jpg里的labels没问题那就随你更改

**Comment by hukaixuan19970627** [comment]
1. gpu利用率（Volatile GPU-Util）和gpu占用率（Memory-Usage）是两个概念。
2. 经测试840×712分辨率的图像在使用矩形训练之后可降低30%左右的显存消耗量。
