### ISSUE TITLE
error: command 'D:\\software\\CUDA9_and_10\\Program Files\\NVIDIA GPU Computing Toolkit\\v9.0\\bin\\nvcc.exe' failed with exit status 1

### ISSUE THREAD

**Issue by fubai3** [hukaixuan19970627/yolov5_obb#270]
您好 我遇到了这个问题 是什么情况导致的呢 谢谢error: command 'D:\\software\\CUDA9_and_10\\Program Files\\NVIDIA GPU Computing Toolkit\\v9.0\\bin\\nvcc.exe' failed with exit status 1

**Comment by fubai3** [comment]
error: command 'D:\\software\\CUDA9_and_10\\Program Files\\NVIDIA GPU Computing Toolkit\\v9.0\\bin\\nvcc.exe' failed with exit status 1
nvcc fatal   : Option '--cl-version' needs to be specified with option '--use-local'
显示了这个 怎么指定use-local呢  谢谢

**Comment by devil1213** [comment]
你好 我在运行安装环境步骤中的python setup.py develop时也出现了error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3\\bin\\nvcc.exe' failed with exit status 1这个错误 我的环境是cuda 11.3 torch1.10.1   python 3.8按照 配置文件进行配置但是有错误 请问你解决了吗

**Comment by hukaixuan19970627** [comment]
windows执行
```
python setup.py 
```
时报这个错误的话参考 #224

**Comment by joish-li** [comment]
> 你好 我在运行安装环境步骤中的python setup.py develop时也出现了error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc.exe' failed with exit status 1这个错误 我的环境是cuda 11.3 torch1.10.1 python 3.8按照 配置文件进行配置但是有错误 请问你解决了吗

俺的是Visual Studio 的版本不对，2017，2019都可以，我是2022，改了就好了
