### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by devil1213** [hukaixuan19970627/yolov5_obb#274]
你好 按照getstar开始运行项目 数据集是切割的DOTA数据集 开始训练后 如果不加 noval命令 就是每多训练一次就会增加使用的GPU显存 会报爆显存的错误 如果加上 noval命令 训练第一次train之后会爆出 TypeError: not all arguments converted during string formatting 这个错误，请问怎么解决 谢谢

**Comment by hukaixuan19970627** [comment]
建议重启再试一次

**Comment by devil1213** [comment]
> 建议重启再试一次

你好我无论是重启还是更换3090显卡都会出现 请问有人在windows10上利用DOTA数据集实现这个项目吗 想请教一下怎么弄  谢谢

**Comment by hukaixuan19970627** [comment]
不大明白你描述的问题是怎样的，我在使用时并未发现显存泄露的问题。你是指training时显存保持不变，但是一旦进入validation状态，显存就会增加是吗，那下一个epoch时显存有没有恢复呢？

**Comment by devil1213** [comment]
> 不大明白你描述的问题是怎样的，我在使用时并未发现显存泄露的问题。你是指training时显存保持不变，但是一旦进入validation状态，显存就会增加是吗，那下一个epoch时显存有没有恢复呢？

是的 输入--noval 可以解决这个显存问题 但是会报另一个错误 我已经在使用linux系统进行训练了 感谢回答
