### ISSUE TITLE
box_loss unnormal

### ISSUE THREAD

**Issue by Mason1992-Git** [hukaixuan19970627/yolov5_obb#275]
作者，你好！
我在训练自己的数据集的时候结果出现loss收敛不正常，detect测试无结果的现象。数据集50张，训练300epoch。
result.png
![results](https://user-images.githubusercontent.com/79744902/162551909-5004169d-1e11-47f6-ae76-e5ed43f436eb.png)
R_curve
![R_curve](https://user-images.githubusercontent.com/79744902/162551929-20b55630-8ce6-45ca-8b50-3140f1cb9c02.png)
P_curve
![P_curve](https://user-images.githubusercontent.com/79744902/162551951-a4e1db9b-9c2b-401e-a67c-64449bf43fb5.png)

train_batch0
![train_batch0](https://user-images.githubusercontent.com/79744902/162551965-a2ba4916-8224-42d4-a7bd-0d93002f9668.jpg)
hyp.yaml
lr0: 0.01
lrf: 0.2
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.05
cls: 0.5
cls_pw: 1.0
theta: 0.5
theta_pw: 1.0
obj: 1.0
obj_pw: 1.0
iou_t: 0.2
anchor_t: 4.0
fl_gamma: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 180.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.5
fliplr: 0.5
mosaic: 0.0
mixup: 0.1
copy_paste: 0.0
cls_theta: 180
csl_radius: 2.0

opt.yaml
weights: weights\yolov5m.pt
cfg: ''
data: data\yolov5obb_demo.yaml
hyp: data\hyps\obb\hyp.finetune_dota.yaml
epochs: 300
batch_size: 8
imgsz: 1024
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 2
project: runs\train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\exp

**Comment by Mason1992-Git** [comment]
我在detect文件中打断点，模型forward是有结果的，只是因为confidence过小，再NMS中全部被筛出了。这是因为训练不够吗？但是只有50张数据集，300个epoch应该能够比较好的收敛了啊。感谢您的

**Comment by hukaixuan19970627** [comment]
精度曲线的上升趋势停止才表示收敛了，你这个训练情况都还没有稳定下来
