### ISSUE TITLE
About --agnostic-nms

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/yolov5_obb#276]
![image](https://user-images.githubusercontent.com/54108453/162687301-5a430e72-ab1e-47cb-b8c9-5f7d0f9ebe3c.png)
请问，在这段代码中，x[:, 6:7] 为什么要乘以 max_wh, rboxes[:,:2]为什么要加上c？
谢谢

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/162696670-9c14053a-d77a-42de-985b-7553214d1bd1.png)

c的值为类别id*4096或0，c=0时就是对所有类别的框进行NMS，即一个物体至多只有一个预测类别；c=cls_id*4096相当于把不同类别的框远远地分隔了，这样NMS处理时就只会针对同类别的框之间进行NMS，即一个物体可以有多个预测类别

**Comment by kuazhangxiaoai** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/162696670-9c14053a-d77a-42de-985b-7553214d1bd1.png)
> 
> c的值为类别id×4096或0，c=0时就是对所有类别的框进行NMS，即一个物体至多只有一个预测类别；c=cls_id×4096相当于把不同类别的框远远地分隔了，这样NMS处理时就只会针对同类别的框之间进行NMS，即一个物体可以有多个预测类别

既然这样，应该还要有一个减去c的操作，使得 rbox[:, :2] 恢复原始的坐标，但是我并没有发现这样的操作。

**Comment by hukaixuan19970627** [comment]
有问题的话最好先debug一遍，NMS的输出是框的索引，rbox只是个中间变量
