### ISSUE TITLE
关于多标签预测得问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/yolov5_obb#277]
看了您得 general.py 代码，在 non_max_suppression_obb函数中， 为什么multi_label=True能够达到多标签预测得效果？看您并没有按照cls进行分组nms啊？
![image](https://user-images.githubusercontent.com/54108453/162690036-adca2561-82da-4b86-b1aa-39e495f665a3.png)

**Comment by hukaixuan19970627** [comment]
这个问题要结合 #276 一起看。
