### ISSUE TITLE
version of yolov5

### ISSUE THREAD

**Issue by lesterlee89** [hukaixuan19970627/yolov5_obb#278]
great work!
base version of yolov5,  4.0, 5.0, or 6.0 ?

**Comment by hukaixuan19970627** [comment]
6.0.
[Update.md](https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/ChangeLog.md)
![image](https://user-images.githubusercontent.com/72599120/162893422-ed5254a1-1ccb-4f52-853d-55c23ee86fae.png)

**Comment by lesterlee89** [comment]
thanks
