### ISSUE TITLE
标签起始角点是否会影响训练？

### ISSUE THREAD

**Issue by zysc1996** [hukaixuan19970627/yolov5_obb#279]
您好，我有一批四角标注的旋转框标签，由于标注规则不明确，顺逆时针以及起始角点都不固定，请问会影响标签转换么？如果有影响的话，是一定要处理成左上角为起点顺时针标注么？

**Comment by hukaixuan19970627** [comment]
1. poly四个点的顺序对yolov5_obb项目没有影响
2. 首先你的标签格式肯定存在错误，请按照getstart.md里的label格式检查一下；另外labels里有负值
![image](https://user-images.githubusercontent.com/72599120/163106036-7f645722-a07b-42af-a52f-fde53bc43dcf.png)

**Comment by zysc1996** [comment]
我仔细检查过标签，可以确定没有负值。现在怀疑是这样一个问题，由于裁剪的原因，很多边缘处的目标被截断了，标注的时候会有一条边是竖直或水平的，这样的话在调用cv2.minAreaRect（）方法的时候是否会返回负值？

**Comment by hukaixuan19970627** [comment]
> 我仔细检查过标签，可以确定没有负值。现在怀疑是这样一个问题，由于裁剪的原因，很多边缘处的目标被截断了，标注的时候会有一条边是竖直或水平的，这样的话在调用cv2.minAreaRect（）方法的时候是否会返回负值？

根据我贴出的代码逻辑截图来看，你的数据集标签里面肯定有负值，不然不会触发“negative label values...”提示，你可以自己打个断点debug看看
