### ISSUE TITLE
utils\nms_rotated\setup.py出问题

### ISSUE THREAD

**Issue by WxWuser** [hukaixuan19970627/yolov5_obb#280]
> （win10）环境：torch==1.8.0+cu111 torchvision==0.9.0+cu111

照着 install.md 里面步骤，但是会报错
![QQ截图20220413125022](https://user-images.githubusercontent.com/52120917/163103758-04e07291-3900-4155-9604-fe2eac418b02.png)
![QQ截图20220413125045](https://user-images.githubusercontent.com/52120917/163103768-d1095693-1fdf-4fd0-8508-7b5148c57ef9.png)

**Comment by hukaixuan19970627** [comment]
windows 编译通不过可以参考 #224

**Comment by WxWuser** [comment]
> 

C:\Users\Administrator\Desktop\yolov5_obb-master\utils\nms_rotated>python setup.py develop
running develop
D:\python\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\python\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing nms_rotated_ext.egg-info\PKG-INFO
writing dependency_links to nms_rotated_ext.egg-info\dependency_links.txt
writing top-level names to nms_rotated_ext.egg-info\top_level.txt
reading manifest file 'nms_rotated_ext.egg-info\SOURCES.txt'
writing manifest file 'nms_rotated_ext.egg-info\SOURCES.txt'
running build_ext
D:\python\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building '.nms_rotated_ext' extension
Emitting ninja build file C:\Users\Administrator\Desktop\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-38\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\python\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib/x64" /LIBPATH:D:\python\libs /LIBPATH:D:\python /LIBPATH:D:\python\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EXPORT:PyInit_nms_rotated_ext C:\Users\Administrator\Desktop\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-38\Release\src/nms_rotated_cpu.obj C:\Users\Administrator\Desktop\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-38\Release\src/nms_rotated_cuda.obj C:\Users\Administrator\Desktop\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-38\Release\src/nms_rotated_ext.obj C:\Users\Administrator\Desktop\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-38\Release\src/poly_nms_cuda.obj /OUT:build\lib.win-amd64-cpython-38\nms_rotated_ext.cp38-win_amd64.pyd /IMPLIB:C:\Users\Administrator\Desktop\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-38\Release\src\nms_rotated_ext.cp38-win_amd64.lib
LINK : fatal error LNK1181: 无法打开输入文件“C:\Users\Administrator\Desktop\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-38\Release\src\nms_rotated_cpu.obj”
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
C:\Users\Administrator\Desktop\yolov5_obb-master\utils\nms_rotated>

**Comment by hukaixuan19970627** [comment]
1. 按照install.md检查torch cuda版本是否相互匹配
2. windows编译参考 https://github.com/hukaixuan19970627/yolov5_obb/issues/224 更改文件的编码格式
如果还报错，建议找到报错位置利用搜索引擎寻求解决办法。
早日换linux早日轻松

**Comment by huangqi111** [comment]
你问题解决了么，我也遇到你这个问题

**Comment by huangqi111** [comment]
你的问题解决了么
