### ISSUE TITLE
训练结束后的val_pred显示问题以及detect的输出问题

### ISSUE THREAD

**Issue by MonaZJU** [hukaixuan19970627/yolov5_obb#281]
作者你好，我这几天刚跑通这块代码，遇到一些问题希望得到解答
1.训练结束后，在runs/train文件夹里输出的val_pred没有结果 但用detect跑同样的图片能输出结果 请问是什么原因？

2.还有一个问题是：我按照getstart.md里的image demo跑了一遍，输出的图像框都是正常的矩形。 用自己的一个倾斜车牌训练集训练出的模型来跑detect，调试发现角度的输出值也都是0，是哪里出了问题么?

**Comment by MonaZJU** [comment]
![train_batch0](https://user-images.githubusercontent.com/74694379/163132246-beeadf92-eede-4f87-9a8c-ee656df99c88.jpg)
![val_batch0_labels](https://user-images.githubusercontent.com/74694379/163132286-3101d49b-e7c0-4738-a15f-a84f98c832b7.jpg)
![val_batch0_pred](https://user-images.githubusercontent.com/74694379/163132300-a1273279-ec0c-4369-958a-577df1ca2a60.jpg)
![000002](https://user-images.githubusercontent.com/74694379/163132417-b3cd2685-72e9-42d0-affd-8a4206792297.jpg)

测试中打印发现倾斜角度都是0
类似下面这样
obboxes: tensor([[131.59673, 132.08067, 247.99940, 180.00000,   0.00000]]
obboxes: tensor([[133.32658, 103.00681, 247.73935, 180.00000,   0.00000]]

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/163135391-4e63f7b2-3ebf-4003-ac2b-76e93b4b9567.png)
将上述选定的文件内容截图发一下，我看看训练情况

**Comment by MonaZJU** [comment]
![111](https://user-images.githubusercontent.com/74694379/163142368-d2ebb2c0-5b1f-4233-9c1f-d77a8b869dba.jpg)
![222](https://user-images.githubusercontent.com/74694379/163142391-1d7809a0-0832-4d23-8fe6-ddf92554a554.jpg)

train和val的截图已经发了，其中没有任何结果的是val_pred，最后一个单张有结果的是运行detect出来的结果

**Comment by MonaZJU** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/163135391-4e63f7b2-3ebf-4003-ac2b-76e93b4b9567.png) 将上述选定的文件内容截图发一下，我看看训练情况

已发

**Comment by hukaixuan19970627** [comment]
训练曲线表明模型的预测效果越来越差，猜测可能是目标区域在图像中的内容占比太大，使用scale>1的数据增强策略很容易让目标边框被截断或者超出图像显示范围。
建议设置mosaic=0.0，然后如下图所示更改代码
![image](https://user-images.githubusercontent.com/72599120/163147670-9b4aa219-9e86-4d5c-8715-7ac8694c41aa.png)

**Comment by MonaZJU** [comment]
> 训练曲线表明模型的预测效果越来越差，猜测可能是目标区域在图像中的内容占比太大，使用scale>1的数据增强策略很容易让目标边框被截断或者超出图像显示范围。 建议设置mosaic=0.0，然后如下图所示更改代码（yolov5_obb/utils/augmentations.py） ![image](https://user-images.githubusercontent.com/72599120/163147670-9b4aa219-9e86-4d5c-8715-7ac8694c41aa.png)

好的我改了再试试  如果还有问题再reopen吧
