### ISSUE TITLE
可以跑通demo，但是把dota数据放进去就不行

### ISSUE THREAD

**Issue by cyp-happy** [hukaixuan19970627/yolov5_obb#283]
![616acce9b9bc744f2c25946ed20c23d](https://user-images.githubusercontent.com/52364854/163432960-f37e7285-8275-4073-87a5-dafbaa70cd61.jpg)

**Comment by cyp-happy** [comment]
我看了，最新的版本代码是不用转yolo格式的，之前大佬也回答了别人，说是数据集的文件格式不对，但是不是只要在data/yolov5obb_demo.yaml中修改数据集地址就行吗

**Comment by cyp-happy** [comment]
我可以训练一张图，但是不能训练1000张图
这是我的文件路径
yolov5
----dataset
-------train
------------images
------------labelTxt
------------imgnamefile.txt

**Comment by cyp-happy** [comment]
请问文件路径会对代码训练有什么影响

**Comment by hukaixuan19970627** [comment]
建议检查下labels格式

**Comment by cyp-happy** [comment]
![image](https://user-images.githubusercontent.com/52364854/163741594-d4791d51-cca4-4897-8369-65947c3fcb4e.png)
这是我的label,是不是要把前两行删掉

**Comment by hukaixuan19970627** [comment]
> ![image](https://user-images.githubusercontent.com/52364854/163741594-d4791d51-cca4-4897-8369-65947c3fcb4e.png) 这是我的label,是不是要把前两行删掉

嗯
