### ISSUE TITLE
ImportError: cannot import name 'nms_rotated_ext' from 'utils.nms_rotated'

### ISSUE THREAD

**Issue by wangyansenhub** [hukaixuan19970627/yolov5_obb#284]
train.py error:
ImportError: cannot import name 'nms_rotated_ext' from 'utils.nms_rotated'

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues?q=cannot+import+name+%27nms_rotated_ext%27+from+%27utils.nms_rotated%27
