### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by huang-boom** [hukaixuan19970627/yolov5_obb#285]
![error](https://user-images.githubusercontent.com/81954521/163583990-127a40f8-a039-4e53-a300-b89ff378e8f7.png)
Ubuntu1804子系统，配置好了环境，但是运行train.py报错

**Comment by huang-boom** [comment]
问题解决了，忘了填cfg文件

**Comment by huang-boom** [comment]
![微信截图_20220416112639](https://user-images.githubusercontent.com/81954521/163659750-4a4c6c1f-10bf-4e64-927f-3738c622fc6b.png)
ValueError: not enough values to unpack (expected 3, got 0)
这是数据集的问题吗？

**Comment by hukaixuan19970627** [comment]
建议先把getstart.md全部运行一遍

**Comment by wangjiawen-123** [comment]
请问楼主解决了嘛，我也是这个问题，我用自己写的split不会报错并且train的效果还不错，就是val时会过拟合，后来我换成长边法裁剪（这位大佬的DOTA_YOLO版本），然后就报错了，用单张图片做demo发现也没什么问题，但是整体裁剪就会报错，我实在不知道是什么原因

**Comment by huang-boom** [comment]
> 请问楼主解决了嘛，我也是这个问题，我用自己写的split不会报错并且train的效果还不错，就是val时会过拟合，后来我换成长边法裁剪（这位大佬的DOTA_YOLO版本），然后就报错了，用单张图片做demo发现也没什么问题，但是整体裁剪就会报错，我实在不知道是什么原因

解决了，ValueError: not enough values to unpack (expected 3, got 0)这个报错是数据集标签的问题

**Comment by wangjiawen-123** [comment]
> 

可以问下具体是怎么改的吗，是用原版的DOTA_devkit裁剪嘛还是怎么办，谢谢！！

**Comment by huang-boom** [comment]
> > 
> 
> 可以问下具体是怎么改的吗，是用原版的DOTA_devkit裁剪嘛还是怎么办，谢谢！！

![image](https://user-images.githubusercontent.com/81954521/164885221-b13c3ea8-09dd-487b-8577-3eec7e4c592f.png)
我是把所有的标签文件里面的前两行删除了就解决了问题

**Comment by wangjiawen-123** [comment]
我用YOLO_Transform.py那个文件把dota格式转成了yolo格式，可视化也ok，但就是train还是会报错，去掉前两行也还是这个错，用dota格式送入训练不会报错但是PR都为0，转为yolo格式就一直这个错，请问您知道我哪里错了吗
这是转为yolo格式和可视化的结果：
![error-1](https://user-images.githubusercontent.com/73467053/164909572-0068e0d0-2643-40b0-9100-7a2df4ad0ae0.png)

**Comment by huang-boom** [comment]
> 我用YOLO_Transform.py那个文件把dota格式转成了yolo格式，可视化也ok，但就是train还是会报错，去掉前两行也还是这个错，用dota格式送入训练不会报错但是PR都为0，转为yolo格式就一直这个错，请问您知道我哪里错了吗 这是转为yolo格式和可视化的结果： ![error-1](https://user-images.githubusercontent.com/73467053/164909572-0068e0d0-2643-40b0-9100-7a2df4ad0ae0.png)

![image](https://user-images.githubusercontent.com/81954521/164910297-a0d8206f-c383-426d-8022-e9eb8fafedab.png)
![image](https://user-images.githubusercontent.com/81954521/164910071-e6319168-bcc5-4234-8195-eb3ff92ae162.png)
作者大佬的知乎文章最后说项目大改了，使用教程应该参考getstart.md，所以我觉得现在应该是只能用DOTA格式的数据集标签进行训练了吧，你这个应该是数据集没有按照作者的格式来才会训练异常，或者你这个可能是单目标检测（nc=1）

**Comment by hukaixuan19970627** [comment]
@wangjiawen-123 项目大更新过，建议当成全新项目重新学习如何使用，先按照install.md重新安装环境，再根据getstart.md运行一遍demo就可以熟悉yolov5_obb的基本使用。

**Comment by wangjiawen-123** [comment]
> > 我用YOLO_Transform.py那个文件把dota格式转成了yolo格式，可视化也ok，但就是train还是会报错，去掉前两行也还是这个错，用dota格式送入训练不会报错但是PR都为0，转为yolo格式就一直这个错，请问您知道我哪里错了吗 这是转为yolo格式和可视化的结果：![error-1](https://user-images.githubusercontent.com/73467053/164909572-0068e0d0-2643-40b0-9100-7a2df4ad0ae0.png)
> 
> ![image](https://user-images.githubusercontent.com/81954521/164910297-a0d8206f-c383-426d-8022-e9eb8fafedab.png) ![image](https://user-images.githubusercontent.com/81954521/164910071-e6319168-bcc5-4234-8195-eb3ff92ae162.png)作者大佬的知乎文章最后说项目大改了，使用教程应该参考 getstart.md，所以我觉得现在应该是只能用DOTA格式的数据集标签进行训练了吧，你这个应该是数据集没有按照作者的格式来才会训练异常，或者你这个可能是单目标检测（nc=1） 格式按这个来，要有个imgnamefile.txt文件 https://github.com/hukaixuan19970627/yolov5_obb/tree/master/dataset/dataset_demo
好哒！！！谢谢，我没仔细看，疏忽了
