### ISSUE TITLE
关于mosaic数据增强的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/yolov5_obb#286]
请问，关于mosaic增强中的img4 为两倍的原图尺寸，也就是( 2024, 2024 )，再通过random_perspective对img4进行尺寸改变，这种操作会不会改变图像的数据特征（目标变小了），从而影响到最后的检测效果呢？
![image](https://user-images.githubusercontent.com/54108453/163748902-52f48b81-b46a-4621-a66f-121e322e5b86.png)
![image](https://user-images.githubusercontent.com/54108453/163749310-9262d1fa-13f9-4aac-825e-ee755242ab33.png)

**Comment by hukaixuan19970627** [comment]
镜像问题：多尺度训练会不会改变图像的数据特征从而影响到最后的检测效果？
你可以从这个角度来思考random_perspective
