### ISSUE TITLE
检测结果问题detect.py

### ISSUE THREAD

**Issue by Rachel1111** [hukaixuan19970627/yolov5_obb#287]
您好，我训练目标是两类，在检测的时候只能检测到其中一个类别，另一个类检测不到；然后检测不到这个类在可视化里我看它的precision是1，是不是不对？

**Comment by hukaixuan19970627** [comment]
没看明白，能否将你遇到的问题用可视化的方式进行说明？

**Comment by Rachel1111** [comment]
![confusion_matrix](https://user-images.githubusercontent.com/44667124/163764552-77c03011-d3df-4a77-af42-c5f406f1a0f2.png)
![val_batch1_labels](https://user-images.githubusercontent.com/44667124/163764593-91c96d4b-9a01-4f1a-bed4-f8b6577ee825.jpg)
您好，这个是我训练完后出来的结果，我看它是能够把fangge和shizhi这两类检测出来的，但我用detect.py检测时就只能检测到fungge这一类；zhishi这一类就没检测到

**Comment by Rachel1111** [comment]
然后shizhi的几个数据指标是不是不对

**Comment by hukaixuan19970627** [comment]
> ![confusion_matrix](https://user-images.githubusercontent.com/44667124/163764552-77c03011-d3df-4a77-af42-c5f406f1a0f2.png) ![val_batch1_labels](https://user-images.githubusercontent.com/44667124/163764593-91c96d4b-9a01-4f1a-bed4-f8b6577ee825.jpg) 您好，这个是我训练完后出来的结果，我看它是能够把fangge和shizhi这两类检测出来的，但我用detect.py检测时就只能检测到fungge这一类；zhishi这一类就没检测到

建议仔细看一下生成图像的名称，别把预测图和labels图搞混了

**Comment by Rachel1111** [comment]
> > ![confusion_matrix](https://user-images.githubusercontent.com/44667124/163764552-77c03011-d3df-4a77-af42-c5f406f1a0f2.png) ![val_batch1_labels](https://user-images.githubusercontent.com/44667124/163764593-91c96d4b-9a01-4f1a-bed4-f8b6577ee825.jpg) 您好，这个是我训练完后出来的结果，我看它是能够把fangge和shizhi这两类检测出来的，但我用detect.py检测时就只能检测到fungge这一类；zhishi这一类就没检测到
> 
> 建议仔细看一下生成图像的名称，别把预测图和labels图搞混了

奥我看到了，我把这两个搞混了，谢谢呀
