### ISSUE TITLE
utils/nms_rotated下setup出问题

### ISSUE THREAD

**Issue by yuxin7** [hukaixuan19970627/yolov5_obb#288]
cuda 11.3
torch 1.10
gcc版本：4.8.5

错误：
gcc: error: unrecognized command line option '-std=c++14'
error: command  '/usr/bin/gcc'  failed with exit code 1

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/280#issuecomment-1098764425
