### ISSUE TITLE
question about the dataset

### ISSUE THREAD

**Issue by lesterlee89** [hukaixuan19970627/yolov5_obb#291]
dear author
1.if i use the yolov5_obb to detect the **none top view image**, just like Look at a car from a pedestrian perspective. does it has a good result. i want to detect the angle of the rede line.
![232](https://user-images.githubusercontent.com/51075754/164136189-4c5e4587-ab57-4d68-b735-0e4cb8e6c43e.png)

**Comment by hukaixuan19970627** [comment]
I don't know, I haven't done any experiments in pedestrian-perspective-image dataset.
