### ISSUE TITLE
label标注相关问题

### ISSUE THREAD

**Issue by auspicious-youth** [hukaixuan19970627/yolov5_obb#292]
有没有专门适配x1      y1       x2        y2       x3       y3       x4       y4       classname的标注工具？
目前我使用的是wkentaro/labelme，两个问题：
1、每个json文件里面会再次存储一次imageData信息，占用空间比较大，
2、没办法直接利用detect的标签结果，直接使用txt标签在此基础上修改调整再次加入训练（类似yolov5的save-label可以直接再次拿来用labelImg查看编辑，然后直接加入数据集）

**Comment by hukaixuan19970627** [comment]
目前没有尽善尽美的标注工具，都得自己写一些脚本来辅助完成标注工作。
1. github搜索rotate label关键词就有很多旋转框的标注工具，看你喜欢用哪个。[roLabelImg](https://github.com/cgvict/roLabelImg)出来的是xml文件，应该符合你的需求。
2. 写一个txt转xml的脚本，或者修改roLabelImg相关代码使其处理的文件是txt，再配合detect.py进行使用，这样就能实现你说的多次查看编辑功能

**Comment by ryouchinsa** [comment]
[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel, you can draw oriented bounding boxes and export to the DOTA OBB format.
```
x1 y1 x2 y2 x3 y3 x4 y4 category difficult
1300.536987 1413.503784 1192.848755 1535.568848 530.876038 951.562073 638.564270 829.497009 truck 0
```

![draw_obb_polygon](https://user-images.githubusercontent.com/1954306/209951610-a343bd8c-7d49-4382-a4dd-bd9cf92bd318.jpg)
