### ISSUE TITLE
在安装nms_rotated时报错 FAILED: D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/build/temp.win-amd64-cpython-38/Release/src/poly_nms_cuda.obj

### ISSUE THREAD

**Issue by a1802lzw** [hukaixuan19970627/yolov5_obb#293]
报错信息太多，没有放全
截取报错主体如下

FAILED: D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/build/temp.win-amd64-cpython-38/Release/src/poly_nms_cuda.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc --generate-dependencies-with-compile --dependency-output D:\lzw_workspace\model\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-38\Release\src/poly_nms_cuda.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -ID:\Programs\miniconda3\envs\38cu11\lib\site-packages\torch\include -ID:\Programs\miniconda3\envs\38cu11\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Programs\miniconda3\envs\38cu11\lib\site-packages\torch\include\TH -ID:\Programs\miniconda3\envs\38cu11\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -ID:\Programs\miniconda3\envs\38cu11\include -ID:\Programs\miniconda3\envs\38cu11\Include -ID:\Programs\vs2019\VC\Tools\MSVC\14.29.30133\ATLMFC\include -ID:\Programs\vs2019\VC\Tools\MSVC\14.29.30133\include "-ID:\Windows Kits\10\include\10.0.19041.0\ucrt" "-ID:\Windows Kits\10\include\10.0.19041.0\shared" "-ID:\Windows Kits\10\include\10.0.19041.0\um" "-ID:\Windows Kits\10\include\10.0.19041.0\winrt" "-ID:\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c D:\lzw_workspace\model\yolov5_obb-master\utils\nms_rotated\src\poly_nms_cuda.cu -o D:\lzw_workspace\model\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-38\Release\src/poly_nms_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_rotated_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61
D:/Programs/miniconda3/envs/38cu11/lib/site-packages/torch/include\c10/macros/Macros.h(189): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
D:/Programs/miniconda3/envs/38cu11/lib/site-packages/torch/include\c10/macros/Macros.h(189): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(107): error: expected a declaration

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(108): error: expected a declaration

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(109): error: identifier "n1" is undefined

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(110): error: identifier "n2" is undefined

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(112): error: expected a declaration

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(117): warning: parsing restarts here after previous syntax error

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(118): error: expected a declaration

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(166): warning: parsing restarts here after previous syntax error

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(167): error: expression must have a constant value
D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(167): note: attempt to access run-time storage

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(168): error: identifier "dev_polys" is undefined

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(168): error: identifier "col_start" is undefined

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(169): error: expression must have a constant value
D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(169): note: attempt to access run-time storage

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(169): error: variable "block_polys" has already been defined

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(171): error: expression must have a constant value
D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(171): note: attempt to access run-time storage

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(171): error: variable "block_polys" has already been defined

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(173): error: expected a declaration

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(176): error: expected a declaration

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(219): warning: parsing restarts here after previous syntax error

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(221): error: this declaration has no storage class or type specifier

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(221): error: expected a ";"

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(224): warning: parsing restarts here after previous syntax error

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(226): error: identifier "boxes_num" is undefined

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(226): error: identifier "col_blocks" is undefined

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(227): error: this declaration has no storage class or type specifier

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(227): error: declaration is incompatible with "void __THCudaCheck(cudaError_t, const char *, int)"
D:/Programs/miniconda3/envs/38cu11/lib/site-packages/torch/include\THC/THCGeneral.h(61): here

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(227): error: identifier "mask_dev" is undefined

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(227): error: too many initializer values

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(236): error: this declaration has no storage class or type specifier

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(236): error: declaration is incompatible with "void *memset(void *, int, size_t)"
D:/Programs/vs2019/VC/Tools/MSVC/14.29.30133/include\vcruntime_string.h(63): here

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(236): error: too many initializer values

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(236): error: a value of type "size_t *" cannot be used to initialize an entity of type "int"

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(238): error: identifier "boxes" is undefined

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(242): error: expected a declaration

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(255): warning: parsing restarts here after previous syntax error

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(257): error: expected a declaration

D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu(260): error: expected a declaration

D:/Programs/vs2019/VC/Tools/MSVC/14.29.30133/include\xstring(446): error: expression preceding parentheses of apparent call must have (pointer-to-) function type
          detected during:
            instantiation of "_Elem *std::_Narrow_char_traits<_Elem, _Int_type>::assign(_Elem *, size_t, _Elem) [with _Elem=char, _Int_type=int]"
(3272): here
            instantiation of "std::basic_string<_Elem, _Traits, _Alloc> &std::basic_string<_Elem, _Traits, _Alloc>::assign(std::basic_string<_Elem, _Traits, _Alloc>::size_type, _Elem) [with _Elem=char, _Traits=std::char_traits<char>, _Alloc=std::allocator<char>]"
(2543): here
            instantiation of "std::basic_string<_Elem, _Traits, _Alloc>::basic_string(std::basic_string<_Elem, _Traits, _Alloc>::size_type, _Elem) [with _Elem=char, _Traits=std::char_traits<char>, _Alloc=std::allocator<char>]"
D:/Programs/vs2019/VC/Tools/MSVC/14.29.30133/include\string(539): here

D:/Programs/vs2019/VC/Tools/MSVC/14.29.30133/include\xmemory(1809): error: expression preceding parentheses of apparent call must have (pointer-to-) function type
          detected during:
            instantiation of "_Ptr std::_Zero_range(_Ptr, _Ptr) [with _Ptr=int64_t *]"
(1824): here
            instantiation of "std::_Alloc_ptr_t<_Alloc> std::_Uninitialized_value_construct_n(std::_Alloc_ptr_t<_Alloc>, std::_Alloc_size_t<_Alloc>, _Alloc &) [with _Alloc=std::_Rebind_alloc_t<std::allocator<int64_t>, int64_t>]"
D:/Programs/vs2019/VC/Tools/MSVC/14.29.30133/include\vector(1648): here
            instantiation of "std::vector<_Ty, _Alloc>::pointer std::vector<_Ty, _Alloc>::_Ufill(std::vector<_Ty, _Alloc>::pointer, std::vector<_Ty, _Alloc>::size_type, std::_Value_init_tag) [with _Ty=int64_t, _Alloc=std::allocator<int64_t>]"
D:/Programs/vs2019/VC/Tools/MSVC/14.29.30133/include\vector(493): here
            instantiation of "void std::vector<_Ty, _Alloc>::_Construct_n_copies_of_ty(std::vector<_Ty, _Alloc>::size_type, const _Ty2 &) [with _Ty=int64_t, _Alloc=std::allocator<int64_t>, _Ty2=std::_Value_init_tag]"
D:/Programs/vs2019/VC/Tools/MSVC/14.29.30133/include\vector(503): here
            instantiation of "std::vector<_Ty, _Alloc>::vector(std::vector<_Ty, _Alloc>::size_type, const _Alloc &) [with _Ty=int64_t, _Alloc=std::allocator<int64_t>]"
D:/Programs/miniconda3/envs/38cu11/lib/site-packages/torch/include\c10/core/MemoryFormat.h(57): here

D:/Programs/vs2019/VC/Tools/MSVC/14.29.30133/include\xutility(4554): error: expression preceding parentheses of apparent call must have (pointer-to-) function type
          detected during:
            instantiation of "void std::_Fill_memset(_CtgIt, _Ty, size_t) [with _CtgIt=__nv_bool *, _Ty=__nv_bool]"
(4627): here
            instantiation of "_OutIt std::fill_n(_OutIt, _Diff, const _Ty &) [with _OutIt=__nv_bool *, _Diff=size_t, _Ty=__nv_bool]"
D:/Programs/vs2019/VC/Tools/MSVC/14.29.30133/include\array(453): here
            instantiation of "void std::array<_Ty, _Size>::fill(const _Ty &) [with _Ty=__nv_bool, _Size=5ULL]"
D:/Programs/miniconda3/envs/38cu11/lib/site-packages/torch/include\ATen/record_function.h(318): here

34 errors detected in the compilation of "D:/lzw_workspace/model/yolov5_obb-master/utils/nms_rotated/src/poly_nms_cuda.cu".

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/280#issuecomment-1098764425

**Comment by a1802lzw** [comment]
> #280 (comment)

非常感谢，完美解决

**Comment by huangqi111** [comment]
Can you share your own nms_rotated_ext.cp3x-win_amd64.pyd file?
