### ISSUE TITLE
预测全为background，是不是nc和names需要改？

### ISSUE THREAD

**Issue by a1802lzw** [hukaixuan19970627/yolov5_obb#294]
![confusion_matrix](https://user-images.githubusercontent.com/58769778/164588700-8b5a2e1c-050b-4990-a8c7-0bab987b61da.png)

这是目前的nc和names
![1650597102(1)](https://user-images.githubusercontent.com/58769778/164588969-e4cf8f64-b5fd-4fb1-8aed-e77511b0851e.png)

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/164614235-db44ead6-c825-4c94-a38c-7cbc5b64b60b.png)
复现DOTAv1.5的精度可以直接下载训练文件压缩包，里面包含了所有的训练参数和超参配置

**Comment by a1802lzw** [comment]
> 复现DOTAv1.5的精度可以直接下载训练文件压缩包，里面包含了所有的训练参数和超参配置
下错权重了，下了coco的yolo权重，但是居然训练成功了，难怪全部预测成background，val完全错了
