### ISSUE TITLE
demo在执行val时报错

### ISSUE THREAD

**Issue by zy1017zy** [hukaixuan19970627/yolov5_obb#295]
Evaluating pycocotools mAP... saving runs/val/obb_demo_split/best_obb_predictions.json...
---------------------The hbb and obb results has been saved in json file-----------------------
loading annotations into memory...
pycocotools unable to run: [Errno 2] No such file or directory: 'dataset/annotations/instances_val2017.json'
Results saved to runs/val/obb_demo_split

**Comment by zy1017zy** [comment]
想请问一下，这个报错对后面有影响嘛？去看了路径里面，pr曲线等文件已经有了

**Comment by zy1017zy** [comment]
您好，还有个问题，demo里面有个imgnamefile。这个txt文件是需要我自己在运行之前把所有的图片名称写进去嘛，还是在运行程序的过程中就可以自动生成呢？我试了一下，不会自己生成啊……是不是我中间哪步漏掉了呢？谢谢！

**Comment by shenhaibb** [comment]
> 想请问一下，这个报错对后面有影响嘛？去看了路径里面，pr曲线等文件已经有了

没有影响 只是不能生成coco评估指标的结果

**Comment by shenhaibb** [comment]
> 您好，还有个问题，demo里面有个imgnamefile。这个txt文件是需要我自己在运行之前把所有的图片名称写进去嘛，还是在运行程序的过程中就可以自动生成呢？我试了一下，不会自己生成啊……是不是我中间哪步漏掉了呢？谢谢！

我是手动输入的
`classes = ['plane', 'baseball-diamond', 'bridge', 'ground-track-field', 'small-vehicle',
               'large-vehicle', 'ship', 'tennis-court', 'basketball-court', 'storage-tank',
               'soccer-ball-field', 'roundabout', 'harbor', 'swimming-pool', 'helicopter']`

`with open(os.path.join(root_dir, 'classes.txt'), 'w') as f:`
     `for cls in classes:`
          `f.write(cls + '\n')`

**Comment by zy1017zy** [comment]
> > 您好，还有个问题，demo里面有个imgnamefile。这个txt文件是需要我自己在运行之前把所有的图片名称写进去嘛，还是在运行程序的过程中就可以自动生成呢？我试了一下，不会自己生成啊……是不是我中间哪步漏掉了呢？谢谢！
> 
> 我是手动输入的 `classes = ['plane', 'baseball-diamond', 'bridge', 'ground-track-field', 'small-vehicle', 'large-vehicle', 'ship', 'tennis-court', 'basketball-court', 'storage-tank', 'soccer-ball-field', 'roundabout', 'harbor', 'swimming-pool', 'helicopter']`
> 
> `with open(os.path.join(root_dir, 'classes.txt'), 'w') as f:` `for cls in classes:` `f.write(cls + '\n')`

您好，可以告诉我加到哪儿吗？新手小白不太懂诶…麻烦您啦！

**Comment by shenhaibb** [comment]
> 
你直接 运行`for cls in classes: f.write(cls + '\n')`，输出的结果粘贴到imgnamefile里

**Comment by shenhaibb** [comment]
> imgnamefile

不好意思是我看错了问题了
imgnamefile.txt里的图片名称 你可以自己手动写一个读取文件夹里的图片名称的方法

**Comment by hukaixuan19970627** [comment]
DOTA_devkit/dota_evaluation_task1.py中的def image2txt()可以实现imgnamefile.txt的自动生成

**Comment by zy1017zy** [comment]
> > imgnamefile
> 
> 不好意思是我看错了问题了 imgnamefile.txt里的图片名称 你可以自己手动写一个读取文件夹里的图片名称的方法

没事儿 谢谢您啦！

**Comment by zy1017zy** [comment]
> DOTA_devkit/dota_evaluation_task1.py中的def image2txt()可以实现imgnamefile.txt的自动生成

感谢博主！找到啦！谢谢您！
