### ISSUE TITLE
导出模型时如何取消导出后处理？

### ISSUE THREAD

**Issue by a1802lzw** [hukaixuan19970627/yolov5_obb#296]
在这个模型输出中 output是展平过的还是后处理过的？
![1650869940(1)](https://user-images.githubusercontent.com/58769778/165036592-fefd9d48-e87f-44b6-8e02-a5de9a9edc7f.png)

想要导出为如下输出，因为c++部署就是以这个格式进行后处理的
![image](https://user-images.githubusercontent.com/58769778/165036889-dbb4e49c-fd4d-45e1-b9e1-a9194f5c9a51.png)

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/165233900-820f4fb2-f622-475d-9afa-930bae899fbd.png)

**Comment by a1802lzw** [comment]
> 我的改动如下，可以使用
![1650954786(1)](https://user-images.githubusercontent.com/58769778/165236522-98859eb2-4ce6-4cdf-84bc-b92ccaf93555.png)

**Comment by a1802lzw** [comment]
我的改动如下，可以做个参考

![1650954786(1)](https://user-images.githubusercontent.com/58769778/165236714-c52cb491-2b2e-48f9-905d-0dbf2632d794.png)
