### ISSUE TITLE
作者这个新版的代码中loss.py中关于使用CSL角度那里没有加入高斯的窗口函数吗？我没有在loss.py中看到

### ISSUE THREAD

**Issue by wq1108** [hukaixuan19970627/yolov5_obb#297]
作者这个新版的代码中loss.py中关于使用CSL角度那里没有加入高斯的窗口函数吗？我没有在loss.py中看到
# theta Classification by Circular Smooth Label
 t_theta = tgaussian_theta[i].type(ps.dtype) # target theta_gaussian_labels
 ltheta += self.BCEtheta(ps[:, class_index:], t_theta)

 tcls, tbox, indices, anchors, tgaussian_theta = self.build_targets(p, targets)  # targets

在build_target中如下：
gaussian_theta_labels = t[:, 7:-1]

没有看到窗口函数的使用

**Comment by hukaixuan19970627** [comment]
为了提高训练效率，yolov5_obb的CSL label处理过程在pre-process代码中实现，具体代码片段在utils/dataset.py中的 def __getitem__()。

**Comment by wq1108** [comment]
感谢大佬！在getitem中引用的poly2rbox函数中看到了
