### ISSUE TITLE
预测时的坐标转换问题

### ISSUE THREAD

**Issue by yzz-cver** [hukaixuan19970627/yolov5_obb#299]
在utils/rboxs_utils.py中，旋转框转为四点坐标，为什么是下面的转换关系？
![image](https://user-images.githubusercontent.com/53545589/165216353-7a1033a2-19cd-4985-9fce-166d50086a28.png)

**Comment by hukaixuan19970627** [comment]
....这哪有为什么啊，旋转矩形框有中心点，有旋转角度，有框的边长，求顶点坐标不就是利用各种三角关系么，把三角关系式写成代码就ok

**Comment by yzz-cver** [comment]
顺时针旋转矩阵和逆时针旋转矩阵是不一样的，按照代码里的写的对应的是逆时针旋转矩阵，所以想问下为什么不是顺时针旋转矩阵，
![image](https://user-images.githubusercontent.com/53545589/165245156-01400069-c92d-4fbd-9e01-53aa59de7caa.png)

**Comment by hukaixuan19970627** [comment]
这个和旋转框的定义方式有关，这篇文章讲得比较清楚，你可以参考一下
https://zhuanlan.zhihu.com/p/459018810

**Comment by yzz-cver** [comment]
好的，谢谢
