### ISSUE TITLE
论文相关推荐

### ISSUE THREAD

**Issue by d5423197** [hukaixuan19970627/yolov5_obb#300]
你好作者,

感谢您的开源代码. 由于是刚接触这个领域, 想请问您一下有没有相关资料, 论文能帮助理解. 阅读了您在知乎上的内容, 有部分内容似乎与升级后的版本有些出入 (例如对角度的处理). 

感谢,

ZD

**Comment by hukaixuan19970627** [comment]
旋转检测入门的话默认你已经具备水平框目标检测基础，可以跟进这个repo按照**发布时间顺序**进行论文阅读：
https://github.com/SJTU-Thinklab-Det/DOTA-DOAI
节省时间的话个人建议阅读顺序为R2CNN -> RRPN -> RoI Transformer -> Oriented R-CNN，之后可以根据兴趣自行扩展阅读相关论文。

**Comment by hukaixuan19970627** [comment]
快速理解旋转框定义方式可以参考：
https://zhuanlan.zhihu.com/p/459018810

**Comment by d5423197** [comment]
作者您好，

谢谢您的回复，先关闭这个问题了
