### ISSUE TITLE
大佬您好，好久不见有个问题请教

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/yolov5_obb#305]
我现在有这样一种需求，就是比如我打算检测一个弯曲的绳子，这个绳子在送入训练的时候因为剪切 等操作会变得不完整，我想要这个标注数据在绳子被剪切的时候也要舍弃被剪切的部分，也就是说我的这个需要训练的标注数据不想有空白的地方。
如下图所示：
原始标注数据如下：
![图片](https://user-images.githubusercontent.com/42164696/167295271-31e698f7-de53-47e8-b0f1-a26713c81bb3.png)

经过样本增强等操作后实际训练的图像如下图：
![图片](https://user-images.githubusercontent.com/42164696/167295291-d29fa1b8-03ee-453d-8ceb-d352d7a933c3.png)

而我实际想要的训练的时候的数据如下图：

![图片](https://user-images.githubusercontent.com/42164696/167295313-baa00946-3a84-4726-b5b9-89acc30d5655.png)

请问这个设置咱程序里面有吗？

**Comment by HKVINS89757** [comment]
![image](https://user-images.githubusercontent.com/42164696/167343437-a75f952a-78de-4ea2-969e-7925926b3217.png)
是不是在这个地方？

**Comment by HKVINS89757** [comment]
但是这个直接clip的逻辑好像不太适用于obb

**Comment by hukaixuan19970627** [comment]
按照你的需求应该这样改：输入为poly形式 -> 一系列的数据增强 -> clip裁剪目标 -> 生成最小外接水平矩形 
yolov5_obb的当前处理逻辑为：输入为poly形式 -> 一系列的数据增强 -> 生成最小外接水平矩形 -> 仅保留(cx, cy)在图像范围内的rboxes

**Comment by HKVINS89757** [comment]
> 按照你的需求应该这样改：输入为poly形式 -> 一系列的数据增强 -> clip裁剪目标 -> 生成最小外接水平矩形 yolov5_obb的当前处理逻辑为：输入为poly形式 -> 一系列的数据增强 -> 生成最小外接水平矩形 -> 仅保留(cx, cy)在图像范围内的rboxes

谢谢
