### ISSUE TITLE
torchaudio 

### ISSUE THREAD

**Issue by rhj0103** [hukaixuan19970627/yolov5_obb#306]
请问torchaudio这个包对训练有影响吗？因为我没有安装他，但是仍然可以运行，非常感谢～

**Comment by hukaixuan19970627** [comment]
项目所需环境清单：
https://github.com/hukaixuan19970627/yolov5_obb/blob/master/requirements.txt

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/167780626-9be6b956-623d-46c2-b2d3-d6dbf7095da6.png)
环境有问题就按照install.md重新安装一遍

**Comment by rhj0103** [comment]
可我是可以运行的，并没有报错，请问也需要重新装环境嘛？

**Comment by hukaixuan19970627** [comment]
那随你便了，安装环境就是为了项目能正常运行。环境清单之外的库无所谓的

**Comment by rhj0103** [comment]
重新安装后，在最后一步出现以下问题：
x-special/nautilus-clipboard
copy
file:///home/ysx/%E6%A1%8C%E9%9D%A2/2022-05-11%2021-01-18%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png

**Comment by rhj0103** [comment]
`(yolo5) ysx@ysx-virtual-machine:~/Yolov5-Project/yolov5+yolof+crossformer/yolov5_obb-master/utils/nms_rotated$ python setup.py develop
running develop
running egg_info
writing nms_rotated_ext.egg-info/PKG-INFO
writing dependency_links to nms_rotated_ext.egg-info/dependency_links.txt
writing top-level names to nms_rotated_ext.egg-info/top_level.txt
reading manifest file 'nms_rotated_ext.egg-info/SOURCES.txt'
writing manifest file 'nms_rotated_ext.egg-info/SOURCES.txt'
running build_ext
error: [Errno 2] No such file or directory: '/home/ysx/anaconda3/envs/yolo5/bin/nvcc': '/home/ysx/anaconda3/envs/yolo5/bin/nvcc'
`

**Comment by rhj0103** [comment]
`(yolo5) ysx@ysx-virtual-machine:~/Yolov5-Project/yolov5+yolof+crossformer/yolov5_obb-master/utils/nms_rotated$ python setup.py develop

running develop

running egg_info

writing nms_rotated_ext.egg-info/PKG-INFO

writing dependency_links to nms_rotated_ext.egg-info/dependency_links.txt

writing top-level names to nms_rotated_ext.egg-info/top_level.txt

reading manifest file 'nms_rotated_ext.egg-info/SOURCES.txt'

writing manifest file 'nms_rotated_ext.egg-info/SOURCES.txt'

running build_ext

error: [Errno 2] No such file or directory: '/home/ysx/anaconda3/envs/yolo5/bin/nvcc': '/home/ysx/anaconda3/envs/yolo5/bin/nvcc'
`

**Comment by hukaixuan19970627** [comment]
。。。。我的建议是把虚拟环境删了，按照install.md再安装一遍，最省事儿

**Comment by rhj0103** [comment]
好的，非常感谢您的建议！
