### ISSUE TITLE
不能为RTX 3060使用CUDA !

### ISSUE THREAD

**Issue by Avant-Gardiste** [hukaixuan19970627/yolov5_obb#307]
有谁尝试过用RTX3060训练模型，因为我不能用它来训练，也不能用它来推理。有谁有办法吗 ？
Thank you in advance !

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/167560778-18493b00-e93d-43aa-98f3-e612fa784c93.png)
如果还有问题那就详细描述一下你遇到的错误，最好详细到别人可以复现这个错误

**Comment by Avant-Gardiste** [comment]
好的！谢谢。谢谢你，我将重新尝试这个 !

**Comment by hukaixuan19970627** [comment]
没明白你的意思，你指的是RTX 3060无法运行这个项目而其它系列的显卡却可以正常运行吗

**Comment by Wangfeng2394** [comment]
我也遇到过这个问题 ，已经解决了 ，好像是cuda版本的问题。你可以自己找下原因 ，作者也没有你的显卡 没法回答的
