### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by Aming1998** [hukaixuan19970627/yolov5_obb#308]
Traceback (most recent call last):
  File "train.py", line 633, in <module>
    main(opt)
  File "train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 373, in train
    compute_loss=compute_loss)
  File "/home/jd/anaconda3/envs/python3.6_torch1.3/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/jd/projects/yolov5_obb-master/val.py", line 206, in run
    out = non_max_suppression_obb(out, conf_thres, iou_thres, labels=lb, multi_label=True, agnostic=single_cls) # list*(n, [cxcylsθ, conf, cls]) θ ∈ [-pi/2, pi/2)
  File "/home/jd/projects/yolov5_obb-master/utils/general.py", line 853, in non_max_suppression_obb
    _, i = obb_nms(rboxes, scores, iou_thres)
  File "/home/jd/projects/yolov5_obb-master/utils/nms_rotated/nms_rotated_wrapper.py", line 41, in obb_nms
    inds = nms_rotated_ext.nms_rotated(dets_th, scores, iou_thr)
RuntimeError: CUDA error: invalid device function
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          
Segmentation fault (core dumped)

您好 我想请问 我在按照get_started指示下对nms函数等均编译成功的情况下 在跑第一个epoch时 进行nms操作时出现这种报错 不知道如何解决

**Comment by Avant-Gardiste** [comment]
I think you should add a parser argument called --device (0,1,2,3 if you are using gpu or cpu instead) when you want to launch training, for example "python train.py --weights yolov5s.pt --epochs 10 --device cpu (if you are using cpu for sure otherwise 0,1,2 or 3)". Hope this helps !

**Comment by hukaixuan19970627** [comment]
Delete nms_rotated_ext.cpython-??-?????-????-gnu.so and install yolov5_obb again.
![image](https://user-images.githubusercontent.com/72599120/167560547-d264cbf0-edae-4128-b0b5-fa5de34a1373.png)

**Comment by hukaixuan19970627** [comment]
再重新编译一次nms_rotated_ext

**Comment by Aming1998** [comment]
> I think you should add a parser argument called --device (0,1,2,3 if you are using gpu or cpu instead) when you want to launch training, for example "python train.py --weights yolov5s.pt --epochs 10 --device cpu (if you are using cpu for sure otherwise 0,1,2 or 3)". Hope this helps !

Thanks for your advice!

**Comment by Aming1998** [comment]
> 再重新编译一次nms_rotated_ext

谢谢大佬 我昨晚自己重新配了环境 现在已经可以跑啦！
