### ISSUE TITLE
为什么我的训练结果是这样的

### ISSUE THREAD

**Issue by cop123123** [hukaixuan19970627/yolov5_obb#310]
![abbe3207eb2dbac488a7f70e76a7239](https://user-images.githubusercontent.com/74242026/167793852-4ba22b6a-3f2d-4078-980e-5ea54c3c4cfb.png)

**Comment by cop123123** [comment]
类别数为15

**Comment by cop123123** [comment]
results.png
![image](https://user-images.githubusercontent.com/74242026/167967426-fc9a9bc6-dc8f-4a35-820a-470b9147881f.png)
train_batch0.jpg
![image](https://user-images.githubusercontent.com/74242026/167967490-12aed0d0-5bf6-4f16-aa2c-e9995aa44952.png)

**Comment by cop123123** [comment]
train_batch1.jpg
![image](https://user-images.githubusercontent.com/74242026/167968220-2720c2e1-8b41-4b34-a979-397a5340fb75.png)
train_batch2.jpg
![image](https://user-images.githubusercontent.com/74242026/167968257-dace71b5-0e49-4545-b936-a202e8181214.png)

**Comment by cop123123** [comment]
hyp.yaml
lr0: 0.001
lrf: 0.2
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.1
cls: 0.5
cls_pw: 1.0
obj: 1.0
obj_pw: 1.0
angle: 0.8
angle_pw: 1.0
iou_t: 0.2
anchor_t: 4.0
fl_gamma: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.5
fliplr: 0.5
mosaic: 1.0
mixup: 0.0

**Comment by cop123123** [comment]
labels.jpg
![image](https://user-images.githubusercontent.com/74242026/167968414-32babc36-ab26-4ed9-bd4e-7218b43fd0ad.png)

**Comment by cop123123** [comment]
opt.yaml
weights: weights/YOLOv5_DOTAv1.5_OBB.pt
cfg: ''
data: data/DOTA_ROTATED.yaml
hyp: data/hyp.scratch.yaml
epochs: 200
batch_size: 4
img_size:
- 600
- 600
rect: false
resume: false
nosave: false
notest: true
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
name: ''
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 0
total_batch_size: 4
world_size: 1
global_rank: -1

**Comment by cop123123** [comment]
另外几张图片训练结果中没有，我将验证集设置为和训练集一样，但是不知道为什么训练结果中没有验证集的损失情况。另外数据集使用的是dota数据集，类别数为15，在yaml文件中设置的nc为16

**Comment by cop123123** [comment]
数据集共250张

**Comment by hukaixuan19970627** [comment]
你这用的是去年版本的代码，建议使用最新版本的代码

**Comment by cop123123** [comment]
好的，我再试一下！

**Comment by cop123123** [comment]
有没有windows的版本呀老哥

**Comment by LUO77123** [comment]
> 有没有windows的版本呀老哥

这个Windows也适用

**Comment by cop123123** [comment]
但是在windows上总是编译失败，可以看看你的代码嘛

**Comment by cop123123** [comment]
> > 有没有windows的版本呀老哥
> 
> 这个Windows也适用

但是在windows上总是编译失败，可以看看你的代码嘛

**Comment by LUO77123** [comment]
什么代码？

**Comment by LUO77123** [comment]
nms_rotated_ext.cp39-win_amd64.pyd？

**Comment by LUO77123** [comment]
> > > 有没有windows的版本呀老哥
> > 
> > 
> > 这个Windows也适用
> 
> 但是在windows上总是编译失败，可以看看你的代码嘛

nms_rotated_ext.cp39-win_amd64.pyd？

**Comment by cop123123** [comment]
> > > > 有没有windows的版本呀老哥
> > > 
> > > 
> > > 这个Windows也适用
> > 
> > 
> > 但是在windows上总是编译失败，可以看看你的代码嘛
> 
> nms_rotated_ext.cp39-win_amd64.pyd？
是的，就是在Windows环境上进行编译会出现这个问题

ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import)

**Comment by LUO77123** [comment]
> > > > > 有没有windows的版本呀老哥
> > > > 
> > > > 
> > > > 这个Windows也适用
> > > 
> > > 
> > > 但是在windows上总是编译失败，可以看看你的代码嘛
> > 
> > 
> > nms_rotated_ext.cp39-win_amd64.pyd？
> > 是的，就是在Windows环境上进行编译会出现这个问题
> 
> ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import)

文件我可以给你，怎么出现问题我也不太清楚

**Comment by cop123123** [comment]
> > > > > > 有没有windows的版本呀老哥
> > > > > 
> > > > > 
> > > > > 这个Windows也适用
> > > > 
> > > > 
> > > > 但是在windows上总是编译失败，可以看看你的代码嘛
> > > 
> > > 
> > > nms_rotated_ext.cp39-win_amd64.pyd？
> > > 是的，就是在Windows环境上进行编译会出现这个问题
> > 
> > 
> > ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import)
> 
> 文件我可以给你，怎么出现问题我也不太清楚

好的老哥，我可以加一下你的联系方式嘛，这是我的 qq2211230441

**Comment by LUO77123** [comment]
> 2211230441

发你QQ邮箱了

**Comment by LUO77123** [comment]
> > > > > > > 有没有windows的版本呀老哥
> > > > > > 
> > > > > > 
> > > > > > 这个Windows也适用
> > > > > 
> > > > > 
> > > > > 但是在windows上总是编译失败，可以看看你的代码嘛
> > > > 
> > > > 
> > > > nms_rotated_ext.cp39-win_amd64.pyd？
> > > > 是的，就是在Windows环境上进行编译会出现这个问题
> > > 
> > > 
> > > ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import)
> > 
> > 
> > 文件我可以给你，怎么出现问题我也不太清楚
> 
> 好的老哥，我可以加一下你的联系方式嘛，这是我的 qq2211230441

发你QQ邮箱了

**Comment by cop123123** [comment]
> 

收到了！感谢！我去试一下~

**Comment by cop123123** [comment]
> > > > > > > > 有没有windows的版本呀老哥
> > > > > > > 
> > > > > > > 
> > > > > > > 这个Windows也适用
> > > > > > 
> > > > > > 
> > > > > > 但是在windows上总是编译失败，可以看看你的代码嘛
> > > > > 
> > > > > 
> > > > > nms_rotated_ext.cp39-win_amd64.pyd？
> > > > > 是的，就是在Windows环境上进行编译会出现这个问题
> > > > 
> > > > 
> > > > ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import)
> > > 
> > > 
> > > 文件我可以给你，怎么出现问题我也不太清楚
> > 
> > 
> > 好的老哥，我可以加一下你的联系方式嘛，这是我的 qq2211230441
> 
> 发你QQ邮箱了

我收到了~超级感谢！我去试试

**Comment by cop123123** [comment]
> > > > > > > > 有没有windows的版本呀老哥
> > > > > > > 
> > > > > > > 
> > > > > > > 这个Windows也适用
> > > > > > 
> > > > > > 
> > > > > > 但是在windows上总是编译失败，可以看看你的代码嘛
> > > > > 
> > > > > 
> > > > > nms_rotated_ext.cp39-win_amd64.pyd？
> > > > > 是的，就是在Windows环境上进行编译会出现这个问题
> > > > 
> > > > 
> > > > ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import)
> > > 
> > > 
> > > 文件我可以给你，怎么出现问题我也不太清楚
> > 
> > 
> > 好的老哥，我可以加一下你的联系方式嘛，这是我的 qq2211230441
> 
> 发你QQ邮箱了

可以请教一下你，就是你在下载完这个项目之后是如何在Windows上复现的嘛，需要什么步骤嘛

**Comment by LUO77123** [comment]
按着作者的readme，但是我用完整data数据集
训练一半后面就全是nan，不知道是不是用了adamw优化器原因

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月13日(周五) 下午2:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 为什么我的训练结果是这样的 (Issue #310)




         
有没有windows的版本呀老哥
  
这个Windows也适用
  
但是在windows上总是编译失败，可以看看你的代码嘛
  
nms_rotated_ext.cp39-win_amd64.pyd？
 是的，就是在Windows环境上进行编译会出现这个问题
  
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import)
  
文件我可以给你，怎么出现问题我也不太清楚
  
好的老哥，我可以加一下你的联系方式嘛，这是我的 qq2211230441
  
发你QQ邮箱了
  
可以请教一下你，就是你在下载完这个项目之后是如何在Windows上复现的嘛，需要什么步骤嘛

**Comment by cop123123** [comment]
> 按着作者的readme，但是我用完整data数据集 训练一半后面就全是nan，不知道是不是用了adamw优化器原因
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月13日(周五) 下午2:28 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [hukaixuan19970627/yolov5_obb] 为什么我的训练结果是这样的 (Issue #310) 有没有windows的版本呀老哥 这个Windows也适用 但是在windows上总是编译失败，可以看看你的代码嘛 nms_rotated_ext.cp39-win_amd64.pyd？ 是的，就是在Windows环境上进行编译会出现这个问题 ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import) 文件我可以给你，怎么出现问题我也不太清楚 好的老哥，我可以加一下你的联系方式嘛，这是我的 qq2211230441 发你QQ邮箱了 可以请教一下你，就是你在下载完这个项目之后是如何在Windows上复现的嘛，需要什么步骤嘛 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你等我配置好环境也试试dota数据集

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/168232421-7203549c-fa00-4f9f-9bb1-3e4e5cf2e1c4.png)

**Comment by cop123123** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/168232421-7203549c-fa00-4f9f-9bb1-3e4e5cf2e1c4.png)
唉，没有ubantu环境.....人麻了

**Comment by hukaixuan19970627** [comment]
那个图片的意思是windows不推荐，环境比较容易出问题，出了问题的话点进那个issue链接找解决办法

**Comment by cop123123** [comment]
> 那个图片的意思是windows不推荐，环境比较容易出问题，出了问题的话点进那个issue链接找解决办法
好的老哥！

**Comment by cop123123** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/168232421-7203549c-fa00-4f9f-9bb1-3e4e5cf2e1c4.png)

 File "C:\Users\Administrator\Desktop\yolov5_obb1\utils\datasets.py", line 444, in __init__
    labels, shapes, self.segments = zip(*cache.values())
ValueError: not enough values to unpack (expected 3, got 0)
您好想问一下用自己的数据集进行训练，出现了这个问题

**Comment by cop123123** [comment]
> 那个图片的意思是windows不推荐，环境比较容易出问题，出了问题的话点进那个issue链接找解决办法
老哥，想问一下训练自己的数据集需要注意什么嘛

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/168737765-0bd100a4-d6f7-4120-ac7b-9a484cfebcac.png)
