### ISSUE TITLE
Having trouble understanding the code here, any help would be appreciated!

### ISSUE THREAD

**Issue by d5423197** [hukaixuan19970627/yolov5_obb#311]
https://github.com/hukaixuan19970627/yolov5_obb/blob/3f2e708640a408a275814c4e87dd034da991ec69/utils/loss.py#L245-L250

作者你好,

在看这部分源码的时候, 有些无法理解这部分.
gxy表示的是ground truth的cx, cy
不理解gxi以及接下来是在做什么, 或者有什么资料可以帮助理解这个part吗

谢谢

**Comment by hukaixuan19970627** [comment]
搜索引擎搜索一下yolov5 跨网格匹配

**Comment by d5423197** [comment]
太感谢了，自己看了好久也没摸出个门道
