### ISSUE TITLE
opencv调用onnx格式文件报错

### ISSUE THREAD

**Issue by Hone-Xu** [hukaixuan19970627/yolov5_obb#313]
想请教下，用yolo导出的onnx文件在被opencv调用时报错，这个要怎么改
![微信截图_20220512141742](https://user-images.githubusercontent.com/96858577/168004763-dc7737e0-360a-4733-906d-36705d38089c.png)
@hukaixuan19970627

**Comment by yang-gis** [comment]
> 想请教下，用yolo导出的onnx文件在被opencv调用时报错，这个要怎么改 ![微信截图_20220512141742](https://user-images.githubusercontent.com/96858577/168004763-dc7737e0-360a-4733-906d-36705d38089c.png) @hukaixuan19970627

你这个别人也没法答复你。你要做的是：（1）说明自己如何导出的onnx （2）给出onnx文件

**Comment by hukaixuan19970627** [comment]
这个我不会，反正detect onnx模型是完全没问题，个性化问题建议百度/google。
