### ISSUE TITLE
train.py运行错误

### ISSUE THREAD

**Issue by TDStudou** [hukaixuan19970627/yolov5_obb#314]
错误代码如下
train: weights=weights\yolov5m.pt, cfg=, data=data\dotav15_poly.yaml, hyp=data\hyps\obb\hyp.finetune_dota.yaml, epochs=10, batch_size=4, imgsz=512, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=0, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs\train, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: fatal: unable to access 'https://github.com/hukaixuan19970627/yolov5_obb.git/': Empty reply from server
Command 'git fetch && git config --get remote.origin.url' timed out after 5 seconds
YOLOv5  3f2e7086 torch 1.10.1+cu113 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)

hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, theta=0.5, theta_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=180.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.5, fliplr=0.5, mosaic=0.95, mixup=0.1, copy_paste=0.0, cls_theta=180, csl_radius=2.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5  runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/

WARNING: Dataset not found, nonexistent paths: ['C:\\media\\test\\DOTA\\DOTAv1.5\\val_split_1024_gap200\\images']
Traceback (most recent call last):
  File "C:\Users\TDS\yolov5_obb\train.py", line 632, in <module>
    main(opt)
  File "C:\Users\TDS\yolov5_obb\train.py", line 529, in main
    train(opt.hyp, opt, device, callbacks)
  File "C:\Users\TDS\yolov5_obb\train.py", line 102, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "C:\Users\TDS\yolov5_obb\utils\general.py", line 418, in check_dataset
    raise Exception('Dataset not found.')
Exception: Dataset not found.
麻烦请大佬指点一下

**Comment by TDStudou** [comment]
大佬我最近刚入门深度学习，拿到您的项目以后也看了readme和getstart，但是相关的疑问还是很多，目前主要疑问如下：1，DOTA数据集该存放在哪个文件夹？我将要训练的图片和label放入yolov5-obb/dataset/dadaset-demo以后运行了ImgSplit_multi_process.py，得到了分割好的图片存放在yolov5-obb/dataset/dataset_demo_rate1.0_split1024_gap200里，接下来运行train.py却出现上面的错误，之后按照'C:\media\test\DOTA\DOTAv1.5\val_split_1024_gap200\images'建立文件夹并没有作用，是windows和其他操作系统之间的差距造成的吗？我需要把数据集的train，val，test放在哪些地方呢？2，在运行val.py时会有AssertionError: 'data/yolov5obb_demo.yaml' acceptable suffix is ('.yaml', '.yml')的报错，这是什么原因呢？
希望能得到大佬的解答，万分感谢！

**Comment by TDStudou** [comment]
训练文件要放在yolov5同一级目录，第一个问题解决了。OSError: [WinError 1455] 页面文件太小，无法完成操作。这个问题参考网上修改了yolov5\utils\datasets.py里的num-works还是会出现，大佬能指点一下吗

**Comment by hukaixuan19970627** [comment]
先“运行”一遍getstart.md，里面有训练/测试/评估流程的demo，如果demo可以正常运行那说明环境没有问题。
之后要训练自定义数据集的话就按照demo文件的结构举一反三不就可以了。
