### ISSUE TITLE
 作者你好，我在你基础上修改了一版kldloss的旋转目标检测，可以给你提个pull request么

### ISSUE THREAD

**Issue by lalalagogogochong** [hukaixuan19970627/yolov5_obb#316]

**Comment by hukaixuan19970627** [comment]
如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的

**Comment by lalalagogogochong** [comment]
> 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的

通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动

**Comment by LUO77123** [comment]
> > 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的
> 
> 通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动

兄弟，你是通过YOLOX的KLD版本改过来的吗？

**Comment by QingYuan-L** [comment]
老哥，写好了吗，请问kld和csl对比有提升吗？

**Comment by LUO77123** [comment]
> > 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的
> 
> 通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动

我也修改了，还没测效果，兄弟你的效果咋样

**Comment by monument-and-sea-all-the-gift** [comment]
修改成kld的损失，obj的损失好像要重新设计，大佬们怎么搞的

**Comment by monument-and-sea-all-the-gift** [comment]
输出形状(b,3,size,size,5+class_num+180),这形状能直接应用于KLD_loss吗，180应该是类似于one_hot形式的，而KLD好像需要角度值，先argmax（）转换成角度了再搞？，而且有9个框，需要有过滤的逻辑么

**Comment by monument-and-sea-all-the-gift** [comment]
> > > 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的
> > 
> > 
> > 通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动
> 
> 我也修改了，还没测效果，兄弟你的效果咋样

我自己也改了一版，把iou_loss换成了kld，并去掉了angle_loss

**Comment by monument-and-sea-all-the-gift** [comment]
正在测试效果

**Comment by LUO77123** [comment]
> > > > 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的
> > > 
> > > 
> > > 通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动
> > 
> > 
> > 我也修改了，还没测效果，兄弟你的效果咋样
> 
> 我自己也改了一版，把iou_loss换成了kld，并去掉了angle_loss

一样的，我也是这么改的

**Comment by monument-and-sea-all-the-gift** [comment]
> > > > > 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的
> > > > 
> > > > 
> > > > 通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动
> > > 
> > > 
> > > 我也修改了，还没测效果，兄弟你的效果咋样
> > 
> > 
> > 我自己也改了一版，把iou_loss换成了kld，并去掉了angle_loss
> 
> 一样的，我也是这么改的

好像样本小了，损失降不动，训练集才400张，

**Comment by monument-and-sea-all-the-gift** [comment]
> > > > > > 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的
> > > > > 
> > > > > 
> > > > > 通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动
> > > > 
> > > > 
> > > > 我也修改了，还没测效果，兄弟你的效果咋样
> > > 
> > > 
> > > 我自己也改了一版，把iou_loss换成了kld，并去掉了angle_loss
> > 
> > 
> > 一样的，我也是这么改的
> 
> 好像样本小了，损失降不动，训练集才400张，

还有一个问题，网络输出最后一个维度为5+num_class+180，180的one_hot去回归角度和kld的角度不一样，要不要把180变成1

**Comment by LUO77123** [comment]
> > > > > > > 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的
> > > > > > 
> > > > > > 
> > > > > > 通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动
> > > > > 
> > > > > 
> > > > > 我也修改了，还没测效果，兄弟你的效果咋样
> > > > 
> > > > 
> > > > 我自己也改了一版，把iou_loss换成了kld，并去掉了angle_loss
> > > 
> > > 
> > > 一样的，我也是这么改的
> > 
> > 
> > 好像样本小了，损失降不动，训练集才400张，
> 
> 还有一个问题，网络输出最后一个维度为5+num_class+180，180的one_hot去回归角度和kld的角度不一样，要不要把180变成1

我就改成1

**Comment by monument-and-sea-all-the-gift** [comment]
> > > > > > > > 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的
> > > > > > > 
> > > > > > > 
> > > > > > > 通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动
> > > > > > 
> > > > > > 
> > > > > > 我也修改了，还没测效果，兄弟你的效果咋样
> > > > > 
> > > > > 
> > > > > 我自己也改了一版，把iou_loss换成了kld，并去掉了angle_loss
> > > > 
> > > > 
> > > > 一样的，我也是这么改的
> > > 
> > > 
> > > 好像样本小了，损失降不动，训练集才400张，
> > 
> > 
> > 还有一个问题，网络输出最后一个维度为5+num_class+180，180的one_hot去回归角度和kld的角度不一样，要不要把180变成1
> 
> 我就改成1

你拿dota训练的嘛，还是自己的数据集，自己的数据集，角度回归的准么

**Comment by monument-and-sea-all-the-gift** [comment]
> > > > > > > > > > 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我也修改了，还没测效果，兄弟你的效果咋样
> > > > > > > 
> > > > > > > 
> > > > > > > 我自己也改了一版，把iou_loss换成了kld，并去掉了angle_loss
> > > > > > 
> > > > > > 
> > > > > > 一样的，我也是这么改的
> > > > > 
> > > > > 
> > > > > 好像样本小了，损失降不动，训练集才400张，
> > > > 
> > > > 
> > > > 还有一个问题，网络输出最后一个维度为5+num_class+180，180的one_hot去回归角度和kld的角度不一样，要不要把180变成1
> > > 
> > > 
> > > 我就改成1
> > 
> > 
> > 你拿dota训练的嘛，还是自己的数据集，自己的数据集，角度回归的准么
> 
> 服务器有问题，还没有拿DATA跑

用作者的预训练权重去迁移学习其他数据集效果会好么

**Comment by LUO77123** [comment]
> > > > > > > > > > > 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我也修改了，还没测效果，兄弟你的效果咋样
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我自己也改了一版，把iou_loss换成了kld，并去掉了angle_loss
> > > > > > > 
> > > > > > > 
> > > > > > > 一样的，我也是这么改的
> > > > > > 
> > > > > > 
> > > > > > 好像样本小了，损失降不动，训练集才400张，
> > > > > 
> > > > > 
> > > > > 还有一个问题，网络输出最后一个维度为5+num_class+180，180的one_hot去回归角度和kld的角度不一样，要不要把180变成1
> > > > 
> > > > 
> > > > 我就改成1
> > > 
> > > 
> > > 你拿dota训练的嘛，还是自己的数据集，自己的数据集，角度回归的准么
> > 
> > 
> > 服务器有问题，还没有拿DATA跑
> 
> 用作者的预训练权重去迁移学习其他数据集效果会好么

自己改个backbone呗，用1K或者22K的训练权重嘛

**Comment by LUO77123** [comment]
> > > > > > > > > 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动
> > > > > > > 
> > > > > > > 
> > > > > > > 我也修改了，还没测效果，兄弟你的效果咋样
> > > > > > 
> > > > > > 
> > > > > > 我自己也改了一版，把iou_loss换成了kld，并去掉了angle_loss
> > > > > 
> > > > > 
> > > > > 一样的，我也是这么改的
> > > > 
> > > > 
> > > > 好像样本小了，损失降不动，训练集才400张，
> > > 
> > > 
> > > 还有一个问题，网络输出最后一个维度为5+num_class+180，180的one_hot去回归角度和kld的角度不一样，要不要把180变成1
> > 
> > 
> > 我就改成1
> 
> 你拿dota训练的嘛，还是自己的数据集，自己的数据集，角度回归的准么

训练12个epoch，效果很差

**Comment by LUO77123** [comment]
> > > > > > > > > 如果是提供了一个可切换KLD Loss和CSL选项的PR的话，那我肯定很乐意merge进来的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 通过配置参数切换训练方式可以么，我需要再修改一下，等修改好了，你帮忙看一下，因为目前我只是在自己的车辆数据集上跑的，没有在DOTA数据集上跑过，但是数据加载那些我都是用的你的，没有做过改动
> > > > > > > 
> > > > > > > 
> > > > > > > 我也修改了，还没测效果，兄弟你的效果咋样
> > > > > > 
> > > > > > 
> > > > > > 我自己也改了一版，把iou_loss换成了kld，并去掉了angle_loss
> > > > > 
> > > > > 
> > > > > 一样的，我也是这么改的
> > > > 
> > > > 
> > > > 好像样本小了，损失降不动，训练集才400张，
> > > 
> > > 
> > > 还有一个问题，网络输出最后一个维度为5+num_class+180，180的one_hot去回归角度和kld的角度不一样，要不要把180变成1
> > 
> > 
> > 我就改成1
> 
> 你拿dota训练的嘛，还是自己的数据集，自己的数据集，角度回归的准么

你测试没有，我测了DATA1.5也就70%左右的map0.5，不比CSL高，还低了几个点
