### ISSUE TITLE
nan in training

### ISSUE THREAD

**Issue by LUO77123** [hukaixuan19970627/yolov5_obb#319]
第一个epoch训练到中间就直接变成nan，但是还在用nan训练，不知道问题在哪里
    Epoch   gpu_mem    box     obj        cls         theta    labels       img_size 
     0/119     6.51G     0.086    0.1064   0.04166    0.1764       186      1024:  81%|████████  | 2990/3683 [1:03:00<14:31,  1.26s/it]
     0/119     6.51G     0.086    0.1064   0.04166    0.1764       186      1024:  81%|████████  | 2991/3683 [1:03:00<14:32,  1.26s/it]
     0/119     6.51G     0.086    0.1064   0.04166    0.1764        93      1024:  81%|████████  | 2991/3683 [1:03:01<14:32,  1.26s/it]
     0/119     6.51G     0.086    0.1064   0.04166    0.1764        93      1024:  81%|████████  | 2992/3683 [1:03:01<14:46,  1.28s/it]
  突然就不对了
     0/119     6.51G       nan       nan       nan       nan       220      1024:  81%|████████  | 2992/3683 [1:03:03<14:46,  1.28s/it]
     0/119     6.51G       nan       nan       nan       nan       220      1024:  81%|████████▏ | 2993/3683 [1:03:03<14:36,  1.27s/it]
     0/119     6.51G       nan       nan       nan       nan        88      1024:  81%|████████▏ | 2993/3683 [1:03:04<14:36,  1.27s/it]
     0/119     6.51G       nan       nan       nan       nan        88      1024:  81%|████████▏ | 2994/3683 [1:03:04<14:12,  1.24s/it]
不知原因喃

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/239#issuecomment-1086631327

**Comment by hukaixuan19970627** [comment]
自定义数据集？

**Comment by LUO77123** [comment]
> 自定义数据集？

就是DATA数据集，分割1024，gap=512

**Comment by LUO77123** [comment]
> 自定义数据集？

![image](https://user-images.githubusercontent.com/87272337/168237458-3937932f-1f51-4128-9b1d-1cd864088c5b.png)
![image](https://user-images.githubusercontent.com/87272337/168237483-726ca2e2-4460-477d-8f38-fabe8206afd5.png)
![image](https://user-images.githubusercontent.com/87272337/168237516-9a63bbb4-2cba-4821-9d88-a77f5b38e3eb.png)
![image](https://user-images.githubusercontent.com/87272337/168237539-e8081e54-e117-4311-b7c0-a0cb70b8f1f9.png)
![image](https://user-images.githubusercontent.com/87272337/168237551-6377d14f-737f-42ae-90d0-1d615ca981f7.png)
![image](https://user-images.githubusercontent.com/87272337/168237574-ebdd5164-4144-40bf-8175-325069b84c43.png)

**Comment by hukaixuan19970627** [comment]
你用默认的预训练模型和配置文件训练看看，先排除一下安装环境的影响

**Comment by LUO77123** [comment]
> 你用默认的预训练模型和配置文件训练看看，先排除一下安装环境的影响
好的，大佬，我又从新开了一遍，epoch设为1，目前训练一半多还是正常的，等这次错了，我就换默认的尝试一次，demo是没有任何问题，训练20轮都可以

**Comment by LUO77123** [comment]
> 你用默认的预训练模型和配置文件训练看看，先排除一下安装环境的影响

好的，大佬，这个配置训练demo几十轮都可以，现在从新训练data数据集1轮，训了一半多了，等在报错就换成默认的预训练模型和配置文件试一下，谢谢大佬

**Comment by hukaixuan19970627** [comment]
AdamW初始学习率不能设为0.01，我印象里都是设为0.001甚至更小，那个0.01是SGD的学习率参数设置，你改为SGD看看。

**Comment by LUO77123** [comment]
> AdamW初始学习率不能设为0.01，我印象里都是设为0.001甚至更小，那个0.01是SGD的学习率参数设置，你改为SGD看看。

好的，大佬，我这次跑的是Adam，就是弄错了，看了6.1的文件配置，写了应该改成0.001，大佬太厉害了

**Comment by Wangfeng2394** [comment]
学习率我都设置到0.03了，训练的效果挺好的。。。。

**Comment by LUO77123** [comment]
> 学习率我都设置到0.03了，训练的效果挺好的。。。。

SGD还是Adam,还是AdamW？

**Comment by LUO77123** [comment]
> AdamW初始学习率不能设为0.01，我印象里都是设为0.001甚至更小，那个0.01是SGD的学习率参数设置，你改为SGD看看。

这次训练了一个epoch（4卡都要2个多小时，哭了），又成功了，不知道是不是从AdamW换成Adam的缘由。看到gap=512时，cc也才57个，有点少。
                  Class           Images     Labels          P          R       mAP@.5    mAP@.5:.95
                    all               10132     227311      0.474       0.12     0.0724      0.022
               plane               10132       8973      0.308      0.644      0.466      0.163
    baseball-diamond      10132        637          1             0            0          0
              bridge               10132       1480          0           0             0          0
  ground-track-field        10132        410          0            0             0          0
       small-vehicle            10132     141679      0.216     0.0979     0.0691     0.0171
       large-vehicle            10132      14053       0.16      0.353      0.131     0.0374
                ship                 10132      38116      0.366       0.27      0.221      0.064
        tennis-court            10132       1866          1          0   0.000499   0.000117
    basketball-court         10132        432          1               0          0          0
        storage-tank           10132      10222      0.416     0.0559      0.107     0.0325
   soccer-ball-field          10132        449          0               0          0          0
          roundabout          10132        575          1              0          0          0
              harbor              10132       6382          1          0    0.00162   0.000453
       swimming-pool       10132       1663      0.127      0.504      0.161      0.037
          helicopter             10132        317          1              0          0          0
     container-crane        10132         57          0                0          0          0

**Comment by hukaixuan19970627** [comment]
> > AdamW初始学习率不能设为0.01，我印象里都是设为0.001甚至更小，那个0.01是SGD的学习率参数设置，你改为SGD看看。
> 
> 这次训练了一个epoch（4卡都要2个多小时，哭了），又成功了，不知道是不是从AdamW换成Adam的缘由。看到gap=512时，cc也才57个，有点少。 Class Images Labels P R mAP@.5 mAP@.5:.95 all 10132 227311 0.474 0.12 0.0724 0.022 plane 10132 8973 0.308 0.644 0.466 0.163 baseball-diamond 10132 637 1 0 0 0 bridge 10132 1480 0 0 0 0 ground-track-field 10132 410 0 0 0 0 small-vehicle 10132 141679 0.216 0.0979 0.0691 0.0171 large-vehicle 10132 14053 0.16 0.353 0.131 0.0374 ship 10132 38116 0.366 0.27 0.221 0.064 tennis-court 10132 1866 1 0 0.000499 0.000117 basketball-court 10132 432 1 0 0 0 storage-tank 10132 10222 0.416 0.0559 0.107 0.0325 soccer-ball-field 10132 449 0 0 0 0 roundabout 10132 575 1 0 0 0 harbor 10132 6382 1 0 0.00162 0.000453 swimming-pool 10132 1663 0.127 0.504 0.161 0.037 helicopter 10132 317 1 0 0 0 container-crane 10132 57 0 0 0 0

建议检查下训练时的gpu利用率，确保训练期间没有出现利用率为0的情况，我这边yolov5m batchsize=64 epochs=300训dotav1.5也才花不到15h，不过你这个模型的显存占用量未免太大了一点

**Comment by LUO77123** [comment]
> > > AdamW初始学习率不能设为0.01，我印象里都是设为0.001甚至更小，那个0.01是SGD的学习率参数设置，你改为SGD看看。
> > 
> > 
> > 这次训练了一个epoch（4卡都要2个多小时，哭了），又成功了，不知道是不是从AdamW换成Adam的缘由。看到gap=512时，cc也才57个，有点少。 Class Images Labels P R mAP@.5 mAP@.5:.95 all 10132 227311 0.474 0.12 0.0724 0.022 plane 10132 8973 0.308 0.644 0.466 0.163 baseball-diamond 10132 637 1 0 0 0 bridge 10132 1480 0 0 0 0 ground-track-field 10132 410 0 0 0 0 small-vehicle 10132 141679 0.216 0.0979 0.0691 0.0171 large-vehicle 10132 14053 0.16 0.353 0.131 0.0374 ship 10132 38116 0.366 0.27 0.221 0.064 tennis-court 10132 1866 1 0 0.000499 0.000117 basketball-court 10132 432 1 0 0 0 storage-tank 10132 10222 0.416 0.0559 0.107 0.0325 soccer-ball-field 10132 449 0 0 0 0 roundabout 10132 575 1 0 0 0 harbor 10132 6382 1 0 0.00162 0.000453 swimming-pool 10132 1663 0.127 0.504 0.161 0.037 helicopter 10132 317 1 0 0 0 container-crane 10132 57 0 0 0 0
> 
> 建议检查下训练时的gpu利用率，确保训练期间没有出现利用率为0的情况，我这边yolov5m batchsize=64 epochs=300训dotav1.5也才花不到15h，不过你这个模型的显存占用量未免太大了一点

我用的是convnext_tiny作为骨干的YOLOV5m，卡是1080ti 4张，一共的batchsize是8，相当于1张2个batchsize，内存占用6G，Model Summary: 313 layers, 38786865 parameters, 38786865 gradients, 93.4 GFLOPs，训练出来的best.pt文件也就78M，就不知道为什么显存占用很大

**Comment by hukaixuan19970627** [comment]
你干脆在原始的yolov5上替换convnext为backbone好了，coco数据集的图像分辨率还更低，训练速度肯定更快。如果coco数据集上都不能获得精度的提升的话，换到DOTA遥感图像数据集上得表现也不会更好

**Comment by LUO77123** [comment]
好的，这个我尝试一下喃

**Comment by LUO77123** [comment]
> > > > AdamW初始学习率不能设为0.01，我印象里都是设为0.001甚至更小，那个0.01是SGD的学习率参数设置，你改为SGD看看。
> > > 
> > > 
> > > 这次训练了一个epoch（4卡都要2个多小时，哭了），又成功了，不知道是不是从AdamW换成Adam的缘由。看到gap=512时，cc也才57个，有点少。 Class Images Labels P R mAP@.5 mAP@.5:.95 all 10132 227311 0.474 0.12 0.0724 0.022 plane 10132 8973 0.308 0.644 0.466 0.163 baseball-diamond 10132 637 1 0 0 0 bridge 10132 1480 0 0 0 0 ground-track-field 10132 410 0 0 0 0 small-vehicle 10132 141679 0.216 0.0979 0.0691 0.0171 large-vehicle 10132 14053 0.16 0.353 0.131 0.0374 ship 10132 38116 0.366 0.27 0.221 0.064 tennis-court 10132 1866 1 0 0.000499 0.000117 basketball-court 10132 432 1 0 0 0 storage-tank 10132 10222 0.416 0.0559 0.107 0.0325 soccer-ball-field 10132 449 0 0 0 0 roundabout 10132 575 1 0 0 0 harbor 10132 6382 1 0 0.00162 0.000453 swimming-pool 10132 1663 0.127 0.504 0.161 0.037 helicopter 10132 317 1 0 0 0 container-crane 10132 57 0 0 0 0
> > 
> > 
> > 建议检查下训练时的gpu利用率，确保训练期间没有出现利用率为0的情况，我这边yolov5m batchsize=64 epochs=300训dotav1.5也才花不到15h，不过你这个模型的显存占用量未免太大了一点
> 
> 我用的是convnext_tiny作为骨干的YOLOV5m，卡是1080ti 4张，一共的batchsize是8，相当于1张2个batchsize，内存占用6G，Model Summary: 313 layers, 38786865 parameters, 38786865 gradients, 93.4 GFLOPs，训练出来的best.pt文件也就78M，就不知道为什么显存占用很大

|   3  GeForce GTX 108...  On   | 00000000:07:00.0 Off |                  N/A |
| 41%   72C    P2   216W / 220W |   9070MiB / 11178MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  On   | 00000000:08:00.0 Off |                  N/A |
| 37%   66C    P2   192W / 220W |   5379MiB / 11178MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  On   | 00000000:0C:00.0 Off |                  N/A |
| 38%   68C    P2   192W / 220W |   5379MiB / 11178MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  On   | 00000000:0D:00.0 Off |                  N/A |
| 49%   84C    P2   173W / 220W |   5379MiB / 11178MiB |    100%    
占用100%
