### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by wafa-bouzouita** [hukaixuan19970627/yolov5_obb#321]

**Comment by wafa-bouzouita** [comment]
Hello,

I want to train yyolov5_obb using transfer-learning 
Is it possible?

Best regards and Thank you

**Comment by wafa-bouzouita** [comment]
Hi,

Thank you for your response.
In my case, I have few data. So, I want to freeze the backbone and the detector model and train the output layer with my data.
When training I changed the "freeze" parameter to "23", but I have 0 as mAP and I am not sure if this is correct.

Could you please give me some details on how to do that?

Thank you.

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/169635058-4904048b-5e07-461c-8594-3ca7b0462bb5.png)
@wafa-bouzouita

**Comment by hukaixuan19970627** [comment]
And in my experience, training from scratch can get better performance.

**Comment by wafa-bouzouita** [comment]
The problem is that in my application I must use only a very small data (~50) to train the model . But even using transfer learning (freeze=10 or 24) didn't give good results (mAP~0) . Have you please an idea how to deal with small data with yolov5_obb?
