### ISSUE TITLE
大佬为什么demo跑通了，跑了150epoch，初始权重用的yolov5m.pt,最后预测可视化啥都没有预测呀

### ISSUE THREAD

**Issue by zhanguser0614** [hukaixuan19970627/yolov5_obb#322]

**Comment by zhanguser0614** [comment]
python train.py --data 'data/yolov5obb_demo_split.yaml' --epochs 10 --batch-size 2 --img 1024 --device 0
我是用的这行吧epoch加到150后面预测发现还是预测为0，是数据集只有一张图片的原因吗，刚接触这个

**Comment by hukaixuan19970627** [comment]
demo只是为了验证环境是否安装无误以及让人快速上手。复现DOTA精度请参考ReadMe.md:
![image](https://user-images.githubusercontent.com/72599120/168459680-3ebb8ccb-aa71-427d-b28d-17d4181d7eca.png)
