### ISSUE TITLE
Train your own data set - single target detection

### ISSUE THREAD

**Issue by winstion504** [hukaixuan19970627/yolov5_obb#323]
Use yolov5s model of yoloV5 rotating target to train my own data set (more than 1000 pieces,600*600 size, detection target is relatively large). , and changed nc to 2. Single target detection, the final detection will generate a lot of prediction boxes, confusion. Blogger, please ask how to adjust. thank you。
![results](https://user-images.githubusercontent.com/77868489/168465695-02d38a6b-928e-4b01-a855-7cb98e766f27.png)
![1652606146(1)](https://user-images.githubusercontent.com/77868489/168465741-535378c8-01d7-4543-b1db-c04ac541ff6b.jpg)

**Comment by hukaixuan19970627** [comment]
From your loss curve, the model haven't converged, so you need to adjust the training epoch to 300 or much bigger.

**Comment by winstion504** [comment]
Hello, blogger. Set training times to 400, NC to 2, single target detection. The training diagram is shown below. In the prediction, the center of each target was found. The prediction box has an Angle to the target. Please check whether the Angle loss still does not converge in my result.thank you。
![results](https://user-images.githubusercontent.com/77868489/169490622-433aa3e8-444f-471e-aca3-65a105c0b1a4.png)

**Comment by hukaixuan19970627** [comment]
The information you're providing isn't comprehensive enough, can you upload these files?
![image](https://user-images.githubusercontent.com/72599120/169651593-bf0d3a15-8e9d-4acf-a251-dfeaa2c2a471.png)

**Comment by winstion504** [comment]
![results](https://user-images.githubusercontent.com/77868489/169685765-3afe3d06-0960-4198-bfca-a40e1911bfee.png)
博主，这是我训练400轮的结果，检测精度只有50%，而且预测未能偏转目标区域，存在角度差。谢谢

**Comment by winstion504** [comment]
![1653208279(1)](https://user-images.githubusercontent.com/77868489/169686066-45551a62-39f8-4e03-994f-cedb6341efd2.jpg)
![1653208408(1)](https://user-images.githubusercontent.com/77868489/169686075-5345079b-0a8b-478b-80a4-389bf01c2f97.jpg)
![labels](https://user-images.githubusercontent.com/77868489/169686081-113d6d76-6cda-4d4f-857d-129fa7cf7d28.jpg)
![labels_correlogram](https://user-images.githubusercontent.com/77868489/169686085-f84d6ff6-adb0-4f7d-bfa8-b9ee1b168e78.jpg)
![results](https://user-images.githubusercontent.com/77868489/169686092-485a139a-434c-4b9c-a46b-c1390bc87f9e.png)

![train_batch0](https://user-images.githubusercontent.com/77868489/169686095-0f8de7e8-1607-434b-909e-d56cd1e35408.jpg)
![val_batch0_labels](https://user-images.githubusercontent.com/77868489/169686097-8b9fa9aa-e892-48f5-be61-fd446aa21439.jpg)
![val_batch0_pred](https://user-images.githubusercontent.com/77868489/169686105-5ff48505-030e-4963-9f79-c955c2c50107.jpg)

Blogger, this is the result of 400 rounds of training thank you

**Comment by hukaixuan19970627** [comment]
It doesn't look like you're using my repo

**Comment by winstion504** [comment]
> It doesn't look like you're using my repo
Thank you very much, blogger. Before using your code to train your own data set, is the data set format to use doTA format?

**Comment by hukaixuan19970627** [comment]
[GetStart.md](https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/GetStart.md)
