### ISSUE TITLE
训练结果精度很低

### ISSUE THREAD

**Issue by tianxiu322** [hukaixuan19970627/yolov5_obb#325]
大佬能帮我看看原因吗？
results.png
![results](https://user-images.githubusercontent.com/37444556/168730353-fc911319-91bb-44df-92db-51ced85da655.png)

labels.jpg
![labels](https://user-images.githubusercontent.com/37444556/168730421-75e949c8-1943-4870-9a76-56741cb58031.jpg)

labels_correlogram.jpg
![labels_correlogram](https://user-images.githubusercontent.com/37444556/168730549-fb913693-8cef-409f-b14e-eb926bd75409.jpg)

train_batch0.jpg
![train_batch0](https://user-images.githubusercontent.com/37444556/168730591-e41882b8-86c5-4ac9-b1fd-ef1e5d8a213e.jpg)
train_batch1.jpg
![train_batch1](https://user-images.githubusercontent.com/37444556/168730620-07d96982-13c3-4da3-a7e5-0cc492b62eae.jpg)

test_batch1_pred.jpg
![test_batch1_pred](https://user-images.githubusercontent.com/37444556/168730662-2845b0e4-8b60-4ff2-83cf-e8addb021469.png)
test_batch1_labels.jpg
![test_batch1_labels](https://user-images.githubusercontent.com/37444556/168730683-b094a6e2-87f5-4476-a85b-aa3508b24e4c.png)

test_batch2_pred.jpg
![test_batch2_pred](https://user-images.githubusercontent.com/37444556/168730771-ac840424-fc96-4c9e-9431-b9630767d63e.png)
test_batch2_labels.jpg
![test_batch2_labels](https://user-images.githubusercontent.com/37444556/168730802-881d9ece-9db6-4e00-82ef-80d01cf0dda7.png)

hyp
lr0: 0.01
lrf: 0.2
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.05
cls: 0.5
cls_pw: 1.0
theta: 0.5
theta_pw: 1.0
obj: 1.0
obj_pw: 1.0
iou_t: 0.2
anchor_t: 4.0
fl_gamma: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.2
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
cls_theta: 180
csl_radius: 2.0

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/168736399-690e2918-1411-484d-a02d-db6af1fead93.png)

**Comment by tianxiu322** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/168736399-690e2918-1411-484d-a02d-db6af1fead93.p数据集用的dotav1.5,裁成了1024*1024的，gap500，发现cc类ap还是0

**Comment by tianxiu322** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/168736399-690e2918-1411-484d-a02d-db6af1fead93.png)

数据集用的dotav1.5,裁成了1024*1024的，gap500，发现cc类ap还是0

**Comment by tianxiu322** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/168736399-690e2918-1411-484d-a02d-db6af1fead93.png)
数据集用的v1.5，裁成了1024*1024，gap500，cc类ap是0

**Comment by hukaixuan19970627** [comment]
你用的应该不是我这个项目吧

**Comment by tianxiu322** [comment]
> 你用的应该不是我这个项目吧

应该是我数据处理方式的问题

**Comment by lukanightfever** [comment]
您好，问题解决了吗，我的情况跟你一模一样，map曲线也差不多。
