### ISSUE TITLE
how to convert format of my dataset for training on yolov5_obb

### ISSUE THREAD

**Issue by Houangnt** [hukaixuan19970627/yolov5_obb#326]

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/168962533-ebac709c-7269-43da-848c-01af8423f984.png)

**Comment by ryouchinsa** [comment]
[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel, you can draw oriented bounding boxes and export to the DOTA OBB format.
```
x1 y1 x2 y2 x3 y3 x4 y4 category difficult
1300.536987 1413.503784 1192.848755 1535.568848 530.876038 951.562073 638.564270 829.497009 truck 0
```

![draw_obb_polygon](https://user-images.githubusercontent.com/1954306/209951610-a343bd8c-7d49-4382-a4dd-bd9cf92bd318.jpg)
