### ISSUE TITLE
关于小目标检测 求指点

### ISSUE THREAD

**Issue by Wangfeng2394** [hukaixuan19970627/yolov5_obb#328]
作者大大您好！
我记得您曾经说过这个会过滤掉5*5的小目标，请问这个代码具体在哪呢，翻了半天也没找到，期待您解答！

**Comment by Wangfeng2394** [comment]
![图片](https://user-images.githubusercontent.com/42164696/169047508-9ed962d6-bc87-4c9c-82b6-909bc6bb6d48.png)
是这里么

**Comment by Wangfeng2394** [comment]
![图片](https://user-images.githubusercontent.com/42164696/169047719-6b3d2995-6316-475b-99af-9ad178973bbe.png)
貌似zhe'li？

**Comment by hukaixuan19970627** [comment]
三个地方
def check_anchors()
def kmean_anchors()
def __getitem__()

**Comment by Wangfeng2394** [comment]
谢谢大佬

**Comment by Wangfeng2394** [comment]
大佬您好，再问个问题，就是
