### ISSUE TITLE
为啥nms_ratated文件夹下没有这个nms_rotated_ext呀？我这是在Windows上运行的，是因为要在Linux上先编译吗？

### ISSUE THREAD

**Issue by shubudao** [hukaixuan19970627/yolov5_obb#329]
![问题](https://user-images.githubusercontent.com/50509401/169182172-a655cfe8-864c-4d95-aa90-c52701acc721.png)
![图片](https://user-images.githubusercontent.com/50509401/169182178-55c0a5d2-6e97-437f-a385-ee3006cab708.png)

**Comment by DiaJB** [comment]
您好，请问您解决了嘛
