### ISSUE TITLE
demo跑通，但是跑自己的时候合并结果报错

### ISSUE THREAD

**Issue by zhanguser0614** [hukaixuan19970627/yolov5_obb#330]
python DOTA_devkit/ResultMerge_multi_process.py --scrpath "/root/autodl-tmp/run/val/exp2/obb_demo/obb_predictions_Txt" --dstpath 'runs/val/dotav15_test_split/obb_predictions_Txt_Merged'
运行这行命令显示 No module named 'DOTA_devkit'

**Comment by hukaixuan19970627** [comment]
demo能跑通，自制数据集报错那说明是你使用方式上有问题，建议自己对照getstart.md流程好好检查下

**Comment by zhanguser0614** [comment]
好嘞感谢感谢
