### ISSUE TITLE
I have this Error : /yolov5_obb/utils/nms_rotated/nms_rotated_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

### ISSUE THREAD

**Issue by wafa-bouzouita** [hukaixuan19970627/yolov5_obb#331]

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/169452593-8fa5adeb-e23e-4fb7-8d3b-135d33a099b0.png)
[install.md](https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/install.md)

**Comment by 1ift** [comment]
你好，我也遇到了这个问题。
1.我是在linux下使用cpu检测
2.是在运行detect时发生的这个错误
![image](https://user-images.githubusercontent.com/82379573/169483684-3c0d9d44-6183-4053-baf6-4459e420c57a.png)
3.nms_rotated那一步已经运行过，运行结果如下。是否这里没有成功？
![image](https://user-images.githubusercontent.com/82379573/169483939-b16463a6-c724-4fe0-87ed-4d8843a301b8.png)
望解惑，万分感谢。

**Comment by wafa-bouzouita** [comment]
Thank for your response, it works correctly now

**Comment by 1ift** [comment]
I met the same problem as you, could you tell me how you solved it?

**Comment by wafa-bouzouita** [comment]
I did exactly the same installation steps mentionned in Install.md file (link : https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/install.md)  and the problem was resolved (in linux environement)
