### ISSUE TITLE
Single class dataset training

### ISSUE THREAD

**Issue by Wangfeng2394** [hukaixuan19970627/yolov5_obb#332]
大佬您好 又来麻烦您了：
我现在想训练一个单细胞模型，不知道是否支持(我记得您好久以前说不太支持？)
如果训练单目标需要注意哪些事项呢？
比如类别数是否需要设置为2？

**Comment by hukaixuan19970627** [comment]
单目标识别时设置nc=2，随便新增个classname就行

**Comment by Wangfeng2394** [comment]
![图片](https://user-images.githubusercontent.com/42164696/169640376-832926ff-4385-4579-a4b6-1c5d8e8d90b1.png)
![图片](https://user-images.githubusercontent.com/42164696/169641539-9da9db39-1c39-4220-9ba0-7b3bf118c492.png)
这两个地方都要改么 大佬

**Comment by yxfreedom** [comment]
会以下面的为准

**Comment by yxfreedom** [comment]
nc会以下面的data yaml文件为准

**Comment by Wangfeng2394** [comment]
谢谢大佬

**Comment by Wangfeng2394** [comment]
大佬您好，再问个问题，就是您说的这个"随便新增个classname就行"，需要再数据集里面随便再弄个图像标定一下么，比如我有1000张我想训练的类别的图像，需要随便弄一张 随便新增的类么

**Comment by hukaixuan19970627** [comment]
不需要额外标注，单目标数据集设置nc=2，随便新增个类名就行
