### ISSUE TITLE
ModuleNotFoundError: No module named 'DOTA_devkit'

### ISSUE THREAD

**Issue by zhanguser0614** [hukaixuan19970627/yolov5_obb#334]
![image](https://user-images.githubusercontent.com/94903297/169531532-549489a4-d773-4c06-af58-7a02b2455b30.png)
大佬这是安装成功了吗

**Comment by zhanguser0614** [comment]
可是后面评估数据集的时候File "/root/yolov5_obb/dataset/DOTA_devkit/ResultMerge_multi_process.py", line 13, in <module>
    import DOTA_devkit.dota_utils as util
ModuleNotFoundError: No module named 'DOTA_devkit'出现了这个错误
这是跑demo预测的时候出现的情况

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/169634903-5dd46cfd-25fe-4a05-aab5-085a9e0a8014.png)

**Comment by zhanguser0614** [comment]
![image](https://user-images.githubusercontent.com/94903297/169637080-78cc255a-abae-4482-966a-14e4e453d461.png)
大佬帮我看看，我的确是在cd yolovu_obb 文件夹下运行的，用的是分割后的数据

**Comment by zhanguser0614** [comment]
可是还是报同样的错误

**Comment by hukaixuan19970627** [comment]
你是不是删了什么文件，比如__init__.py？这个属于无法正确import其它.py文件类型的错误，建议自己检查/解决。

**Comment by zhanguser0614** [comment]
我正常安装的应该没删啥吧。不过我刚刚检查发现大佬项目DOTA_devkit文件夹下的__init__.py文件里面是空的，没有代码

**Comment by zhanguser0614** [comment]
谢谢大佬，我已经解决了，我参考你的知乎的关于这个工具包的文章，把import 代码稍微改了点现在好使了

**Comment by zhanguser0614** [comment]
> 

https://github.com/CAPTAIN-WHU/DOTA_devkit参考一下他的，或者try:
    import dota_utils as util
except:
    import dota_kit.dota_utils as util
import polyiou

**Comment by zhanguser0614** [comment]
> > 谢谢大佬，我已经解决了，我参考你的知乎的关于这个工具包的文章，把import 代码稍微改了点现在好使了
> 
> 兄弟，我也是这个问题，不知道你怎么解决的喃

**Comment by LUO77123** [comment]
> > > 谢谢大佬，我已经解决了，我参考你的知乎的关于这个工具包的文章，把import 代码稍微改了点现在好使了
> > 
> > 
> > 兄弟，我也是这个问题，不知道你怎么解决的喃

好的，谢谢兄弟
