### ISSUE TITLE
超出opencv的θ定义范围[-90, 0)

### ISSUE THREAD

**Issue by monument-and-sea-all-the-gift** [hukaixuan19970627/yolov5_obb#335]
![图片](https://user-images.githubusercontent.com/66421027/169739945-d6d303ef-34f3-404a-a847-2313f2658789.png)

**Comment by monument-and-sea-all-the-gift** [comment]
期待您的回复，谢谢，自己的数据集，标注完之后才加的pad进行reszie，所以label进行了修正，train_batch0.jpg看上去是有问题的，位置有偏移，角度没问题

**Comment by hukaixuan19970627** [comment]
请下载最新版本的源码，重新学习xiang项目的使用，另外记得花十分钟看一遍readme
![image](https://user-images.githubusercontent.com/72599120/170031379-fb1c5ae7-ffeb-44f0-a79a-f0440a88dbb1.png)
