### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by shubudao** [hukaixuan19970627/yolov5_obb#337]
This is the label of my picture and the modified dataaset.yaml , I don't know why it doesn't work！
Can you tell me?
![define](https://user-images.githubusercontent.com/50509401/169837295-8f720263-2d48-47db-a156-0bd42d282c04.png)
![wrong](https://user-images.githubusercontent.com/50509401/169837317-2eaea36f-009a-4872-af83-9ce8dbed5300.png)
![label](https://user-images.githubusercontent.com/50509401/169837324-0c0b4b58-0111-46f6-896f-833c5b92bd90.png)

**Comment by monument-and-sea-all-the-gift** [comment]
你的数据集都没转换，看下数据集格式吧

**Comment by shubudao** [comment]
x1      y1       x2        y2       x3       y3       x4       y4       classname     diffcult

1686.0   1517.0   1695.
![label](https://user-images.githubusercontent.com/50509401/170703355-0aebecf6-f7d2-4837-b188-ca6c5ade183b.png)
0   1511.0   1711.0   1535.0   1700.0   1541.0   large-vehicle      1
我是按照这个格式转换的呀！

**Comment by shubudao** [comment]
@monument-and-sea-all-the-gift 能指点一下吗？

**Comment by monument-and-sea-all-the-gift** [comment]
x，y为框的中心坐标，w为框的最长边，h为框的最短边，θ为顺时针旋转遇到最长边的角度范围为0到179，x,y,w,h需要除以图片的w和h，你可以看看作者发的知乎




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 晚上8:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hukaixuan19970627/yolov5_obb] ValueError: not enough values to unpack (expected 3, got 0) (Issue #337)





 
@monument-and-sea-all-the-gift 能指点一下吗？

**Comment by shubudao** [comment]
那不是老版的数据格式吗？新版的不是要求四个坐标，一个类别和一个难度系数吗？

**Comment by shubudao** [comment]
![image](https://user-images.githubusercontent.com/50509401/170706232-9113bb55-3b94-4017-acb4-30be61f3673a.png)

**Comment by monument-and-sea-all-the-gift** [comment]
实际训练的label不一样，那个只是中间过程




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 晚上9:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hukaixuan19970627/yolov5_obb] ValueError: not enough values to unpack (expected 3, got 0) (Issue #337)

**Comment by shubudao** [comment]
@monument-and-sea-all-the-gift  先谢谢，我先调整一下标签试一下！

**Comment by shubudao** [comment]
@monument-and-sea-all-the-gift 还是不行呀，这是我转换后的标签以及问题
![label](https://user-images.githubusercontent.com/50509401/170871623-c720afdc-8c78-4084-8235-4cbd17b06c1b.png)
![wrong](https://user-images.githubusercontent.com/50509401/170871626-e94f1535-daec-46e3-9158-a20916dd2bb5.png)

**Comment by shubudao** [comment]
![labek](https://user-images.githubusercontent.com/50509401/170871670-53e08dad-2b57-45de-ade6-eb3872bd9889.png)
标签图贴错了

**Comment by hukaixuan19970627** [comment]
跑一边getstart.md，如果demo没跑通，说明是环境问题，重装一下。如果demo跑通了，自制数据集报错，那说明路径/使用方式/数据结构等等方面存在问题，自己对照demo检查一下

**Comment by monument-and-sea-all-the-gift** [comment]
> ![labek](https://user-images.githubusercontent.com/50509401/170871670-53e08dad-2b57-45de-ade6-eb3872bd9889.png) 标签图贴错了

跑通没有，没有跑通的话，直接邮箱联系，给你指点指点

**Comment by shubudao** [comment]
@monument-and-sea-all-the-gift 没有跑通，demo可以跑通

**Comment by shubudao** [comment]
没有跑通，demo可以跑通，这是数据集格式







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hukaixuan19970627/yolov5_obb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hukaixuan19970627/yolov5_obb] ValueError: not enough values to unpack (expected 3, got 0) (Issue #337)





  
 标签图贴错了
  
跑通没有，没有跑通的话，直接邮箱联系，给你指点指点

**Comment by shubudao** [comment]
我的标签格式是按照这个格式来的
![example](https://user-images.githubusercontent.com/50509401/170929231-5a822e44-694e-4d67-bdaf-3f67ce35d8dc.png)

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/170938084-3e16c3bb-1c6f-4395-a82d-cf11039a46d9.png)

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/170938310-3a949588-f4d9-4abe-908f-a2fc9c56fdef.png)

**Comment by monument-and-sea-all-the-gift** [comment]
> 没有跑通，demo可以跑通，这是数据集格式
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hukaixuan19970627/yolov5_obb" ***@***.***&gt;; 发送时间:&nbsp;2022年5月30日(星期一) 中午1:41 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [hukaixuan19970627/yolov5_obb] ValueError: not enough values to unpack (expected 3, got 0) (Issue #337) 标签图贴错了 跑通没有，没有跑通的话，直接邮箱联系，给你指点指点 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你尝试把class的那些换成数字没有

**Comment by shubudao** [comment]
这是demo里面的label 
![label](https://user-images.githubusercontent.com/50509401/170942252-a719e34d-4a74-4bde-a780-65873e5f821e.png)

**Comment by shubudao** [comment]
我再按这个标签调整一下看看

**Comment by monument-and-sea-all-the-gift** [comment]
> 

哦，好像和这没关系，你这就是数据加载的问题，你看看路径之类的

**Comment by shubudao** [comment]
我先看看

**Comment by monument-and-sea-all-the-gift** [comment]
![image](https://user-images.githubusercontent.com/66421027/170943906-a96a364b-0533-47cb-8b46-adfb5460fef5.png)
为自己的label格式，就是这样，能train啊

**Comment by monument-and-sea-all-the-gift** [comment]
![image](https://user-images.githubusercontent.com/66421027/170944540-933e79a1-cade-408c-b7ec-2dc4108f9730.png)
class_name xc yc w h 西塔，label这种格式能train啊

**Comment by hukaixuan19970627** [comment]
一切以github上的getstart.md为准

**Comment by shubudao** [comment]
OK，首先谢谢两位的耐心指导，我的网络已经能够训练了，然后我总结了一下我的问题：
1）label格式应按照（x1, y1, x2, y2, x3, y3, x4, y4, class, dif）此种格式！
2）可能是我开始的路径设置有问题，我把数据集换了个路径就OK了！

**Comment by monument-and-sea-all-the-gift** [comment]
最终数据需要归一化的，为classname x y w h θ



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 晚上8:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hukaixuan19970627/yolov5_obb] ValueError: not enough values to unpack (expected 3, got 0) (Issue #337)





 
x1      y1       x2        y2       x3       y3       x4       y4       classname     diffcult
 
1686.0   1517.0   1695.
 
 0   1511.0   1711.0   1535.0   1700.0   1541.0   large-vehicle      1
 我是按照这个格式转换的呀！

**Comment by weiyaokun** [comment]
> OK，首先谢谢两位的耐心指导，我的网络已经能够训练了，然后我总结了一下我的问题： 1）label格式应按照（x1, y1, x2, y2, x3, y3, x4, y4, class, dif）此种格式！ 2）可能是我开始的路径设置有问题，我把数据集换了个路径就OK了！

你好  我也是上面这个问题  请问你是怎么解决的？那个标签路径需要添加吗？在哪添加？

**Comment by shubudao** [comment]
你是什么问题？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hukaixuan19970627/yolov5_obb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 下午2:52
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [hukaixuan19970627/yolov5_obb] ValueError: not enough values to unpack (expected 3, got 0) (Issue #337)





  
OK，首先谢谢两位的耐心指导，我的网络已经能够训练了，然后我总结了一下我的问题： 1）label格式应按照（x1, y1, x2, y2, x3, y3, x4, y4, class, dif）此种格式！ 2）可能是我开始的路径设置有问题，我把数据集换了个路径就OK了！
  
你好  我也是上面这个问题  请问你是怎么解决的？那个标签路径需要添加吗？在哪添加？

**Comment by shubudao** [comment]
demo跑通了吗？

**Comment by weiyaokun** [comment]
demo&nbsp; 跑通了
我的也是这个问题


这是我标签

这是我的yolov5obb_demo.yaml






Dr.κ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hukaixuan19970627/yolov5_obb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hukaixuan19970627/yolov5_obb] ValueError: not enough values to unpack (expected 3, got 0) (Issue #337)





 
demo跑通了吗？

**Comment by shubudao** [comment]
标签呢？

**Comment by weiyaokun** [comment]
Dr.κ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hukaixuan19970627/yolov5_obb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 下午3:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hukaixuan19970627/yolov5_obb] ValueError: not enough values to unpack (expected 3, got 0) (Issue #337)





 
标签呢？

**Comment by shubudao** [comment]
首先看标签本身的格式是否正确，之后的路径设置里面不要有中文，相对路径不好使就用绝对路径

**Comment by shubudao** [comment]
你直接在这发，截个图看看

**Comment by weiyaokun** [comment]
> 你直接在这发，截个图看看

![2d6430bd2632005992a33d1df97a699](https://github.com/hukaixuan19970627/yolov5_obb/assets/96097588/503fe7c6-109d-4dbb-aba4-d591e2688182)
<img width="342" alt="3779f4d2f98b0f1aa682fa418103921" src="https://github.com/hukaixuan19970627/yolov5_obb/assets/96097588/245bc529-5cf9-4816-b0c5-430f324dba1c">
<img width="688" alt="8187d80429b08b1a908a35c2c2685d0" src="https://github.com/hukaixuan19970627/yolov5_obb/assets/96097588/be777378-3bd4-40b4-8ad9-6f0935f923dd">

**Comment by shubudao** [comment]
你试试这个文章提到的方法：
http://t.csdn.cn/ShrQS

**Comment by weiyaokun** [comment]
我用的自定义数据集   训练命令是python train.py \
  --weights 'runs/train/yolov5s_csl_dotav1/weights/best.pt' \
  --data 'data/yolov5obb_demo.yaml' \
  --hyp 'data/hyps/obb/hyp.finetune_dota.yaml' \
  --epochs 300 \
  --batch-size 8 \
  --img 640 \
  --workers 16 \
  --device 0,1,2,3

**Comment by weiyaokun** [comment]
> 你试试这个文章提到的方法： http://t.csdn.cn/ShrQS

好的  我试试   thanks

**Comment by shubudao** [comment]
你用的多卡？

**Comment by weiyaokun** [comment]
嗯额 四卡

**Comment by shubudao** [comment]
豪，那你的batch_size可以设置更大的值，反正你用640的图片投喂

**Comment by shubudao** [comment]
你的问题解决了吗？

**Comment by weiyaokun** [comment]
还没有  我按照您刚刚发哪个   改了  还是不行
<img width="311" alt="image" src="https://github.com/hukaixuan19970627/yolov5_obb/assets/96097588/902589d3-fbc0-47a8-8cca-dd0322bc1c34">

**Comment by shubudao** [comment]
你把你的报错截图看看

**Comment by shubudao** [comment]
parent
├── yolov5
└── datasets
    └── DOTAv1.5
        ├── train_split_rate1.0_subsize1024_gap200
        ├── val_split_rate1.0_subsize1024_gap200
        └── test_split_rate1.0_subsize1024_gap200
            ├── images
                 |────1.jpg
                 |────...
                 └────10000.jpg
            ├── labelTxt
                 |────1.txt
                 |────...
                 └────10000.txt
你的数据集是按照这个结构组织的吗？

**Comment by weiyaokun** [comment]
不是

**Comment by shubudao** [comment]
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/50509401/a9f06883-1eb8-4d42-8075-d796c030586b)

**Comment by shubudao** [comment]
数据集结构一定要和他对应

**Comment by shubudao** [comment]
数据集所在的位置无所谓，但数据集一定要划分为 train、test、val，每个里面分别包含 image 和 LabelTxt

**Comment by weiyaokun** [comment]
我是自定义数据集   没有使用分割  所以就用那个dataset_demo里面的数据集格式
这是我的
<img width="214" alt="image" src="https://github.com/hukaixuan19970627/yolov5_obb/assets/96097588/88346bbd-34a0-404d-9482-dd21cb66f35f">

**Comment by shubudao** [comment]
那个 imgnamefile.txt 可以没有，是给你自己看的，但整体的数据集格式不能变，要有 test 集，用于实时训练测试

**Comment by weiyaokun** [comment]
现在报错变成了这个
![1685952574763](https://github.com/hukaixuan19970627/yolov5_obb/assets/96097588/bf594b35-4582-4a5e-a44b-e440014aa98b)

**Comment by shubudao** [comment]
你直接截最后的报错信息

**Comment by shubudao** [comment]
看看是哪里出错了

**Comment by weiyaokun** [comment]
<img width="640" alt="image" src="https://github.com/hukaixuan19970627/yolov5_obb/assets/96097588/83fd488b-858b-4c98-90ad-c5b4b69ee7ab">

**Comment by shubudao** [comment]
标签标注中间用空格隔开，别用逗号，看原始标签
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/50509401/e512c358-6788-426f-886a-5ce08f7c2baa)

**Comment by weiyaokun** [comment]
我改下试试

**Comment by weiyaokun** [comment]
OK  已经没有corrupted
<img width="691" alt="image" src="https://github.com/hukaixuan19970627/yolov5_obb/assets/96097588/62c68840-f2bc-4bc8-85f8-1fc38e2cd90a">

**Comment by weiyaokun** [comment]
非常感谢大佬  已经可以训练了 @shubudao

**Comment by shubudao** [comment]
没事，相互学习，相互促进！

**Comment by goodfishboy** [comment]
> This is the label of my picture and the modified dataaset.yaml , I don't know why it doesn't work！ Can you tell me? ![define](https://user-images.githubusercontent.com/50509401/169837295-8f720263-2d48-47db-a156-0bd42d282c04.png) ![wrong](https://user-images.githubusercontent.com/50509401/169837317-2eaea36f-009a-4872-af83-9ce8dbed5300.png) ![label](https://user-images.githubusercontent.com/50509401/169837324-0c0b4b58-0111-46f6-896f-833c5b92bd90.png)

您好，这个问题解决了吗，能加个q：508152494，请教一下吗

**Comment by wangchuangg** [comment]
![Uploading image.png…]()
这个错误怎么解决呀，好几天了，都没有解决这个

**Comment by wangchuangg** [comment]
<img width="544" alt="image" src="https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/4a3cdb7c-db01-482e-9a88-daf5304e0eea">
出现这个
Traceback (most recent call last):
  File "/hy-tmp/yolov5_obb/train.py", line 633, in <module>
    main(opt)
  File "/hy-tmp/yolov5_obb/train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "/hy-tmp/yolov5_obb/train.py", line 213, in train
    train_loader, dataset = create_dataloader(train_path, imgsz, batch_size // WORLD_SIZE, gs, names, single_cls,
  File "/hy-tmp/yolov5_obb/utils/datasets.py", line 101, in create_dataloader
    dataset = LoadImagesAndLabels(path, names, imgsz, batch_size,
  File "/hy-tmp/yolov5_obb/utils/datasets.py", line 444, in __init__
    labels, shapes, self.segments = zip(*cache.values())
ValueError: not enough values to unpack (expected 3, got 0)
这个问题该怎么解决，数据集是DOTA1.5，然后用CSDN上裁剪DOTA的代码，裁剪成1024*1024的，然后txt文件也是对应的进行裁剪，但是裁剪后的txt文件中，会出现没有标签的情况。训练的时候，就出现了这种情况

**Comment by wangchuangg** [comment]
我的数据集格式：
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/24a839fe-545e-4aea-9601-b75fa67aaaa7)
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/e1a4b094-387a-453a-9b55-34736924f1c0)
<img width="342" alt="image" src="https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/b1acfb05-4459-4040-8e96-f78a6fbadeb6">
然后有些裁剪的格式就变成了这种没有标签的样子，还是根据下载的DOTA1.5数据集进行裁剪的。上面出现的这个，
imagesource:GoogleEarth
gsd:0.242183449549
不知道会不会影响标签数据。
出现：Traceback (most recent call last):
  File "/hy-tmp/yolov5_obb/train.py", line 633, in <module>
    main(opt)
  File "/hy-tmp/yolov5_obb/train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "/hy-tmp/yolov5_obb/train.py", line 213, in train
    train_loader, dataset = create_dataloader(train_path, imgsz, batch_size // WORLD_SIZE, gs, names, single_cls,
  File "/hy-tmp/yolov5_obb/utils/datasets.py", line 101, in create_dataloader
    dataset = LoadImagesAndLabels(path, names, imgsz, batch_size,
  File "/hy-tmp/yolov5_obb/utils/datasets.py", line 444, in __init__
    labels, shapes, self.segments = zip(*cache.values())
ValueError: not enough values to unpack (expected 3, got 0)
是我用的裁剪后的数据集有错误吗，要是错了该怎么修改呀，真的不会，能不能帮帮我呀
关于数据集，我用官方的那个ImgSplit_multi_process进行裁剪时，因为test数据集图像没有标签，就不能进行裁剪，就按照了CSDN上的代码进行裁剪，然后图像的格式变成了jpg，裁剪对应的txt文件，有些会出现标注是空的
@shubudao @weiyaokun @monument-and-sea-all-the-gift

**Comment by shubudao** [comment]
@weiyaokun 首先，demo跑通了吗，如果跑通了说明环境配置没问题
其次，你这个数据格式有问题，看原始标签，把上面两行去掉
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/50509401/c92dfcbc-1b1c-4b5f-9d2f-3e7c3084637b)
最后，如果还不行，检查一下数据集路径，不要有中文字符，数据集结构一定要和他对应
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/50509401/c79ecd38-5e42-407c-bad4-0ad2eafa75bf)
最简单的实验方法就是先弄几张正确的图片以及标签，整个新的路径，跑一下，看看行不行，行的话就按这个格式整，不行就再对照demo检查检查

**Comment by wangchuangg** [comment]
您好。我下载官方的DOTA1.5数据集，我使用官方的那个ImgSplit_multi_process进行裁剪时，因为test数据集图像没有标签，就不能进行裁剪，但是train和val数据集能用官方的ImgSplit_multi_process
然后我又按照了CSDN上的代码进行裁剪，然后图像的格式变成了jpg，裁剪对应的txt文件，有些会出现标注是空的。就像下面这样
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/918d760a-eb31-478e-a3c8-3fba9db666ea)
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/6a23e366-3981-475d-9ecd-88732fc64388)
然后不管我用官方提供的裁剪工具，还是使用CSDN上找到的裁剪工具得到的数据集进行训练时，都是会出现：
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/ef4f1fa0-017f-4035-8dae-3722e94583b2)
出现这种错误，就不知道怎么改了，找了很多相关的解决方法，都是说数据集的标签格式有问题。就是不知道怎么解决？能不能教教我如何解决这个出现的错误呀？

**Comment by shubudao** [comment]
@wangchuangg，我很好奇你到底有没有看前面提到的经验，这个项目代码本身是提供了DOTA数据集的裁剪代码的，你既然已经知道了是数据标签出错，那就改吗：看看裁剪代码，学着写一个不就得了；用网上的代码就看看人家怎么实现的，哪里有问题就改一改；而且有标注为空不是很正常吗，图片那么大，不可能哪里都有目标的！
而且我很好奇你的demo能不能跑通，前面提到的方法你试了吗，前面踩过的坑你都避免了吗？

**Comment by wangchuangg** [comment]
> @wangchuangg，我很好奇你到底有没有看前面提到的经验，这个项目代码本身是提供了DOTA数据集的裁剪代码的，你既然已经知道了是数据标签出错，那就改吗：看看裁剪代码，学着写一个不就得了；用网上的代码就看看人家怎么实现的，哪里有问题就改一改；而且有标注为空不是很正常吗，图片那么大，不可能哪里都有目标的！ 而且我很好奇你的demo能不能跑通，前面提到的方法你试了吗，前面踩过的坑你都避免了吗？

![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/6ca033e0-cecf-4962-a407-b2f66cab5e43)
这次运行demo确实没成功。

**Comment by wangchuangg** [comment]
> @wangchuangg，我很好奇你到底有没有看前面提到的经验，这个项目代码本身是提供了DOTA数据集的裁剪代码的，你既然已经知道了是数据标签出错，那就改吗：看看裁剪代码，学着写一个不就得了；用网上的代码就看看人家怎么实现的，哪里有问题就改一改；而且有标注为空不是很正常吗，图片那么大，不可能哪里都有目标的！ 而且我很好奇你的demo能不能跑通，前面提到的方法你试了吗，前面踩过的坑你都避免了吗？

![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/498ea29c-37fc-4418-90c3-b49414c6cd27)

demo确实没有运行成功，但是我根据这个错误提示，我这个cuda是可用的呀。（哥，不要生气哈，我确实是太笨了，真对不起）

**Comment by shubudao** [comment]
@wangchuangg 你有多卡吗，你device敢选1

**Comment by shubudao** [comment]
@wangchuangg 你先搞懂那些参数是什么意思吧！

**Comment by wangchuangg** [comment]
> @wangchuangg 你有多卡吗，你device敢选1
这些参数我知道呀，
我是运行的时候已经改成了0，出现这个问题

**Comment by wangchuangg** [comment]
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/b9326998-f307-47df-b45f-faeecc296510)

**Comment by shubudao** [comment]
> ![image](https://user-images.githubusercontent.com/141005166/270082785-b9326998-f307-47df-b45f-faeecc296510.png)

非要我戳穿你吗？
![270082079-498ea29c-37fc-4418-90c3-b49414c6cd27](https://github.com/hukaixuan19970627/yolov5_obb/assets/50509401/6200d620-5e55-4ecf-959f-2fcd3b38bb0e)

**Comment by wangchuangg** [comment]
> > ![image](https://user-images.githubusercontent.com/141005166/270082785-b9326998-f307-47df-b45f-faeecc296510.png)
> 
> 非要我戳穿你吗？ ![270082079-498ea29c-37fc-4418-90c3-b49414c6cd27](https://user-images.githubusercontent.com/50509401/270086790-6200d620-5e55-4ecf-959f-2fcd3b38bb0e.png)

谢谢你，指出来了，可是我在train.py里的参数device里面改了呀，改成了0。也保存了呀。再运行咋还是这样呀（我底子很差，）

**Comment by wangchuangg** [comment]
> > ![image](https://user-images.githubusercontent.com/141005166/270082785-b9326998-f307-47df-b45f-faeecc296510.png)
> 
> 非要我戳穿你吗？ ![270082079-498ea29c-37fc-4418-90c3-b49414c6cd27](https://user-images.githubusercontent.com/50509401/270086790-6200d620-5e55-4ecf-959f-2fcd3b38bb0e.png)
谢谢你，指出来了，我都没注意这个。可是我是在train.py里的参数device里面改了呀，改成了0。也保存了呀。再运行的时候出现这样，现在我在命令行里输入--device 0，就没有这个错误了。(我问的问题，让你看笑话了。)

**Comment by wangchuangg** [comment]
> > ![image](https://user-images.githubusercontent.com/141005166/270082785-b9326998-f307-47df-b45f-faeecc296510.png)
> 
> 非要我戳穿你吗？ ![270082079-498ea29c-37fc-4418-90c3-b49414c6cd27](https://user-images.githubusercontent.com/50509401/270086790-6200d620-5e55-4ecf-959f-2fcd3b38bb0e.png)
谢谢你，指出来了，我都没注意这个。可是我是在train.py里的参数device里面改了呀，改成了0。也保存了呀。再运行的时候出现这样，现在我在命令行里输入--device 0，就没有这个错误了。(我问的问题，让你看笑话了。)

**Comment by wangchuangg** [comment]
> > > ![image](https://user-images.githubusercontent.com/141005166/270082785-b9326998-f307-47df-b45f-faeecc296510.png)
> > 
> > 
> > 非要我戳穿你吗？ ![270082079-498ea29c-37fc-4418-90c3-b49414c6cd27](https://user-images.githubusercontent.com/50509401/270086790-6200d620-5e55-4ecf-959f-2fcd3b38bb0e.png)
> > 谢谢你，指出来了，我都没注意这个。可是我是在train.py里的参数device里面改了呀，改成了0。也保存了呀。再运行的时候出现这样，现在我在命令行里输入--device 0，就没有这个错误了。(我问的问题，让你看笑话了。)

![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/0a997c5c-ea25-43ba-a174-330ce0615b50)
demo运行出来了，但是这个精度看着像是HBB的呀，会不会是我运行demo的时候，demoshujj没有进行切分导致的呀，接下来就是切分数据集了吧。（哥，别骂了，我知道我很菜，太蠢了，问的问题都是在污您的眼）

**Comment by shubudao** [comment]
@wangchuangg 看得出来，你是完全没看GetStart.md，那估计你也没去看作者的知乎文章讲解了；同时，从你的问题中不难看出，你没有读代码，不知道打印出来的信息代表什么；而你现在遇到的问题，都是一些很基础的问题。
我目前的建议是先从头理清相关的概念，读一读代码，看看作者的图像是如何切割的，map是如何计算的，以及如何将模型运行起来，而不是毫无思考的去咨询求助。
言尽于此，与君共勉！

**Comment by wangchuangg** [comment]
> @wangchuangg 看得出来，你是完全没看GetStart.md，那估计你也没去看作者的知乎文章讲解了；同时，从你的问题中不难看出，你没有读代码，不知道打印出来的信息代表什么；而你现在遇到的问题，都是一些很基础的问题。 我目前的建议是先从头理清相关的概念，读一读代码，看看作者的图像是如何切割的，map是如何计算的，以及如何将模型运行起来，而不是毫无思考的去咨询求助。 言尽于此，与君共勉！
好的好的，但是我看了GetStart.md呀

**Comment by wangchuangg** [comment]
@shubudao 已经明白了，谢谢您了。我流程都没没弄清楚，潦草的看文件，是这样的，已经知道问题了，会去认真琢磨，仔细去看的。还是要谢谢，一直麻烦您，前面的问题都删了，谢谢您哈。

**Comment by kevinrsb** [comment]
我现在的情况是环境用cpu的，我没有下pytorch，可以分割图片，就是不能运行train，也是ValueError: not enough values to unpack (expected 3, got 0)这个问题，我是运行demo都不行，我之前用cpu运行成功过的，现在不知道为什么又不行了@shubudao

**Comment by kevinrsb** [comment]
![57779a71f94f4d4b830252f38314bea](https://github.com/hukaixuan19970627/yolov5_obb/assets/141244352/c8ec1a9c-d7df-4472-aec4-2baefa264e06)
![ef7e64d758c5581c8b58ebb9ce03b20](https://github.com/hukaixuan19970627/yolov5_obb/assets/141244352/5ea445ed-5ff7-4c53-aa9d-2189087671bc)
cpu的环境应该是没问题吧，因为我之前试了很多次gpu'的都不行就想用cpu试试，然后成功过，结果现在又不行了@shubudao
