### ISSUE TITLE
box loss异常

### ISSUE THREAD

**Issue by tianxiu322** [hukaixuan19970627/yolov5_obb#338]
dalao能帮我看看原因吗，用的UCAS_AOD数据集，两个类别，box损失异常
用的yolov5m+csl
是不是nms的问题，dalao有什么建议吗？

**results.png**
![results](https://user-images.githubusercontent.com/37444556/169865725-784e6241-96da-43dd-8f9b-f414f5e86f8b.png)

**train_batch0**
![train_batch0](https://user-images.githubusercontent.com/37444556/169865964-7fbac6c0-2f6c-48bf-9c5b-242a114d0e6b.jpg)

**test_batch0_labels**
![test_batch0_labels](https://user-images.githubusercontent.com/37444556/169866116-53a5644e-4805-4560-b315-8874b07c241a.png)

**test_batch0_pred**
![test_batch0_pred](https://user-images.githubusercontent.com/37444556/169866221-e854ea55-7590-48d6-a4a6-44a37c4ed5d4.png)

**labels.jpg**
![labels](https://user-images.githubusercontent.com/37444556/169866575-ca729024-d343-45dd-84f1-0ebb9a35e8dd.jpg)

**labels_correlogram.jpg**
![labels_correlogram](https://user-images.githubusercontent.com/37444556/169866684-8a55cd2e-66e4-4b6f-999b-00771a360e71.jpg)

**hyp.yaml**
lr0: 0.01
lrf: 0.2
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.05
cls: 1.0
cls_pw: 1.0
theta: 0.5
theta_pw: 1.0
obj: 1.0
obj_pw: 1.0
iou_t: 0.2
anchor_t: 4.0
fl_gamma: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 180.0
translate: 0.1
scale: 0.2
shear: 0.0
perspective: 0.0
flipud: 0.5
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
cls_theta: 180
csl_radius: 2.0

**Comment by hukaixuan19970627** [comment]
在验证集精度曲线上升趋势停止之前，都不能叫做收敛

**Comment by tianxiu322** [comment]
> 在验证集精度曲线上升趋势停止之前，都不能叫做收敛

那为什么前100多个epoch的box loss会这样呢，dalao有什么思考方向或者建议吗？
我重新跑了个500epoch的，box loss甚至从第300个epoch才稳定下降，前面都在波动

**Comment by hukaixuan19970627** [comment]
Loss一般看不出来什么，它的波动通常和数据有关。收敛的怎么样主要看训练集的精度曲线趋势如何，泛化性怎么样主要看验证集的精度曲线

**Comment by tianxiu322** [comment]
> Loss一般看不出来什么，它的波动通常和数据有关。收敛的怎么样主要看训练集的精度曲线趋势如何，泛化性怎么样主要看验证集的精度曲线

okay，谢谢~
