### ISSUE TITLE
mAP Question about Custom Dataset 

### ISSUE THREAD

**Issue by Hone-Xu** [hukaixuan19970627/yolov5_obb#341]
想请教下，我的为什么训练出来是这样的
results.png
![image](https://user-images.githubusercontent.com/96858577/170174596-c74d63e5-fe8d-40ae-8914-0b186cab857d.png)
train_batch0.jpg
![image](https://user-images.githubusercontent.com/96858577/170190298-59f6da11-5bb8-44e9-82b2-401c4f890e48.png)
train_batch1.jpg
![image](https://user-images.githubusercontent.com/96858577/170190384-bdc3d7ab-afac-4f0a-9469-ce1ed6837fa6.png)
train_batch2.jpg
![image](https://user-images.githubusercontent.com/96858577/170190422-2abc6c3b-31ae-473c-9f59-e4679f6626f1.png)
train_batch3.jpg
![image](https://user-images.githubusercontent.com/96858577/170190478-787ebfa5-0aaa-407f-90f8-df3e897e8080.png)
val_batch0_labels.jpg
![image](https://user-images.githubusercontent.com/96858577/170190626-1ad1d63d-f842-4a8d-acbf-15b1946923fc.png)
val_batch1_labels.jpg
![image](https://user-images.githubusercontent.com/96858577/170190655-3a745dd2-d85d-4391-8153-fb325b058cd6.png)
@hukaixuan19970627 @sunbuhui @Ethan-niu

**Comment by Hone-Xu** [comment]
lr0: 0.01
lrf: 0.2
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.1
cls: 0.5
cls_pw: 1.0
theta: 0.5
theta_pw: 1.0
obj: 1.0
obj_pw: 1.0
iou_t: 0.2
anchor_t: 4.0
fl_gamma: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.5
fliplr: 0.5
mosaic: 0.1
mixup: 0.0
copy_paste: 0.0
cls_theta: 180
csl_radius: 2.0

**Comment by Hone-Xu** [comment]
![image](https://user-images.githubusercontent.com/96858577/170175040-df57fe0e-de62-451d-a3c3-2764106ced7f.png)

**Comment by Hone-Xu** [comment]
![image](https://user-images.githubusercontent.com/96858577/170175040-df57fe0e-de62-451d-a3c3-2764106ced7f.png)

**Comment by sunbuhui** [comment]
😂早忘了，还是另请高明吧

**Comment by hukaixuan19970627** [comment]
1. patience参数表示yolov5_obb经历patience个epoch的训练之后，若验证集的最高精度未发生改变，则中止训练。既然模型还未收敛，那你就往大了调呗
2. 在你的应用场景中，建议数据增强策略关闭mixup，别的参数可以保持项目的默认设置不变
3. 尽量调大batchsize，不然BN层的均值和方差参数可能计算的不准

**Comment by Hone-Xu** [comment]
请问修改后我的mAP还是不上升这个是为什么
![image](https://user-images.githubusercontent.com/96858577/170605118-272a5bde-1d6c-4bf5-aebb-adee572029be.png)
train_batch0.jpg
![image](https://user-images.githubusercontent.com/96858577/170605217-88870346-9cb3-4dd8-8d7c-c8fa89cf9def.png)

**Comment by Hone-Xu** [comment]
我的两个类标注数量差距有点大，和这个有关系吗

**Comment by hukaixuan19970627** [comment]
初步分析可能是学习率的问题，看精度曲线、Loss曲线的话可以发现warmup截断收敛还是挺正常的，但是之后Box Loss就下不去了。建议lr0改成0.005~0.01试试看效果会不会好一点，权重文件记得用我提供的DOTAv1.5的预训练权重

**Comment by hukaixuan19970627** [comment]
数据集规模很小的话可以参考这个[issue](https://github.com/hukaixuan19970627/yolov5_obb/issues/367)，他碰到的问题和你类似。

**Comment by FlinkRay** [comment]
> 数据集规模很小的话可以参考这个[issue](https://github.com/hukaixuan19970627/yolov5_obb/issues/367)，他碰到的问题和你类似。

作者，您好，我想问一下在训练的时候map、precision、recall一直为0的错误原因是什么
![results](https://user-images.githubusercontent.com/39163544/175245784-a3532b7d-0c1a-4237-b629-e6f688e51ca9.png)
![image](https://user-images.githubusercontent.com/39163544/175245858-c64fd607-b4e8-4630-98ad-9980e03a9011.png)
loss是有的

**Comment by hukaixuan19970627** [comment]
@FlinkRay 新开一个issue

**Comment by FlinkRay** [comment]
> @FlinkRay 新开一个issue

已经新开了，麻烦您帮忙看看
