### ISSUE TITLE
About --augment

### ISSUE THREAD

**Issue by lizifan123** [hukaixuan19970627/yolov5_obb#344]
作者您好，请问在val时采取多尺度测试是设augment为True就可以吗，我这么操作以后在val数据集中map反而降了0.07，这是为啥啊，谢谢作者解答

**Comment by hukaixuan19970627** [comment]
在线TTA代码我还没有进行过旋转检测的改进，建议先别用。

**Comment by lizifan123** [comment]
好的，谢谢您
