### ISSUE TITLE
模型链接404

### ISSUE THREAD

**Issue by ipyffor** [hukaixuan19970627/yolov5_obb#345]

**Comment by hukaixuan19970627** [comment]
#250

**Comment by ipyffor** [comment]
我测试了一下，提供的yolov5m模型输入尺寸是不是2048的，我对比了下参数imgsz用1024和2048，使用1024有很多漏检，2048结果好很多，测试图片是项目里面的，而您的表格标注的尺寸是1024，这是不是有问题，我需要使用trt模型，2048对于我来说尺寸太大了，您提供的yolov5s和yolov5-tiny链接都显示404。
