### ISSUE TITLE
Loss Function

### ISSUE THREAD

**Issue by jytJYT8** [hukaixuan19970627/yolov5_obb#346]
请问新版项目的损失计算部分有用到旋转框iou吗，置信度损失是怎样实现的呢

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/170454574-9ed8acaf-511e-4951-8084-905e2a9c6f2e.png)

**Comment by jytJYT8** [comment]
请问编译的nms_rotated是用来进行非极大值抑制的吗，是否使用了旋转框iou呢
