### ISSUE TITLE
提供的yolov5m模型输入尺寸错误？

### ISSUE THREAD

**Issue by ipyffor** [hukaixuan19970627/yolov5_obb#348]
我测试了一下，提供的yolov5m模型输入尺寸是不是2048的，我对比了下参数imgsz用1024和2048，使用1024有很多漏检，2048结果好很多，测试图片是项目里面的，而您的表格标注的尺寸是1024，这是不是有问题，我需要使用trt模型，2048对于我来说尺寸太大了，您提供的yolov5s和yolov5-tiny链接都显示404。

_Originally posted by @ipyffor in https://github.com/hukaixuan19970627/yolov5_obb/issues/345#issuecomment-1138350621_

**Comment by hukaixuan19970627** [comment]
1.大图推理精度高于小图是正常现象，这也是提点的一种手段。用不了2048你就用1024或者640呗
2.后两个权重文件还没上传

**Comment by wangsun1996** [comment]
> 

想请问一下，在官方的yolov5中有s,m,l等规模的模型，输入分辨率也有640和1280两种。想问下您在DOTA上，选择高分辨率的输入图像与选择低分辨率的输入图像，如果想达到相近的map性能指标，选择模型规模的对应关系是怎么样的？
您有做过类似的测试吗？感谢
