### ISSUE TITLE
nms_rotated_ext cuda question/issue

### ISSUE THREAD

**Issue by d5423197** [hukaixuan19970627/yolov5_obb#349]
你好博主,

感谢您的开源代码.
在使用的时候, 出现下面的问题, 
![1653630775(1)](https://user-images.githubusercontent.com/61330860/170638689-8b93dd4d-2b39-449d-971c-10c7f263471f.png)
上面显示已经检测到cuda, 但是在运行到nms rotated部分出错, 这部分代码我目测是博主用别的语言写的? 不是很清楚这个错误该如何处理. 准确来说是我把同样的环境和代码在一个服务器上跑成功了之后, 挪到了另一个服务器上出现了这个问题. 不知道是否描述清楚, 任何帮助都感谢

**Comment by hukaixuan19970627** [comment]
不同电脑/服务器的CUDA依赖环境都不完全相同，所以需要重新编译一遍CUDA代码，复制过去是没用的

**Comment by monument-and-sea-all-the-gift** [comment]
> 你好博主,
> 
> 感谢您的开源代码. 在使用的时候, 出现下面的问题, ![1653630775(1)](https://user-images.githubusercontent.com/61330860/170638689-8b93dd4d-2b39-449d-971c-10c7f263471f.png) 上面显示已经检测到cuda, 但是在运行到nms rotated部分出错, 这部分代码我目测是博主用别的语言写的? 不是很清楚这个错误该如何处理. 准确来说是我把同样的环境和代码在一个服务器上跑成功了之后, 挪到了另一个服务器上出现了这个问题. 不知道是否描述清楚, 任何帮助都感谢

这看着就是torch的cuda版本和服务器的cuda版本不对应

**Comment by d5423197** [comment]
谢谢你的回复 有点没理解你的回复, 默认不就是使用torch的cuda吗?

> > 你好博主,
> > 感谢您的开源代码. 在使用的时候, 出现下面的问题, ![1653630775(1)](https://user-images.githubusercontent.com/61330860/170638689-8b93dd4d-2b39-449d-971c-10c7f263471f.png) 上面显示已经检测到cuda, 但是在运行到nms rotated部分出错, 这部分代码我目测是博主用别的语言写的? 不是很清楚这个错误该如何处理. 准确来说是我把同样的环境和代码在一个服务器上跑成功了之后, 挪到了另一个服务器上出现了这个问题. 不知道是否描述清楚, 任何帮助都感谢
> 
> 这看着就是torch的cuda版本和服务器的cuda版本不对应
