### ISSUE TITLE
大佬您好，同一个模型，为什么训练的时候层数和val时候的层数不一样？

### ISSUE THREAD

**Issue by Wangfeng2394** [hukaixuan19970627/yolov5_obb#351]
训练的时候是这样的：
![image](https://user-images.githubusercontent.com/42164696/170744093-85ee98f4-a2a8-4a07-b210-f14402832e62.png)
val的时候是这样的：
![image](https://user-images.githubusercontent.com/42164696/170744157-93f655da-4c9f-4832-a74d-fc1d1945ce49.png)

**Comment by Wangfeng2394** [comment]
为什么呢

**Comment by hukaixuan19970627** [comment]
推理时为了加速会融合conv和bn层，相关原理可以用搜索引擎搜索一下“吸BN”

**Comment by Wangfeng2394** [comment]
谢谢
