### ISSUE TITLE
大佬您好，请问标注文件里面的difficult 在训练的时候有用嘛？

### ISSUE THREAD

**Issue by Wangfeng2394** [hukaixuan19970627/yolov5_obb#352]
比如我遇到一个总是检测错误的杂质 ，我标记个difficult会对训练有帮助嘛

**Comment by hukaixuan19970627** [comment]
DOTA格式的labels中的diffcult值范围为0~2，普遍的处理逻辑是diffcult=2的box会被删除掉，不参与训练
![image](https://user-images.githubusercontent.com/72599120/170915710-c72b1754-e185-4703-bf92-3309a851a8b6.png)
