### ISSUE TITLE
关于验证集的问题

### ISSUE THREAD

**Issue by 619732457** [hukaixuan19970627/yolov5_obb#353]
作者你好，根据您的项目我已经在自己的数据集上有些结果，但我现在有些疑惑
path: ./dataset # dataset root dir
train: dataset_demo/images # train images (relative to 'path') 
val: dataset_demo/images   # val images (relative to 'path') 
test: dataset_demo/images  # test images (optional)

根据这个迁移到我的数据集上
path: ./dataset # dataset root dir
train: myDataset/images # train images (relative to 'path')
val: myDataset/images   # val images (relative to 'path')
test: myDataset/images  # test images (optional)

第一个问题是，请问这样写的话，验证集就和训练集是一样的吗，验证集和训练集相同对结果有影响吗？
使用上述写法我已经有结果了，然后如果想使用其他的验证集，我新建了两个文件夹放图像和txt文件
train: Scanning 'dataset/myDataset/labelTxt.cache' images and labels... 633 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████████████████████████████████████████████████████████| 633/633 [00:00<?, ?it/s]
val: Scanning 'dataset/myDataset/valImages' images and labels...0 found, 155 missing, 0 empty, 0 corrupted: 100%|████████████████████████████████████████████████████████████| 155/155 [00:00<00:00, 1893.49it/s]
val: WARNING: No labels found in dataset/myDataset/valImages.cache. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
val: New cache created: dataset/myDataset/valImages.cache

第二个问题是，请问对于验证集的图像和txt文件有什么存放格式要求吗，我想使用其他的验证集

**Comment by hukaixuan19970627** [comment]
yolov5_obb每训练一个epoch，就会在验证集上评估一次精度，精度整体表现最高的那个epoch的权重会被命名为best.pt
