### ISSUE TITLE
mAP stagnates (Dota 1.5)

### ISSUE THREAD

**Issue by wafa-bouzouita** [hukaixuan19970627/yolov5_obb#355]
I trained yolov5_obb with Dota1.5 and the mAP stops improving, it stagnates at 0.524.. 
Could you indicate me how to improve this and how to obtain better results please?
thank you

**Comment by wafa-bouzouita** [comment]
hyp.yaml 

lr0: 0.01
lrf: 0.2
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.05
cls: 0.5
cls_pw: 1.0
theta: 0.5
theta_pw: 1.0
obj: 1.0
obj_pw: 1.0
iou_t: 0.2
anchor_t: 4.0
fl_gamma: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 180.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.5
fliplr: 0.5
mosaic: 0.95
mixup: 0.1
copy_paste: 0.0
cls_theta: 180
csl_radius: 2.0

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/172104433-dc317976-86ab-4add-bcee-df4c79d70f8f.png)
![image](https://user-images.githubusercontent.com/72599120/172104650-63f970dc-dabf-4d29-904b-606f7f696b98.png)
