### ISSUE TITLE
Exact position

### ISSUE THREAD

**Issue by Bwwwah** [hukaixuan19970627/yolov5_obb#356]
Hello,
My problem is that i want to be able to grab my object with pliers so i need its orientation, shape etc. Do you think i can get the the exact shape with yolov5_obb ?
Thanks !

**Comment by hukaixuan19970627** [comment]
How precise do you want the shape to be? yolov5_obb can only predict **rectangular boxes with orientation**.

**Comment by Bwwwah** [comment]
Too bad, I wanted the exact outline of the object. I used the facebook algo instead. [detectron2](https://github.com/facebookresearch/detectron2)
