### ISSUE TITLE
Missing theta loss

### ISSUE THREAD

**Issue by ngxingyu** [hukaixuan19970627/yolov5_obb#357]
https://github.com/hukaixuan19970627/yolov5_obb/blob/c7409fff231749eba063367a4328ed3def0bbbdc/train.py#L265

`results = (0, 0, 0, 0, 0, 0, 0, 0)  # P, R, mAP@.5, mAP@.5-.95, val_loss(box, obj, cls, theta)`

**Comment by hukaixuan19970627** [comment]
This bug has been fixed in https://github.com/hukaixuan19970627/yolov5_obb/commit/61bfc70300aad9284593a41ab1fe3525499f7769
