### ISSUE TITLE
de'te'ct.py中模型预测出来的值代表啥意思？

### ISSUE THREAD

**Issue by yuxin7** [hukaixuan19970627/yolov5_obb#361]
[**cx cy l s obj num_cls theta_cls**]的意思是：
cx cy l s：中心点x坐标，中心点y坐标，长边长度，短边长度。
obj是预测准确率吗？？？  num_cls的代表每一类的可能性吗？ theta_cls:0-180度的可能性吗？

**Comment by hukaixuan19970627** [comment]
可以这么理解，还有不清楚的可以把circular smooth label原文看一遍。
