### ISSUE TITLE
使用自己的数据集训练后，损失异常，box损失先是快速增大，然后才慢慢收敛

### ISSUE THREAD

**Issue by dahu-1998** [hukaixuan19970627/yolov5_obb#362]
自己识别的物体比较简单，设置参数都是默认参数没有更改，作者看下知道这是为啥子么
![results](https://user-images.githubusercontent.com/81225720/172807417-ee4aec19-21be-4e4c-a457-4c4f8019e944.png)
![train_batch4](https://user-images.githubusercontent.com/81225720/172807504-aa4cc830-4c9e-4157-a481-f13775a19459.jpg)

**Comment by hukaixuan19970627** [comment]
请将yolov5_obb代码更新至最新版本，重新按照install.md检查安装环境，按照getstart.md运行流程demo
