### ISSUE TITLE
[Question]Online tool to annotate image

### ISSUE THREAD

**Issue by tailtNinjavanVN** [hukaixuan19970627/yolov5_obb#363]
[Question]
Hi experts,

Sorry, I'm newbie.

What online tool you annotate obb object ?

Sincere apologies if the question has bothered you!

Thank in advanced!

**Comment by Avant-Gardiste** [comment]
Hi, you can use roLabelImg (https://github.com/cgvict/roLabelImg), i used also Roboflow (https://blog.roboflow.com/yolov5-for-oriented-object-detection/). 
PS : If you use roLabelImg you will get your final annoations in the following format (class, cx, cy, w, h, angle), then you need to convert it into the following format (x1 y1 x2 y2 x3 y3 x4 y4 x5 y5 x6 y6 x7 y7 x8 y8 class difficulty).
Hope this will help you !

**Comment by ryouchinsa** [comment]
[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel, you can draw oriented bounding boxes and export to the DOTA OBB format.
```
x1 y1 x2 y2 x3 y3 x4 y4 category difficult
1300.536987 1413.503784 1192.848755 1535.568848 530.876038 951.562073 638.564270 829.497009 truck 0
```

![draw_obb_polygon](https://user-images.githubusercontent.com/1954306/209951610-a343bd8c-7d49-4382-a4dd-bd9cf92bd318.jpg)
