### ISSUE TITLE
support for device_type='mps'?

### ISSUE THREAD

**Issue by vshesh** [hukaixuan19970627/yolov5_obb#364]
pytorch released support for M1 macbooks with device type "mps" a while ago.

I think yolov5 repo has support for it, would it be possible to add support here? 

i chased error messages for a while when trying to fix it on my own until I began to get errors about things like "cannot cast Float result to desired type  long long' at which point I didn't know what was going on anymore. 

Perhaps merging the new yolov5 will solve the problem?

**Comment by hukaixuan19970627** [comment]
Can you successfully run the following command on M1 macbooks?
```
cd utils/nms_rotated
python setup.py develop  #or "pip install -v -e ."
```
I'm sure the rest of the yolov5_obb except the **def obb_nms()** works well on the M1. So the problem you need to solve is how to make the CUDA code of def obb_nms() run successfully on M1.

**Comment by hukaixuan19970627** [comment]
I don't have a Mackbook so I can't help you with this, sorry.
