### ISSUE TITLE
nms rotate

### ISSUE THREAD

**Issue by d5423197** [hukaixuan19970627/yolov5_obb#366]
作者您好,

据您所知, 这个nms rotate的部分有写成py的吗, 就是不用c++的

谢谢,

ZD

**Comment by hukaixuan19970627** [comment]
https://github.com/ZhangGongjie/Soft-NMS-for-Rotated-Rectangles/blob/master/softnms_rotate.py

**Comment by d5423197** [comment]
谢谢了
