### ISSUE TITLE
Custom Dataset Question

### ISSUE THREAD

**Issue by BandyKenny** [hukaixuan19970627/yolov5_obb#367]
1、我看到作者跟新后，使用了DATO格式的标签，但对于顺序的说明不是特别清楚（因为我是用rolabelIMG转成DATO的），是所有的旋转框/非旋转框都按照左上角顶点开始取四个点的位置吗？
2、我得到的DATO标签4个点虽然都是顺时针，但是起始顺序不是一致的，非旋转的label是从左上角开始的顺时针，但是有些旋转框的点是从右下角开始的，这种情况我是不是需要在计算四个点的时候加个180°？

3、以下附上我训练配置的一些参数和结果（使用的预训练模型）
![image](https://user-images.githubusercontent.com/43592362/173751824-77a82b03-49bf-43e9-ad9c-6e6c0963435f.png)
![labels_correlogram](https://user-images.githubusercontent.com/43592362/173752067-6384c2e1-a918-4548-8668-e2165efbce24.jpg)
![labels_xyls](https://user-images.githubusercontent.com/43592362/173752084-3c68443b-fb23-42ac-b7e6-93719de55947.jpg)
![P_curve](https://user-images.githubusercontent.com/43592362/173752125-91f82ca4-41e2-4241-8bee-7208c7a0b301.png)
![PR_curve](https://user-images.githubusercontent.com/43592362/173752139-b00f5110-fab0-435a-bdc7-c805ef130884.png)
![R_curve](https://user-images.githubusercontent.com/43592362/173752158-838a8a4f-7ff3-4af4-9d6e-5a5d9cd2ab06.png)
![results](https://user-images.githubusercontent.com/43592362/173752175-5c0e7a90-f361-402c-ba4e-116be981729d.png)
![train_batch0](https://user-images.githubusercontent.com/43592362/173752189-35218e57-6b83-4b17-a4d3-8a1c53478cd3.jpg)
![train_batch6](https://user-images.githubusercontent.com/43592362/173752221-04dd095f-aff6-4e88-8d5b-17d1c102f5fa.jpg)

配置如下：
![image](https://user-images.githubusercontent.com/43592362/173752256-ff5fee37-0fe6-49d1-9540-90e5c0b04d68.png)
![image](https://user-images.githubusercontent.com/43592362/173752318-acbe6499-4a87-47d3-b15c-5ab91f06d984.png)

**Comment by BandyKenny** [comment]
4、同时我提交一下我遇到的数据问题：
例如这一张图像，在voc格式下是这样的，但是转为DOTA后，取的点就从右下角开始算x1，y1了：
![00000012](https://user-images.githubusercontent.com/43592362/173752879-1d4ceab9-53e5-4b98-acf9-b9e1cfd61cca.jpg)
![image](https://user-images.githubusercontent.com/43592362/173752921-3c5044e6-9cdb-4c4b-a89d-7ed5eefc9dd5.png)
![image](https://user-images.githubusercontent.com/43592362/173752977-56c89aa9-1bc7-4be9-ae4b-fe8596b0ee76.png)
但是，例如这张图像，也是旋转框，但是是从左上角第一个开始顺时针的：
![00000509](https://user-images.githubusercontent.com/43592362/173753603-cf64aeb4-8e44-4eea-8a37-fafed1201d38.jpg)
![image](https://user-images.githubusercontent.com/43592362/173753633-0fa7fc90-589a-4cac-8a71-8f1a28529887.png)
![image](https://user-images.githubusercontent.com/43592362/173753659-c498f971-2b6d-45d1-a0cb-146b7358a453.png)
所以我在想是不是这个原因会导致模型效果这么差┭┮﹏┭┮

**Comment by monument-and-sea-all-the-gift** [comment]
用rolabelimg标注之后可以自己读取xml标签，作者数据集格式很清楚
classname xc yc longside shortside angle，自己转就行了，我自己整了，数据没错就是数据少了，效果也不是很好

**Comment by monument-and-sea-all-the-gift** [comment]
你这用的fintune，感觉遥感领域去fintune你的二维码肯定效果不好，而且你这才200张不到，效果好就怪了

**Comment by BandyKenny** [comment]
奥奥，感谢指导，您说的情况是有可能的；我最担心的就是转从DATO数据格式不一致导致的；
我是先用200张在原v5_6.0上用非旋转试了下效果还行，然后再用rolabelimg全部用旋转框进行标注进行的，发现map达不到0.4
后面我用了原v5里面的预训练模型，发现map有了提升，但是还是比较低，在0.4左右波动
后续我可能打算扩充数据集再来看看效果

**Comment by monument-and-sea-all-the-gift** [comment]
> 

作者您好，我用您的项目在自己数据集上训练（大物体，去掉了mosica），由于样本数量比较少，检测主要集中在角度上，我对图片进行了旋转增强，但是效果不是很好，改为以检测物体中心去旋转，效果虽然好点，但是仍然有漏框和错检的存在，目前数据集1000张，训练600轮，看损失已经收敛，置信度也很低，0.4左右，我该如何提升效果呢，希望得到回复，谢谢

**Comment by hukaixuan19970627** [comment]
> > 
> 
> 作者您好，我用您的项目在自己数据集上训练（大物体，去掉了mosica），由于样本数量比较少，检测主要集中在角度上，我对图片进行了旋转增强，但是效果不是很好，改为以检测物体中心去旋转，效果虽然好点，但是仍然有漏框和错检的存在，目前数据集1000张，训练600轮，看损失已经收敛，置信度也很低，0.4左右，我该如何提升效果呢，希望得到回复，谢谢

新开个issue

**Comment by hukaixuan19970627** [comment]
> > 
> 
> 哦哦，感谢指导，我按照思路改了下，将aug.py中的scale+1改为了1，减小了马赛克，P/R指标稳定了但只有0.4-0.6之间，map值还是比较低在0.35的样子，是不是数据太少了造成的😂

每次训练完有问题就再上传一次result.png

**Comment by BandyKenny** [comment]
【跟新】过来反馈啦，发现根据作者的建议，效果好了很多（我的数据集标注目标偏大，紧密性不大，和遥感数据有些区别），首先上一下结果：
![results](https://user-images.githubusercontent.com/43592362/173963560-0a66671c-c9bc-4de1-9864-39f6c896dc9f.png)
【改动1】其中，因为将aug.py中的scale+1改为了1，并且马赛克设置为了0~0.3之间，所谓我得train_batch.jpg变为了：
![train_batch2](https://user-images.githubusercontent.com/43592362/173963646-4f908cf0-df7f-4dc2-9ff0-a236b66b7f79.jpg)
【改动2】在训练过程中，将patient设置到了最大，同时按照作者的建议，将warmup_epochs改高一点，设为200
【改动3】增加了小样本数据集，这明显有了提升
下面放几张从验证集拿来的效果：
在非旋转图上表现良好
![00000013](https://user-images.githubusercontent.com/43592362/173963839-4141f15a-0c9c-432e-b26f-acc4d35721ac.jpg)
在旋转图上有些还行，可能需要继续扩充增广数据：
![00000320](https://user-images.githubusercontent.com/43592362/173963908-43a22a8d-fdd1-409f-a338-dfc39420e30c.jpg)
![00000377](https://user-images.githubusercontent.com/43592362/173963918-174c9008-9ebf-4519-95d2-583e5ed73e7f.jpg)
这张就是角度基本差了许多：
![00000012](https://user-images.githubusercontent.com/43592362/173963959-77c0d339-de81-4427-8001-c51da9e5b830.jpg)

**Comment by monument-and-sea-all-the-gift** [comment]
作者的dataset好像改了，label的格式都和之前不一样了，新版和旧版不兼容

**Comment by BandyKenny** [comment]
嗯嗯是的，用遥感格式的即可，不用转为Yolo格式了

**Comment by monument-and-sea-all-the-gift** [comment]
> 嗯嗯是的，用遥感格式的即可，不用转为Yolo格式了

我还得转回去，我试试新代码，就说怎么用旧数据集跑新代码跑不动

**Comment by monument-and-sea-all-the-gift** [comment]
> 嗯嗯是的，用遥感格式的即可，不用转为Yolo格式了

我这边转换出来的数据一直报错，不就是4个顶点+classname+diffcult，还有啥问题，画在图上也是对的

**Comment by monument-and-sea-all-the-gift** [comment]
> @BandyKenny 还有新的问题就照旧发一遍训练生成的文件，不然很难分析。
![image](https://user-images.githubusercontent.com/66421027/174021549-7da7ecd0-5f82-4024-9cc7-777d23b3404e.png)
兄弟，这种报错一般什么问题，谢谢

**Comment by BandyKenny** [comment]
@BandyKenny 还有新的问题就照旧发一遍训练生成的文件，不然很难分析。
image
兄弟，这种报错一般什么问题，谢谢
A:我也看不出来呀，感觉是你的样本标签没对（坐标超出范围？还是yolo转回来出问题？）

**Comment by BandyKenny** [comment]
【更新一个提高map方法】在ReadME中作者没有明确提出，但是下来自己尝试，确实有效果；就是数据集输入网络padding为一个正方形，这样网络里面resize基本当作无形变的，这样做的好处就是map我又提高了2个点的样子

**Comment by monument-and-sea-all-the-gift** [comment]
> 【更新一个提高map方法】在ReadME中作者没有明确提出，但是下来自己尝试，确实有效果；就是数据集输入网络padding为一个正方形，这样网络里面resize基本当作无形变的，这样做的好处就是map我又提高了2个点的样子

在yolov5就是这种处理方法，不过我切出来就是正方形，也无所谓了

**Comment by monument-and-sea-all-the-gift** [comment]
> @BandyKenny 还有新的问题就照旧发一遍训练生成的文件，不然很难分析。 image 兄弟，这种报错一般什么问题，谢谢 A:我也看不出来呀，感觉是你的样本标签没对（坐标超出范围？还是yolo转回来出问题？）

感觉是磁盘问题，我训练自己数据集，map才0.65

**Comment by monument-and-sea-all-the-gift** [comment]
> 【更新一个提高map方法】在ReadME中作者没有明确提出，但是下来自己尝试，确实有效果；就是数据集输入网络padding为一个正方形，这样网络里面resize基本当作无形变的，这样做的好处就是map我又提高了2个点的样子

精度召回和map都提升上来了，到0.9左右了，不知道预测效果如何

**Comment by IsenLwww** [comment]
> resize

请问您说的数据集输入网络padding为一个正方形是怎么进行更改的呢？哪个文件呢

**Comment by IsenLwww** [comment]
> 【更新一个提高map方法】在ReadME中作者没有明确提出，但是下来自己尝试，确实有效果；就是数据集输入网络padding为一个正方形，这样网络里面resize基本当作无形变的，这样做的好处就是map我又提高了2个点的样子

请问您说的数据集输入网络padding为一个正方形是怎么进行更改的呢？哪个文件呢
