### ISSUE TITLE
about custom  dataset train 

### ISSUE THREAD

**Issue by monument-and-sea-all-the-gift** [hukaixuan19970627/yolov5_obb#368]
作者您好，我用您的项目在自己数据集上训练（大物体，去掉了mosica），由于样本数量比较少，检测主要集中在角度上，我对图片进行了旋转增强，但是效果不是很好，改为以检测物体中心去旋转，效果虽然好点，但是仍然有漏框和错检的存在，目前数据集1000张，训练600轮，看损失已经收敛，置信度也很低，0.4左右，我该如何提升效果呢，希望得到回复，谢谢

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/173768425-a1ffda53-3d37-42c7-b08e-4235b97631a6.png)
提供一下上述文件内容的截图

**Comment by monument-and-sea-all-the-gift** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/173768425-a1ffda53-3d37-42c7-b08e-4235b97631a6.png) 提供一下上述文件内容的截图

感谢回复，过拟合了，我看看除了扩充数据，还有什么办法

**Comment by monument-and-sea-all-the-gift** [comment]
![image](https://user-images.githubusercontent.com/66421027/173787685-9255d49f-3827-42e9-9a8a-1093f3cb3693.png)
损失曲线这样应该没问题吧

**Comment by hukaixuan19970627** [comment]
建议更新代码后，再复现一遍这个问题，然后提供一下上述文件
