### ISSUE TITLE
DLL load failed while importing nms_rotated_ext: 找不到指定的模块。

### ISSUE THREAD

**Issue by ZhangChaoZhong** [hukaixuan19970627/yolov5_obb#369]
![图片](https://user-images.githubusercontent.com/30583522/174001898-7a82fb15-db33-4a82-8858-22d1aaca74fd.png)
生成好了nms_rotated_ext.;pyd，运行train.py。却报错了，ImportError: DLL load failed while importing nms_rotated_ext: 找不到指定的模块。
![图片](https://user-images.githubusercontent.com/30583522/174011046-4b283b58-7cd3-47d0-8de6-473cf8114392.png)
麻烦哪位大佬指点下，谢谢。

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/174019829-f9201b8b-c43a-487f-a724-f4b6bba1f3ce.png)

**Comment by guanxuefeng** [comment]
> ![图片](https://user-images.githubusercontent.com/30583522/174001898-7a82fb15-db33-4a82-8858-22d1aaca74fd.png) 生成好了nms_rotated_ext.;pyd，运行train.py。却报错了，ImportError: DLL load failed while importing nms_rotated_ext: 找不到指定的模块。 ![图片](https://user-images.githubusercontent.com/30583522/174011046-4b283b58-7cd3-47d0-8de6-473cf8114392.png) 麻烦哪位大佬指点下，谢谢。

请问您解决了吗，我也是和您一样的问题

**Comment by liuxt2002** [comment]
> > ![图片](https://user-images.githubusercontent.com/30583522/174001898-7a82fb15-db33-4a82-8858-22d1aaca74fd.png) 生成好了nms_rotated_ext.;pyd，运行train.py。却报错了，ImportError: DLL load failed while importing nms_rotated_ext: 找不到指定的模块。 ![图片](https://user-images.githubusercontent.com/30583522/174011046-4b283b58-7cd3-47d0-8de6-473cf8114392.png) 麻烦哪位大佬指点下，谢谢。
> 
> 请问您解决了吗，我也是和您一样的问题

请问您解决了吗，可以告诉我您是怎么解决的吗

**Comment by hecheng000** [comment]
你好 请问解决了吗

**Comment by hecheng000** [comment]
> > > ![图片](https://user-images.githubusercontent.com/30583522/174001898-7a82fb15-db33-4a82-8858-22d1aaca74fd.png) 生成好了nms_rotated_ext.;pyd，运行train.py。却报错了，ImportError: DLL load failed while importing nms_rotated_ext: 找不到指定的模块。 ![图片](https://user-images.githubusercontent.com/30583522/174011046-4b283b58-7cd3-47d0-8de6-473cf8114392.png) 麻烦哪位大佬指点下，谢谢。
> > 
> > 
> > 请问您解决了吗，我也是和您一样的问题
> 
> 请问您解决了吗，可以告诉我您是怎么解决的吗

你好 解决了吗

**Comment by lhehejunl** [comment]
> ![图片](https://user-images.githubusercontent.com/30583522/174001898-7a82fb15-db33-4a82-8858-22d1aaca74fd.png) 生成好了nms_rotated_ext.;pyd，运行train.py。却报错了，ImportError: DLL load failed while importing nms_rotated_ext: 找不到指定的模块。 ![图片](https://user-images.githubusercontent.com/30583522/174011046-4b283b58-7cd3-47d0-8de6-473cf8114392.png) 麻烦哪位大佬指点下，谢谢。

你这个问题我遇到了，我当时下载的torch是cpu版本，然后运行python setup.py develop后，去训练。报了这个错，我就改了带cuda的torch版本，是torch-1.7.0+cu110，torchvision也是一样0.8.1+cu110，然后训练就能正常训练了。前提是你先看看issue里面有个标题是windows下的踩坑记录那个里面的内容。希望能帮到你。
