### ISSUE TITLE
Yolov5_obb size?

### ISSUE THREAD

**Issue by wafa-bouzouita** [hukaixuan19970627/yolov5_obb#371]
Hello,

Could you please tell me where in the code we can specify the size of yolov5_obb model ? (yolov5s, yolov5m ..)

Thank you

**Comment by hukaixuan19970627** [comment]
Same as [yolov5](https://github.com/ultralytics/yolov5)
![image](https://user-images.githubusercontent.com/72599120/174228975-dd31c39d-61e1-46f6-9896-923594a1854d.png)
