### ISSUE TITLE
窗口函数

### ISSUE THREAD

**Issue by zhanguser0614** [hukaixuan19970627/yolov5_obb#372]
大佬，关于解决旋转框的ClS圆滑标签的那篇论文我看了，大佬这里是直接用的高斯窗口函数吗？如果我想用三角函数需要修改哪些参数呢，还是说自己在写个关于三角窗口函数的模块

**Comment by hukaixuan19970627** [comment]
可以直接参考：https://github.com/Thinklab-SJTU/CSL_RetinaNet_Tensorflow

**Comment by zhanguser0614** [comment]
谢谢大佬
