### ISSUE TITLE
csl对比

### ISSUE THREAD

**Issue by zhanguser0614** [hukaixuan19970627/yolov5_obb#374]
![image](https://user-images.githubusercontent.com/94903297/174256837-9f6b7cc1-700b-4e1b-8865-ff108e2cec6c.png)
大佬我刚刚拜读了你的知乎专栏，现在我想知道添加csl前后的效果如何，不过你的专栏和现版本的代码不匹配，我没找到对应的代码段。那么在新版本的代码中，大佬是通过csl_label_flag控制是否添加cls吗，还是通过其他的办法呢

**Comment by hukaixuan19970627** [comment]
新版本不支持切换CSL。
