### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by buzhijinxi** [hukaixuan19970627/yolov5_obb#376]
is:issue is:open 作者你好 我想请问一下 yolov5能做这个序列影像的目标跟踪吗 我之前也是用的DOTA数据集实现了目标检测 但是该方法好像在序列影像中对于运动目标的检测效果很差

**Comment by hukaixuan19970627** [comment]
没明白，你能配合可视化图片复现一下你说的情况吗，如果静态图像yolov5_obb检测没问题的话，那动态影像的目标跟踪肯定也是没问题的

**Comment by buzhijinxi** [comment]
第一个是用DOTA数据集得到的检测结果 然后我用自己的数据的时候效果就很差
在检测第二个视频中的对象时 基本上完全检测不到&nbsp;
大概意思就是这样


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hukaixuan19970627/yolov5_obb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月23日(星期四) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hukaixuan19970627/yolov5_obb] 求助 (Issue #376)





 
没明白，你能配合可视化图片复现一下你说的情况吗，如果静态图像yolov5_obb检测没问题的话，那动态影像的目标跟踪肯定也是没问题的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

P0185.png (17.61M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=0c6631322e0bd0986a1889521330044956020203070353071f050351011d02030b051c530d04024b00050953020501565407005735393636025709071b405801325b&t=exs_ftn_download&code=2f12506f




001.mp4 (314.5K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=0e3837628f77cbc96a468f024462021957590051005205031f0b0354534f0406510a1a035757521b030c01535452010053095552626530060209190f1256300b&t=exs_ftn_download&code=287bbb06

**Comment by hukaixuan19970627** [comment]
从你的表述来看，你是利用dota数据集训练得到了一个网络模型，然后利用该模型检测自制数据集的静态图像时发现检测效果很差，然后利用该模型检测视频时效果依然很差，是这样没错吧。
dota数据集的复杂度还没到接近真实世界的程度，所以泛化性不强，如果自制数据集的分布和dota相差太远，检测效果差是正常现象

**Comment by buzhijinxi** [comment]
对的，大概就是这个意思。所以我想请问一下，yolov5有具备检测并跟踪卫星序列影像中的动态目标吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月27日(星期一) 下午3:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hukaixuan19970627/yolov5_obb] 求助 (Issue #376)





 
从你的表述来看，你是利用dota数据集训练得到了一个网络模型，然后利用该模型检测自制数据集的静态图像时发现检测效果很差，然后利用该模型检测视频时效果依然很差，是这样没错吧。
 dota数据集的复杂度还没到接近真实世界的程度，所以泛化性不强，如果自制数据集的分布和dota相差太远，检测效果差是正常现象

**Comment by hukaixuan19970627** [comment]
目标检测和目标跟踪是两个概念，不过前者是基础。yolov5是一个目标检测算法，想通过它实现跟踪效果就必须搭配sort类型算法一起使用

**Comment by buzhijinxi** [comment]
好的 谢谢解惑 感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hukaixuan19970627/yolov5_obb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月17日(星期天) 下午5:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hukaixuan19970627/yolov5_obb] 求助 (Issue #376)





 
目标检测和目标跟踪是两个概念，不过前者是基础。yolov5是一个目标检测算法，想通过它实现跟踪效果就必须搭配sort类型算法一起使用
