### ISSUE TITLE
val.py question &  Reproduce checkpoint

### ISSUE THREAD

**Issue by tinly00** [hukaixuan19970627/yolov5_obb#377]
hello, 我在运行demo成功后，重新用作者的yolov5m_finetune的权重生成dota数据集适用的权重时，runs/val/datav15_test_split文件夹下并没有json和txt文件, 但是提交到dota官网的.zip文件夹要求需要有txt。

看dota官网那个提交页面是有task1和task2，但是运行完val.py后并没有两个task。
![37](https://user-images.githubusercontent.com/93133444/175046505-3d26eb32-15b5-402c-8d42-ec14d57706d9.png)
这里写着包含txt format.

我实现下载好dota1.5数据集后，按作者要求数据集格式分级存放，并进行图像分割后，开始对应read.md进行操作：

我根据下面read.md操作：
![32](https://user-images.githubusercontent.com/93133444/175042678-45fa26d6-fb13-41c5-8b7e-1d5bb5eaadbf.png)

修改val.py:
![33](https://user-images.githubusercontent.com/93133444/175042826-7ad2d415-2fda-43c6-a31d-8ef5cd3f49cc.png)

修改 tools/TestJson2VocClassTxt.py：
![34](https://user-images.githubusercontent.com/93133444/175042938-001de4ef-0d32-40f3-bd01-a06e70e81407.png)

修改DOTA_devkit/ResultMerge_multi_process.py：
![35](https://user-images.githubusercontent.com/93133444/175043153-2bfb758d-5430-4b6b-98be-a79e70943aaf.png)

但是我在修改val.py中的--save_json时，运行val.py,报错：
```
Traceback (most recent call last):
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/val.py", line 405, in <module>
    opt = parse_opt()
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/val.py", line 357, in parse_opt
    parser.add_argument('--save-json', action='dotav15_test_split', help='save a COCO-JSON results file')
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/argparse.py", line 1352, in add_argument
    raise ValueError('unknown action "%s"' % (action_class,))
ValueError: unknown action "dotav15_test_split"
```

将val.py中--save_json修改为默认后，可以运行，但是运行结果中没有json文件和txt文件，只有labels和pred的jpg和png文件：

![36](https://user-images.githubusercontent.com/93133444/175044117-0d4dc402-3f22-4f9e-8c8e-407908bfeac3.png)

confusion_matrix:
![confusion_matrix](https://user-images.githubusercontent.com/93133444/175044214-c4d1837a-f8f3-43a5-9150-ed3973120ddf.png)

val_batch0_labels:
![val_batch0_labels](https://user-images.githubusercontent.com/93133444/175044238-a6f46c06-bb87-4ec7-a6f8-d1df72a99872.jpg)

val_batch0_pred:
![val_batch0_pred](https://user-images.githubusercontent.com/93133444/175044252-7af5736e-d41c-48b5-aa53-6c5e509b5779.jpg)

val_batch1_labels:
![val_batch1_labels](https://user-images.githubusercontent.com/93133444/175044278-af2f4d66-47ba-4de8-b15e-8a4b5af8e649.jpg)

val_batch1_pred:
![val_batch1_pred](https://user-images.githubusercontent.com/93133444/175044288-c138f946-778f-4d21-a1da-aabb8c55a85a.jpg)

val_batch2_labels:
![val_batch2_labels](https://user-images.githubusercontent.com/93133444/175044303-ab9cd621-5df1-41f2-abe8-0cd0b5c18eac.jpg)

val_batch2_pred:
![val_batch2_pred](https://user-images.githubusercontent.com/93133444/175044328-61e1fde7-5a02-418a-84d1-f53e9ac1ef1c.jpg)

请问是哪里出问题了呢？如果您能抽空回答，非常感谢！！
@hukaixuan19970627

**Comment by hukaixuan19970627** [comment]
请使用命令行运行readme中的命令

**Comment by tinly00** [comment]
> 请使用命令行运行readme中的命令
好的谢谢！
