### ISSUE TITLE
训练过程中map、recall、precision为0

### ISSUE THREAD

**Issue by FlinkRay** [hukaixuan19970627/yolov5_obb#378]
训练过程中map、recall、precision为0，用的是自制的舰船数据集，类别为7，其他的配置没有改过
![results](https://user-images.githubusercontent.com/39163544/175080699-e6d299e4-ea59-4c2f-8adf-a35bdf6d1d40.png)

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/175250535-aaef7ed2-216b-40b7-aca6-20a27155ff71.png)
将上述选定文件截图发上来，看看你的训练情况。
另外再详细介绍一下你所使用的数据集（例如规模，图像分辨率）。

**Comment by FlinkRay** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/175250535-aaef7ed2-216b-40b7-aca6-20a27155ff71.png) 将上述选定文件截图发上来，看看你的训练情况。 另外再详细介绍一下你所使用的数据集（例如规模，图像分辨率）。

![image](https://user-images.githubusercontent.com/39163544/175251557-e08bfc60-64de-4966-a4d5-18ce98964435.png)
![image](https://user-images.githubusercontent.com/39163544/175251636-5e7de20e-8f62-439d-a182-89856765d474.png)
![labels_correlogram](https://user-images.githubusercontent.com/39163544/175251763-1f11ec32-93a7-4a37-91ce-7008e67cbca7.jpg)
![labels_xyls](https://user-images.githubusercontent.com/39163544/175251789-6359b74c-a8d6-4d85-bcba-55e2090e7c01.jpg)
![results](https://user-images.githubusercontent.com/39163544/175251883-eb99b354-9283-4891-978f-7090045f0bae.png)
![train_batch0](https://user-images.githubusercontent.com/39163544/175251946-7f985f7f-1186-4c6e-8f17-f4a442f9f327.jpg)
![train_batch1](https://user-images.githubusercontent.com/39163544/175251969-1e3d3381-ee01-4212-983d-2b1b507b2ea2.jpg)
![train_batch2](https://user-images.githubusercontent.com/39163544/175251995-10c06052-c850-4e77-acbb-11aff149ce89.jpg)
![train_batch3](https://user-images.githubusercontent.com/39163544/175252015-cf86c3e5-368d-4268-9b3b-910126ea1f36.jpg)
![val_batch0_labels](https://user-images.githubusercontent.com/39163544/175252080-98099115-f532-46ea-9a7b-f2f19d6d3747.jpg)
![val_batch0_pred](https://user-images.githubusercontent.com/39163544/175252104-bae66d6e-0f33-46a9-b2a4-aae7c0e434a0.jpg)
数据集规模882是切割之后的，分辨率为1024x1024

**Comment by hukaixuan19970627** [comment]
底下的可视化图片不清晰，发原图过来，似乎labels都是错的

**Comment by FlinkRay** [comment]
> 底下的可视化图片不清晰，发原图过来，似乎labels都是错的
原图也是这样看不清

**Comment by FlinkRay** [comment]
> 底下的可视化图片不清晰，发原图过来，似乎labels都是错的
您指的是人工打标签的时候没框对位置？

**Comment by FlinkRay** [comment]
> > 底下的可视化图片不清晰，发原图过来，似乎labels都是错的
> > 您指的是人工打标签的时候没框对位置？
> > 但也不可能都不正确吧



> 底下的可视化图片不清晰，发原图过来，似乎labels都是错的

不好意思，之前看错了，数据集大小是221，在训练过程中也一直显示0
![image](https://user-images.githubusercontent.com/39163544/175266603-9c295895-bc1b-4fd2-bdf6-952933d1b583.png)

**Comment by FlinkRay** [comment]
> 底下的可视化图片不清晰，发原图过来，似乎labels都是错的

确实是label的问题，因为标注的时候是jpg格式，但是要分割必须为png格式，我转换了一下，图片分辨率应该变了，导致label错了。请问有什么办法分割jpg格式的图片吗

**Comment by hukaixuan19970627** [comment]
1. trainbatch图片表示训练原始图像经数据增强后的可视化效果。
2. 把分割程序的读取格式改成jpg，或者利用脚本先读取jpg格式的图片再另存为png格式
3. 建议先训练dota数据集复现一下readme中的表格结果再尝试自制数据集

**Comment by FlinkRay** [comment]
> 1. trainbatch图片表示训练原始图像经数据增强后的可视化效果。
> 2. 把分割程序的读取格式改成jpg，或者利用脚本先读取jpg格式的图片再另存为png格式
> 3. 建议先训练dota数据集复现一下readme中的表格结果再尝试自制数据集

谢谢，我已经成功训练了

**Comment by wind-seed** [comment]
我也出现这个问题，但是我不知道您所说的这些是什么意思，我用的是DOTA2自己分割后的数据集，请问该怎么解决呢

**Comment by wind-seed** [comment]
> 我也出现这个问题，但是我不知道您所说的这些是什么意思，我用的是DOTA2自己分割后的数据集，请问该怎么解决呢

使用您原始配的那个P0032的图片跑，训练过程中map、recall、precision为0

**Comment by 123Liyanxi** [comment]
> > 我也出现这个问题，但是我不知道您所说的这些是什么意思，我用的是DOTA2自己分割后的数据集，请问该怎么解决呢
> 
> 使用您原始配的那个P0032的图片跑，训练过程中map、recall、precision为0

我也是，自己的数据集是用的tif图片跑的，也是label为零，准确率为零，其他都没什么问题

**Comment by 123Liyanxi** [comment]
> > 1. trainbatch图片表示训练原始图像经数据增强后的可视化效果。
> > 2. 把分割程序的读取格式改成jpg，或者利用脚本先读取jpg格式的图片再另存为png格式
> > 3. 建议先训练dota数据集复现一下readme中的表格结果再尝试自制数据集
> 
> 谢谢，我已经成功训练了

想问一下您怎么训练成功的啊
