### ISSUE TITLE
RuntimeError in validation step: Not compiled with GPU support

### ISSUE THREAD

**Issue by blue-sky54** [hukaixuan19970627/yolov5_obb#379]
Hi there, Thank you for sharing your code. 
I want to run your code on Colab with my custom dataset and I get an error in training. 
```RuntimeError: Not compiled with GPU support```

I followed the instruction in this video.
https://www.youtube.com/watch?v=iRkCNo9-slY

**Comment by hukaixuan19970627** [comment]
[Install requirements](https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/install.md)
[Check requirements](https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/GetStart.md)

**Comment by elahe-badali** [comment]
![Uploading image.png…]()

Hi @hukaixuan19970627 
Unfortunately, I'm stuck in this step for 2 weeks. Could you help me to run the code?

**Comment by hukaixuan19970627** [comment]
Delete nms_rotated_ext.cpython-39-x86_64-linux-gnu.so and install yolov5_obb again.
![image](https://user-images.githubusercontent.com/72599120/179392308-533afee3-234e-401a-b26d-3ecc45704acd.png)
