### ISSUE TITLE
Train.py question and mAP can not improveed during trainning 

### ISSUE THREAD

**Issue by tinly00** [hukaixuan19970627/yolov5_obb#380]
我使用自己的数据集训练出现了以下问题，想请教一下：
训练数据集320张左右，数据集建立的是单类、大目标识别，因此没有进行分割，demo已经跑通，下载了作者的权重后，使用作者的权重进行训练，效果并不好：
将patience改300后，epoch300进行训练，结果是mAP越训练越低：

![results](https://user-images.githubusercontent.com/93133444/175243938-555e9039-6fd4-4cd3-860f-ab06f4547827.png)

hyp:
```
lr0: 0.01
lrf: 0.2
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.05
cls: 0.5
cls_pw: 1.0
theta: 0.5
theta_pw: 1.0
obj: 1.0
obj_pw: 1.0
iou_t: 0.2
anchor_t: 4.0
fl_gamma: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 180.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.5
fliplr: 0.5
mosaic: 0.95
mixup: 0.1
copy_paste: 0.0
cls_theta: 180
csl_radius: 2.0
```
opt.yaml :
```
weights: /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/runs/train/exp19/weights/best.pt
cfg: ''
data: data/dotav15_poly.yaml
hyp: data/hyps/obb/hyp.finetune_dota.yaml
epochs: 100
batch_size: 4
imgsz: 1024
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp20

```

![labels_correlogram](https://user-images.githubusercontent.com/93133444/175241463-4716dae0-a981-4cc3-8d81-

![labels_xyls](https://user-images.githubusercontent.com/93133444/175241515-c002cefc-73f2-4714-91ff-f5d11257c78f.jpg)

![confusion_matrix](https://user-images.githubusercontent.com/93133444/175241537-12fff832-84f6-4c95-8d73-5904a3870478.png)

![F1_curve](https://user-images.githubusercontent.com/93133444/175241572-0e44edd2-a4ac-42b2-a6eb-82c87b037935.png)

![P_curve](https://user-images.githubusercontent.com/93133444/175241604-6fce3c8e-88ce-4c9c-8247-f738a133136f.png)

![PR_curve](https://user-images.githubusercontent.com/93133444/175241621-f1b5f700-d5f5-429d-889a-87136fdf15d7.png)

![R_curve](https://user-images.githubusercontent.com/93133444/175241635-b0f3f6aa-2650-4797-8042-cd3ec986331f.png)

train_batch0
![train_batch0](https://user-images.githubusercontent.com/93133444/175241703-95d685c0-1e49-4138-a7ef-e1011e7ae4bf.jpg)

train_batch1
![train_batch1](https://user-images.githubusercontent.com/93133444/175241767-4d42f243-877f-42fc-890e-72c90f2610b5.jpg)

train_bach2
![train_batch2](https://user-images.githubusercontent.com/93133444/175241814-4c6751de-4b08-48cf-a45a-4f8e42c59853.jpg)

val_batch0_labels
![val_batch0_labels](https://user-images.githubusercontent.com/93133444/175242044-6b7b8f50-6187-4c3d-af6a-9e8cb4d56471.jpg)

val_batch0_pred
![val_batch0_pred](https://user-images.githubusercontent.com/93133444/175242115-bf56429e-2681-4bf5-8fd2-133795f3b186.jpg)

val_batch1_labels
![val_batch1_labels](https://user-images.githubusercontent.com/93133444/175242162-1b930bfe-d54f-41cc-a2e5-f4bbf9bedcdf.jpg)

val_batch1_pred
![val_batch1_pred](https://user-images.githubusercontent.com/93133444/175242230-cd33d9c1-7779-4ed0-a087-6be239853ae9.jpg)

问题：
1  在val_batch_pred 可视化中，识别率非常低，漏检测很多，而且检测框和不准，请问需要怎么改进？
2  在此基础上再训练了100个epoch，发现训练mAP越来越低：
![results](https://user-images.githubusercontent.com/93133444/175244510-72bb8ca8-0711-4a99-b6f1-64f9debbb70b.png)
请问如何改进？谢谢！
@hukaixuan19970627  @monument-and-sea-all-the-gift  @BandyKenny

**Comment by monument-and-sea-all-the-gift** [comment]
根据场景来选择数据增强方式，如果是单图上面有多个检测物体，可以加mosaic和mixup，单张只有单个目标物体，我感觉不需要，你这class_num设置的几啊

**Comment by hukaixuan19970627** [comment]
finetune的话学习率设置为0.01就太高了，精度越来越低可以考虑一下是不是学习率设置的不对，warmup_epochs参数调高一点试试看。（可以参考下这个[issue](https://github.com/hukaixuan19970627/yolov5_obb/issues/367)）

**Comment by tinly00** [comment]
> 根据场景来选择数据增强方式，如果是单图上面有多个检测物体，可以加mosaic和mixup，单张只有单个目标物体，我感觉不需要，你这class_num设置的几啊

我只有一个类别，但是单类会出问题，所以加了一个空类，class_num=1, 其中rec是要识别的箱子，none是加的空的类

**Comment by tinly00** [comment]
> finetune的话学习率设置为0.01就太高了，精度越来越低可以考虑一下是不是学习率设置的不对，warmup_epochs参数调高一点试试看。（可以参考下这个[issue](https://github.com/hukaixuan19970627/yolov5_obb/issues/367)）

请问学习率设置一般需要改多少比较合适呢？从0.01改一个数量级，改为0.001会太小吗？warmup epoch 我调高为250可以吗？

**Comment by tinly00** [comment]
> 
来反馈更新啦，根据作者的建议，修改学习率和warmup_epochs后、并将mosaic关掉后，效果有大提升了，谢谢！！
![results](https://user-images.githubusercontent.com/93133444/175528277-3c9ad498-1015-4627-8a0e-88534f625c66.png)

**Comment by tinly00** [comment]
> 
来反馈更新啦，根据作者的建议，修改学习率和warmup_epochs后、并将mosaic关掉后，效果有大提升了，谢谢！！
![results](https://user-images.githubusercontent.com/93133444/175528277-3c9ad498-1015-4627-8a0e-88534f625c66.png)

**Comment by tinly00** [comment]
> > 
> 
> 来反馈更新啦，根据作者的建议，修改学习率和warmup_epochs后、并将mosaic关掉后，效果有大提升了，谢谢！！ ![results](https://user-images.githubusercontent.com/93133444/175528277-3c9ad498-1015-4627-8a0e-88534f625c66.png)

reset  hyp.finefune_dota.yaml:
epoch 100; warmup_epoch: 250; mosaic 0

**Comment by huanghaifeng1234** [comment]
> > >
> 
> reset hyp.finefune_dota.yaml: epoch 100; warmup_epoch: 250; mosaic 0
你好，我也是发现也训练越差，box loss 基本不变，是因为learning rate，太大了吗？你的learning ratio设置的多少呢。如果只有一个类别应该如何修改呢，将class_num设为2，然后把类别标签都设置为1吗

**Comment by tinly00** [comment]
lr0改成了0.001，class_num是设了2，后面填标签名称时候第一个填目标类名称，第二个随便填一个名称。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月27日 13:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [hukaixuan19970627/yolov5_obb] Train.py question and mAP can not improveed during trainning (Issue #380) |

reset hyp.finefune_dota.yaml: epoch 100; warmup_epoch: 250; mosaic 0

你好，我也是发现也训练越差，box loss 基本不变，是因为learning rate，太大了吗？你的learning ratio设置的多少呢。如果只有一个类别应该如何修改呢，将class_num设为2，然后把类别标签都设置为1吗
