### ISSUE TITLE
运行Demo中train,val中的问题

### ISSUE THREAD

**Issue by ddcpowerone** [hukaixuan19970627/yolov5_obb#381]
您好，和您请教在运行您代码中遇到的一些问题。
系统:20.04  pytorch:11.3   model：yolov5m 基本配置都是按照install.md中进行的，安装后开始运行demo，将图片进行了分割：
cd yolov5_obb
python DOTA_devkit/ImgSplit_multi_process.py
python train.py  --weights 'weights/yolov5m.pt' --data 'data/yolov5obb_demo_split.yaml' --hyp 'data/hyps/obb/hyp.finetune_dota.yaml' --epochs 10 --batch-size 2 --img 1024 --device 0
**均未进行程序修改**
![train](https://user-images.githubusercontent.com/49668436/175235268-1a7d96f6-7f97-4373-8ca6-17f75f448a49.png)
![results](https://user-images.githubusercontent.com/49668436/175237090-b5a229a3-07b9-4c5a-ad9d-1902f35301be.png)

**1.这个“labels P R mAP”都是0，不知道是否正确？**

------------------------------------------------------
运行：python val.py \
 --data 'data/yolov5obb_demo_split.yaml' \
 --weights 'runs/train/yolov5m_csl_dotav1.5/weights/best.pt' \
 --batch-size 2 --img 1024 --task 'val' --device 0 --save-json --name 'obb_demo_split'
![val](https://user-images.githubusercontent.com/49668436/175238153-0624eb4b-d6df-4ab4-be2c-74f743b5239b.png)
**2.感觉这个结果就明显和您截取的结果不一样了，不知道问题出在了哪里？**

--------------------------------------------------------
![dota_devkit](https://user-images.githubusercontent.com/49668436/175244379-d4dcf99e-f434-46a3-8316-bd7abf8cc729.png)
**3在运行图片拼接融合后，报"ModuleNotFoundError: No module named 'DOTA_devkit'"**

--------------------------------------------------------
![2022-06-23 15-48-46屏幕截图](https://user-images.githubusercontent.com/49668436/175245389-d86b4f3b-e75a-478e-91fc-d17bf83dd9a2.png)
**4.最后运行了detect.py，感觉还是有问题**

非常感谢您的贡献，请您帮忙看看，自己在demo的过程很痛苦，反复多次测试还是没有结果。感谢您帮忙看看，用的是您新的版本。

**Comment by ddcpowerone** [comment]
您好，所属的别的问题您有出现吗？

**Comment by ddcpowerone** [comment]
> 
> 我和你遇到问题一样，map、recall都为0

您好，所述的别的问题您有出现吗？不知道自己弄的是哪里出问题了

**Comment by FlinkRay** [comment]
> > 我和你遇到问题一样，map、recall都为0
> 
> 您好，所述的别的问题您有出现吗？不知道自己弄的是哪里出问题了

其他的问题我还没有测试过，只是训练了

**Comment by ddcpowerone** [comment]
> 1. train.py 的demo精度为0是正常现象，demo只是花最短的时间展示一下训练流程而已。
> 2. getstart.md中的其它结果是可以复现的，测试时你要下载我提供的DOTA数据集的权重（而不是demo中训练了10个epoch的权重）。
> 3. DOTA_devkit是一个文件夹，你的系统不能将其导入为包，这个只能你自己解决。
> 4. --device 2 的含义是在第三块GPU上运行程序。

-------------------------------------------
**### 非常感谢！您回复的太及时啦！刚刚调试好了demo**

**| 1，不在进行关注了
| 2，主要是要下载提供的权重
| 3，import dota_utils as util
         import polyiou as polyiou
| 4，确是在device 0 就可以啦**

![1](https://user-images.githubusercontent.com/49668436/175300448-4483d565-3fdf-4e7c-9038-5b7dd07b4bbb.png)
![2](https://user-images.githubusercontent.com/49668436/175300458-0ff8e6de-11ac-48fd-a44f-bdbcdc2beac0.png)

非常感谢！继续抓紧学习！
