### ISSUE TITLE
关于nc为1训练的问题

### ISSUE THREAD

**Issue by 1343744768** [hukaixuan19970627/yolov5_obb#382]
大佬，yolov5的正框是支持nc=1训练的，但是在跑你的代码时，nc=1时，cls_loss为0是正常的，但是会出现boxloss不收敛的情况，想请教一下这是为啥，看了您的源码，在计算损失时我觉得没啥问题，也有关于nc>1时才计算cls损失。至于您知乎给出nc=2可以收敛的解决方法，nc=2确实可以收敛，但是实测效果不好。就比如我我要检测大船和小船两类，第一次实验，我的标签确实是两类，然后nc=2去训练的。第二次，我将大小船标签合并当成一类训练，并且nc还是为2，但是实测的话效果不如第一次好，有些就会检测不到目标，框的回归也没有第一次准了。我理解的是，当nc=2时训练单类目标，置信度损失和边框损失都受到了影响，但是实在找不到问题出在哪。

**Comment by hukaixuan19970627** [comment]
我也找不到原因。

**Comment by huanghaifeng1234** [comment]
@1343744768 我也是单类别检测，发现box loss没有变化，请问什么样的方法最有效呢，你的learning rate， box, cls, obj loss weight, 这些超参数是如何设置的呢？

**Comment by 1343744768** [comment]
> @1343744768 我也是单类别检测，发现box loss没有变化，请问什么样的方法最有效呢，你的learning rate， box, cls, obj loss weight, 这些超参数是如何设置的呢？

使用adam优化器，zhe'y这一项改完0.005，训练的单类模型可以拟合的比较好
![image](https://user-images.githubusercontent.com/79694861/177079140-3461aa5e-dcd8-4084-852d-6c0295f8996a.png)

**Comment by 1343744768** [comment]
另外，修改下yolohead效果还能高个几个点，改成类似retinanet那种，分类回归，和角度分类用三个卷积各自卷

**Comment by huanghaifeng1234** [comment]
请问可以共享一下修改yolohead的代码吗，万分感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月4日(周一) 中午12:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 关于nc为1训练的问题 (Issue #382)




 
另外，修改下yolohead效果还能高个几个点，改成类似retinanet那种，分类回归，和角度分类用三个卷积各自卷
