### ISSUE TITLE
val.py

### ISSUE THREAD

**Issue by zhanguser0614** [hukaixuan19970627/yolov5_obb#383]

**Comment by zhanguser0614** [comment]
我想请教一下val.py输出得文件夹里有个predict图片，这是预测的图片么，这个和detect输出的图片有什么不同呢，我发现val输出得预测图片里面的框的置信度值保留了一位小数，detect输出得有两位小数，那么这个val的怎么也弄成两位小数呀

**Comment by hukaixuan19970627** [comment]
val.py主要用于评估数据集的各项性能指标，生成的图片中带有gt字样的是经数据增强后的原图及其labels，带有pred字样的则是对应图片的模型预测结果。
detect.py顾名思义就是实现模型的前向推理过程，可以对图片/视频等输入文件进行预测。
