### ISSUE TITLE
Custom Dataset training

### ISSUE THREAD

**Issue by JTGiser** [hukaixuan19970627/yolov5_obb#386]
![image](https://user-images.githubusercontent.com/23622889/175926193-c76237fc-96c4-4a09-a5ab-bb4db6318a81.png)

![image](https://user-images.githubusercontent.com/23622889/175926310-d1dfa82d-5e9b-46c4-a821-5e586a601401.png)

您好，请问下，我用自定义的数据集进行训练，只有一个分类(car)。上面是自定义标注的样本数据，下面是用样本数据预测的结果。发现预测的结果，好像整体进行了旋转，请问是什么原因造成的？应该怎么解决？谢谢

**Comment by JTGiser** [comment]
第一张图是val_batch0_labels.jpg，第二张图是val_batch0_pred.jpg

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/179392666-28bb8dc7-84f7-4b43-81d5-08ef9decadfe.png)
将上述选定文件截图发上来，看看你的训练情况。
另外再详细介绍一下你所使用的数据集（例如规模，图像分辨率）。
