### ISSUE TITLE
RuntimeWarning: invalid value encountered in subtract

### ISSUE THREAD

**Issue by yuanzhougege** [hukaixuan19970627/yolov5_obb#387]
Validating runs\train\exp9\weights\best.pt...
Fusing layers... 
Model Summary: 213 layers, 7500979 parameters, 0 gradients, 17.4 GFLOPs
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   5%|▍         | 2/42 [00:02<00:53,  1.34s/it]E:\python_xiaoxiangmu\object_detection\yolov5-6.1\yolov5-6.1\utils\rboxs_utils.py:139: RuntimeWarning: invalid value encountered in add
  point1 = center + vector1 + vector2
E:\python_xiaoxiangmu\object_detection\yolov5-6.1\yolov5-6.1\utils\rboxs_utils.py:140: RuntimeWarning: invalid value encountered in subtract
  point2 = center + vector1 - vector2
E:\python_xiaoxiangmu\object_detection\yolov5-6.1\yolov5-6.1\utils\rboxs_utils.py:141: RuntimeWarning: invalid value encountered in subtract
  point3 = center - vector1 - vector2
E:\python_xiaoxiangmu\object_detection\yolov5-6.1\yolov5-6.1\utils\rboxs_utils.py:142: RuntimeWarning: invalid value encountered in add
  point4 = center - vector1 + vector2
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   7%|▋         | 3/42 [00:04<00:57,  1.47s/it]E:\python_xiaoxiangmu\object_detection\yolov5-6.1\yolov5-6.1\utils\rboxs_utils.py:139: RuntimeWarning: invalid value encountered in add
  point1 = center + vector1 + vector2
E:\python_xiaoxiangmu\object_detection\yolov5-6.1\yolov5-6.1\utils\rboxs_utils.py:140: RuntimeWarning: invalid value encountered in subtract
  point2 = center + vector1 - vector2
E:\python_xiaoxiangmu\object_detection\yolov5-6.1\yolov5-6.1\utils\rboxs_utils.py:141: RuntimeWarning: invalid value encountered in subtract
  point3 = center - vector1 - vector2
E:\python_xiaoxiangmu\object_detection\yolov5-6.1\yolov5-6.1\utils\rboxs_utils.py:142: RuntimeWarning: invalid value encountered in add
  point4 = center - vector1 + vector2
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 42/42 [00:58<00:00,  1.39s/it]
                 all        332          0          0          0          0          0
Results saved to runs\train\exp9

进程已结束,退出代码0

请问作者这是什么情况呀

**Comment by d5423197** [comment]
报错里面不都给你说了 invalid value encountered in add, 你打个断点看一下不久晓得了....

**Comment by hukaixuan19970627** [comment]
所以你改了啥，遇到问题最好详细提供一下相关的信息，至少你得让这个问题能够复现，不然不好排查。

**Comment by hukaixuan19970627** [comment]
另外warning是可以忽略的
