### ISSUE TITLE
opencv dnn部署onnx

### ISSUE THREAD

**Issue by chenying6810** [hukaixuan19970627/yolov5_obb#389]
大佬您好，我把训练完的pt权重转成onnx，直接调用是可以预测出结果的，但用opencv dnn调用就不行，我看你的detect.py里也考虑到了使用opencv调用的问题。请问您那可以吗？

**Comment by chenying6810** [comment]
![微信图片_20220702121245](https://user-images.githubusercontent.com/82497368/176986031-9cf7f292-b83d-4f46-9089-6149ccb99b4c.png)

**Comment by chenying6810** [comment]
![微信图片_20220702142525](https://user-images.githubusercontent.com/82497368/176989344-dc2f5aa5-7db0-4164-900f-dd2418a28ccb.png)
zhe's这是onnxruntime推理结果
![微信图片_20220702142700](https://user-images.githubusercontent.com/82497368/176989410-40a6d194-9fa2-4a38-93fa-3d8c4dfba397.png)
这是opencv dnn的推理结果，opencv推理结果是有问题的貌似

**Comment by chenying6810** [comment]
原因是我是opencv 4.6 要是4.5.4才行

**Comment by blackHorz** [comment]
Why is opencv 4.6 not supported, does anyone has workaround for it?
