### ISSUE TITLE
win10

### ISSUE THREAD

**Issue by SSTato** [hukaixuan19970627/yolov5_obb#390]
我在win10上使用yolov5_obb时有错误，请问你这个代码可以在win10系统中使用吗，还是只可以在乌班图上使用

**Comment by d5423197** [comment]
Win11运行正常

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/179393147-d185146c-c966-4063-86c9-78670819b2f8.png)
