### ISSUE TITLE
win10：error: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by Royalbx** [hukaixuan19970627/yolov5_obb#391]
running build_ext
D:\Anaconda\AnacondaInstall\envs\ptcu102\lib\site-packages\torch\utils\cpp_extension.py:316: UserWarning: Error checking compiler version for cl: [Win
Error 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
error: [WinError 2] 系统找不到指定的文件。

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/224
