### ISSUE TITLE
detect.py的推理中的NMS好像有bug

### ISSUE THREAD

**Issue by yuxin7** [hukaixuan19970627/yolov5_obb#392]
这是我推理出的图片。出现了一战图片包含两个目标框的情况。
![GF2_PMS1_E126 7_N36 0_20191215_L2A0004828088-PAN1__1__2296___25424](https://user-images.githubusercontent.com/35183358/177720660-a074b302-ecb6-4613-874c-983f44841bb4.jpg)

这是对应生成的标签：
0 197.723 64.3415 218.83 86.9761 159.388 142.406 138.281 119.772 0.265304
0 189.481 81.601 200.633 93.5598 164.277 127.462 153.125 115.503 0.367633
按道理NMS后只应该保留一个目标啊。

**Comment by hukaixuan19970627** [comment]
你可以调一下iou_thresh
