### ISSUE TITLE
windows: cannot import name 'nms_rotated_ext' from 'utils.nms_rotated'

### ISSUE THREAD

**Issue by TempleLordAnubies** [hukaixuan19970627/yolov5_obb#395]
cannot import name 'nms_rotated_ext' from 'utils.nms_rotated'

**Comment by TempleLordAnubies** [comment]
原来是要先运行一下setup.py

**Comment by SSTato** [comment]
> 原来是要先运行一下setup.py

怎么运行啊，我运行报错了

**Comment by TempleLordAnubies** [comment]
这个里面解决不了的就需要自己找了

**Comment by SSTato** [comment]
> 这个里面解决不了的就需要自己找了

![image](https://user-images.githubusercontent.com/93987794/177961840-3a40d942-eef6-4a8d-885c-0de81af1c468.png)
我到这一步卡住了，还是报错，你的解决了是嘛

**Comment by WeiCaike** [comment]
本人cd 到 utils/nms_rotated，然后 python setup.py develop  + python setup.py install 可以解决

**Comment by TempleLordAnubies** [comment]
> > 这个里面解决不了的就需要自己找了
> 
> ![image](https://user-images.githubusercontent.com/93987794/177961840-3a40d942-eef6-4a8d-885c-0de81af1c468.png) 我到这一步卡住了，还是报错，你的解决了是嘛

我是卡到了这一步
![image](https://user-images.githubusercontent.com/25146735/177980448-62b5e104-ce90-43dd-8820-da537831e7aa.png)

**Comment by TempleLordAnubies** [comment]
你的这个可以先不看最后一步出现了哪个错误，上面如果能找到其他的，可以先把其他错误的搜索一下看看怎么解决

**Comment by TempleLordAnubies** [comment]
> 你的这个可以先不看最后一步出现了哪个错误，上面如果能找到其他的，可以先把其他错误的搜索一下看看怎么解决

先不看最后一行

**Comment by SSTato** [comment]
> python setup.py install



> > > 这里面解决不了的就需要自己找了
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/93987794/177961840-3a40d942-eef6-4a8d-885c-0de81af1c468.png)我到这卡住了，还是报错了，你的解决了是嘛
> 
> 我是卡到了这一步 ![图片](https://user-images.githubusercontent.com/25146735/177980448-62b5e104-ce90-43dd-8820-da537831e7aa.png)

你解决了这个吗
