### ISSUE TITLE
val.py: cannot import name 'nms_rotated_ext' from 'utils.nms_rotated'

### ISSUE THREAD

**Issue by liujiafei666** [hukaixuan19970627/yolov5_obb#396]
val: WARNING: dataset/val/images/0200__1__0___0.jpg: ignoring corrupt image/label: 'dict' object has no attribute 'index'
val: New cache created: dataset/val/labelTxt.cache
Traceback (most recent call last):
  File "/home/liujiafei/yolov5_obb/val.py", line 401, in <module>
    main(opt)
  File "/home/liujiafei/yolov5_obb/val.py", line 374, in main
    run(**vars(opt))
  File "/home/lab517/anaconda3/envs/py39_ljf/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/liujiafei/yolov5_obb/val.py", line 167, in run
    dataloader = create_dataloader(data[task], imgsz, batch_size, stride, names, single_cls, pad=pad, rect=pt,
  File "/home/liujiafei/yolov5_obb/utils/datasets.py", line 101, in create_dataloader
    dataset = LoadImagesAndLabels(path, names, imgsz, batch_size,
  File "/home/liujiafei/yolov5_obb/utils/datasets.py", line 444, in __init__
    labels, shapes, self.segments = zip(*cache.values())
ValueError: not enough values to unpack (expected 3, got 0)
运行val.py的时候遇到上述问题

**Comment by liujiafei666** [comment]
我的label格式是
x1      y1       x2        y2       x3       y3       x4       y4       classname     diffcult
训练的时候没问题
运行val.py出错

**Comment by elahe-badali** [comment]
Hello [liujiafei666](https://github.com/liujiafei666) ,
Could you help me to run this code?

**Comment by Atomsuppress** [comment]
你看下val集的数据标签有问题没，这个提示一般是标签格式有误

**Comment by hukaixuan19970627** [comment]
train.py的训练过程中是会调用val.py的，所以不应该出现这种问题，可能是训练结束后修改了数据集导致的错误。
建议把生成的label.cache文件删掉，然后再运行一次train.py。

**Comment by liujiafei666** [comment]
> .py的训练过程中是会调用val.py的，所以不应该出现这种问题，可能是训练结束后修改了数据集导致的错误。
> 建议把生成的label.cache文件删掉，然后再运行一次train.
cache删除过了，还是一样的问题，训练结束后没有修改数据集。

**Comment by hukaixuan19970627** [comment]
如果getstart里的demo都可以运行而自制数据集不可以，那说明是数据集格式/结构问题，自己检查一下。

**Comment by Sauf4896** [comment]
s

**Comment by Sauf4896** [comment]
dasd

**Comment by goodfishboy** [comment]
> val: WARNING: dataset/val/images/0200__1__0___0.jpg: ignoring corrupt image/label: 'dict' object has no attribute 'index' val: New cache created: dataset/val/labelTxt.cache Traceback (most recent call last): File "/home/liujiafei/yolov5_obb/val.py", line 401, in main(opt) File "/home/liujiafei/yolov5_obb/val.py", line 374, in main run(**vars(opt)) File "/home/lab517/anaconda3/envs/py39_ljf/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context return func(*args, **kwargs) File "/home/liujiafei/yolov5_obb/val.py", line 167, in run dataloader = create_dataloader(data[task], imgsz, batch_size, stride, names, single_cls, pad=pad, rect=pt, File "/home/liujiafei/yolov5_obb/utils/datasets.py", line 101, in create_dataloader dataset = LoadImagesAndLabels(path, names, imgsz, batch_size, File "/home/liujiafei/yolov5_obb/utils/datasets.py", line 444, in **init** labels, shapes, self.segments = zip(*cache.values()) ValueError: not enough values to unpack (expected 3, got 0) 运行val.py的时候遇到上述问题

您好，这个问题解决了吗，能加个q：508152494，请教一下吗

**Comment by kevinrsb** [comment]
请问你这个问题解决了吗@goodfishboy

**Comment by leileilei2000** [comment]
> 如果getstart里的demo都可以运行而自制数据集不可以，那说明是数据集格式/结构问题，自己检查一下。

运行不了你提供的demo数据，也会报这个错误

**Comment by XuetongPei** [comment]
> 如果getstart里的demo都可以运行而自制数据集不可以，那说明是数据集格式/结构问题，自己检查一下。

博主您好，我也无法用demo数据运行val.py，train.py用demo是可以正常运行的

**Comment by XuetongPei** [comment]
> > 如果getstart里的demo都可以运行而自制数据集不可以，那说明是数据集格式/结构问题，自己检查一下。
> 
> 博主您好，我也无法用demo数据运行val.py，train.py用demo是可以正常运行的

不好意思，解决了，用demo测试之前自制数据集训练的权重了（捂脸）
