### ISSUE TITLE
使用tensorrt时速度没有变化

### ISSUE THREAD

**Issue by feiqiu-cyber** [hukaixuan19970627/yolov5_obb#397]
使用export导出best.engine后，跑demo单张图像速度没有变化这是为啥
上面是使用engine下面是使用pt
![image](https://user-images.githubusercontent.com/79258566/178097767-35fabb47-a635-4f54-b223-4c1966e6947a.png)

![image](https://user-images.githubusercontent.com/79258566/178097712-aab677a0-aaa9-4dc7-98e0-0158f56c571f.png)

**Comment by monument-and-sea-all-the-gift** [comment]
试试，批量

**Comment by hukaixuan19970627** [comment]
我没测试过yolov5系列算法部署方面的推理速度，不过测速只测1张图的数据也太没有参考性了，你至少应该拿1000张图来做对比才对。
