### ISSUE TITLE
Label class 15 exceeds nc=2 in data/byself_dotav15_ship_poly.yaml. Possible class labels are 0-1

### ISSUE THREAD

**Issue by Best-effort** [hukaixuan19970627/yolov5_obb#398]
大佬，我按照您的教程，可以正常复现您的代码，但是当我使用同样裁剪过后的数据集，将nc改为2之后就会出现如下的错误？我去网上看了一下说是标签标注的问题。 劳烦您帮忙解决一下
Traceback (most recent call last):
  File "train.py", line 633, in <module>
    main(opt)
  File "train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 219, in train
    assert mlc < nc, f'Label class {mlc} exceeds nc={nc} in {data}. Possible class labels are 0-{nc - 1}'
AssertionError: Label class 15 exceeds nc=2 in data/byself_dotav15_ship_poly.yaml. Possible class labels are 0-1

**Comment by Best-effort** [comment]
这个是我设置的.yaml文件
# Classes
nc: 2  # number of classes
names: ['ship', 'None']  # class names

**Comment by hukaixuan19970627** [comment]
nc=2是数据集类别只有1的时候yolov5_obb默认的参数设置在训练时无法收敛所采用的解决方案。
另外报错说明里很清楚，你的数据集类别数量超过了2
```
Label class 15 exceeds nc=2 in data/byself_dotav15_ship_poly.yaml. Possible class labels are 0-1
```
