### ISSUE TITLE
windows: error: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by Beking1949** [hukaixuan19970627/yolov5_obb#399]
(torch_copy) C:\Users\11201\PycharmProjects\car_detect\utils\nms_rotated>python setup.py develop
running develop
D:\anconda\envs\torch_copy\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\anconda\envs\torch_copy\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing nms_rotated.egg-info\PKG-INFO
writing dependency_links to nms_rotated.egg-info\dependency_links.txt
writing top-level names to nms_rotated.egg-info\top_level.txt
reading manifest file 'nms_rotated.egg-info\SOURCES.txt'
writing manifest file 'nms_rotated.egg-info\SOURCES.txt'
running build_ext
error: [WinError 2] 系统找不到指定的文件。

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/224

**Comment by BuFanZHANG** [comment]
> (torch_copy) C:\Users\11201\PycharmProjects\car_detect\utils\nms_rotated>python setup.py develop running develop D:\anconda\envs\torch_copy\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools. warnings.warn( D:\anconda\envs\torch_copy\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn( running egg_info writing nms_rotated.egg-info\PKG-INFO writing dependency_links to nms_rotated.egg-info\dependency_links.txt writing top-level names to nms_rotated.egg-info\top_level.txt reading manifest file 'nms_rotated.egg-info\SOURCES.txt' writing manifest file 'nms_rotated.egg-info\SOURCES.txt' running build_ext error: [WinError 2] 系统找不到指定的文件。

hello ,我也遇到了这个问题，请问你现在解决了嘛
