### ISSUE TITLE
关于CSL

### ISSUE THREAD

**Issue by shubudao** [hukaixuan19970627/yolov5_obb#401]
我想问一下，当前版本是默认使用CSL来训练旋转角度的吗？我看代码好像将CSL作为数据预处理的一部分了！

**Comment by Beking1949** [comment]
对

**Comment by hukaixuan19970627** [comment]
readme和简介里有，就是yolov5+csl

**Comment by IsenLwww** [comment]
> readme和简介里有，就是yolov5+csl

你好作者，请问您是如何将yolo与csl结合的呢，有论文可以拜读吗
