### ISSUE TITLE
negative label values [ -101], please check your dota format labels

### ISSUE THREAD

**Issue by fffucla** [hukaixuan19970627/yolov5_obb#404]
604.000000 589.000000 556.000000 600.000000 560.000000 616.000000 608.000000 605.000000 other-ship 0
839.000000 -101.000000 603.000000 171.000000 650.000000 212.000000 886.000000 -60.000000 LiquidCargoShip 0

因为数据集本身的坐标注释就带有负数，所以不知该如何转换，请问能有方法可以直接读取含有负值的坐标而不报错吗？

negative label values [         -101], please check your dota format labels

**Comment by hukaixuan19970627** [comment]
numpy里面有个clip操作，会限定数值的最小值和最大值，你可以转换一下labels，或者修改dataloader里面的代码。
