### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by xing-bing** [hukaixuan19970627/yolov5_obb#405]
你好，大佬，请问一下数据集拆之后对于那些没有标签的图片需要删除吗

**Comment by hukaixuan19970627** [comment]
mmdetection里的操作是只加载有label的image进行训练；yolov5的操作是无论有没有labels都会进行训练。
前者这么做的原因我猜是因为没有label，loss为0，所以网络中除了BN层以外的参数都不会进行更新，所以为了节省训练时间就只训练有label的那一部分数据。
而后者有这么一种理念，添加无label的图片进行训练可以提高模型识别纯背景的能力。
至于实际上应该怎么做那见仁见智喽，随便你。
