### ISSUE TITLE
datasets  这文件夹如何生成的，好像没有描述。没找到。。

### ISSUE THREAD

**Issue by minwim** [hukaixuan19970627/yolov5_obb#406]
parent
├── yolov5
└── datasets
    └── DOTAv1.5
        ├── train_split_rate1.0_subsize1024_gap200
        ├── train_split_rate1.0_subsize1024_gap200
        └── test_split_rate1.0_subsize1024_gap200
            ├── images
                 |────1.jpg
                 |────...
                 └────10000.jpg
            ├── labelTxt
                 |────1.txt
                 |────...
                 └────10000.txt

**Comment by hukaixuan19970627** [comment]
你可以参考demo中的数据集结构，这个就是我所使用的DOTA数据集的结构，不一定非得一摸一样。
