### ISSUE TITLE
save_txt出错

### ISSUE THREAD

**Issue by SSTato** [hukaixuan19970627/yolov5_obb#407]
![image](https://user-images.githubusercontent.com/93987794/179477541-c5d2bb01-c9d9-4114-9a6f-fdb63a697c3e.png)
我在使用detect.py保存检测结果的txt文件时报错
AttributeError: 'list' object has no attribute 'tolist'怎么解决呢

**Comment by archg2021** [comment]
> ![image](https://user-images.githubusercontent.com/93987794/179477541-c5d2bb01-c9d9-4114-9a6f-fdb63a697c3e.png) 我在使用detect.py保存检测结果的txt文件时报错 AttributeError: 'list' object has no attribute 'tolist'怎么解决呢

@SSTato I get the same error, were you able to find a solution to this??

**Comment by SSTato** [comment]
> > ![图片](https://user-images.githubusercontent.com/93987794/179477541-c5d2bb01-c9d9-4114-9a6f-fdb63a697c3e.png)我在使用detect.py保存检测结果的txt文件报错AttributeError: 'list' object has no attribute 'tolist'怎么解决呢
> 
> @SSTato我得到了同样的错误，你能找到解决办法吗？

注释掉报错的那行就行了

**Comment by jsxyhelu** [comment]
已经是list了就需要再转为list
有道理
