### ISSUE TITLE
error: identifier "eps" is undefined in device code

### ISSUE THREAD

**Issue by cugwuyanzu** [hukaixuan19970627/yolov5_obb#410]
poly_nms_cuda.cu(27): error: identifier "epss" is undefined in device code
只有我遇到这个问题吗？我看代码中已经定义了啊，为什么会这样？
const double eps=1E-8;

__device__ inline int sig(float d){
    return(d>eps)-(d<-eps);
}
有没有人遇到同样的问题？

**Comment by cugwuyanzu** [comment]
我把函数中的eps直接改成了1E-8
device inline int sig(float d){
return(d>1E-8)-(d<-1E-8);
}
能运行成功了，但是不知道这样对不对

**Comment by hukaixuan19970627** [comment]
https://hub.fastgit.xyz/hukaixuan19970627/yolov5_obb/issues/224

**Comment by scar-on** [comment]
> 我把函数中的eps直接改成了1E-8 device inline int sig(float d){ return(d>1E-8)-(d<-1E-8); } 能运行成功了，但是不知道这样对不对

老哥，后来这样改对了吗请问？

**Comment by GluttonK** [comment]
我把const double eps=1E-8;换成了宏定义#define eps 1e-8，虽然我也不知道为什么明明定义了却显示undefine

**Comment by sangeun-jo** [comment]
Thank you. I worked for me.
My environments is
```
python 3.9
cuda version 11.6
```
