### ISSUE TITLE
Custom Dataset Training

### ISSUE THREAD

**Issue by wanghui589** [hukaixuan19970627/yolov5_obb#414]
![图片](https://user-images.githubusercontent.com/49338402/180959073-6259905f-5eca-445c-ac67-43dcc6da74ea.png)
![图片](https://user-images.githubusercontent.com/49338402/180959198-2716f97f-e6e3-46ea-a82d-f0253ba614b9.png)

**Comment by hukaixuan19970627** [comment]
https://hub.fastgit.xyz/hukaixuan19970627/yolov5_obb/issues/386#issuecomment-1186461244
发的图片看不大清，麻烦按照这个回答再发一次
