### ISSUE TITLE
Correct Label format

### ISSUE THREAD

**Issue by archg2021** [hukaixuan19970627/yolov5_obb#416]
First of all, thanks a lot for the amazing work!.
I am working on a custom Dataset for screws. Initially I labelled the screws in "_format_1_"(see attached images) as per DOTA format, in clockwise order, assuming one edge of the head of screw as the initial point(x1, y1). But the detections I get after initial training are both in _format_1_ and _format_2_. 

1. Which labelling format is correct out of these two?
2. Can I mix both formats or do I need to stick to any one of them?
Format_1 :
![format_1](https://user-images.githubusercontent.com/89192826/181021532-a2451ef7-dded-489f-9348-1b9fda378d97.png)
Format_2 :
![format_2](https://user-images.githubusercontent.com/89192826/181021567-11ee666f-d615-4a47-bed6-b629df5b41df.png)

**Comment by hukaixuan19970627** [comment]
Both formats are correct.
Yolov5_obb just need poly format, the order of the vertices doesn't really matter.

**Comment by archg2021** [comment]
> Both formats are correct. Yolov5_obb just need poly format, the order of the vertices doesn't really matter.

Thanks a lot for your reply!!!

**Comment by Avant-Gardiste** [comment]
@archg2021 @hukaixuan19970627 If orientation matter you should use the same labeling format as figure 1, I already faced the same issue !

**Comment by akamal816** [comment]
@archg2021 what annotation tool are you using?
