### ISSUE TITLE
Custom Dataset Training

### ISSUE THREAD

**Issue by hulinlang** [hukaixuan19970627/yolov5_obb#417]
![image](https://user-images.githubusercontent.com/91964911/181024506-d00d18fb-1690-41ac-b0a1-bb969933b7a5.png)
![image](https://user-images.githubusercontent.com/91964911/181024621-76630466-e141-45e3-9443-cfdc98553535.png)
![image](https://user-images.githubusercontent.com/91964911/181024655-b98795a5-9723-4e68-9890-401466b990b7.png)
![image](https://user-images.githubusercontent.com/91964911/181024769-da695084-87f9-4d51-a5d0-608ca9d2fd3d.png)
![image](https://user-images.githubusercontent.com/91964911/181024836-c99c6790-b961-4553-be87-54d5b91b014e.png)
![image](https://user-images.githubusercontent.com/91964911/181024924-d94ff81b-ec94-4927-bbe8-438f33c3fdb6.png)

**Comment by wanghui589** [comment]
我用的那个SSDD_tiny公共数据集也一直没有精度，很难顶。
请问你解决了么·？

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/386#issuecomment-1186461244
按照这个回答重新发一次哦，提供的信息不大详细。

**Comment by hulinlang** [comment]
> [#386 (comment)](https://github.com/hukaixuan19970627/yolov5_obb/issues/386#issuecomment-1186461244) 按照这个回答重新发一次哦，提供的信息不大详细。

result
![image](https://user-images.githubusercontent.com/91964911/181243808-381a3a3b-22f7-4eb8-a157-48dbe7b4d97d.png)
opt
![image](https://user-images.githubusercontent.com/91964911/181243844-269af03f-cfe4-4c9b-975b-0df9503f5a6b.png)
![image](https://user-images.githubusercontent.com/91964911/181243883-2bf949ab-cf16-410c-b2e5-6dafac1ffae9.png)
hyp
![image](https://user-images.githubusercontent.com/91964911/181243924-26fd9e92-0cec-4b2d-9764-95eefb4383a4.png)
![image](https://user-images.githubusercontent.com/91964911/181243948-4f4cfa9c-2754-413d-ac1d-ad97a87ab97b.png)
train_batch
![image](https://user-images.githubusercontent.com/91964911/181243991-576331d8-daae-4288-8c04-a4a0a5d39dee.png)
![image](https://user-images.githubusercontent.com/91964911/181244012-3eb2fd67-eae9-4f04-ad61-76f36d5cd6e2.png)
![image](https://user-images.githubusercontent.com/91964911/181244060-cc9947b8-9994-474a-993d-ca6026829351.png)
val_batch_labels
![image](https://user-images.githubusercontent.com/91964911/181244136-f749bcb6-763d-4d3f-82e4-92ae414f5c33.png)
val_batch_pre
![image](https://user-images.githubusercontent.com/91964911/181244176-9d8b5ebd-8e42-4de7-80b7-3bd5df604da9.png)
没有labels的那两个文件。
关于数据集
标注如下
![image](https://user-images.githubusercontent.com/91964911/181244349-73484630-cda0-4869-bea0-8f4dcee5aa56.png)
![image](https://user-images.githubusercontent.com/91964911/181244400-92ed9516-009f-4325-9880-73624afa17f5.png)
其中有一些带负数的标注，运行时报警告舍弃了。
图像如下
![image](https://user-images.githubusercontent.com/91964911/181244575-44851665-025c-450a-96ea-7380246b467d.png)
全为1024*1024的SAR图像。
总体一千张，我按9：1分的训练和验证。

**Comment by hukaixuan19970627** [comment]
没生成labels.jpg那两个文件的话说明该数据集的标注文件不符合格式要求。
你应该试过getstart.md里面的demo吧，正常情况下生成的文件应该和demo保持一致，你首先得排除一下labels对训练的影响，因为你的results.jpg中显示出现过nan值，说明数据可能比较“脏”。
labels有负数的话你加个预处理操作，利用np.clip函数把poly值的最小值限制为0就行。

**Comment by hulinlang** [comment]
getstart里的demo运行train.py也没有labels.jpg的两个文件，权重文件时下载的您上传的度盘文件，只是名字没改，其他都一样。
运行的时候有个这个警告：UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`，
效果如下，感觉也有点问题，我做训练时nc的类型都注意改了的，唯一有改动的是imgsize，我改到了1280.
train_batch
![image](https://user-images.githubusercontent.com/91964911/181308551-1462555a-7847-4176-85c6-9885d39ddd4c.png)
val_batch_labels
![image](https://user-images.githubusercontent.com/91964911/181308976-d3b5476c-52a7-46c5-92c1-67b7bddc1b8b.png)
val_batch_pre
![image](https://user-images.githubusercontent.com/91964911/181309026-003e5686-e68d-4628-9347-3d1a83078ee1.png)

**Comment by hukaixuan19970627** [comment]
demo也没有的话，检查下环境依赖的版本和requirements.txt是否保持一致

**Comment by hulinlang** [comment]
> demo也没有的话，检查下环境依赖的版本和requirements.txt是否保持一致
我解决了训练P，R为0的问题，但还是没有labels的两个文件，大概原因就是16xx系的显卡不支持cuda11.3，换回10.2就可以了
具体可以参考这个 https://blog.csdn.net/qq_52902342/article/details/124261371
![image](https://user-images.githubusercontent.com/91964911/181462851-18a18644-348c-4d5c-9f73-2c6df91d5715.png)

**Comment by Rorsc4achhh** [comment]
兄弟，能分享一下作者的weights吗，我能找到的链接都过期了
