### ISSUE TITLE
Windows和Linux下训练速度的差距

### ISSUE THREAD

**Issue by xiamibudayang** [hukaixuan19970627/yolov5_obb#418]
您好，我在linux系统下可以正常训练，训练速度大概是20min/epoch，但是当我在windows系统下训练的时候，训练速度非常慢，需要80min/epoch，由于设备限制，我必须在windows环境下训练，请问可能是什么原因造成训练缓慢的，如何改进呢？

**Comment by hukaixuan19970627** [comment]
同等batchsize的话，显卡的计算性能、显卡的利用率都会影响训练速度
