### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by QuentinAndre11** [hukaixuan19970627/yolov5_obb#419]
Hello,
I'm looking for a pretrained model on aerial object detection (I have a few images, around 100 for now, and I need to use transfer learning). I don't see one here, it seems you use pretrained COCO, is it possible to get your final model for DOTA or any aerial object detection dataset ?
Thanks a lot, and thanks for your work

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/181271172-b548349a-35eb-4357-8632-33376a4e03e4.png)
