### ISSUE TITLE
detect.py加参后报错

### ISSUE THREAD

**Issue by hulinlang** [hukaixuan19970627/yolov5_obb#425]
你好博主，在我运行detect.py加运行参数后，遇见了如下错误
![image](https://user-images.githubusercontent.com/91964911/183233720-72c05db3-2c06-4b51-b996-25c866f3c290.png)
![image](https://user-images.githubusercontent.com/91964911/183233712-a4bf75d8-b2f5-4f22-95fd-d749d245d27c.png)
在没加这个参数前运行时ok的

**Comment by hukaixuan19970627** [comment]
你可以在val.py用这个参数来保存txt
