### ISSUE TITLE
硬件配置

### ISSUE THREAD

**Issue by xing-bing** [hukaixuan19970627/yolov5_obb#426]
大佬你好，我看你的知乎训练时设置batch_size=75,那得多大的显存啊，我训练是设置的batch_size=4结果模型收敛的很慢。

**Comment by hukaixuan19970627** [comment]
忘了，3张1080Ti或者2080Ti吧

**Comment by hukaixuan19970627** [comment]
epoch固定，batch_size大的话，网络的迭代次数就会小。
你batch_size小的话，epoch也可以设置的小一点
