### ISSUE TITLE
大佬最近拜读了您的毕业论文，问一下您后来是不是放弃了CSL，直接从iou损失函数下手解决边界不连续的问题了吗

### ISSUE THREAD

**Issue by wubalahao** [hukaixuan19970627/yolov5_obb#427]

**Comment by NickGitHubName** [comment]
> _No description provided._

您能把论文发我一下吗 495066265@qq.com

**Comment by hukaixuan19970627** [comment]
其实ciou+角度分类是我“个人认为”的目前最好的旋转检测方案，我在yolov5上的实验是发现ciou+角度分类方案收敛速度起码要比RIoU Loss系列方案快个30%~50%的感觉，而且精度表现甚至和KLD、R-CIoU差不多，而且更关键的问题是RIoU 系列Loss实际上是比较难调的，我可能部分Loss权重没设置好，网络的精度就会一直上不去。
之所以毕业论文搞RIoU系列，是因为CSL DCL这些都是别人的东西

**Comment by ddcpowerone** [comment]
> _No description provided._

请问能发一份给吗？1132891303@qq.com

**Comment by guanxuefeng** [comment]
请问能发一份给吗？1850314204@qq.com

**Comment by ToneZe** [comment]
请问能发一份给吗？806324244@qq.com

**Comment by IsenLwww** [comment]
> 请问能发一份给吗？[806324244@qq.com](mailto:806324244@qq.com)

请问你找到作者的论文了吗
