### ISSUE TITLE
[Windows Error]: python setup.py develop

### ISSUE THREAD

**Issue by Yizh6** [hukaixuan19970627/yolov5_obb#429]
我在anaconda中创建了一个环境，并按install.md中的流程执行了前面的所有步骤，但是在执行‘python setup.py develop  #or "pip install -v -e ."’这一步时报了这样的错误
<img width="1266" alt="屏幕截图 2022-08-11 004549" src="https://user-images.githubusercontent.com/111002496/183970871-a038d2f3-b262-486e-9cc0-5db973c49dff.png">
<img width="1129" alt="屏幕截图 2022-08-11 005045" src="https://user-images.githubusercontent.com/111002496/183971068-a1b93698-17c2-428e-a843-69f253dd1a5c.png">
虽然‘install.md’之后的语句运行也显示“完成代码生成”
<img width="1262" alt="屏幕截图 2022-08-11 005522" src="https://user-images.githubusercontent.com/111002496/183971524-334fdc41-a826-4eb8-89e5-763cf5aac5f6.png">
但是运行train.py文件时就会出现这个错误
<img width="1280" alt="屏幕截图 2022-08-11 005455" src="https://user-images.githubusercontent.com/111002496/183972119-996e5e40-dd58-42a9-8c99-deed64f4b29e.png">

我看issue中有人也有这种错误，运行‘python setup.py develop  #or "pip install -v -e ."’这一步就好了，但是我运行这一步会报如上的错误，求解答

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/184366797-2ac2398e-6168-4328-897c-b5711fa9415b.png)

**Comment by Yizh6** [comment]
您好，您发来的邮件已经收到，我会尽快给您回复。

**Comment by Yizh6** [comment]
您好，您发来的邮件已经收到，我会尽快给您回复。
