### ISSUE TITLE
LINK : fatal error LNK1181: 无法打开输入文件

### ISSUE THREAD

**Issue by szq7758** [hukaixuan19970627/yolov5_obb#430]
(pytorch_cpu_12) C:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated>python setup.py develop
running develop
running egg_info
writing nms_rotated.egg-info\PKG-INFO
writing dependency_links to nms_rotated.egg-info\dependency_links.txt
writing top-level names to nms_rotated.egg-info\top_level.txt
reading manifest file 'nms_rotated.egg-info\SOURCES.txt'
writing manifest file 'nms_rotated.egg-info\SOURCES.txt'
running build_ext
building '.nms_rotated_ext' extension
Emitting ninja build file C:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.11.0
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\ProgramData\Ana
conda3\envs\pytorch_cpu_12\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\lib/x64" /LIBPATH:D:\ProgramData\Anaconda3\envs\pytorch_cpu_12\libs /LIBPATH:D:\Prog
ramData\Anaconda3\envs\pytorch_cpu_12\PCbuild\amd64 "/LIBPATH:D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\ATLMFC\lib\x64" "/LIBPATH:D:\Program Files\Microsoft Visual St
udio\2022\Community\VC\Tools\MSVC\14.33.31629\lib\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.20348.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\\lib\10.0.20348.0\\um\x64" c10.lib torch.lib torch_cpu.lib torch_p
ython.lib cudart.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EXPORT:PyInit_nms_rotated_ext C:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-3.8\Rel
ease\src/nms_rotated_cpu.obj C:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-3.8\Release\src/nms_rotated_ext.obj C:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolo
v5_obb-master\utils\nms_rotated\build\temp.win-amd64-3.8\Release\src/nms_rotated_cuda.obj C:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-3.8\Release\src/pol
y_nms_cuda.obj /OUT:build\lib.win-amd64-3.8\nms_rotated_ext.cp38-win_amd64.pyd /IMPLIB:C:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-3.8\Release\src\nms_ro
tated_ext.cp38-win_amd64.lib
LINK : fatal error LNK1181: 无法打开输入文件“C:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-3.8\Release\src\nms_rotated_cpu.obj”
error: command 'D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

这个问题有人遇到过吗，好像是提示的这个文件根本就没有生成。下面的是build.ninja文件的内容：

ninja_required_version = 1.3
cxx = cl
nvcc = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc

cflags = /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DWITH_CUDA -ID:\ProgramData\Anaconda3\envs\pytorch_cpu_12\lib\site-packages\torch\include -ID:\ProgramData\Anaconda3\envs\pytorch_cpu_12\lib\site-packages\torch\include\torch\csrc\api\include -ID:\ProgramData\Anaconda3\envs\pytorch_cpu_12\lib\site-packages\torch\include\TH -ID:\ProgramData\Anaconda3\envs\pytorch_cpu_12\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -ID:\ProgramData\Anaconda3\envs\pytorch_cpu_12\include -ID:\ProgramData\Anaconda3\envs\pytorch_cpu_12\include "-ID:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include" "-ID:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\ATLMFC\include" "-ID:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-ID:\Windows Kits\10\include\10.0.20348.0\ucrt" "-ID:\Windows Kits\10\\include\10.0.20348.0\\um" "-ID:\Windows Kits\10\\include\10.0.20348.0\\shared" "-ID:\Windows Kits\10\\include\10.0.20348.0\\winrt" "-ID:\Windows Kits\10\\include\10.0.20348.0\\cppwinrt"
post_cflags = -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_rotated_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
cuda_cflags = --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -ID:\ProgramData\Anaconda3\envs\pytorch_cpu_12\lib\site-packages\torch\include -ID:\ProgramData\Anaconda3\envs\pytorch_cpu_12\lib\site-packages\torch\include\torch\csrc\api\include -ID:\ProgramData\Anaconda3\envs\pytorch_cpu_12\lib\site-packages\torch\include\TH -ID:\ProgramData\Anaconda3\envs\pytorch_cpu_12\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -ID:\ProgramData\Anaconda3\envs\pytorch_cpu_12\include -ID:\ProgramData\Anaconda3\envs\pytorch_cpu_12\include "-ID:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include" "-ID:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\ATLMFC\include" "-ID:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-ID:\Windows Kits\10\include\10.0.20348.0\ucrt" "-ID:\Windows Kits\10\\include\10.0.20348.0\\um" "-ID:\Windows Kits\10\\include\10.0.20348.0\\shared" "-ID:\Windows Kits\10\\include\10.0.20348.0\\winrt" "-ID:\Windows Kits\10\\include\10.0.20348.0\\cppwinrt"
cuda_post_cflags = -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_rotated_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
ldflags = 

rule compile
  command = cl /showIncludes $cflags -c $in /Fo$out $post_cflags
  deps = msvc

rule cuda_compile
  depfile = $out.d
  deps = gcc
  command = $nvcc --generate-dependencies-with-compile --dependency-output $out.d $cuda_cflags -c $in -o $out $cuda_post_cflags

build C$:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-3.8\Release\src/nms_rotated_cpu.obj: compile C$:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\src\nms_rotated_cpu.cpp
build C$:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-3.8\Release\src/nms_rotated_ext.obj: compile C$:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\src\nms_rotated_ext.cpp
build C$:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-3.8\Release\src/nms_rotated_cuda.obj: cuda_compile C$:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\src\nms_rotated_cuda.cu
build C$:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-3.8\Release\src/poly_nms_cuda.obj: cuda_compile C$:\Users\7758\Desktop\SZQ\Tuxaingshibie\yolov5_obb-master\utils\nms_rotated\src\poly_nms_cuda.cu

**Comment by szq7758** [comment]
翻看了之前的提问，看到了几个和我同样问题的，请问你们解决了吗

**Comment by TempleLordAnubies** [comment]
和我遇到的问题一样，这个我放弃在windows上用了，准备整一个wsl或者用双系统😣

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/184366994-1cc594c6-a65b-46bc-bc28-7a2d72f79b51.png)
