### ISSUE TITLE
训练的时候出现的是HBBmAP的评价指标

### ISSUE THREAD

**Issue by fzwwj95** [hukaixuan19970627/yolov5_obb#432]
用的是OBB的lable，但是训练的时候却一直显示HBBmAP的指标？

**Comment by fzwwj95** [comment]
![image](https://user-images.githubusercontent.com/17897415/184498813-c59fcb0f-fc79-4318-8b07-5700283d3a85.png)

**Comment by fzwwj95** [comment]
使用的参数：
![image](https://user-images.githubusercontent.com/17897415/184498841-ab4b6d32-8c9a-40b0-9569-23c0eaa5602d.png)

**Comment by fzwwj95** [comment]
![1660401476840](https://user-images.githubusercontent.com/17897415/184498934-b330d438-cb69-400f-ae86-3712f107a000.png)

**Comment by hukaixuan19970627** [comment]
https://hub.fastgit.xyz/hukaixuan19970627/yolov5_obb/blob/master/docs/ChangeLog.md
validation就是用的HBB来进行评估，这样可以缩短训练时频繁调用val.py所花的时间

**Comment by DiaJB** [comment]
> https://hub.fastgit.xyz/hukaixuan19970627/yolov5_obb/blob/master/docs/ChangeLog.md validation就是用的HBB来进行评估，这样可以缩短训练时频繁调用val.py所花的时间

大佬，萌新有点儿转不过来弯了，想请教下，咱们不是做的OBB嘛，为什么用HBB去评估啊，就算是缩短了训练的时间，可是用HBB评估是不是无法说明OBB效果很好啊，毕竟一个有角度的，一个完全就是水平的框。

**Comment by Lyle-Xu** [comment]
大佬最后怎么解决的，发现这样，训练的时候val过程完全没有参考价值。

**Comment by Lyle-Xu** [comment]
我在想最后best权重是不是也有问题，只是hbb最好的，并不是obb最好的

**Comment by fzwwj95** [comment]
> 大佬最后怎么解决的，发现这样，训练的时候val过程完全没有参考价值。

可以调用val.py进行验证，我的理解是用hbb舍弃对角度的评估以节约时间，但是只能作为一个参考

**Comment by Lyle-Xu** [comment]
大佬有OBBmap的val.py的代码吗？ 不知道修改哪些部分。邮箱xusir.m01@gmail.com

**Comment by IsenLwww** [comment]
> 大佬有OBBmap的val.py的代码吗？ 不知道修改哪些部分。邮箱[xusir.m01@gmail.com](mailto:xusir.m01@gmail.com)

同问，请问您解决这个问题了吗？如何能进行OBBｍAP的评估呀

**Comment by hecheng000** [comment]
请问有obb的验证的val.py吗 邮箱hecheng01314@163.com

**Comment by IsenLwww** [comment]
> 请问有obb的验证的val.py吗 邮箱[hecheng01314@163.com](mailto:hecheng01314@163.com)

![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/113815413/979e8714-7872-40b2-a3b7-8e3f38cb5d10)

GetStart.md里面有给命令示例

**Comment by hecheng000** [comment]
好的 谢谢啦



在 2024-04-16 10:16:01，"IsenLwww" ***@***.***> 写道：

请问有obb的验证的val.py吗 ***@***.***

image.png (view on web)

GetStart.md里面有给命令示例

**Comment by IsenLwww** [comment]
> 请问有obb的验证的val.py吗 邮箱[hecheng01314@163.com](mailto:hecheng01314@163.com)

不过自己数据集能用来evalution得到OBBｍAP的val我也没有,如果你能找到了可以踢我一下吗，谢谢

**Comment by hecheng000** [comment]
对的 我刚看了一下只是评估dota数据集的好像 我也是需要评估自己的数据集



在 2024-04-16 10:18:32，"IsenLwww" ***@***.***> 写道：

请问有obb的验证的val.py吗 ***@***.***

不过自己数据集能用来evalution得到OBBｍAP的val我也没有

**Comment by IsenLwww** [comment]
> 对的 我刚看了一下只是评估dota数据集的好像 我也是需要评估自己的数据集 在 2024-04-16 10:18:32，"IsenLwww" ***@***.***> 写道： 请问有obb的验证的val.py吗 ***@***.*** 不过自己数据集能用来evalution得到OBBｍAP的val我也没有 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

感觉可以通过作者给出的指令进行生成测试集的txt检测结果，然后照着evalution的代码改一改就行吧（我猜

**Comment by Lyle-Xu** [comment]
下面是val用obb评估。 test评估，上传到dota官方。看使用文档。
meta有一个 detectron2的库，有一个pairwise_iou_rotated函数，专门计算旋转iou。 首先：
1.安装detectron2 根据https://github.com/facebookresearch/detectron2/issues/5008
2.查看官方文档查看pairwise_iou_rotated，查看旋转物体如何定义。好像只要把长边法的角度加一个负号。
3.修改val函数。
国内有rotateddetection好像也有旋转算子。

**Comment by IsenLwww** [comment]
> 下面是val用obb评估。 test评估，上传到dota官方。看使用文档。 meta有一个 detectron2的库，有一个pairwise_iou_rotated函数，专门计算旋转iou。 首先： 1.安装detectron2 根据[facebookresearch/detectron2#5008](https://github.com/facebookresearch/detectron2/issues/5008) 2.查看官方文档查看pairwise_iou_rotated，查看旋转物体如何定义。好像只要把长边法的角度加一个负号。 3.修改val函数。 国内有rotateddetection好像也有旋转算子。

谢谢，不过我使用了mmcv的box_iou_rotated，虽然能跑动，不过我不太确定自己改的对不对，HRSC2016和UCAS-AOD的OBBmAP算出来蛮高的，不敢确定
