### ISSUE TITLE
显示的评价结果是哪个数据集合的结果

### ISSUE THREAD

**Issue by fzwwj95** [hukaixuan19970627/yolov5_obb#433]
代码里没加validation，那么显示的评价结果是哪个集合的结果？
![581096683ef757778adfa63dfe0a805](https://user-images.githubusercontent.com/17897415/184499207-ecaa6b35-ef88-43fa-88ab-89a7a5e84d5f.jpg)

**Comment by hukaixuan19970627** [comment]
代码里有validation，相关dataset可参考配置文件https://hub.fastgit.xyz/hukaixuan19970627/yolov5_obb/blob/master/data/dotav15_poly.yaml
