### ISSUE TITLE
WARNING：NMS time limit 30.0s exceeded

### ISSUE THREAD

**Issue by fzwwj95** [hukaixuan19970627/yolov5_obb#437]
我banchsize设置为48，所以把对应的hyp.finetune_dota.yaml中的lr调为0.24
训练时，验证环节出现NMS time limit 30.0s exceeded报错
修改utils中的general.py的time_limit为40，报错消失
这样除了可能耗时外，会对模型产生不良后果吗？还是有其他的参数需要修改？
![origin_img_v2_041f718e-0cdf-488d-bcb0-572981a0e89g](https://user-images.githubusercontent.com/17897415/184929202-fa4fce5d-f318-4af6-8a61-57a99f459a3a.jpg)
![origin_img_v2_a75fd7a8-d770-4605-b262-7669d0ad7d4g](https://user-images.githubusercontent.com/17897415/184929228-dfb2f625-9c51-46fd-963d-73eec37bca82.jpg)
![origin_img_v2_11d70678-ca70-4f59-ba20-92d8e2ffc6fg](https://user-images.githubusercontent.com/17897415/184929268-d3d80ca4-38b8-4579-a212-0c52e78677e1.jpg)

**Comment by hukaixuan19970627** [comment]
初始学习率设置的不大好导致模型前期收敛效果不好，初期模型的输出无限接近于随机预测，进而导致NMS需要处理的预测框过多。
一般情况下来说，初期收敛不好的模型最终的模型精度相对而言也会更差
