### ISSUE TITLE
多卡训练的时候提示：Reducer buckets have been rebuilt in this iteration

### ISSUE THREAD

**Issue by fzwwj95** [hukaixuan19970627/yolov5_obb#438]
1.多卡训练的时候，在第一个epoch出现提示：Reducer buckets have been rebuilt in this iteration
训练没有停止，不知道是否会存在影响？

2.https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/ChangeLog.md
--这里是使用了4张2080Ti吗？
--也是使用'data/hyps/obb/hyp.finetune_dota.yaml'（https://hub.fastgit.xyz/hukaixuan19970627/yolov5_obb/blob/master/data/hyps/obb/hyp.finetune_dota.yaml） 超参数进行训练的吗？
--这里banchsize75，'data/hyps/obb/hyp.finetune_dota.yaml'中lr0为0.01，我如果banchsize调整为k倍，学习率lr0也要调整为k倍吗?还有其他参数需要修改吗？

**Comment by hukaixuan19970627** [comment]
1. 没影响，具体原因可以用搜索引擎解决
2. yolov5系列算法不需要按batchsize分配学习率，代码会自动完成这一操作
3. 想复现精度可以查看训练log，下载链接里有提供
