### ISSUE TITLE
训练时候显存满了，但是GPU在0-97%反复跳

### ISSUE THREAD

**Issue by fzwwj95** [hukaixuan19970627/yolov5_obb#439]
训练时候显存满了，GPU利用率在0-97%反复跳，不能保持，频率大概一秒钟一次从0-97%再跳到0，这是哪里有问题需要修改吗
数据集是DOTA，按照流程一样分割的1024的图
GPU：一张 3090  24G
yolov5n模型
banchsize 48
一个epoch需要12分钟
![image](https://user-images.githubusercontent.com/17897415/185033882-f5e22e5d-596d-410a-aa7a-03086c4963d3.png)

**Comment by monument-and-sea-all-the-gift** [comment]
如果是1024的图片，bs=48，这个显存占用很正常，看你图片数量多少了，一个epoch要把整个训练集跑完

**Comment by fzwwj95** [comment]
> 如果是1024的图片，bs=48，这个显存占用很正常，看你图片数量多少了，一个epoch要把整个训练集跑完
显存占用很正常,主要是GPU利用率的问题

**Comment by monument-and-sea-all-the-gift** [comment]
> > 如果是1024的图片，bs=48，这个显存占用很正常，看你图片数量多少了，一个epoch要把整个训练集跑完
> > 显存占用很正常,主要是GPU利用率的问题

从没关注过利用率问题，能最终跑出来效果，我连这都不看的

**Comment by fzwwj95** [comment]
> > > 如果是1024的图片，bs=48，这个显存占用很正常，看你图片数量多少了，一个epoch要把整个训练集跑完
> > > 显存占用很正常,主要是GPU利用率的问题
> 
> 从没关注过利用率问题，能最终跑出来效果，我连这都不看的

主要是训练很慢，而且和标称的精度差了2.56%

**Comment by hukaixuan19970627** [comment]
GPU利用率为0，说明GPU已经运算完了一批数据，但下一批数据还没准备好。
因此说明你的设备CPU性能负载不了bs=48的预处理工作，调低bs没准会训练更快

**Comment by fzwwj95** [comment]
>醍醐灌顶
