### ISSUE TITLE
【已顺利训练】Windows踩坑记录

### ISSUE THREAD

**Issue by xwxmars** [hukaixuan19970627/yolov5_obb#440]
好不容易装好了环境跑通了demo，看很多朋友都有windows运行的问题，分享一下我的踩坑（排坑）记录，希望有帮助。

先检查：
pytorch<=1.10（原因见issue #151 ）
cuda和pytorch版本是否匹配
在命令行输入nvcc -V检查cuda是否可用，输入cl检查msvc是否可用（别的c++ compiler理论上也可以但我用的是这个）
正常输出：
<img width="303" alt="nvcc" src="https://user-images.githubusercontent.com/110975389/185050218-9a57377f-54bd-46b5-919e-5018ed941fc1.png">
![cl](https://user-images.githubusercontent.com/110975389/185050240-b1ff3e3b-1fcf-498c-81a4-cf17f1e43d13.png)
确保这些所有就应该能够正常运行。以下是具体报错和解决办法。

首先列出所有问题：
1.	OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
2.	UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。（注意这个是cl，问题4是running build_ext）
3.	ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import)
4.	running build_ext
error: [WinError 2] 系统找不到指定的文件。
5.	fatal error C1083: 无法打开包括文件: “THC/THC.h”: No such file or directory

**1.	OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.**
原因：没有安装cuda或cuda没有加入环境变量
解决：（临时解决）在命令行输入 set CUDA_HOME=/usr/local/cuda-X.X，建议搜索如何添加cuda到环境变量一劳永逸解决。
Ps. 我后来发现是cuda装在了anaconda里面，真实环境里根本没有cuda

**2.	UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。**
原因：没装msvc或者没有配置到环境变量
解决：如果没装MSVC或其她compiler，先安装；如果装好了依然报这个错，将cl.exe添加到path环境变量。配好之后在命令行输入cl，正常输出见开头。

**3.	ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import)**
原因：nms_rotated_ext是从yolov5_obb-master\utils\nms_rotated\src里面的cpp或cu文件编译过来的，需要先进行编译，python才能读懂。因为编码问题，poly_nms_cuda.cu那个文件需要换成 #224 中的版本。
解决：在命令行cd utils\nms_rotated转到setup.py所在的文件夹，然后输入python setup.py develop

**4.	running build_ext**
**error: [WinError 2] 系统找不到指定的文件。**
原因：msvc或cuda compiler不可用
解决：重装。验证msvc：命令行输入cl；验证cuda：命令行输入nvcc -V

**5.	fatal error C1083: 无法打开包括文件: “THC/THC.h”: No such file or directory**
原因：见 #151 ，pytorch>=1.11弃用了一些文件，请使用pytorch<=1.10，我用的是1.10.2（和cuda11.3）
题外话：装cuda和pytorch花了很长时间，torch官网没有1.10.2的命令，我尝试装1.10.0和1.10.1，运行detect的时候报错CUDA version (11.3) mismatches the version that was used to compile PyTorch (10.2)，最后输入conda install pytorch==1.10.2 torchvision torchaudio cudatoolkit=11.3 装好了（记得换清华源

**Comment by Royalbx** [comment]
第四个问题怎么解决呀？重装是重装什么？

**Comment by YoonaIAN** [comment]
您好，我在第三个问题运行python setup.py develop报这样的错误是为什么呢？
runtimeerror：error compiling objects forextension

**Comment by WanFeng123313** [comment]
> 

你好,我运行python setup.py develop也报错了,请问你解决了吗?

**Comment by WanFeng123313** [comment]
> 您好，我在第三个问题运行python setup.py develop报这样的错误是为什么呢？ runtimeerror：error compiling objects forextension

你好,我运行python setup.py develop也报错了,请问你解决了吗?

**Comment by Royalbx** [comment]
已经解决了



在 2022-11-04 22:22:39，"WanFeng123313" ***@***.***> 写道：

你好,我运行python setup.py develop也报错了,请问你解决了吗?

**Comment by WanFeng123313** [comment]
> 已经解决了 在 2022-11-04 22:22:39，"WanFeng123313" ***@***.***> 写道： 你好,我运行python setup.py develop也报错了,请问你解决了吗? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>
请问你是怎么解决的？我那天试了一天都没解决掉

**Comment by Royalbx** [comment]
在setup.py中把 cmdclass={'build_ext': BuildExtension}改为cmdclass={'build_ext': BuildExtension.with_options(use_ninja=False)}


| |
卜玺
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年11月7日 20:06 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [hukaixuan19970627/yolov5_obb] 【已顺利训练】Windows踩坑记录 (Issue #440) |

已经解决了 在 2022-11-04 22:22:39，"WanFeng123313" @.> 写道： 你好,我运行python setup.py develop也报错了,请问你解决了吗? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>
请问你是怎么解决的？我那天试了一天都没解决掉

**Comment by XUAN6288** [comment]
用的vs还是pycharm，MSVC安装失败，尝试了很多次，可以发一份编译好的文件给我吗？

**Comment by Royalbx** [comment]
pycharm。msvc我安装了vs2019。用别人编译的好像不行。我之前试过。



| |
卜玺
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年11月8日 22:05 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [hukaixuan19970627/yolov5_obb] 【已顺利训练】Windows踩坑记录 (Issue #440) |

用的vs还是pycharm，MSVC安装失败，尝试了很多次，可以发一份编译好的文件给我吗？

**Comment by YoonaIAN** [comment]
> > 你好，我在第三个问题运行 python setup.py 开发报这样的错误是为？ runtimeerror：error compile objects forextension
> 
> 你好，我运行python setup.py develop也报错了，请问你解决了吗？

我还是不行，没有解决这个问题

**Comment by Royalbx** [comment]
你这个报错也不完整。不清楚具体原因。我用的pytoch版本为1.10+cu113


| |
卜玺
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年11月9日 10:41 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [hukaixuan19970627/yolov5_obb] 【已顺利训练】Windows踩坑记录 (Issue #440) |

你好，我在第三个问题运行 python setup.py 开发报这样的错误是为？ runtimeerror：error compile objects forextension

你好，我运行python setup.py develop也报错了，请问你解决了吗？

我还是不行，没有解决这个问题

**Comment by WanFeng123313** [comment]
> 在setup.py中把 cmdclass={'build_ext': BuildExtension}改为cmdclass={'build_ext': BuildExtension.with_options(use_ninja=False)} | | 卜玺 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2022年11月7日 20:06 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , ***@***.***> | | 主题 | Re: [hukaixuan19970627/yolov5_obb] 【已顺利训练】Windows踩坑记录 (Issue #440) | 已经解决了 在 2022-11-04 22:22:39，"WanFeng123313" @.> 写道： 你好,我运行python setup.py develop也报错了,请问你解决了吗? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 请问你是怎么解决的？我那天试了一天都没解决掉 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

谢谢，谢谢，我也成功运行了

**Comment by whiterAutumn** [comment]
if you are in this situation. Windows compiles successfully, but there is a problem in training. The loss does not drop. The same data, models and parameters can be trained normally under Ubuntu.
 Epoch   gpu_mem       box       obj       cls     theta    labels  img_size
   52/2999     5.44G    0.1232    0.3267   0.02696    0.7272        33      1280: 100%|██████████| 14/14 [00:17<00:00,  1.26s/it]
     Class     Images     Labels          P          R  HBBmAP@.5  HBBmAP@.5:.95: 100%|██████████| 7/7 [00:04<00:00,  1.63it/s]
                   all         53          0          0          0          0          0

 Epoch   gpu_mem       box       obj       cls     theta    labels  img_size
   53/2999     5.44G    0.1231    0.3131   0.02698    0.7273        33      1280: 100%|██████████| 14/14 [00:17<00:00,  1.27s/it]
       Class     Images     Labels          P          R  HBBmAP@.5  HBBmAP@.5:.95: 100%|██████████| 7/7 [00:04<00:00,  1.59it/s]
                 all         53          0          0          0          0          0

   Epoch   gpu_mem       box       obj       cls     theta    labels  img_size
   54/2999     5.44G    0.1232    0.3001   0.02696    0.7272        21      1280: 100%|██████████| 14/14 [00:17<00:00,  1.28s/it]
       Class     Images     Labels          P          R  HBBmAP@.5  HBBmAP@.5:.95: 100%|██████████| 7/7 [00:04<00:00,  1.63it/s]
                 all         53          0          0          0          0          0

**Comment by Kev1nDeng** [comment]
卡了一周多终于解决了，感谢！

**Comment by BuFanZHANG** [comment]
> 第四个问题怎么解决呀？重装是重装什么？

你好，请问这个问题解决了嘛，我也在这一步出现了问题？如果解决了具体是如何解决的呢

**Comment by Kev1nDeng** [comment]
> > 第四个问题怎么解决呀？重装是重装什么？
> 
> 你好，请问这个问题解决了嘛，我也在这一步出现了问题？如果解决了具体是如何解决的呢

把msvc装好就行了

**Comment by BigBeardYT** [comment]
您好，拜托您百忙之中看了我这个问题，看了所有提问都没人问这个：
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by BuFanZHANG** [comment]
> 您好，拜托您百忙之中看了我这个问题，看了所有提问都没人问这个： error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

安装visual studio 2019里的用于C++的组件，安装后在去搜一下配置环境变量

**Comment by wszswppx** [comment]
你好，我在编译pytorch3d的时候出现了问题4：
```
running build_ext
error: [WinError 2] 系统找不到指定的文件。
```
但是我的`cl`命令和`nvcc -V`输出都正常：
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/32038518/bba53ca4-94df-4869-a022-9b4aa40b96e6)
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/32038518/c5e924da-b126-4897-8209-eff0cc8f8469)

用`cl`编译cpp文件也可以：
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/32038518/0f902e8b-1638-4f05-a703-73b19c38b9e9)
请问您知道这是什么原因吗？

**Comment by BuFanZHANG** [comment]
> 你好，我在编译pytorch3d的时候出现了问题4：
> 
> ```
> running build_ext
> error: [WinError 2] 系统找不到指定的文件。
> ```
> 
> 但是我的`cl`命令和`nvcc -V`输出都正常： ![image](https://private-user-images.githubusercontent.com/32038518/322883300-bba53ca4-94df-4869-a022-9b4aa40b96e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzk3MjgsIm5iZiI6MTcxMzI3OTQyOCwicGF0aCI6Ii8zMjAzODUxOC8zMjI4ODMzMDAtYmJhNTNjYTQtOTRkZi00ODY5LWEwMjItOWI0YWE0MGI5NmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE0NTcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MjA0MjIwYTZjYjFiZThiNWYxMzI0ZWIxMjIzYWY2ODZmMjU0MDM2ZWFhMWNlMDQ4MTNlNTg3OWVmNWYxNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mx6tVICXzMLp16cHwn125SIW3pJsbXwZ2xhgwYpHtXE) ![image](https://private-user-images.githubusercontent.com/32038518/322883448-c5e924da-b126-4897-8209-eff0cc8f8469.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzk3MjgsIm5iZiI6MTcxMzI3OTQyOCwicGF0aCI6Ii8zMjAzODUxOC8zMjI4ODM0NDgtYzVlOTI0ZGEtYjEyNi00ODk3LTgyMDktZWZmMGNjOGY4NDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE0NTcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMTdmNjMxOTUzZDY5NDVkOWEzYjZhMzMwNmM0MDM2M2E0MTdjOWM0ODBjZjA1MGU3ZjA2NTkzMWYzNzdhYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._6in5r7G2HSqm1TKmqB3zSsECUSNRqQQVu7KIzfxjU4)
> 
> 用`cl`编译cpp文件也可以： ![image](https://private-user-images.githubusercontent.com/32038518/322884472-0f902e8b-1638-4f05-a703-73b19c38b9e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzk3MjgsIm5iZiI6MTcxMzI3OTQyOCwicGF0aCI6Ii8zMjAzODUxOC8zMjI4ODQ0NzItMGY5MDJlOGItMTYzOC00ZjA1LWE3MDMtNzNiMTljMzhiOWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE0NTcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNWI3ZmI4M2QxMGNmZWQ3MTI3OWM5ODU0YzA0ZjBkY2NjY2EyZWI3ZGY3Y2RmMTAwZDI4ZjZlZTVjN2M2NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3fxd4oBHzJuNwvoqZ9FBkXh3rOKp-j3C3PEV14nR5_Q) 请问您知道这是什么原因吗？

之前我遇到是因为vs版本不对，使用2019版本，然后编译文件用issues 里的那个，跟着教程走一遍就行了
