### ISSUE TITLE
预测框颜色调整

### ISSUE THREAD

**Issue by shubudao** [hukaixuan19970627/yolov5_obb#444]
我想将预测框长边和短边的颜色设置不同，该如何修改？

**Comment by shubudao** [comment]
有大佬指点一下吗？

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/blob/b00c3f245e50e7a80460a1b949d22ea7dfeb27a0/utils/plots.py#L113
画图函数在这儿
