### ISSUE TITLE
[linux]Install yolov5-obb  error: could not create 'nms_rotated.egg-info': Permission denied

### ISSUE THREAD

**Issue by ZKZontheway** [hukaixuan19970627/yolov5_obb#445]
显卡3090
OS Ubuntu 20.04
CUDA Driver Version 11.6
CUDA Toolkit Version 11.3 
torch.version.cuda 11.3

配置环境过程中出现问题
python setup.py develop
![1](https://user-images.githubusercontent.com/68090076/185643430-69028e7a-83e0-46df-b6a2-449619d9c394.png)

然后我试了一下另外一个方法
pip install -v -e .
![2 1](https://user-images.githubusercontent.com/68090076/185646536-a7dad90c-3221-46e1-9301-ab41661084e9.png)
![2 2](https://user-images.githubusercontent.com/68090076/185646592-7e9af0fe-7025-43a3-b410-c0658cbbeeba.png)
![2 3](https://user-images.githubusercontent.com/68090076/185647081-02a36ebf-7f6c-4cbe-a5d1-f4d149de3a47.png)
![2 4](https://user-images.githubusercontent.com/68090076/185647133-83573558-6db2-4860-9da6-5282696afb10.png)

两种方法都不行，并且都出现了error: could not create 'nms_rotated.egg-info': Permission denied

我试着给方法前面加上sudo
sudo python setup.py develop
![3](https://user-images.githubusercontent.com/68090076/185650788-b19c14a4-5dd0-46f5-89f7-cb7e4618530d.png)

sudo pip install -v -e .
![4 1](https://user-images.githubusercontent.com/68090076/185650673-e0754d85-aae9-4033-9674-a88befa5fe42.png)
![4 2](https://user-images.githubusercontent.com/68090076/185650696-b35977a4-94cf-44cb-a2fa-575f340c20a8.png)
![4 3](https://user-images.githubusercontent.com/68090076/185650847-f236b945-3348-49b9-907e-913f773e754d.png)
![4 4](https://user-images.githubusercontent.com/68090076/185650938-fa098b40-a590-4842-bfb9-b802d684d913.png)
![4 5](https://user-images.githubusercontent.com/68090076/185650983-363f83e2-5913-4b5d-b21b-e05a632c7ff1.png)
![4 6](https://user-images.githubusercontent.com/68090076/185651003-ee45f154-c8be-497a-970d-3350927f79e0.png)

也还是不行

**Comment by ZKZontheway** [comment]
问题找到了，我git clone下来权限有问题，权限只有只读，改一下权限就好

**Comment by weiyaokun** [comment]
> 问题找到了，我git clone下来权限有问题，权限只有只读，改一下权限就好

你好  怎么该权限呢
