### ISSUE TITLE
single class training problem

### ISSUE THREAD

**Issue by ZuyongWu** [hukaixuan19970627/yolov5_obb#452]
单类别训练时，设置nc=1，模型不收敛，issue看到挺多的，我的也不收敛。

我的疑惑是，当nc=1时，theta的loss会是从十多开始往下掉且不会收敛；
而设置nc=2，theta的loss就从0.8开始往下掉且会收敛

theta_loss跟nc之间有关系吗？

**Comment by ibtehajali67** [comment]
what answer you find for this
