### ISSUE TITLE
有没有大佬将nms_rotated修改到支持torch1.11或者1.12版本呀

### ISSUE THREAD

**Issue by LUO77123** [hukaixuan19970627/yolov5_obb#456]
目前作者大佬提供的支持1.10.1及以下版本，有没有大佬将nms_rotated修改到支持torch1.11或者1.12版本呀

**Comment by myknowntime** [comment]
我也想用 1.12 版本的 torch，请问您最后怎么解决的？

**Comment by LUO77123** [comment]
彻底改了程序，调用mmcv写的，就可以支持torch更新



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月16日(周日) 下午5:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [hukaixuan19970627/yolov5_obb] 有没有大佬将nms_rotated修改到支持torch1.11或者1.12版本呀 (Issue #456)




 
我也想用 1.12 版本的 torch，请问您最后怎么解决的？

**Comment by sjx3906** [comment]
请问大佬可以提供一下怎么改的嘛QAQ
