### ISSUE TITLE
验证集label为0

### ISSUE THREAD

**Issue by llO-Oll** [hukaixuan19970627/yolov5_obb#461]
python val.py --data 'data/yolov5obb_split.yaml' --weights 'runs/train/exp4/weights/best.pt' --batch-size 2 --img 1024 --task 'val' --device 0 --save-json --name 'obb_val_split'

![image](https://user-images.githubusercontent.com/57003610/190848199-28fccefa-ad6a-49c5-b951-d9073ab7524d.png)
感觉是没找到验证集的label文件夹

配置文件yolov5obb_split.yaml路径位置如下
path: ./dataset/DOTAv1.5 # dataset root dir
train: train_demo_rate1.0_split1024_gap200/images #images   # train images (relative to 'path') 
val: val_demo_rate1.0_split1024_gap200/images #images  # val images (relative to 'path') 
test: dataset_demo_rate1.0_split1024_gap200/images  #images # test images (optional)

数据集路径如下：
datasets   
----DOTAv1.5 
--------val_split_rate1.0_subsize1024_gap200
----------------images
------------------------1.jpg
------------------------ ...
------------------------ 10000.jpg
----------------labelTxt
------------------------ 1.txt
------------------------ ...
------------------------ 10000.txt

**Comment by llO-Oll** [comment]
参照#424 修改代码后，然后删除cache文件重新验证，可以解决

**Comment by Winniesea** [comment]
@llO-Oll 按照#424修改后，训练过程中label有时候为0有时候不为0。然后按照您的思路，按照#424修改后删除了labelTxt.cache文件又出现了这类报错‘LoadImagesAndLabels' object has no attribute 'cls_names'。请问是什么情况？

**Comment by guanxuefeng** [comment]
> @llO-Oll＃＃424修改，训练训练中有时候有时候有时候有时候有时候不不不不不不不不不不不不不。。。。然后然后然后按照按照删掉了删掉了labeltxt.cache文件'cls_names'。请问是什么情况？

您解决了吗

**Comment by ibtehajali67** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/424 , I have tried this update and delete my cache file in valid folde its working for me
