### ISSUE TITLE
如何在CPU上使用detect.py？

### ISSUE THREAD

**Issue by Nifdi01** [hukaixuan19970627/yolov5_obb#498]
我是计算机视觉的新手，想在我的笔记本电脑上测试yolov5_obb。我没有GPU，想用我的CPU进行推理。谁能告诉我怎么做?

**Comment by fighting666777** [comment]
参数里的device改为cpu就可以啦

**Comment by Nifdi01** [comment]
如前所述，这是一个参数问题

**Comment by ibtehajali67** [comment]
> As mentioned, it's a matter of parameters

hi if you want to run on cpu you just have to download python file softnms_rotate.py from [https://github.com/ZhangGongjie/Soft-NMS-for-Rotated-Rectangles] and put that file into utils folder.
then go to general.py and do these 2 step.
it will work on cpu.
<img width="321" alt="step_1" src="https://user-images.githubusercontent.com/49198838/223405979-58e2ced1-2dfe-4954-8338-eab13d9e6e3e.PNG">
<img width="340" alt="step_2" src="https://user-images.githubusercontent.com/49198838/223405981-a21facd4-ea00-418f-a612-75bee97549c2.PNG">
