### ISSUE TITLE
训练自己的数据集的异常

### ISSUE THREAD

**Issue by etoilestar** [hukaixuan19970627/yolov5_obb#541]
您好，在我训练自己的数据集时，从刚开始我只有obj的损失不为0，其他均为0，请问是为什么呀？？

**Comment by etoilestar** [comment]
<img width="502" alt="1678537962350" src="https://user-images.githubusercontent.com/58216919/224484757-dde53a13-e7e4-4703-8bc8-79e01e930132.png">

**Comment by etoilestar** [comment]
找到解决办法了，评论关闭

**Comment by zzzzzzxm** [comment]
请问是什么解决办法呢？
