### ISSUE TITLE
Issue: No results running dataset_demo

### ISSUE THREAD

**Issue by Rorsc4achhh** [hukaixuan19970627/yolov5_obb#559]
Running in windows, Py39_Torch1.10_cu10.2.
Training with demo dataset. 

python train.py `
>>   --weights 'weights/yolov5s.pt' `
>>   --data 'data/yolov5obb_demo.yaml' `
>>   --hyp 'data/hyps/obb/hyp.finetune_dota.yaml' `
>>   --epochs 10 `
>>   --batch-size 1 `
>>   --img 1024 `
>>   --device 0

The generated predict picture is just the original picture without any result on it, below is the result. How to fix this?
![results](https://user-images.githubusercontent.com/106846731/233863679-4ec49f55-45b3-4085-8ad0-e633aa64e643.png)
![val_batch0_pred](https://user-images.githubusercontent.com/106846731/233863800-e465adbe-4180-4a24-b8d1-1942acb2be80.jpg)

**Comment by Rorsc4achhh** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/417
Have already went through this, but it seems won't work.
Tried on laptop rtx2060 windows10 and also 3070 on windows 11, following the install.md, I just don't know why there's no result.

**Comment by Fraulainee** [comment]
Hello, I am having the same problem. How did you fix this?

**Comment by Rorsc4achhh** [comment]
> Hello, I am having the same problem. How did you fix this?

train your own dataset with at least two kinds of objects in your --data 'data/yolov5obb_dataset.yaml' ` file.

**Comment by HungVS** [comment]
@Rorsc4achhh 
Thanks for your sharing, 

Does my dataset must actually include 2 kinds of objects, or I just need to config 2 classes in the 'data/yolov5obb_dataset.yaml' file even though my dataset still contains only 1 object kind?

**Comment by Fraulainee** [comment]
> @Rorsc4achhh Thanks for your sharing,
> 
> Does my dataset must actually include 2 kinds of objects, or I just need to config 2 classes in the 'data/yolov5obb_dataset.yaml' file even though my dataset still contains only 1 object kind?

no. if you only have 1 object/class simply add a placeholder class such as "None" in the yaml file. it'll work just fine.

**Comment by Fraulainee** [comment]
> > Hello, I am having the same problem. How did you fix this?
> 
> train your own dataset with at least two kinds of objects in your --data 'data/yolov5obb_dataset.yaml' ` file.

thank you! I figured it out

**Comment by HungVS** [comment]
@Fraulainee Thank you, I'll give it a try.
