### ISSUE TITLE
 Cannot open include file: 'THC/THC.h': No such file or directory

### ISSUE THREAD

**Issue by boatman-27** [hukaixuan19970627/yolov5_obb#607]
Hey! so i been trying to install yolov5-obb as mentioned in step e in the install.md file in the docs folders. however, it doesnt work i installed CUDA toolkit 11.7 with cuDNN v8.9.4 and i installed pyTorch as explained in the pystorch start locally website but i always get stuck in the step e especially "python setup.py develop  #or "pip install -v -e ." ". if anyone can lmk what i did wrong or which cuda i should use please lmk. i get these 2 errors:  fatal error C1083: Cannot open include file: 'THC/THC.h': No such file or directory
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin\\nvcc.exe' failed with exit code 2.

any help would be appreciated.
![image_2023-09-28_151459605](https://github.com/hukaixuan19970627/yolov5_obb/assets/78026178/b844d245-5e06-4553-941a-dd7cbc41ab0a)
![image_2023-09-28_151506914](https://github.com/hukaixuan19970627/yolov5_obb/assets/78026178/e205cfa6-0383-414f-be00-20103d29d879)

**Comment by Chenjiangwen** [comment]
Have you tried compiling with 'pip install -v -e .' in the correct virtual environment? I have successfully started training using this method.

**Comment by boatman-27** [comment]
I did yeah. can you please tell me the steps you followed and what correct virtual environment i should the compile with?
i made a virtual environment and it created a folder outside the main yolov5_obb folder. then i activated it and installed pytorch with this command:
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
then cd yolov5_obb
then pip install -r requirements.txt  
then cd utils/nms_rotated
then pip install -v -e .

and im still getting the same error:
atal error C1083: Cannot open include file: 'THC/THC.h': No such file or directory
  poly_nms_cuda.cu
  error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin\\nvcc.exe' failed with exit code 2
  
  
  error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by boatman-27** [comment]
> Have you tried compiling with 'pip install -v -e .' in the correct virtual environment? I have successfully started training using this method.


I did yeah. can you please tell me the steps you followed and what correct virtual environment i should the compile with?
i made a virtual environment and it created a folder outside the main yolov5_obb folder. then i activated it and installed pytorch with this command:
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
then cd yolov5_obb
then pip install -r requirements.txt
then cd utils/nms_rotated
then pip install -v -e .

and im still getting the same error:
atal error C1083: Cannot open include file: 'THC/THC.h': No such file or directory
poly_nms_cuda.cu
error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe' failed with exit code 2

error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

please tell me what i did wrong. Thank you for your time

**Comment by tom123478** [comment]
i have same wrong

**Comment by Chenjiangwen** [comment]
> > Have you tried compiling with 'pip install -v -e .' in the correct virtual environment? I have successfully started training using this method.
> 
> I did yeah. can you please tell me the steps you followed and what correct virtual environment i should the compile with? i made a virtual environment and it created a folder outside the main yolov5_obb folder. then i activated it and installed pytorch with this command: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 then cd yolov5_obb then pip install -r requirements.txt then cd utils/nms_rotated then pip install -v -e .
> 
> and im still getting the same error: atal error C1083: Cannot open include file: 'THC/THC.h': No such file or directory poly_nms_cuda.cu error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe' failed with exit code 2
> 
> error: subprocess-exited-with-error
> 
> × python setup.py develop did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> please tell me what i did wrong. Thank you for your time

@boatman-27 @tom123478  You may try replacing the contents of the folder yolov5_obb->utils->nms_rotated with the following files and then give it another try. [link](https://drive.google.com/file/d/1o4c0qxM8Jbdyy1TXlhs84Ae3czQCSYVp/view?usp=sharing)

**Comment by boatman-27** [comment]
> > > Have you tried compiling with 'pip install -v -e .' in the correct virtual environment? I have successfully started training using this method.
> > 
> > 
> > I did yeah. can you please tell me the steps you followed and what correct virtual environment i should the compile with? i made a virtual environment and it created a folder outside the main yolov5_obb folder. then i activated it and installed pytorch with this command: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 then cd yolov5_obb then pip install -r requirements.txt then cd utils/nms_rotated then pip install -v -e .
> > and im still getting the same error: atal error C1083: Cannot open include file: 'THC/THC.h': No such file or directory poly_nms_cuda.cu error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe' failed with exit code 2
> > error: subprocess-exited-with-error
> > × python setup.py develop did not run successfully. │ exit code: 1 ╰─> See above for output.
> > note: This error originates from a subprocess, and is likely not a problem with pip.
> > please tell me what i did wrong. Thank you for your time
> 
> @boatman-27 @tom123478 You may try replacing the contents of the folder yolov5_obb->utils->nms_rotated with the following files and then give it another try. [link](https://drive.google.com/file/d/1o4c0qxM8Jbdyy1TXlhs84Ae3czQCSYVp/view?usp=sharing)

Thank you! can you please give me access

**Comment by Chenjiangwen** [comment]
cjwen
***@***.***



&nbsp;&nbsp;My mistake, it should be fine now.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hukaixuan19970627/yolov5_obb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月15日(星期天) 下午3:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hukaixuan19970627/yolov5_obb]  Cannot open include file: 'THC/THC.h': No such file or directory (Issue #607)





    
Have you tried compiling with 'pip install -v -e .' in the correct virtual environment? I have successfully started training using this method.
  
I did yeah. can you please tell me the steps you followed and what correct virtual environment i should the compile with? i made a virtual environment and it created a folder outside the main yolov5_obb folder. then i activated it and installed pytorch with this command: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 then cd yolov5_obb then pip install -r requirements.txt then cd utils/nms_rotated then pip install -v -e .
 and im still getting the same error: atal error C1083: Cannot open include file: 'THC/THC.h': No such file or directory poly_nms_cuda.cu error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe' failed with exit code 2
 error: subprocess-exited-with-error
 × python setup.py develop did not run successfully. │ exit code: 1 ╰─&gt; See above for output.
 note: This error originates from a subprocess, and is likely not a problem with pip.
 please tell me what i did wrong. Thank you for your time
  
@boatman-27 @tom123478 You may try replacing the contents of the folder yolov5_obb-&gt;utils-&gt;nms_rotated with the following files and then give it another try. link
  
Thank you! can you please give me access

**Comment by Chenjiangwen** [comment]
My mistake, it should be fine now.

> > > > Have you tried compiling with 'pip install -v -e .' in the correct virtual environment? I have successfully started training using this method.
> > > 
> > > 
> > > I did yeah. can you please tell me the steps you followed and what correct virtual environment i should the compile with? i made a virtual environment and it created a folder outside the main yolov5_obb folder. then i activated it and installed pytorch with this command: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 then cd yolov5_obb then pip install -r requirements.txt then cd utils/nms_rotated then pip install -v -e .
> > > and im still getting the same error: atal error C1083: Cannot open include file: 'THC/THC.h': No such file or directory poly_nms_cuda.cu error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe' failed with exit code 2
> > > error: subprocess-exited-with-error
> > > × python setup.py develop did not run successfully. │ exit code: 1 ╰─> See above for output.
> > > note: This error originates from a subprocess, and is likely not a problem with pip.
> > > please tell me what i did wrong. Thank you for your time
> > 
> > 
> > @boatman-27 @tom123478 You may try replacing the contents of the folder yolov5_obb->utils->nms_rotated with the following files and then give it another try. [link](https://drive.google.com/file/d/1o4c0qxM8Jbdyy1TXlhs84Ae3czQCSYVp/view?usp=sharing)
> 
> Thank you! can you please give me access

**Comment by boatman-27** [comment]
> My mistake, it should be fine now.
> 
> > > > > Have you tried compiling with 'pip install -v -e .' in the correct virtual environment? I have successfully started training using this method.
> > > > 
> > > > 
> > > > I did yeah. can you please tell me the steps you followed and what correct virtual environment i should the compile with? i made a virtual environment and it created a folder outside the main yolov5_obb folder. then i activated it and installed pytorch with this command: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 then cd yolov5_obb then pip install -r requirements.txt then cd utils/nms_rotated then pip install -v -e .
> > > > and im still getting the same error: atal error C1083: Cannot open include file: 'THC/THC.h': No such file or directory poly_nms_cuda.cu error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe' failed with exit code 2
> > > > error: subprocess-exited-with-error
> > > > × python setup.py develop did not run successfully. │ exit code: 1 ╰─> See above for output.
> > > > note: This error originates from a subprocess, and is likely not a problem with pip.
> > > > please tell me what i did wrong. Thank you for your time
> > > 
> > > 
> > > @boatman-27 @tom123478 You may try replacing the contents of the folder yolov5_obb->utils->nms_rotated with the following files and then give it another try. [link](https://drive.google.com/file/d/1o4c0qxM8Jbdyy1TXlhs84Ae3czQCSYVp/view?usp=sharing)
> > 
> > 
> > Thank you! can you please give me access

ahh all good, it installed now. tysm and with this ill close this issue. :)
