### ISSUE TITLE
Problems with using CSL（circular smooth label）

### ISSUE THREAD

**Issue by LeiaJ520** [hukaixuan19970627/yolov5_obb#626]
How to set parameters to use CSL labels? I set use_gaussian=True in the poly2rbox function in yolov5_obb/utils/rboxs_utils.py, but there is an error in training. The error content is as follows:
tuple indices must be integers or slices, not tuple
Traceback (most recent call last):
File "/home/lxj/yolov5_obb/train.py", line 633, in
main(opt)
File "/home/lxj/yolov5_obb/train.py", line 530, in main
train(opt.hyp, opt, device, callbacks)
File "/home/lxj/yolov5_obb/train.py", line 238, in train
check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz)
File "/home/lxj/yolov5_obb/utils/autoanchor.py", line 49, in check_anchors
ls_edges.append(rboxes[:, 2:4])
TypeError: tuple indices must be integers or slices, not tuple

**Comment by Lyle-Xu** [comment]
大佬怎么解决的

**Comment by LeiaJ520** [comment]
> 大佬怎么解决的

翻看了项目之前的issue，作者目前的这个项目不支持CSL的切换，默认就是使用了CSL，CSL的使用代码是在yolov5_obb/utils/datasets.py中 def __getitem__(self, index)中， 不需要修改 poly2rbox function 中的 use_gaussian=False

**Comment by Lyle-Xu** [comment]
谢谢

**Comment by hecheng000** [comment]
> > 大佬怎么解决的
> 
> 翻看了项目之前的issue，作者目前的这个项目不支持CSL的切换，默认就是使用了CSL，CSL的使用代码是在yolov5_obb/utils/datasets.py中 def **getitem**(self, index)中， 不需要修改 poly2rbox function 中的 use_gaussian=False

意思是只能用csl是吗 能否关掉做下对比啊

**Comment by LeiaJ520** [comment]
是的，只能用CSL，没有开关的接口，如果要做对比，只能自己改代码

**Comment by hecheng000** [comment]
> 是的，只能用CSL，没有开关的接口，如果要做对比，只能自己改代码

好的 谢谢
