### ISSUE TITLE
旋转框标注方式和后续旋转检测优化

### ISSUE THREAD

**Issue by wangchuangg** [hukaixuan19970627/yolov5_obb#628]
您好，我想问一下，项目更新之后使用的是DOTA数据集格式进行训练。那么现在旋转物体标注方式是不是就是八参数法了(还是说是DOTA格式的任意四边形法)，后续的旋转检测优化是不是就是基于八参数法进行的了。还是说使用DOTA格式进行训练和使用YOLO格式训练，都是基于五参数法进行旋转检测优化的呀

**Comment by Lyle-Xu** [comment]
长边法，yolov5多了角度分类 ef poly2rbox(polys, num_cls_thata=180, radius=6.0, use_pi=False, use_gaussian=False）全局搜索这个函数

**Comment by wangchuangg** [comment]
> 长边法，yolov5多了角度分类 ef poly2rbox(polys, num_cls_thata=180, radius=6.0, use_pi=False, use_gaussian=False）全局搜索这个函数
就是虽然运行是用的DOTA数据集格式，但是还是基于五参数的长边定义法

**Comment by wangchuangg** [comment]
> 长边法，yolov5多了角度分类 ef poly2rbox(polys, num_cls_thata=180, radius=6.0, use_pi=False, use_gaussian=False）全局搜索这个函数

好的，谢谢您
