### ISSUE TITLE
我是用demo进行训练依然显示corrupted，环境跟着作者重新配置了好几次，请问是哪里的问题？

### ISSUE THREAD

**Issue by leileilei2000** [hukaixuan19970627/yolov5_obb#658]
![obb](https://github.com/hukaixuan19970627/yolov5_obb/assets/144891526/467b26f4-7de4-4ff4-a56e-9188d4ae4027)

**Comment by Leo5050xvjf** [comment]
same here

**Comment by Robertcore** [comment]
降低下numpy版本 pip install numpy==1.23
