### ISSUE TITLE
我看到数据有个warning 必须图片高度等于宽度

### ISSUE THREAD

**Issue by aoluming** [hukaixuan19970627/yolov5_obb#98]
## Additional context
如果高度不等于宽度我该怎么修改呢

**Comment by hukaixuan19970627** [comment]
> > imread图像之后，对宽高不一致的图像进行pad处理使其宽高一致就可以了
> 
> 好的谢谢，这个在代码中会自己处理吗，还是说需要自己写代码处理

这个要你自己加，我这个项目专门针对dota数据集的，切割dota图像的时候就会切割成长宽一致的图像，所以代码里没有这部分的操作
